### ISSUE TITLE
iOS 调用SDK初始化方法后直接调用登录方法总是报SDK未初始化的错误

### ISSUE THREAD

**Issue by PengChJ** [tencentyun/TIMSDK#10]
TIMManager
- (int)initSdk:(TIMSdkConfig*)config
调用这个方法后直接调用
- (int)login: (TIMLoginParam*)param succ:(TIMLoginSucc)succ fail:(TIMFail)fail
总是回调失败的闭包，错误是SDK未初始化，我试验过，如果推迟1秒钟登录就会成功，既然这个SDK初始化方法有多线程等待时间，为什么不用闭包回调传回初始化结果，以免直接调用登录方法失败报错。

**Comment by rexchang2016** [comment]
收到，增加新的 init 接口回调确实很有必要，同时，我们稍后也会在春节后上班的前两周重点优化init成功率，务必不让大家继续被这个问题困扰。

**Comment by lynxzhang** [comment]
新版本问题已经优化
