### ISSUE TITLE
最新版本拿不到用户资料timMsg.getSenderProfile()得到的TIMUserProfile拿不到用户头像和名字

### ISSUE THREAD

**Issue by Enlogty** [tencentyun/TIMSDK#100]
最新版本拿不到用户资料timMsg.getSenderProfile()得到的TIMUserProfile拿不到用户头像和名字

**Comment by Enlogty** [comment]
final MessageInfo msg = getItem(position);
        final TIMMessage timMsg = msg.getTIMMessage();
        TIMUserProfile senderProfile = timMsg.getSenderProfile();
        //  测试 获取用户的头像
       LogUtil.d("faceUrl: "+senderProfile.getFaceUrl()+"   userName: "+senderProfile.getNickName());
//-------------

04-26 21:43:06.491 12074-12074/com.tencent.qcloud.tim.tuikit D/CJT: faceUrl:    userName:

**Comment by Enlogty** [comment]
ChatAdapter.java 的onBindViewHolder 里面 senderProfile拿不到用户信息

**Comment by lynxzhang** [comment]
这个问题已经正在优化了，下个版本会优化解决

**Comment by lynxzhang** [comment]
新版本已经优化
