### ISSUE TITLE
android 5.1.56  oppo vivo android11 语音通话闪退

### ISSUE THREAD

**Issue by Yuanarcheannovice** [tencentyun/TIMSDK#1000]
android 5.1.56  oppo vivo android11 语音通话时 是否静音 切换 闪退

issue内容：

【当前现象】：oppo vivo android11手机 语音通话时 是否静音 切换 闪退
【集成包】：IMSDK   tuikit
【机型】： 
OPPO PEDM00
V2054A

【之前版本有无此问题】：不知道
![image](https://user-images.githubusercontent.com/18046524/119626087-6f07d980-be3d-11eb-98e5-682612b4c1d9.png)
![image](https://user-images.githubusercontent.com/18046524/119626106-74652400-be3d-11eb-9634-45d4b1424281.png)
![image](https://user-images.githubusercontent.com/18046524/119626199-88a92100-be3d-11eb-8830-bc1e8708b120.png)
![image](https://user-images.githubusercontent.com/18046524/119626227-9068c580-be3d-11eb-87fc-745ebabf88d1.png)

**Comment by kentoo** [comment]
您好，这个问题在trtc8.5.10026版本已经解决，您更新trtc到最新版本就行
