### ISSUE TITLE
请问web版本的npm提示不要用这个版本。那最新版本应该用哪个

### ISSUE THREAD

**Issue by bulolo** [tencentyun/TIMSDK#1003]
https://www.npmjs.com/package/tim-js-sdk

![image](https://user-images.githubusercontent.com/10026498/120130937-e81a7e80-c1f9-11eb-8443-00c268fbc646.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，目前2.11.0版本有问题
如需新版本（2.11.1）欢迎交流 q2562367495 注明来意

**Comment by yangq1990** [comment]
请参考此文档接入 https://cloud.tencent.com/document/product/269/37413
