### ISSUE TITLE
【Web】-【2.9.4】：【TIM.login报错：Error: request format or params invalid】

### ISSUE THREAD

**Issue by Nick-LCY** [tencentyun/TIMSDK#1010]
【当前现象】：使用userID和userSig尝试登入时报错：Error: request format or params invalid
【集成包】：IMSDK
【相关截图】：
![image](https://user-images.githubusercontent.com/46786312/122035352-f75a1880-ce04-11eb-8be6-ff4b9c8e5a09.png)
【相关代码】：
`      this.tim.login({ userID, userSig }).then(res => {
        resolve(res)
      }).catch(err => {
        reject(err)
      })
`
【其他说明】：之前遇到过这个错误，通过npm卸载重装了之后SDK错误消失。这次又发生这个错误，且代码与之前可运行时没有任何区别。

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，目前这是已知问题，老版sdk已不再维护，建议更新到2.10.2，尝试测试下
技术问题，欢迎交流，q2562367495 注明来意

**Comment by SFFI** [comment]
2.11.0的我也遇到这个问题。

**Comment by Nick-LCY** [comment]
> 您好，根据您的问题，目前这是已知问题，老版sdk已不再维护，建议更新到2.10.2，尝试测试下
> 技术问题，欢迎交流，q2562367495 注明来意

之前也尝试过新版，并没有解决这个问题，才换回的旧版本。之后如果再遇到这个问题该怎么处理呢？

**Comment by Tencent-Alice** [comment]
只能具体分析下看看，欢迎交流

**Comment by xty1992a** [comment]
今天遇到类似问题，发现是没传 SDKAppID，传了后就正常了
