### ISSUE TITLE
sdk数据请求

### ISSUE THREAD

**Issue by liu-sir666** [tencentyun/TIMSDK#1012]
在使用微信小程序时，按照官方得引用方法，登录im后为什么一直发起http请求，不是ws吗？sdk已是最新版本，在2.8.新版本上没见到会有http得请求

截图如下
![image](https://user-images.githubusercontent.com/51902166/122846380-4db0e500-d338-11eb-833d-e55bf81f8c9e.png)

请问一下这是什么原因？

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，长轮询都是只要是longpolling，测试走的是ws的，建议更新最新版本2.10.2 
技术问题 欢迎交流 q2562367495 注明来意

**Comment by liu-sir666** [comment]
请问 tim-wx-sdk-ws 这个包是什么包？网上有让安装这个的，

**Comment by yangq1990** [comment]
从v2.11.2起，sdk支持了websocket
v2.10.2及一下，都是http
[更新日志](https://cloud.tencent.com/document/product/269/38492)
