### ISSUE TITLE
TXIMSDK_TUIKit_iOS 

### ISSUE THREAD

**Issue by guang123** [tencentyun/TIMSDK#1013]
# 腾讯云IM标准版
  pod 'ISVImageScrollView', '~> 0.1.2'
  pod 'TXIMSDK_TUIKit_iOS'
集成后报错
/Users/***/Desktop/***/Pods/TXIMSDK_TUIKit_iOS/TUIKit/Classes/Section/Group/TUIGroupInfoController.m:447:50: No visible @interface for 'TIMManager' declares the selector 'deleteConversationAndMessages:receiver:'

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，是从旧版的tuikit组件 imsdk到v5版本吗，如果是旧版tuikit   ，那么imsdk只能指定更新到4.9.1或者之前的 ，无法使用V5，请知悉
技术问题，欢迎交流 ，q2562367495 注明来意
