### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.imsdk.manager.NativeManager.nativeSetUserConfig(com.tencent.imsdk.TIMUserConfig)

### ISSUE THREAD

**Issue by liamyu** [tencentyun/TIMSDK#102]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.imsdk.manager.NativeManager.nativeSetUserConfig(com.tencent.imsdk.TIMUserConfig)

设备：x86模拟器
sdk版本：api 'com.tencent.imsdk:imsdk:4.3.81'

当前是否不支持x86架构？如果不支持能否添加一下支持？用真机比较麻烦，特别是我们用的ReactNative，Reload的时候摇手机摇到手断。。。

**Comment by lynxzhang** [comment]
您好，感谢您的反馈，这个需求正在开发中，后续的版本会加上

**Comment by vinsonswang** [comment]
x86和x86-64架构下个版本会支持

**Comment by lynxzhang** [comment]
最新版本已经支持
