### ISSUE TITLE
【iOS】-【5.4.666】：【崩溃后，database is not inited】

### ISSUE THREAD

**Issue by chaosVoid** [tencentyun/TIMSDK#1020]
【iOS】-【5.4.666】：【崩溃后，database is not inited】
【集成包】：TXIMSDK_TUIKit_live_iOS_Professional
【当前现象】：
一次崩溃后，会话列表空表，控制台输出：database is not inited
【机型】：模拟器 iphone12mini 14.4
【之前版本有无此问题】：崩溃前正常。macOS11.4+xcode12.4
【有无日志或者截图】：
TIM: 2021-07-22 21:27:10.572 E 61870-4764959   |-database.cpp:82                         Select                                  |database is not inited
TIM: 2021-07-22 21:27:10.573 E 61870-4764959   |-conversation_storage.cpp:81             OnGetConversationList                   |get conversation list|error code:7010|error message:database is not inited
TIM: 2021-07-22 21:27:10.574 E 61870-4764959   |-conversation_manager.cpp:234            OnGetConversationListFromStorage        |error code:7010|error message:database is not inited
日志完整链接: https://pan.baidu.com/s/136bjz1QOaL2Q7Y4cCUMb8g 提取码: 3e47

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，确认下具体是什么操作（调用的哪个接口），另真机测试是否正常
技术问题 欢迎交流 q2562367495 注明来意
