### ISSUE TITLE
【Android】-【5.5.892】：【V2TIMConversationManager调用getInstance报错】

### ISSUE THREAD

**Issue by HuZengKan** [tencentyun/TIMSDK#1026]
【Android】-【5.5.892】：【V2TIMConversationManager调用getInstance报错】
【集成包】：TUIKIT
【当前现象】：除了V2TIMManager能调用getInstance，其他V2TIM*Manager都报相同错误，看源码是没写public。
V2TIMManager源码：
`public static V2TIMManager getInstance() `
V2TIMConversationManager源码：
`static V2TIMConversationManager getInstance()`
开发语言是kotlin，有可能是不写public被kotlin默认为private类型了
同样有该问题的类：V2TIMMessageManager、V2TIMGroupManager、V2TIMSignalingManagerabstract、V2TIMConversationManager、V2TIMFriendshipManager、V2TIMOfflinePushManager
【机型】：华为P30
【之前版本有无此问题】：TUIKIT 5.1.56版本（不含V2的Manager）之前没有，5.5.892有
【日志】：Cannot access 'getInstance': it is package-private in 'V2TIMConversationManager'

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，关于您的V2TIMConversationManager调用getInstance报错的问题这边通过文档确认V2TIMConversationManager里面没有此getInstance方法所以会导致调用失败：https://im.sdk.qcloud.com/doc/zh-cn/classcom_1_1tencent_1_1imsdk_1_1v2_1_1V2TIMManager.html#abc854ab9dd97661a8d45bed952aee158
可以具体描述这个方法
技术问题 欢迎交流 q2562367495 注明来意

**Comment by HuZengKan** [comment]
重新去看了一下文档，原来调用方法改了，要这样来获取
`V2TIMManager.getConversationManager()`
