### ISSUE TITLE
【iOS】-【5.4.666】：【总未读消息数永远是0】

### ISSUE THREAD

**Issue by chaosVoid** [tencentyun/TIMSDK#1029]
【iOS】-【5.4.666】：【未读消息数永远是0】
【集成包】：TXIMSDK_TUIKit_live_iOS_Professional
【当前现象】：
1）V2TIMManager.sharedInstance()?.getTotalUnreadMessageCount 获取未读数为0
2）V2TIMManager.sharedInstance().getConversationList 获取到会话列表，从V2TIMConversation的unreadCount属性拿未读数仍然是0
3）通过会话V2TIMConversation获取getC2CHistoryMessageList每条消息V2TIMMessage，
消息的isRead未读标记是正常的。
目前临时用遍历会话消息来统计总未读数。
【机型】：模拟器 14.5   iphone12、se2等

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，看下是否设置调整下
![7D940628-24A5-4F28-83CB-A303540DF54D](https://user-images.githubusercontent.com/74762384/129135871-36ee5f3d-99b6-4dc9-a6ff-6812ccf5475b.jpeg)
技术问题 欢迎交流 q2562367495 注明来意
