### ISSUE TITLE
TIMManager 的getInstanceById搞 笑呢吗

### ISSUE THREAD

**Issue by Gloud-Zhao** [tencentyun/TIMSDK#103]
public class TIMManager {
    private static final String TAG = "TIMManager";
    private static TIMManager mInstance = new TIMManager();
    private static BaseManager mBase;

    private TIMManager() {
        mBase = BaseManager.getInstance();
    }

    public static TIMManager getInstance() {
        return mInstance;
    }

    public static synchronized TIMManager getInstanceById(String identification) {
        return getInstance();
    }

这段代码搞笑呢吗，认真的吗
![image](https://user-images.githubusercontent.com/13994354/56942515-bf70b800-6b4d-11e9-9d8a-5a29853489b4.png)

**Comment by vinsonswang** [comment]
感谢反馈，下个版本会优化这里
