### ISSUE TITLE
【iOS】-【5.4.666】：【聊天页-语音通话消息-点击不能直接回拨】

### ISSUE THREAD

**Issue by chaosVoid** [tencentyun/TIMSDK#1030]
【iOS】-【5.4.666】：【聊天页-语音通话消息-点击不能直接回拨】
【集成包】：TXIMSDK_TUIKit_live_iOS_Professional
语音通话消息是文本消息，不能直接点击回拨。
微信有的功能，SDK这算是超精简版吗？
这个功能应该算是很基础的吧？

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，目前im暂不支持这个功能，可以业务侧实现，可以点击这个字的同时发送自定义消息，拉起这个通话页面，
https://cloud.tencent.com/document/product/269/37067
可以参考
技术问题 欢迎交流 q2562367495 注明来意
