### ISSUE TITLE
Android 输入框、表情、扩展功能按钮+三者切换不流畅，弹跳明显

### ISSUE THREAD

**Issue by GitJoBo** [tencentyun/TIMSDK#1036]
Android 输入框、表情、扩展功能按钮+三者切换不流畅，弹跳明显；能否达到tim，或微信那种效果

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，您现在使用的sdk版本号是多少，这个问题可以录制复现下吗，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
您好，这个已和您q沟通，这个目前是已知优化问题，后续将继续优化哈
