### ISSUE TITLE
Android 消息异常问题

### ISSUE THREAD

**Issue by shingohu** [tencentyun/TIMSDK#104]
1.断网情况下发送的消息,会直接失败,失败回调中打印消息状态也为失败,但是本地状态貌似没变,联网再次拉去消息时会直接重发
2.断网情况下发送消息,失败,下次进来后这条消息重新发送了,但是变成了两条，然后再进来变成了四条,反正消息是异常的. 重现步骤,demo任意账号进入,发起会话,随便搜索一个 如123 然后断网发消息,退出,联网再进来,消息会异常。

网络正常情况下,都没问题,一旦网络异常,就会各种异常,希望加强下弱网或者无网情况下的测试.
老版本在无网情况下还能看看会话,消息记录,现在无网基本什么都做不了

**Comment by shingohu** [comment]
断网下发消息异常这块的bug非常严重,严重到无法使用了. demo都是很容易重现的  
问题2 参考demo中 拉取消息时,发送中的自动重发,我这边会新增一条消息,也就是会出现重复消息，demo中会自动重发成功,但是退出登录在进来发现消息变成了2条,一条成功的一条是失败的

**Comment by lynxzhang** [comment]
感谢您的反馈，断网重连相关的问题我们正在优化

**Comment by whalehe** [comment]
请您更新下新版本验证此问题
