### ISSUE TITLE
【企业微信小程序】-【2.12.1】：【使用中出现访问链接存在安全风险，api.im.qcloud.com】

### ISSUE THREAD

**Issue by kido050313** [tencentyun/TIMSDK#1042]
【集成包】：IMSDK
【当前现象】：企业微信小程序使用im时，偶然出现安全风险提示，非必现。经查这个域名（api.im.qcloud.com）在sdk中已经不存在了，所以想请问为何会出现这个提示，如何解决。用户使用时出现这种提示对我们产品很影响。具体现象如下图：
![image](https://user-images.githubusercontent.com/29145782/134303054-a0a8807d-6570-46d3-a0f3-0801c46b3f5a.png)

【机型】：如华为Mate 20
【之前版本有无此问题】：无，首次出现
【有无日志或者截图】：暂无日志（2021-09-17 4点20左右）

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，是偶发的话增大了判断难度，可以提供下具体userid，后台排查下
技术问题 欢迎交流 q2562367495 注明来意

**Comment by kido050313** [comment]
> 您好，根据您的问题，是偶发的话增大了判断难度，可以提供下具体userid，后台排查下
> 技术问题 欢迎交流 q2562367495 注明来意
userid：13651489056
手机机型：iphone11
时间：2021-09-17 16:21

**Comment by Tencent-Alice** [comment]
您好，是只有这一个用户出现吗，访问链接还有吗，加下q，方便问题交互
