### ISSUE TITLE
android 增强版 5.6.1200 视频通话 app 在后台时 接收通话的一方，在收到离线推送的消息时通话界面不弹出,只有进程被杀死后,才能唤醒弹出

### ISSUE THREAD

**Issue by zyyzhy** [tencentyun/TIMSDK#1044]
【Android】-【5.6.1200】：【 视频通话 app 在后台时 接收通话的一方，在收到离线推送的消息时通话界面不弹出】
【集成包】：TUIKIT和 TUIKIT-LIVE
【当前现象】：android 增强版 5.6.1200 视频通话 app 在后台时 接收通话的一方，在收到离线推送的消息时通话界面不弹出,只有进程被杀死后,才能唤醒弹出
【机型】：华为P9

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，ios端是正常吗，可以视频复现看下吗
技术支撑 欢迎交流 q2562367495 注明来意
