### ISSUE TITLE
IMSDK Message.java的cloudCustomString不会持久化

### ISSUE THREAD

**Issue by yinlijun2004** [tencentyun/TIMSDK#1045]
【Android】-【5.6.1200】：【 Message.java的cloudCustomString不会保存】
【集成包】：IMSDK
【当前现象】：Android Studio集成新版本TUIKit，发现设置cloudCustomString不会保存，只会保存在内存中，不会进行持久化，也不会同步到云端。
【机型】：Android设备
【之前版本有无此问题】：有
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

请问是否什么时候可以支持，我这边在发送自定义消息后，有修改消息自定义字段的需求（比如红包的打开状态等）。请问是否有支持的计划？

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，请问cloudCustomString具体是指什么，可以描述下这一步的目的
技术问题 欢迎交流 q2562367495 注明来意

**Comment by yinlijun2004** [comment]
> 您好，根据您的问题，请问cloudCustomString具体是指什么，可以描述下这一步的目的
> 技术问题 欢迎交流 q2562367495 注明来意

cloudCustomString是com.tencent.imsdk.message.Message类里的一个字段，看注释的描述，可以作为消息的附加信息，并且可以更改并同步到云端的，所以才有此一问，另个类似的字段是localCustomString，这个字段是有用的，但是不会同步到云端。

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，cloudCustomString可以云端同步，localCustomString 是本地使用
技术问题，欢迎交流，方便交互 q2562367495  注明来意
