### ISSUE TITLE
【H5/WEB】-【5.6.1200】：无法语音视频

### ISSUE THREAD

**Issue by xiongyi1994** [tencentyun/TIMSDK#1046]
【H5/WEB】-【5.6.1200】：无法语音视频
【集成包】：IMSDK
【当前现象】：自己集成SDK和使用官方demo都无法进行语音或者视频聊天，
【机型】：Chrome浏览器
【之前版本有无此问题】：不确定
【有无日志或者截图】：
![3E749EC4871D139AE4F6F9F93C7708D4](https://user-images.githubusercontent.com/14069949/134831861-8e6441a7-55b2-4045-9822-8f2500baca02.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，web端对浏览器是有要求的，升级下浏览器版本再试试
如未解决，欢迎交流，q2562367495 注明来意

**Comment by xiongyi1994** [comment]
im的应用id要跟音视频是同一个应用id
