### ISSUE TITLE
【iOS】-【5.6.1202】：【与第三方依赖库冲突导致App启动闪退】

### ISSUE THREAD

**Issue by wbcyclist** [tencentyun/TIMSDK#1047]
请问SDK内部集成的第三方库有哪些？分别是什么版本？
现发现跟项目中集成的`Protobuf`库版本不一致导致应用闪退
<img width="1731" alt="截屏2021-09-26 下午7 04 53" src="https://user-images.githubusercontent.com/2424522/134838114-f57882f0-059a-43e3-8579-f279e6851aff.png">

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 这个问题是必现吗，   还有提供下手机型号，便于进一步定位case 
技术问题 欢迎交流  Q2562367495 注明来意

**Comment by wbcyclist** [comment]
> 您好 根据您的问题 这个问题是必现吗， 还有提供下手机型号，便于进一步定位case
> 技术问题 欢迎交流 Q2562367495 注明来意

你好，这跟手机型号无关，是必现的。麻烦能找下你们那边的研发问问SDK用的Protobuf库是什么版本吗？我这边知道你们SDK用的版本对齐下就行了。

**Comment by Tencent-Alice** [comment]
您好 关于您的问题，增强版的 Protobuf 是自己写的，并不是第三方库，请知悉。具体的报错相关信息不是imsdk framework ，可以先自行检查下
如还有问题 欢迎交流 方便沟通

**Comment by wbcyclist** [comment]
> 您好 关于您的问题，增强版的 Protobuf 是自己写的，并不是第三方库，请知悉。具体的报错相关信息不是imsdk framework ，可以先自行检查下
> 如还有问题 欢迎交流 方便沟通

空项目集成imsdk与另外一个有依赖`Protobuf`的sdk就会报错，我们这边是这么定位库冲突导致的。
请问你们SDK内部的`Protobuf`增强版是以开源的哪个版本进行改动？
