### ISSUE TITLE
Didn't find class "com.tencent.imsdk.session.SessionBroadcastReceiver"

### ISSUE THREAD

**Issue by chenheqiang** [tencentyun/TIMSDK#1062]
【Android】-【com.tencent.imsdk:imsdk:5.1.66】：【找不到SessionBroadcastReceiver类】
【集成包】：com.tencent.imsdk:imsdk:5.1.66
【当前现象】：线上爆出一个Mi Note3 手机crash，目前只有这一个
【机型】：Mi Note3 Android 9系统
【之前版本有无此问题】：之前版本是 com.tencent.imsdk:imsdk:4.5.45 没有出现过 。新版本升级到5.1.66出现
【有无日志或者截图】：

 java.lang.ClassNotFoundException
Didn't find class "com.tencent.imsdk.session.SessionBroadcastReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xueqiu.android-Idk-MyA_EUIkHGAFcw65jA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xueqiu.android-Idk-MyA_EUIkHGAFcw65jA==/lib/arm, /data/app/com.xueqiu.android-Idk-MyA_EUIkHGAFcw65jA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]

**Comment by vinsonswang** [comment]
把 manifest 中的注册的 SessionBroadcastReceiver 删掉即可，新版本不用在配置文件中注册任何广播和服务。
