### ISSUE TITLE
运行demo 报错  Default FirebaseApp is not initialized . 

### ISSUE THREAD

**Issue by EmperorBoBo** [tencentyun/TIMSDK#1080]
【Android】-【】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT  
【当前现象】：Android Studio集成最新新版本TUIKit，升级到gradle 7.0.2  运行demo, 无法编译通过，直接崩溃，Default FirebaseApp is not initialized . 
【机型】：谷歌pixel 4 
【之前版本有无此问题】：TUIKIT 4.4.479版本之前没有，4.4.479有
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/17866576/146625691-59949297-f5d0-4c10-bba4-f717385c8877.png)

**Comment by mattak** [comment]
The same issue happens to me.
I fixed by adding following firebase dependencies and download google-services.json

```
    implementation platform('com.google.firebase:firebase-bom:30.2.0')
    implementation "com.google.firebase:firebase-messaging"
    implementation "com.google.firebase:firebase-crashlytics"
    implementation "com.google.firebase:firebase-analytics"
    implementation "com.google.firebase:firebase-iid"
```
