### ISSUE TITLE
【Android】-【6.0.1975】：【Error inflating class com.tencent.qcloud.tuikit.tuichat.ui.view.ChatView】

### ISSUE THREAD

**Issue by Chen-Xi-g** [tencentyun/TIMSDK#1104]
issue标题：TUIKit 单独使用TUIC2CChatFragment 奔溃闪退

【Android】-【6.0.1975】：【Error inflating class com.tencent.qcloud.tuikit.tuichat.ui.view.ChatView】
issue内容：

【当前现象】：项目中引入TuiKit，单独使用TUIC2CChatFragment时候报错闪退。
【集成包】：IMSDK
【机型】：所有机型
【之前版本有无此问题】：第一次集成，之前也集成过没有遇到相关问题
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/37918545/155706467-f96f469f-0dff-4fbe-a5b7-257796122195.png)

[堆栈日志.txt](https://github.com/tencentyun/TIMSDK/files/8140688/default.txt)

**Comment by Chen-Xi-g** [comment]
目前推测错误原因在新版本的 新增皮肤设置能力, 现在将进行尝试修复, 成功后请求Pull Request

**Comment by Chen-Xi-g** [comment]
当前版本TUIKit感觉并不是很友好，个别项目中的Theme设置并非一致。引入项目还需要设置预定义属性默认值。

**Comment by harperhpliu** [comment]
感谢您为我们发现了一个问题。由于担心 TUIKit 自定义的主题与用户设置的主题冲突，所以在 TUICore  的 TUIThemeManager 中只为实现了 ITUIThemeChangeable 接口的 Activity 设置主题。您可以为您的 Activity 实现此接口以表明适配换肤。

这个规则过于隐晦，我们考虑在下个版本去掉。感谢您的建议。

**Comment by Chen-Xi-g** [comment]
@harperhpliu 我有一个小建议。比如主题功能，可以分离需要替换的控件样式，通过代理模式，在TUICore和其他的扩展模块中设置默认的属性值。如果用户需要自定义，只需要实现接口并且传递自己的资源文件ID。这样对用户来说会更加便捷，也可以更自由的自定义，也不会出现因为Theme需要赋予默认值造成异常。
