### ISSUE TITLE
iOS 请问关系链完善完了吗？

### ISSUE THREAD

**Issue by iOSniuniu** [tencentyun/TIMSDK#112]
请问iOS最新版本关系链完善好了吗？

**Comment by vinsonswang** [comment]
已经完善了，可以用最新版本4.3.81

**Comment by iOSniuniu** [comment]
您好！我pod下来，没有发现 检查指定好友关系接口
- (int)checkFriends:(TIMFriendCheckInfo*)checkInfo succ:(TIMFriendCheckSucc)succ fail:(TIMFail)fail;

**Comment by iOSniuniu** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/23394247/57291310-c40b1280-70f1-11e9-985d-145a9c5d695e.png"> 之前 iOS3.2.2  SDK版本 这几个接口都没有

**Comment by vinsonswang** [comment]
1、checkFriends这个接口我们下个版本补上，目前可以用getFriendList来判断在不在列表里来间接判断
2、现在是获取所有好友资料接口getFriendList，回调包含所有好友关系链资料和好友的用户资料
3、新版本接口是TIMFriendshipManager中的getFriendGroups
详细接口说明可以见官网文档：https://cloud.tencent.com/document/product/269/33927#.E8.8E.B7.E5.8F.96.E6.89.80.E6.9C.89.E5.A5.BD.E5.8F.8B

**Comment by iOSniuniu** [comment]
请问下个版本什么时候更新呢？

**Comment by vinsonswang** [comment]
checkFriends这个接口我们下个版本补上
-------
这周要发的版本里来不及带上了，计划在5月底的版本里带上

**Comment by iOSniuniu** [comment]
您好！我pod 了 4.3.135 版本
<img width="877" alt="image" src="https://user-images.githubusercontent.com/23394247/58677682-89fafc80-838f-11e9-9701-049b9d9b8e03.png">
这个方法没有找到

**Comment by iOSniuniu** [comment]
您好！ 请问 群监听 TIMGroupListener 在新版本中废弃调了吗？
![image](https://user-images.githubusercontent.com/23394247/58859415-50eac100-86dc-11e9-8fb9-15dc1e56b97c.png)

**Comment by whalehe** [comment]
您好，iOS关系链已完善，可以升级到最新版本
