### ISSUE TITLE
Android 4.3.81版本，TIMConversationExt拉取消息列表，拉出了很多OnLineMessage

### ISSUE THREAD

**Issue by aoomeo** [tencentyun/TIMSDK#114]
Android4.3.81版本，通过TIMConversationExt.getMessage获取最近消息，拉出了很多OnlineMessage。卸载后，能正确拉出非OnlineMessage。有没有接口或者方法能拉出非OnlineMessage的List？

**Comment by lynxzhang** [comment]
感谢您的反馈，后续我们会优化这个问题

**Comment by aoomeo** [comment]
@lynxzhang 若修复好了这个问题，请通知我一下，以便我更新imsdk

**Comment by vinsonswang** [comment]
明天的版本会修复这个问题

**Comment by lynxzhang** [comment]
您好，这个问题已经优化，麻烦更新最新的 4.3.118版本
