### ISSUE TITLE
【iOS】-【4.4.479】：【好友申请列表,信息不全,有名字没有头像怎么显示,会补吗?】

### ISSUE THREAD

**Issue by gengqizhi** [tencentyun/TIMSDK#115]
/**
 * 未决请求
 */
@interface TIMFriendPendencyItem : TIMCodingModel

/**
 * 用户标识
 */
@property(nonatomic,strong) NSString* identifier;
/**
 * 增加时间
 */
@property(nonatomic,assign) uint64_t addTime;
/**
 * 来源
 */
@property(nonatomic,strong) NSString* addSource;
/**
 * 加好友附言
 */
@property(nonatomic,strong) NSString* addWording;

/**
 * 加好友昵称
 */
@property(nonatomic,strong) NSString* nickname;

/**
 * 未决请求类型
 */
@property(nonatomic,assign) TIMPendencyType type;

@end

**Comment by annidy** [comment]
头像可以通过getUserProfile接口获取到
