### ISSUE TITLE
Android 4.3.81 6012请求超时

### ISSUE THREAD

**Issue by liukai2530533** [tencentyun/TIMSDK#116]
按文档调用登录接口-就是超时  但是debug断点的情况下又可以登录成功  这是什么情况

**Comment by liukai2530533** [comment]
1	#00 pc 00013786 /data/app/com.guadou.imcomponentrunalone-2/lib/arm/libsession.so [armeabi-v7a]
2	#01 pc 0002710f /data/app/com.guadou.imcomponentrunalone-2/lib/arm/libsession.so [armeabi-v7a]
3	#02 pc 000270f7 /data/app/com.guadou.imcomponentrunalone-2/lib/arm/libsession.so [armeabi-v7a]
4	#03 pc 00027253 /data/app/com.guadou.imcomponentrunalone-2/lib/arm/libsession.so [armeabi-v7a]
5	#04 pc 0002d573 /data/app/com.guadou.imcomponentrunalone-2/lib/arm/libsession.so [armeabi-v7a]
6	#05 pc 000304c9 /data/app/com.guadou.imcomponentrunalone-2/lib/arm/libsession.so [armeabi-v7a]
7	#06 pc 0003f567 /system/lib/libc.so (__pthread_start(void*)+30) [armeabi-v7a]
8	#07 pc 00019c37 /system/lib/libc.so (__start_thread+6) [armeabi-v7a]

**Comment by liukai2530533** [comment]
试过各种页面各种环境，在非debug断点情况下，很少能登录成功。只有少数情况能登录成功，就算登录成功多半会崩溃，信息如下

#00 pc 0000000000042f68 /data/app/com.guadou.imcomponentrunalone-2YzxdlOu0KMVeHO6fE4gNA==/lib/arm64/libsession.so [arm64-v8a]
--
2 #01 pc 000000000004de94 /data/app/com.guadou.imcomponentrunalone-2YzxdlOu0KMVeHO6fE4gNA==/lib/arm64/libsession.so [arm64-v8a]
3 #02 pc 0000000000052cb8 /data/app/com.guadou.imcomponentrunalone-2YzxdlOu0KMVeHO6fE4gNA==/lib/arm64/libsession.so [arm64-v8a]
4 #03 pc 0000000000082e10 /system/lib64/libc.so (__pthread_start(void*)+36) [arm64-v8a]
5 #04 pc 0000000000024080 /system/lib64/libc.so (__start_thread+68) [arm64-v8a]

**Comment by kenvies** [comment]
这个问题你是怎么解决的

**Comment by whalehe** [comment]
您好，6012问题做过较大优化，可以升级到新版本验证下。
