### ISSUE TITLE
无法搜索到118这个版本

### ISSUE THREAD

**Issue by 616115891** [tencentyun/TIMSDK#123]
<img width="544" alt="屏幕快照 2019-05-15 下午2 32 44" src="https://user-images.githubusercontent.com/14053894/57753293-5cbb1700-771e-11e9-9129-58e0ec487cb5.png">

**Comment by lynxzhang** [comment]
-> TXIMSDK_iOS (4.3.118)
   TXIMSDK_iOS
   pod 'TXIMSDK_iOS', '~> 4.3.118'
   - Homepage: https://cloud.tencent.com/document/product/269/3794
   - Source:   https://github.com/tencentyun/TIMSDK.git
   - Versions: 4.3.118, 4.3.81, 4.2.52, 4.2.28, 4.2.10, 4.2.9, 4.2.2, 4.2.1,
   4.0.13, 4.0.12, 4.0.10, 4.0.8, 4.0.7, 4.0.4, 4.0.3, 4.0.2, 4.0.1 [master
   repo]

**Comment by lynxzhang** [comment]
-> TXIMSDK_iOS (4.3.118)
   TXIMSDK_iOS
   pod 'TXIMSDK_iOS', '~> 4.3.118'
   - Homepage: https://cloud.tencent.com/document/product/269/3794
   - Source:   https://github.com/tencentyun/TIMSDK.git
   - Versions: 4.3.118, 4.3.81, 4.2.52, 4.2.28, 4.2.10, 4.2.9, 4.2.2, 4.2.1,
   4.0.13, 4.0.12, 4.0.10, 4.0.8, 4.0.7, 4.0.4, 4.0.3, 4.0.2, 4.0.1 [master
   repo]

**Comment by lynxzhang** [comment]
pod search 失败：
pod setup
pod repo update
rm ~/Library/Caches/CocoaPods/search_index.json
执行下上面的命令试下

**Comment by 616115891** [comment]
> pod search 失败：
> pod setup
> pod repo update
> rm ~/Library/Caches/CocoaPods/search_index.json
> 执行下上面的命令试下

我试试
