### ISSUE TITLE
相同网络环境和代码逻辑下, 118 版本 IM 登陆超时 6012, 回退 81 版本正常

### ISSUE THREAD

**Issue by fectong** [tencentyun/TIMSDK#124]

**Comment by vinsonswang** [comment]
请问下，是哪个接口的onSuccess没有回调？

**Comment by fectong** [comment]
> 请问下，是哪个接口的onSuccess没有回调？

TIMManager.getInstance().login(String identifier, String userSig, TIMCallBack callback)
后来我又跟了下, 发现等待一段时间后 onError 回调 code 6012 | 超时 (可以确定当时网络是没问题的)
试了十几次没登陆成功, 回退到81版本后就好了

**Comment by SeniorDoctorHui** [comment]
同意这点,Android118确实会莫名超时

**Comment by fairytale110** [comment]
你们问题挺多呀

**Comment by vinsonswang** [comment]
这周会发版本优化网络情况

**Comment by whalehe** [comment]
您好，6012问题，最新版本有较大优化，可以升级到最新版本验证下。
