### ISSUE TITLE
TIMManagerExt.getInstance().deleteConversationAndLocalMsgs 崩溃

### ISSUE THREAD

**Issue by fairytale110** [tencentyun/TIMSDK#125]
当长按删除无效单聊会话时，导致崩溃。
版本：通过TUIKit集成，4.3.118

![image](https://user-images.githubusercontent.com/30248926/57839841-0d4a1900-77fa-11e9-98b2-15b8bc7e50d8.png)

![image](https://user-images.githubusercontent.com/30248926/57839578-93b22b00-77f9-11e9-86af-aa7aebf7234f.png)

**Comment by vinsonswang** [comment]
新版本 4.3.135 解决了，可以更新下版本
