### ISSUE TITLE
获取群组自定义字段  size=0

### ISSUE THREAD

**Issue by meihuali** [tencentyun/TIMSDK#128]
/**
 * 获取群组自定义字段 map
 * @return 群组自定义字段 map
 */
public Map<String, byte[]> getCustom()    这个方法取出来size=0

**Comment by lynxzhang** [comment]
1、控制台上配置 private类型的群的   群维度（比如group_info）和 群成员维度（比如group_member）  的自定义字段后
![CB7A1198FE01E15C13542AC5E8A4E754](https://user-images.githubusercontent.com/12908172/57919512-85ccda80-78cb-11e9-9b47-4255f740bb34.jpg)

**Comment by vinsonswang** [comment]
需要在登录 IM SDK 之前，设置自定义的拉取字段，通过 TIMGroupSettings 进行相应的设置，可以参考官网文档示例代码
https://cloud.tencent.com/document/product/269/9236#.E8.AE.BE.E7.BD.AE.E6.8B.89.E5.8F.96.E5.AD.97.E6.AE.B5
