### ISSUE TITLE
TUIKit 用的是3.5版本的IM SDK，跟官网最新的4.0版本没什么区别

### ISSUE THREAD

**Issue by shelby-yao** [tencentyun/TIMSDK#13]
TUIKit 用的是3.5版本的IM SDK，跟官网最新的4.0版本没什么区别

我用的3.3.2的官方SDK发现不一样额？官方有4.0sdk了吗？前几天下的只有IM_iOS_SDK_2.7.2和IM_iOS_SDK_3.3.2

**Comment by rexchang2016** [comment]
您好，当前 github 里的就是 4.0 的 SDK， 4.0 相比于 3.5 的区别在于，4.0 是完全重写的。
