### ISSUE TITLE
libImSDKCore崩溃，希望对你们有帮助

### ISSUE THREAD

**Issue by Gloud-Zhao** [tencentyun/TIMSDK#132]
backtrace:
    #00 pc 0002b258  /data/app/cn.xx.xx/lib/arm/libImSDKCore.so (_ZN6imcore10DataReport14ReportInternalEv+127)
    #01 pc 0002ad25  /data/app/cn.xx.xx/lib/arm/libImSDKCore.so (_ZN6imcore10DataReport6ReportERKNS_10ReportItemE+496)
    #02 pc 00044cf1  /data/app/cn.xx.xx/lib/arm/libImSDKCore.so
    #03 pc 0002e111  /data/app/cn.xx.xx/lib/arm/libImSDKCore.so

**Comment by yvonneyl** [comment]
同崩溃

**Comment by lynxzhang** [comment]
感谢您的反馈，我们定位下

**Comment by Gloud-Zhao** [comment]
> 感谢您的反馈，我们定位下

4.3.18Android版貌似问题挺多的，目前我们线上用号看 Bugly上崩溃的挺多的，最近两周Tim好像不更新了，不像之前四五天一个版

**Comment by lynxzhang** [comment]
新版本已经发布，优化了一些crash问题，麻烦更新下，另外你们这边的crash堆栈也可以贴下，我们会定位解决
