### ISSUE TITLE
Android onRefreshConversation回调问题

### ISSUE THREAD

**Issue by AnJiuZhe** [tencentyun/TIMSDK#135]
TUKIT初始化后，调用login方法登录，为什么onRefreshConversation这个方法会回调两次？而且两次的List<TIMConversation> conversations是一样的数据。
![image](https://user-images.githubusercontent.com/30287547/58166827-3c123480-7cbd-11e9-99e1-2960f8b60e43.png)

**Comment by vinsonswang** [comment]
感谢反馈，明天的版本会修复这个问题
