### ISSUE TITLE
iOS 4.3.118 关系链监听器的两个问题

### ISSUE THREAD

**Issue by LearnGittt** [tencentyun/TIMSDK#136]
1.当好友更改资料时，会收到- (void)onFriendProfileUpdate:(NSArray *)profiles 回调，但是数组里的TIMSNSChangeInfo信息全是空的，连identifier都没有；
2.当收到好友请求和发送好友请求时都会走- (void)onAddFriendReqs:(NSArray<TIMFriendPendencyInfo *> *)reqs 回调，但是TIMFriendPendencyInfo里并不包含加还是被加的信息，所以在onAddFriendReqs里无法判断是谁加谁。建议要么发送好友请求时别走回调，要么把TIMFriendPendencyInfo改为TIMFriendPendencyItem。

**Comment by lynxzhang** [comment]
感谢您的反馈，今天会发新版本，问题一的 identifier 和 昵称信息会带上，其他的问题因为时间原因今天的版本跟不上了，我们已经收集整理，会在下个版本一起彻底优化。

**Comment by whalehe** [comment]
您好，可以更新到4.4.627版本，验证下。
