### ISSUE TITLE
新版本集成问题

### ISSUE THREAD

**Issue by jun-hui** [tencentyun/TIMSDK#137]
1、初始化SDK和登录都没收到回调，只能从返回的int类型数据判断吗？
2、使用demo里面的代码，看不到输入框（demo正常）
3、viewDidAppear方法里重新布局frame后输入框显示正常，但是消息发送不出去，一直在转圈，同时控制台打印 date cannot be nil

**Comment by lynxzhang** [comment]
1、initSdk 可以通过return的 int 值判断是否返回成功，登录 login 成功和失败都是有回调的，可以参考下demo的代码

**Comment by jun-hui** [comment]
你好，登录的确实没有走回调，代码是完全按照demo上写的, 不论是我们自己的用户签名还是官网生成的签名在登录的时候都没有走回调，控制台也没看到有错误信息；消息发送的时候时间是空的，控制台会提示时间是nil，消息发送没提示，应该是没登录成功，所以发送消息没提示

**Comment by jun-hui** [comment]
找到问题了，登录方法写在主线程中就可以了
