### ISSUE TITLE
和matisse库冲突

### ISSUE THREAD

**Issue by ooftf** [tencentyun/TIMSDK#139]
tuikit和matisse库都使用了activity_matisse.xml，但是内部布局却不一样导致引起
 java.lang.ClassCastException: com.tencent.qcloud.uikit.common.component.picture.internal.ui.widget.CheckRadioView cannot be cast to com.zhihu.matisse.internal.ui.widget.CheckRadioView
tuikit能不能把activity_matisse.xml的名字改一下

**Comment by parkhuang** [comment]
我们有可能会在未来的版本里去掉matisse的使用，当前您可以先在代码里面用全类名即包名+类名的方式来使用相同类名的不同类。

**Comment by ooftf** [comment]
> 我们有可能会在未来的版本里去掉matisse的使用，当前您可以先在代码里面用全类名即包名+类名的方式来使用相同类名的不同类。
> 
> 如果仍然有问题，可以把您使用的代码贴上来

不是类的的问题，而是res资源文件重名问题，这种问题除非我们下载源码重新自己打包，我还没有找到其他方法

**Comment by whalehe** [comment]
最新版本已经修改，可以更新验证此问题。

**Comment by ooftf** [comment]
这个问题已验证修改，但是又发现一个类似的问题#183
