### ISSUE TITLE
2019.5.24号你们发布的135版本的iOS pod文件的路径配置的是错的

### ISSUE THREAD

**Issue by wujiangwei** [tencentyun/TIMSDK#142]
麻烦改正下，你们的客户用pod更新下，全部都是找不到头文件了。
更新这么随便的么，pod路径都写错
不测试的下....

**Comment by wujiangwei** [comment]
![image](https://user-images.githubusercontent.com/2360576/58380381-06ce5500-7fe3-11e9-889e-3450819f6f57.png)
![image](https://user-images.githubusercontent.com/2360576/58380382-0c2b9f80-7fe3-11e9-8aeb-93e90123224f.png)

**Comment by wujiangwei** [comment]
你们的iOS SDK问题真多。
要么就是更新了bug，你们的pod不更新。
要么就是更新了pod，有问题。

**Comment by wujiangwei** [comment]
发布环节可以优化下么。

**Comment by lynxzhang** [comment]
好的，感谢您的反馈，我们马上优化下
