### ISSUE TITLE
4.3.135  setAccoutType 没有这个方法了？

### ISSUE THREAD

**Issue by DSYliangweihao** [tencentyun/TIMSDK#143]
TIMSdkConfig config = new TIMSdkConfig(sdkAppId) 
	.setAccoutType(accountType) 这个方法在这个版本没有了

**Comment by vinsonswang** [comment]
是的，废弃了

**Comment by DSYliangweihao** [comment]
麻烦在文档里里面也更一下吧

**Comment by vinsonswang** [comment]
后面会统一出一份接口变更的文档
