### ISSUE TITLE
tuikit android源码集成编译报错

### ISSUE THREAD

**Issue by yummyChina** [tencentyun/TIMSDK#144]
错误: 无法将类 Canvas中的方法 save应用到给定类型;
需要: 没有参数
找到: int
原因: 实际参数列表和形式参数列表长度不同

 canvas.save(Canvas.ALL_SAVE_FLAG);编译无法通过
ext {
    compileSdkVersion = 28
    minSdkVersion = 16
    targetSdkVersion = 28
    versionCode = 1
    versionName = "4.3.81"
    abiFilters = ['armeabi-v7a', 'arm64-v8a']//'arm64-v8a', 'armeabi-v7a', 'x86', 'armeabi'
    arguments = "-DANDROID_STL=c++_shared"
    cppFlags = "-std=c++11"
}
必须使用27？

**Comment by stabbkai** [comment]
改为canvas.save()就可以了

**Comment by whalehe** [comment]
解决办法：直接调canvas.save();
google在android P（28）中删除了canvas.save(int);方法
reference：https://developer.android.com/sdk/api_diff/28/changes/android.graphics.Canvas
