### ISSUE TITLE
集成和RN的库冲突

### ISSUE THREAD

**Issue by woshiluoyong** [tencentyun/TIMSDK#145]
RN项目里面android原生集成报这个错
**More than one file was found with OS independent path 'lib/arm64-v8a/libc++_shared.so',**
gradle加上这个
packagingOptions { // fix DuplicateRelativeFileException
        exclude 'lib/x86/libc++_shared.so'
        exclude 'lib/arm64-v8a/libc++_shared.so'
        exclude 'lib/x86_64/libc++_shared.so'
        exclude 'lib/armeabi-v7a/libc++_shared.so'
    },郁闷,折腾好久!!!

这个目前我的处理方案是不直接依赖tuikit项目
1).先把
1.imsdk-4.3.135.aar用命令:unzip imsdk-4.3.135.aar -d tempFolder解压
2.然后进入jni目录里面把下面每个目录里面的libc++_shared.so删掉
3.再执行命令jar cvf imsdk-4.3.135-new.aar -C tempFolder/ .压缩成aar
4.项目再依赖imsdk-4.3.135-new.aar即可

2).再把tuikit项目的:
1.assets目录文件
2.包com.tencent.qcloud.uikit下面的源码
3.res下面的资源文件
4.AndroidManifest.xml里面的配置
5.build.gradle文件里面的除了导入imsdk代码全部配置
这些东西直接依赖到业务项目

希望对各位有帮助!折腾爽了!!

编译运行又报im的jni实现找不到:
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.imsdk.conversation.ConversationManager.nativeGetConversations(java.util.List) (tried Java_com_tencent_imsdk_conversation_ConversationManager_nativeGetConversations and Java_com_tencent_imsdk_conversation_ConversationManager_nativeGetConversations__Ljava_util_List_2)(这个报错自己的锅:是因为没调TUIKit.init初始化原因)

**Comment by kurisu994** [comment]
我加了 ` packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
` 就没问题了

**Comment by woshiluoyong** [comment]
大概是我依赖的库和这个库里面依赖的shared.so冲突了
