### ISSUE TITLE
iOS ImSDK内部缺失 TIMFriendshipManager

### ISSUE THREAD

**Issue by lf-sytc** [tencentyun/TIMSDK#15]
TIMFriendshipManager 整个被移除掉了

**Comment by liukai2530533** [comment]
Android 一样的，还不够完善不能在项目中使用，好友关系链的相关路径的类都没有 com.tencent.imsdk.TIMFriendshipManager;

我看demo中的联系人，好友之类的都没有完善 写的是敬请期待，估计也是没有写好

**Comment by liukai2530533** [comment]
好友关系链的相关拓展包 com.tencent.imsdk.ext.sns.TIMFriendFutureItem;  都是缺失的

**Comment by lf-sytc** [comment]
之前在腾讯云官网上下载的sdk是有的 
现在统一迁移到Github上 就缺失了

**Comment by 814349837** [comment]
那现在的sdk基本上不能替换之前？

**Comment by lynxzhang** [comment]
这里统一回复下，新版本重构重点优化了SDK稳定性和安装包体积，因为时间原因，TIMFriendshipManager 逻辑还没加上，这个正在开发，预计3月初上线，对关系链逻辑需求强烈的建议先等下，暂时不要更新新的版本。
