### ISSUE TITLE
system load so library failed, libImSDKCore.so

### ISSUE THREAD

**Issue by kurisu994** [tencentyun/TIMSDK#152]
`E/art: dlopen("/data/app/com.xxx.xxx-2/lib/arm64/libImSDKCore.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.xxx.xxx-2/lib/arm64/libImSDKCore.so"...
05-30 11:09:37.585 25500-25644/com.xxx.xxx E/NativeManager: system load so library failed, libImSDKCore.so 
     exception : java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.xxx.xxx-2/lib/arm64/libImSDKCore.so"...

E/art: No implementation found for void com.tencent.imsdk.manager.NativeManager.nativeSetUserConfig(com.tencent.imsdk.TIMUserConfig) (tried Java_com_tencent_imsdk_manager_NativeManager_nativeSetUserConfig and Java_com_tencent_imsdk_manager_NativeManager_nativeSetUserConfig__Lcom_tencent_imsdk_TIMUserConfig_2)
`
初始化就崩溃
设备型号：oppo R9
cup信息：

Processor	: AArch64 Processor rev 2 (aarch64)
processor	: 0
BogoMIPS	: 26.00
Features	: fp asimd aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

Hardware	: MT6755

**Comment by whalehe** [comment]
您好，可以用最新版本验证下~
