### ISSUE TITLE
iOS调用- (int)logout:(TIMLoginSucc)succ fail:(TIMFail)fail;返回code -1

### ISSUE THREAD

**Issue by ZiShengXie** [tencentyun/TIMSDK#156]
如题，调用TIMManager - (int)logout:(TIMLoginSucc)succ fail:(TIMFail)fail 的方法返回code:"-1" err:"stat_reg req:parsing failed" 常见错误里没有说明这个是什么错误。请问是什么情况下会返回这个？

**Comment by whalehe** [comment]
您好，tinyid==0或者解包失败都会返回-1，可以升级到最新版本验证此问题，如有复现，按照issue模板，提供下具体信息：https://github.com/tencentyun/TIMSDK/issues/176
