### ISSUE TITLE
【小程序版本】：【能否提供websocket版本？】

### ISSUE THREAD

**Issue by crazyevent** [tencentyun/TIMSDK#158]
看到那一串的http请求脑壳疼，最重要的是，似乎有内存泄露，im挂久了连小程序IDE都挂掉了。

**Comment by rexchang2016** [comment]
感谢您的反馈，正在基于 websocket 开发新版本的 websdk 版本，预计还要 1 个多月时间

**Comment by WGinit** [comment]
您好，websocket 版本更新了吗
