### ISSUE TITLE
请问设置好友备注和好友自定义字段 什么时候添加

### ISSUE THREAD

**Issue by iOSniuniu** [tencentyun/TIMSDK#159]
请问设置好友备注和好友自定义字段 V4版本 什么时候添加
![image](https://user-images.githubusercontent.com/23394247/58940357-dab58f80-87ab-11e9-8878-aa8869c4cab4.png)

**Comment by lynxzhang** [comment]
已经添加，请调用 TIMFriendshipManager.h 里面的 modifySelfProfile 函数设置
