### ISSUE TITLE
【小程序版本】：【未读计数webim.MsgStore.sessMap()是空的】

### ISSUE THREAD

**Issue by DerrickYang007** [tencentyun/TIMSDK#162]
var skey= 'C2Czhangsan';    // 拼装 skey
var sessMap = webim.MsgStore.sessMap();    // 获取 sessMap
sessMap[skey].unread();    // 获取未读消息记数
这个是云通信官方文档中的例子。
用户对用户私聊时使用的代码。

我的好友会话列表要显示好友消息未读计数。
我使用webim.MsgStore.seeMap()后 sessMap为空，一条会话都没有。
但是我用 获得历史会话列表 api    
getRecentContactList 是可以获得会话数据的。
为啥这个webim.MsgStore.seeMap()获取不到？
我是在小程序中使用的。

**Comment by yangq1990** [comment]
hi，请参考以下内容：

新版小程序 im:
https://github.com/tencentyun/TIMSDK/tree/master/WXMini
sdk文档：
https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/TIM.html
