### ISSUE TITLE
安卓版本 4.3.145集成问题

### ISSUE THREAD

**Issue by JiaRui-Shi** [tencentyun/TIMSDK#165]
报错信息：
java.lang.UnsatisfiedLinkError: Native method not found: com.tencent.imsdk.manager.NativeManager.nativeGetVersion:()Ljava/lang/String;

**Comment by JiaRui-Shi** [comment]
SO包的问题，已解决

**Comment by hoffergg** [comment]
> SO包的问题，已解决

怎么解决的啊？
