### ISSUE TITLE
【iOS】-【4.3.145】：【集成TUIKit，聊天列表不能显示头像和昵称】

### ISSUE THREAD

**Issue by sunleic** [tencentyun/TIMSDK#166]
c to c 聊天的时候，昵称的值是ID，头像是写死的本地头像

**Comment by xionganyin** [comment]
我也遇到这个问题了，好像是因为的TMIMSDK_TUIKit_iOS.podspec有问题，可以把TUIKitFace.bundle和TUIKitResource.bundle手动拷贝到项目，然后添加资源引用来临时解决。具体见图
![image](https://user-images.githubusercontent.com/4514707/59530985-7adf8700-8f17-11e9-9628-1a440197e33a.png)

**Comment by sunleic** [comment]
> 我也遇到这个问题了，好像是因为的TMIMSDK_TUIKit_iOS.podspec有问题，可以把TUIKitFace.bundle和TUIKitResource.bundle手动拷贝到项目，然后添加资源引用来临时解决。具体见图
> ![image](https://user-images.githubusercontent.com/4514707/59530985-7adf8700-8f17-11e9-9628-1a440197e33a.png)

不是默认头像这个意思，是说真实的头像和昵称没有显示

**Comment by fairytale110** [comment]
我是直接导入TUIKit源码的，方便配合业务改，要TuiKit完全符合每个人的胃口我觉得不现实，建议你也这样，自己改改很好用的。


![image](https://user-images.githubusercontent.com/30248926/59814401-cba41500-9347-11e9-9a33-348b267f425b.png)

**Comment by annidy** [comment]
> > 我也遇到这个问题了，好像是因为的TMIMSDK_TUIKit_iOS.podspec有问题，可以把TUIKitFace.bundle和TUIKitResource.bundle手动拷贝到项目，然后添加资源引用来临时解决。具体见图
> > ![image](https://user-images.githubusercontent.com/4514707/59530985-7adf8700-8f17-11e9-9628-1a440197e33a.png)
> 
> 不是默认头像这个意思，是说真实的头像和昵称没有显示

C2C不显示昵称，GROUP消息才显示昵称

**Comment by whalehe** [comment]
目前使用Demo中使用网络随机头像，点击修改头像，就可以请求一张网络图片作为头像，可以参考最新Demo代码，如果您需要自己上传头像，需要对应服务器存头像图片。请知悉~

C2C不显示昵称（聊天界面标题就是对方昵称或者ID），GROUP消息才显示昵称
