### ISSUE TITLE
iOS 4.4.479 全新的UI设计在哪里体现了？？

### ISSUE THREAD

**Issue by fairytale110** [tencentyun/TIMSDK#169]
iOS 4.4.479 全新的UI设计在哪里体现了？？
为什么TUIKitDemo里面运行起来和旧版本毫无区别？？

**Comment by whalehe** [comment]
您好，目前TUIKit代码结构都变了，还有bugfix。资料页，聊天区域消息气泡等。如果您的项目已经写了一套自己的UI的，就不建议您升级。

**Comment by fairytale110** [comment]
好的。，谢谢
