### ISSUE TITLE
不理解啊

### ISSUE THREAD

**Issue by jj89757hhb** [tencentyun/TIMSDK#17]
运行了 但是没看到账号注册入口？我怎么通过程序注册账号？ 而不是通过管理后台

**Comment by vinsonswang** [comment]
管理后台签发userSig只是用来做调试用的。正确签发方式是把生成userSig代码部署在您的服务器上，APP根据不同账号向服务器请求对应的userSig，可以参考[服务器生成 UserSig 方案](https://cloud.tencent.com/document/product/269/32688#.E6.9C.8D.E5.8A.A1.E5.99.A8.E7.94.9F.E6.88.90-usersig)  和  [帐号登录集成说明](https://cloud.tencent.com/document/product/269/1507)

**Comment by ls19491314** [comment]
必须要有自己的服务器吗？不能通过TIM 注册账号设置密码吗

**Comment by vinsonswang** [comment]
> 必须要有自己的服务器吗？不能通过TIM 注册账号设置密码吗

TIM只负责用userID和userSig登录IM后台，账号登录如果需要密码的话是需要自己搭服务器器维护账号密码的
