### ISSUE TITLE
TUIKit Android搭建完成后，运行报错

### ISSUE THREAD

**Issue by zlqscount** [tencentyun/TIMSDK#171]
以aar方式集成
implementation(name: 'tuikit-4.4.479', ext: 'aar')
implementation(name: 'imsdk-4.4.479', ext: 'aar')
运行app后几秒内会报错，导致闪退。

06-18 09:45:10.530 23058-23058/com.zcql.zcql E/SessionWrapper: initForNative, service not ready
06-18 09:45:10.585 23058-23058/com.zcql.zcql E/SessionWrapper: initForNative, service not ready
06-18 09:45:20.426 23058-23304/com.zcql.zcql E/AndroidRuntime: FATAL EXCEPTION: Thread-1058
    Process: com.zcql.zcql, PID: 23058
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.tencent.qcloud.tim.uikit.config.CustomFaceConfig.getFaceGroups()' on a null object reference
        at com.tencent.qcloud.tim.uikit.component.face.FaceManager$1.run(FaceManager.java:70)

**Comment by parkhuang** [comment]
问题在本周发布的版本会修复
