### ISSUE TITLE
新版tuikit4.4.479的类名是不是和文档不符啊

### ISSUE THREAD

**Issue by ooftf** [tencentyun/TIMSDK#173]
原来的GroupChatPanel现在变成哪个类啊
还有C2CChatPanel又变成哪个了
使用文档怎么还是原来的类啊，看的一脸懵逼啊
设置会话id的方法也没有实例啊，只告诉我们使用chatInfo但是没有告诉我们都需要设置哪些属性啊
变动这么打，难道不应该单独出一份迁移文档吗

**Comment by whalehe** [comment]
您好，新版本TUIKit文档链接参考：https://github.com/tencentyun/TIMSDK/wiki，官网文档正在同步更新。

issue反馈模板链接参考：
https://github.com/tencentyun/TIMSDK/wiki/TIMSDK-issue%E6%9C%89%E6%95%88%E5%8F%8D%E9%A6%88%E6%A8%A1%E6%9D%BF
