### ISSUE TITLE
iOS 自定义导航栏导致聊天界面显示不全

### ISSUE THREAD

**Issue by dsencheng** [tencentyun/TIMSDK#177]
【iOS】 - 【4.4.479】：【自定义导航栏导致无法显示聊天界面】
【当前现象】：自定义导航栏，设置 self.navigationBar.translucent = NO;  导致聊天页面显示不全。
【有无日志或者截图】：

【BaseNavigationController】
- (instancetype)initWithRootViewController:(UIViewController *)rootViewController{
    if (self = [super initWithRootViewController:rootViewController]) {
        self.navigationBar.translucent = NO;
    }
    return self;
}

【AppDelegate】
TIMConversation *conv = [[TIMManager sharedInstance] getConversation:TIM_C2C receiver:@"abc"];
    ConversationViewController *controller = [[ConversationViewController alloc] initWithConversation:conv];
    self.window.rootViewController = [[BaseNavigationController alloc] initWithRootViewController:controller];

**Comment by dsencheng** [comment]
[[UINavigationBar appearance] setBackgroundImage:[UIImage imageWithColor:[UIColor whiteColor]] forBarMetrics:UIBarMetricsDefault];

也会导致聊天页面显示不出来，这是什么bug？

**Comment by annidy** [comment]
设置 `self.navigationBar.translucent = NO` 在push后TUIChatViewController大小会改变。快速的修改方案是
```
    _inputController = [[TUIInputController alloc] init];
    _inputController.view.frame = CGRectMake(0, self.view.frame.size.height - TTextView_Height - Bottom_SafeHeight, self.view.frame.size.width, TTextView_Height + Bottom_SafeHeight);
+    _inputController.view.autoresizingMask = UIViewAutoresizingFlexibleTopMargin;
    _inputController.delegate = self;

```
