### ISSUE TITLE
【windows】-【4.4.479】WINOWS版本崩溃

### ISSUE THREAD

**Issue by lvfoxx** [tencentyun/TIMSDK#179]
【当前现象】：WINDOWS版本在频繁收到消息的时候会崩溃
【之前版本有无此问题】：之前版本没有接入过
【有无日志或者描述】： coredump文件如下

[error.log](https://github.com/tencentyun/TIMSDK/files/3304307/error.log)
[crash.dmp.log](https://github.com/tencentyun/TIMSDK/files/3304309/crash.dmp.log)

**Comment by lvfoxx** [comment]
0x2FE96B2D (imsdk.dll) (crash.dmp 中)处有未经处理的异常: 0xC0000005: 读取位置 0x00000000 时发生访问冲突
看起来像是一个空指针的问题，能否提供可以调试的pdb文件。

**Comment by whalehe** [comment]
您好，可以更新到最新版本验证下。
