### ISSUE TITLE
【iOS】-【4.4.479】：【部分机型iPhone SE，聊天界面不能正常使用】

### ISSUE THREAD

**Issue by xins134** [tencentyun/TIMSDK#181]
iPhone SE  
iOS 12.1
最新版SDK 和TUI
1.聊天界面下部分输入框没有，包括表情按钮，查看视图层级，高度为0
如图
![](https://github.com/xins134/Issues/blob/master/IMG_0029.PNG)
![](https://github.com/xins134/Issues/blob/master/Jietu20190619-114044.jpg)
2.不显示昵称，显示用户名，即ID，为何？？？？
3.头像不显示
4.别人发送失败的消息能看到？ 还能我重新发送？
5.你们先弄好一个能用的版本来吧

**Comment by fairytale110** [comment]
你先把Demo跑起来再说把，

**Comment by xins134** [comment]
@fairytale110 demo还不是不显示头像，不正确显示昵称，昵称位置显示的用户id

**Comment by annidy** [comment]
您的反馈已收到，我们会在下个版本修复此bug

**Comment by annidy** [comment]
4.4.627 已解决
