### ISSUE TITLE
【Android】-【4.4.479】：【media_grid_content布局和matisse使用名称冲突】

### ISSUE THREAD

**Issue by ooftf** [tencentyun/TIMSDK#183]
【当前现象】：Android Studio集成新版本TUIKit，使用matisse报错
【日志】：java.lang.ClassCastException: com.tencent.qcloud.tim.uikit.component.picture.internal.ui.widget.MediaGrid cannot be cast to com.zhihu.matisse.internal.ui.widget.MediaGrid
这是我第二次提出类似问题，上次问题链接#139
分析：由于TUIKIT使用了和matisse相同名称的资源文件导致
建议解决方式：TUIKIT可以为资源名称添加统一前缀防止和其他资源产生冲突

**Comment by whalehe** [comment]
已经去掉matisse库
