### ISSUE TITLE
何时才有一个完整能用TUIKIT的版本啊？

### ISSUE THREAD

**Issue by xins134** [tencentyun/TIMSDK#184]
何时才有一个完整能用TUIKIT的版本啊？
包括聊天室好友关系等，像网易的UI框架那样完整能商用的版本？

**Comment by whalehe** [comment]
您好，建议先运行我们的最新的Demo工程。更多功能还在开发中。有任何问题，反馈issue，描述按照issue模板进行反馈当前遇到的问题：https://github.com/tencentyun/TIMSDK/wiki/TIMSDK-issue%E6%9C%89%E6%95%88%E5%8F%8D%E9%A6%88%E6%A8%A1%E6%9D%BF
