### ISSUE TITLE
ios UI上图片不显示

### ISSUE THREAD

**Issue by ghostMan-sniper** [tencentyun/TIMSDK#186]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/13954365/59891345-64e63080-9407-11e9-8189-1987f864a5f3.png">
这是神马情况，咱也不知道，咱也不敢问

**Comment by firebrk** [comment]
bundle路径不对， 应该是framework的bundle

**Comment by fairytale110** [comment]
不是framework的bundle，你这是TUIkit的资源文件路径没配置对导致的，亲测

**Comment by firebrk** [comment]
意思就是TUIkit的资源文件路径按照framework的路径来配
_#define TUIKitResource(name) [[[NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"TUIKitResource" ofType:@"bundle"]] resourcePath] stringByAppendingPathComponent:name]_
这个在pod里是找不到的

**Comment by annidy** [comment]
bundle路径不对，或者TUIKitResource.bundle没有在build时拷贝到app目录
