### ISSUE TITLE
【小程序版本】：【show_one_msg.js文件中for on有bug】

### ISSUE THREAD

**Issue by xiezhaofeng** [tencentyun/TIMSDK#187]
for(var m in userIdList)在循环的时候，会比预期多循环一次，建议改成for(var m of userIdList)在show_one_msg.js里。

**Comment by yangq1990** [comment]
hi，请参考以下内容：

新版小程序 im:
https://github.com/tencentyun/TIMSDK/tree/master/WXMini
sdk文档：
https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/TIM.html
