### ISSUE TITLE
【Android】-【4.4.479】：【Demo使用GenerateTestUserSig，Android 9.0 加密报错】

### ISSUE THREAD

**Issue by EternalPlan** [tencentyun/TIMSDK#188]
我知道加密应该是服务器生成的,然后返回.
我只是想在本地测试生成,然后测试使用.

GenerateTestUserSig当中 
Signature signature = Signature.getInstance("SHA256withECDSA", "BC");

报错:
java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for Signature.SHA256withECDSA.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.

应该是9.0之后  不再提供这个加密了.

**Comment by whalehe** [comment]
您好，收到您的反馈，我们用华为Mate 10 Android 9.0系统，尝试验证是没有问题的，问下你这边机器是？机型兼容问题，我们尽快评估。

**Comment by EternalPlan** [comment]
小米8 SE 
![device-2019-06-29-134626](https://user-images.githubusercontent.com/18061136/60380219-74ebb900-9a74-11e9-8e29-e8a78b4846c2.png)

**Comment by EternalPlan** [comment]
应该不是机型的问题 而是编译版本的问题.
下面是我的版本信息:
compileSdkVersion: 28,
buildToolsVersion: "28.0.3",
minSdkVersion    : 17,
targetSdkVersion : 28
-----------------------------------------------
我的是28.
而demo版本是27.

**Comment by EternalPlan** [comment]
应该不是机型的问题 而是编译版本的问题.
下面是我的版本信息:
compileSdkVersion: 28,
buildToolsVersion: "28.0.3",
minSdkVersion : 17,
targetSdkVersion : 28
我的是28.
而demo版本是27.

**Comment by whalehe** [comment]
您好，修改方法如下，在GenerateTestUserSig.java中GenTLSSignature方法：

            Signature signature = null;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                signature = Signature.getInstance("SHA256withECDSA"); //适配Android P及以后版本，否则报错NoSuchAlgorithmException
            } else {
                signature = Signature.getInstance("SHA256withECDSA", "BC");
            }

后续版本会使用HMAC-SHA256加密算法，更简单和无兼容性问题。
