### ISSUE TITLE
【Android】-【4.4.479】： TuiKit源码集成 随机性无法登录6632

### ISSUE THREAD

**Issue by 2314372037** [tencentyun/TIMSDK#190]
【当前现象】： 通过TUIKit.login随机性无法登录，报错6632，如下日志，wifi和4g网络都有这种情况
【日志】：
data_report.cpp:169 |operator()           > report error|code:6632

session_for_android.cpp:32  |operator()           > found sended packet timeout. cmd wtlogin64.trans_emp, appSeq: 60663

transport.cpp:183 |RequestCallbackOnErrorAsync > recv error code: 6632, errmsg: Session for Android send packet timeout

**Comment by whalehe** [comment]
您好，之前双进程的问题，现在全面切换到单进程，可以再尝试用新版本验证下。
