### ISSUE TITLE
【Android】-【4.4.479】：【三星手机不能播放IOS发送过来的视频】

### ISSUE THREAD

**Issue by qiuqiutang** [tencentyun/TIMSDK#191]
当前版本：imsdk:4.4.479
问题：三星不能播放IOS发送过来的视频（以前Android IMSDK的版本也有这问题，一直存在）
（PS：Android设备发送给三星的视频是可以播放的，IOS发送给Android非三星品牌的视频也是可以播放的）

**Comment by whalehe** [comment]
你好，Android系统播放器的兼容问题，下个版本修复。

**Comment by whalehe** [comment]
4.4.900 已修复
