### ISSUE TITLE
【iOS】-【4.4.479】：【引入TUIInputController,键盘就是不能响应任何事件】

### ISSUE THREAD

**Issue by F80EZ6** [tencentyun/TIMSDK#192]
![image](https://user-images.githubusercontent.com/45870862/60074338-40ff5380-9755-11e9-9937-894c807999c7.png)
![image](https://user-images.githubusercontent.com/45870862/60074356-4bb9e880-9755-11e9-8b61-fd995954b692.png)

为什么键盘不能点击和响应????  是一个摆设

**Comment by annidy** [comment]
键盘能不能显示出来？键盘不是App控制，是系统自动显示
