### ISSUE TITLE
【需求】Android和IOS平台有没有直接将数据直接导入数据库的功能？

### ISSUE THREAD

**Issue by fengbianyun** [tencentyun/TIMSDK#193]
之前我们一直使用其它IM服务商提供的技术，但是运行了很长一段时间，发现平台并不稳定。现在需要切换到咱们IM平台，有的用户，客户端有上千条会话相关的数据，这部分数据我怎么迁移到Im平台？sdk里面是否提供了本地数据批量插入的功能？

**Comment by fengbianyun** [comment]
@whalehe @vinsonswang

**Comment by whalehe** [comment]
您好，收到您的反馈，我们会尽快评估。
