### ISSUE TITLE
BaseManager: Login failed, code 6707|msg RawData packet timeout

### ISSUE THREAD

**Issue by 2314372037** [tencentyun/TIMSDK#195]
随机性无法登录，求大神解决

**Comment by 2314372037** [comment]
transport.cpp:183 |RequestCallbackOnErrorAsync > recv error code: 6707, errmsg: RawData packet timeout

**Comment by whalehe** [comment]
您好，6707，表示网络已断开，未建立连接，或者 socket 连接时检测到无网络。可以再用最新版本验证下
