### ISSUE TITLE
SessionManager 中关于置顶项的保存和加载有bug，置顶三个，只能加载出第一个

### ISSUE THREAD

**Issue by coolstar1204** [tencentyun/TIMSDK#196]
【当前现象】：如ChatListFragemnt界面置顶多个用户，下次启动只加载出1个用户置顶。
【之前版本有无此问题】：没测试
【有无日志或者描述】：
mTopList = mSessionPreferences.getStringSet(TOP_LIST, new HashSet<String>());
mSessionPreferences.edit().putStringSet(TOP_LIST, mTopList).commit();
[https://pan.baidu.com/s/1ArSWP-1E26riTSNYOInISA ](url)提取码: mqbu 
[https://pan.baidu.com/s/1gzojkOzibtsbvvGBOHpHPA](url) 提取码: 7hb8

**Comment by whalehe** [comment]
您好，收到您的反馈，我们会尽快在下个迭代处理。

**Comment by whalehe** [comment]
您好，从4.4.479版本后，不再有SessionManager，可以用使用ConversationManagerKit中的setConversationTop置顶某个会话。可以验证下，如有问题，随时反馈。
