### ISSUE TITLE
TIMManager.getInstance().getLoginUser()不为空，无法判断是否登录

### ISSUE THREAD

**Issue by ma343599083** [tencentyun/TIMSDK#200]
IOS把Android端挤下线后，android端使用 TIMManager.getInstance().getLoginUser()不为空，但是官方文档说：通过 TIMManager 成员方法 getLoginUser 可以获取当前用户名，也可以通过这个方法判断是否已经登录。

SDK版本:imsdk-4.4.479

**Comment by lynxzhang** [comment]
你好，这个问题最新版本已经优化，麻烦更新下最新版本
