### ISSUE TITLE
【iOS】-【4.4.627】：【聊天界面不能正常显示图标】

### ISSUE THREAD

**Issue by chenchaohui6666** [tencentyun/TIMSDK#203]
[iOS] - [4.4.627] : 【聊天界面无法显示图标，也没有找到修改的位置。】
如图
![WeChatd9f3bfba3c9388cea3935f217ea5235e](https://user-images.githubusercontent.com/48901808/60418081-9f747800-9c14-11e9-8754-e04df86088ec.png)

**Comment by annidy** [comment]
TUIKitResoure.bundle是不没加到工程里？

**Comment by whalehe** [comment]
您好，确认下资源文件是否加到工程中？如果还有问题，再随时反馈

**Comment by hackjie** [comment]
这 podspec 里面写的  spec.resource = ['iOS/TUIKit/Resources/TUIKitFace.bundle','iOS/TUIKit/Resources/TUIKitResource.bundle'] 是认真的么

Pod::Spec.new do |spec|
  spec.name         = 'TXIMSDK_TUIKit_iOS'
  spec.version      = '4.4.716'
  spec.platform     = :ios 
  spec.ios.deployment_target = '8.0'
  spec.license      = { :type => 'Proprietary',
      :text => <<-LICENSE
        copyright 2017 tencent Ltd. All rights reserved.
        LICENSE
       }
  spec.homepage     = 'https://cloud.tencent.com/document/product/269/3794'
  spec.documentation_url = 'https://cloud.tencent.com/document/product/269/9147'
  spec.authors      = 'tencent video cloud'
  spec.summary      = 'TXIMSDK_TUIKit_iOS'
  spec.xcconfig     = { 'VALID_ARCHS' => 'armv7 arm64 x86_64', }
  spec.libraries    = 'stdc++'

  spec.dependency 'MMLayout'
  spec.dependency 'SDWebImage'
  spec.dependency 'TXIMSDK_iOS'
  spec.dependency 'ReactiveObjC'
  spec.dependency 'Toast'
  spec.dependency 'ISVImageScrollView'
  
  spec.requires_arc = true

  spec.source = { :git => 'https://github.com/tencentyun/TIMSDK.git', :tag => spec.version}
  spec.source_files = 'iOS/TUIKit/Classes/**/*.{h,m,mm}'
  # spec.vendored_frameworks = ''
  spec.vendored_libraries = ['iOS/TUIKit/Classes/third/voiceConvert/opencore-amrnb/libopencore-amrnb.a', 'iOS/TUIKit/Classes/third/voiceConvert/opencore-amrwb/libopencore-amrwb.a']
  spec.resource = ['iOS/TUIKit/Resources/TUIKitFace.bundle','iOS/TUIKit/Resources/TUIKitResource.bundle']
end

# pod trunk push TXIMSDK_TUIKit_iOS.podspec --use-libraries --allow-warnings
