### ISSUE TITLE
【iOS】-【4.4.479】：【界面显示不全，底部输入框无法显示】

### ISSUE THREAD

**Issue by xuyuqiang** [tencentyun/TIMSDK#204]
![IMG_FAA5C72BD667-1](https://user-images.githubusercontent.com/11585488/60430097-0868e980-9c2f-11e9-9d75-5a07ca11d77d.jpeg)
机型：iphoneX
开发环境：swift

**Comment by whalehe** [comment]
您好，可以用最新版本iOS 4.4.716试试，如还有问题，再随时反馈
