### ISSUE TITLE
【iOS】-【4.4.479】：【bundle文件需要手动导入，才能使用】

### ISSUE THREAD

**Issue by xuyuqiang** [tencentyun/TIMSDK#205]
看了TUIKit中，引入项目文件的方式
#define TUIKitResource(name) [[[NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"TUIKitResource" ofType:@"bundle"]] resourcePath] stringByAppendingPathComponent:name]

在swift环境pod引入的项目，无法找到文件，需要手动引入bundle才可以

**Comment by hackjie** [comment]
确实，最新版本也没解决

**Comment by Jijingcheng** [comment]
有点坑，在这里花了几个小时找原因

**Comment by simpleLiYu** [comment]
怎么手动引入bundle

**Comment by lynxzhang** [comment]
#define TUIKitFace(name) [[NSBundle mainBundle] pathForResource:@"TUIKitFace" ofType:@"bundle"] == nil ? ([[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent: @"Frameworks/TXIMSDK_TUIKit_iOS.framework/TUIKitFace.bundle"] stringByAppendingPathComponent:name]) : ([[[NSBundle mainBundle] pathForResource:@"TUIKitFace" ofType:@"bundle"] stringByAppendingPathComponent:name])

**Comment by lynxzhang** [comment]
最新版本 TUIKit 这块已经做了兼容，麻烦更新到 4.5.55 版本
