### ISSUE TITLE
你好  点击会话窗口的头像区域的回调函数在哪？

### ISSUE THREAD

**Issue by jj89757hhb** [tencentyun/TIMSDK#21]
点击会话窗口的头像区域的回调函数在哪？
![default](https://user-images.githubusercontent.com/957927/53384028-7d43c280-39b4-11e9-93e2-81008b424012.png)

**Comment by vinsonswang** [comment]
Android在ChatPanel类，ChatListEvent事件的onUserIconClick回调方法

**Comment by jj89757hhb** [comment]
我说ios
