### ISSUE TITLE
iOS [4.4.627] 图片不见了

### ISSUE THREAD

**Issue by JQHee** [tencentyun/TIMSDK#210]
![1](https://user-images.githubusercontent.com/12505317/60492150-f180d080-9cdc-11e9-9d4f-a0d611ca016c.png)
![2](https://user-images.githubusercontent.com/12505317/60492157-f5145780-9cdc-11e9-91dc-823e4bbe276e.png)
![3](https://user-images.githubusercontent.com/12505317/60492161-f776b180-9cdc-11e9-8a28-bf1c8de39309.png)

描述：图片未发送完成，直接退出当前页面，发送的图片不见了

**Comment by annidy** [comment]
图片加载顺序问题，旧版本优先从网络下载图片，应该先从本地读取。最新版本TUIKit已解决。
