### ISSUE TITLE
【android】-【4.4.627】：【demo遇到的坑】

### ISSUE THREAD

**Issue by caik13** [tencentyun/TIMSDK#211]
【当前现象】：
1、比如登录之后没有调用
`
ThirdPushTokenMgr.getInstance().setIsLogin(true);
ThirdPushTokenMgr.getInstance().setPushTokenToTIM();
`
上报推送token。
2、获取华为推送 token的SplashActivity类没有在清单里注册，导致代码里没有调用gettoken，获取不到华为的推送token。
3、不是好友不能发送消息。

**Comment by whalehe** [comment]
您好，前面2个已经在最新Demo中加入，第3个不是好友也是可以调用SendMessage发送消息的，请知悉。
