### ISSUE TITLE
Android，聊天界面输入法开启时，点击更多+按钮，输入法没有隐藏

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#212]
如图所示 
<img width="330" alt="屏幕快照 2019-07-02 下午4 06 51" src="https://user-images.githubusercontent.com/41293421/60495562-9e5e4c00-9ce3-11e9-818f-f6e2f12032d9.png">

**Comment by whalehe** [comment]
您好，麻烦你按照issue模板进行提交，方便我们定位和排查问题：https://github.com/tencentyun/TIMSDK/issues/176
