### ISSUE TITLE
ios [4.4.627] 不显示头像信息

### ISSUE THREAD

**Issue by xuyuqiang** [tencentyun/TIMSDK#214]
设置了个人信心，发送消息时也带了头像信息，显示的时候不会显示

**Comment by annidy** [comment]
具体是那边不显示？接收端？

**Comment by Zhangyanshen** [comment]
你有没有报 module 'imsdk' not found ?

**Comment by whalehe** [comment]
您好，可以用4.4.716试试，也可以参考Demo中头像逻辑相关，还有问题，随时反馈。
