### ISSUE TITLE
Android Demo没有自动登录

### ISSUE THREAD

**Issue by cuitianxia** [tencentyun/TIMSDK#215]
android里面的Constants有自动登录的判断，却没用上，demo功能不全

**Comment by whalehe** [comment]
您好，Demo的登录只是演示，考虑需要开发者需要自己替换sdkappid和获取userSig，这块可以存个sharedpreferences，然后下次登录取出sharedpreferences的值，得到用户名和密码，调用登录接口就可以实现自动登录了。
