### ISSUE TITLE
最新版本，iOS 聊天列表，聊天界面，都不显示头像，建议修改

### ISSUE THREAD

**Issue by xins134** [tencentyun/TIMSDK#216]
聊天界面不显示头像，检查代码发现是你们的代码逻辑问题，少了头像赋值的代码，如下：
![Jietu20190703-174602](https://user-images.githubusercontent.com/12149063/60582215-f1ef9900-9dba-11e9-9014-4b5955b51947.jpg)
下方图为个人修改意见，
![Jietu20190703-174641](https://user-images.githubusercontent.com/12149063/60582275-10559480-9dbb-11e9-9efe-0fc1a6006354.jpg)
建议你们及时完善啊，还有其他显示头像的地方

**Comment by xins134** [comment]
这样也不行，对于自己发送的消息无效
只有在设置cell data的时候重新获取此条消息的发送人，再重新给头像赋值，才稳妥点

**Comment by fairytale110** [comment]
根据我的实际经验，头像这块建议自己实现，比如登录成功后 统一获取所有会话的联系人信息，然后通知更新会话列表和对话界面以及其它涉及IM个人信息的位置，TUIKit不能完全满足所有人的需求其实。需要自己改改。

**Comment by xins134** [comment]
@fairytale110 基础功能理应实现，并且允许用户自定义修改，理应做成这样，毕竟商业软件，付费了的啊

**Comment by enamor** [comment]
这头像 昵称 问题也是醉了 感觉这是 最基本的需要解决的问题 从年前到现在 。。。。。

**Comment by annidy** [comment]
> 这样也不行，对于自己发送的消息无效
> 只有在设置cell data的时候重新获取此条消息的发送人，再重新给头像赋值，才稳妥点

多谢提醒，下周发布时会完善这里

**Comment by annidy** [comment]
> 根据我的实际经验，头像这块建议自己实现，比如登录成功后 统一获取所有会话的联系人信息，然后通知更新会话列表和对话界面以及其它涉及IM个人信息的位置，TUIKit不能完全满足所有人的需求其实。需要自己改改。

如果是好友关系，对方资料变更会有推送过来，届时底层会自动更新Profile，如果是陌生人就没办法了。登录后，在后台任务里调用-[TIMFriendshipManager GetUserProfile]强制拉取一遍用户资料，如果没有更新速度会非常快

**Comment by annidy** [comment]
fix in 4.4.716
