### ISSUE TITLE
Android Demo  Android9.0

### ISSUE THREAD

**Issue by yanqi02** [tencentyun/TIMSDK#217]
java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for Signature.SHA256withECDSA.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
这个错

**Comment by whalehe** [comment]
您好，方便提供下机型和编译配置信息么？

**Comment by yanqi02** [comment]
我新建了一个空项目单纯获取usersng ,使用模拟器api  26能打印出来，但是装到我的手机上就不显示了， 我看了上面有一个是说  compileSdkVersion 这个改到28  但还是报错，这个是它给的网址https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
我的手机是vivo Z3x

**Comment by whalehe** [comment]
您好，修改方法如下，在GenerateTestUserSig.java中GenTLSSignature方法：

            Signature signature = null;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                signature = Signature.getInstance("SHA256withECDSA"); //适配Android P及以后版本，否则报错NoSuchAlgorithmException
            } else {
                signature = Signature.getInstance("SHA256withECDSA", "BC");
            }

后续版本会使用HMAC-SHA256加密算法，更简单和无兼容性问题。

**Comment by yanqi02** [comment]
解决了
