### ISSUE TITLE
Android 单聊显示对方昵称的bug

### ISSUE THREAD

**Issue by cuitianxia** [tencentyun/TIMSDK#218]
原代码 if (properties.getLeftNameVisibility() == 0) {
                if (msg.isGroup()) { // 群聊默认显示对方的昵称
                    usernameText.setVisibility(View.VISIBLE);
                } else { // 单聊默认不显示对方昵称
                    usernameText.setVisibility(View.GONE);
                }
            } else {
                usernameText.setVisibility(properties.getLeftNameVisibility());
            }
            if (usernameText.getVisibility() == View.GONE) {
                RelativeLayout.LayoutParams params = (RelativeLayout.LayoutParams) msgContentLinear.getLayoutParams();
                params.topMargin = 17;
                msgContentLinear.setLayoutParams(params);
            }
改后
//            if (properties.getLeftNameVisibility() == 0) {//被修改的地方因为View.VISIBLE==0，会造成对方昵称永恒显示不出来
            if (properties.getLeftNameVisibility() != View.VISIBLE) {
                if (msg.isGroup()) { // 群聊默认显示对方的昵称
                    usernameText.setVisibility(View.VISIBLE);
                } else { // 单聊默认不显示对方昵称
                    usernameText.setVisibility(View.GONE);
                }
            } else {
                usernameText.setVisibility(properties.getLeftNameVisibility());
            }
            if (usernameText.getVisibility() == View.GONE) {
                RelativeLayout.LayoutParams params = (RelativeLayout.LayoutParams) msgContentLinear.getLayoutParams();
                params.topMargin = 17;
                msgContentLinear.setLayoutParams(params);
            }

**Comment by cuitianxia** [comment]
demo尽快完善

**Comment by whalehe** [comment]
您好，单聊（ C2C）从产品初衷是不显示对方昵称的（因为标题栏就有了对方昵称或ID），群聊（Group）才显示，如果您需要单聊（ C2C）显示对方昵称可以自行修改相关代码。
