### ISSUE TITLE
【windows】-【4.4.627】：【IMApp 编译出错】

### ISSUE THREAD

**Issue by Chris85bh** [tencentyun/TIMSDK#220]
【当前现象】：VS2015 编译报一堆错误，但在编辑器里没有报错。
【机型】：
【之前版本有无此问题】：不知
【有无日志或者截图】：
`1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\log.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\log.cpp(46): error C2065: “log_lineno”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\log.cpp(50): error C2065: “log_mutilline_”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\log.cpp(110): error C2065: “log_lineno”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\log.cpp(132): error C2065: “log_mutilline_”: 未声明的标识符
1>  crashdump.cpp
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(1544): warning C4091: “typedef ”: 没有声明变量时忽略“”的左侧
1>c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(3190): warning C4091: “typedef ”: 没有声明变量时忽略“”的左侧
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(56): error C2065: “bRet”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(56): error C2228: “.c_str”的左边必须有类/结构/联合
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(59): error C2065: “bRet”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(60): error C2065: “bRet”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(60): error C2228: “.c_str”的左边必须有类/结构/联合
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(84): error C2065: “bRet”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(85): error C2065: “bRet”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(85): error C2228: “.c_str”的左边必须有类/结构/联合
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(88): error C2065: “bRet”: 未声明的标识符
1>d:\toolprojects\timsdk-master\cross-platform\windows\imapp\common\crashdump.cpp(88): error C2228: “.c_str”的左边必须有类/结构/联合
1>  正在生成代码...
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========`

**Comment by whalehe** [comment]
您好，尝试用windows 4.4.717试试，还有问题，随时反馈。
