### ISSUE TITLE
Android 怎么让会话列表分离，分成群会话列表和好友会话列表

### ISSUE THREAD

**Issue by cuitianxia** [tencentyun/TIMSDK#224]
一个是主页fragment一个是跳转进入的activiy
第一次每次初始化ConversationLayout都会造成列表同步刷新，把ConversationProvider里面的attachAdapter里面的绑定注掉以后不再刷新
第二次 在每次有新消息时，进入查看后的刷新列表会再次造成列表同步刷新，变成后进入那一个列表的会话列表

**Comment by cuitianxia** [comment]
我现在是在每个fragment的onResum都刷新了列表筛选重新放入数据，不过我觉得合适很合适

**Comment by whalehe** [comment]
您好，这个可以根据ConversationInfo中的isGroup是否是群聊进行分别填充到会话列表adapter中。可以放在不同fragment中。
