### ISSUE TITLE
couldn't find "libImSDK.so"

### ISSUE THREAD

**Issue by imxiaopeng** [tencentyun/TIMSDK#226]
按照以下方式初始化，报错；cpu过滤armeabi
 try {
                int sdkId ;
                TIMSdkConfig config = new TIMSdkConfig(sdkId)
                        .enableLogPrint(true)
                        .setLogListener(new TIMLogListener() {
                            @Override
                            public void log(int level, String tag, String msg) {
                                L.e(msg);
                            }
                        });
                //初始化 SDK
                TIMManager.getInstance().init(getApplicationContext(), config);
            } catch (Exception e) {
                e.printStackTrace();
            }

**Comment by zhaopingfu** [comment]
同问，为啥没有armeabi 的so呢

**Comment by imxiaopeng** [comment]
提了工单说不支持armeabi了，只能用v7和v8；
//腾讯云通信不支持armeabi 如果App 只定位国内使用，可以只打包 armeabi-v7a 架构的 so 文件，这样可以将安装包增量压缩到5M以内；
 // 如果App 希望上架 Google Play，可以打包 armeabi-v7a 和 arm64-v8a (google play商店强制)两个架构的 so 文件。

**Comment by whalehe** [comment]
您好，一般armeabi-v7a 架构就完全满足了，如果有问题，可以随时再反馈。
