### ISSUE TITLE
【Android】-【4.4.631】：【用户设备时间不正确，比正常时间快或者慢，发送图片都会失败】

### ISSUE THREAD

**Issue by danielxu** [tencentyun/TIMSDK#227]
【Android】-【4.4.631】：【用户设备时间不正确，比正常时间快或者慢，发送图片都会失败】
【当前现象】：图片上传成功，但是报错：File upload success: server check non image
【之前版本有无此问题】：有
【有无日志或者截图】：
![8411562840575_ pic_hd](https://user-images.githubusercontent.com/232521/61044418-327a9280-a40b-11e9-9c20-06347c0c1adf.jpg)

**Comment by whalehe** [comment]
您好，我用Demo测试时没有问题的。麻烦提供下复现的日志，方便我们排查和定位问题。

**Comment by whalehe** [comment]
您好，建议用716版本试试，看是否还存在此问题，如有问题，麻烦提供下复现的日志，方便我们排查和定位问题。
