### ISSUE TITLE
【Web】-【4.4.627】：【setAutoRead方法无效】

### ISSUE THREAD

**Issue by delayhsiao** [tencentyun/TIMSDK#232]
【当前现象】：通过WebSDK，收到消息后立即设置setAutoRead，在参数正确且无报错的情况下，Android和IOS端消息的已读状态依旧为未读，且WebSDK中缺少获取消息已读状态的接口。
【之前版本有无此问题】：之前一直没有
【有无日志或者截图】：暂无日志

**Comment by yangq1990** [comment]
感谢反馈。自动已读上报和已读回执是不同的概念，后者已经列入开发计划，后续会支持
