### ISSUE TITLE
【Android】-【4.4.716】：【第一次注册账号，Demo 通讯录默认不显示任何内容】

### ISSUE THREAD

**Issue by w3336713** [tencentyun/TIMSDK#233]
创建了应用，使用随意账号登录了以后，点击通讯录，全部空白，没有任何展示，只有点击右上方添加好友了以后，才会正常展示。

**Comment by whalehe** [comment]
您好，收到你的反馈，demo这个问题，下版本修复。属于体验问题。

**Comment by whalehe** [comment]
4.4.900 已修复

**Comment by zhuyonghao** [comment]
下载最新的安卓demo，4.4.900不显示任何好友

**Comment by zhuyonghao** [comment]
比如已经是好友，并有近期消息，但是通讯录不显示好友，还需要重新添加一次好友才显示。添加好友时不需要验证就通过验证了
