### ISSUE TITLE
【Android】-【4.4.627】：聊天界面的头像和昵称应该怎么设置

### ISSUE THREAD

**Issue by returntoorigin** [tencentyun/TIMSDK#235]
聊天界面的头像和昵称应该怎么设置，不是获取用户的资料，是消息列表头像和昵称的展示

**Comment by whalehe** [comment]
你好，需要如下步骤：
1、需要您在个人资料头像设置，上传图片生成url，调用修改资料接口，传到IM后台，
2、在MessageContentHolder中，通过 TIMUserProfile profile = TIMFriendshipManager.getInstance().queryUserProfile(msg.getFromUser())，获取消息发送者资料，资料里就是您事先设置的头像url
3、给leftUserIcon设置url
 if (!TextUtils.isEmpty(profile.getFaceUrl()) && !msg.isSelf()) {
          List<String> urllist = new ArrayList<>();
          urllist.add(profile.getFaceUrl());
          leftUserIcon.setIconUrls(urllist);
         urllist.clear();
}

下个版本会将会话列表，聊天界面，详情资料，通讯录中的头像在Demo展示

昵称目前逻辑是有的，c2c消息不显示对方昵称，群聊显示群成员昵称，同样也是在
MessageContentHolder中

**Comment by Wzert** [comment]
TIMFriendshipManager.getInstance().queryUserProfile()是只能获取好友的资料吗
