### ISSUE TITLE
【Android】-【4.4.716】：【账号登录后几秒就掉线onDisconnected()】

### ISSUE THREAD

**Issue by heart100** [tencentyun/TIMSDK#240]
//设置连接状态事件监听器
                .setConnectionListener(new TIMConnListener() {
                    @Override
                    public void onConnected() {
                        Log.i(TAG, "onConnected");
                    }
                    @Override
                    public void onDisconnected(int code, String desc) {
                        Log.i(TAG, "onDisconnected");
                    }

                    @Override
                    public void onWifiNeedAuth(String name) {
                   
                    }
                });

**Comment by whalehe** [comment]
您好，可否提供下日志，方便分析和排查问题

**Comment by heart100** [comment]
onDisconnected(int code, String desc) code=0

**Comment by vinsonswang** [comment]
在4.4.900版本针对这点做了优化，麻烦升级下
