### ISSUE TITLE
【Android】-【4.4.716】：【按住发送语音事件 应该修改如下】

### ISSUE THREAD

**Issue by heart100** [tencentyun/TIMSDK#241]
case MotionEvent.ACTION_UP:
                    case MotionEvent.ACTION_CANCEL:
                        mAudioCancel = motionEvent.getY() - mStartRecordY < -100;
                        if (mChatInputHandler != null) {
                            mChatInputHandler.stopRecording();
                        }
                        AudioPlayer.getInstance().stopRecord();
                        mSendAudioButton.setText("按住说话");
                        break;

**Comment by whalehe** [comment]
您好，收到您的反馈，下版本会处理~

**Comment by whalehe** [comment]
4.4.900 已修复
