### ISSUE TITLE
将TIMSDK和我自己的模块封装成aar后，在项目中引用并初始化IMSDK，报如下错误

### ISSUE THREAD

**Issue by furuiCQ** [tencentyun/TIMSDK#246]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.imsdk.log.QLog.nativeWriteLog(int, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_com_tencent_imsdk_log_QLog_nativeWriteLog and Java_com_tencent_imsdk_log_QLog_nativeWriteLog__ILjava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)

**Comment by furuiCQ** [comment]
at com.tencent.imsdk.log.QLog.nativeWriteLog(Native Method)
        at com.tencent.imsdk.log.QLog.log(QLog.java:73)
        at com.tencent.imsdk.log.QLog.i(QLog.java:41)
        at com.tencent.imsdk.TIMManager.doForeground(TIMManager.java:167)

**Comment by whalehe** [comment]
您好，提issue，请参考https://github.com/tencentyun/TIMSDK/issues/176，无法确认您的具体信息已经版本，可以尝试用最近版本再试试，如有问题，再随时反馈。

**Comment by lhzlg3368** [comment]
> ```
> java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.imsdk.log.QLog.nativeWriteLog(int, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_com_tencent_imsdk_log_QLog_nativeWriteLog and Java_com_tencent_imsdk_log_QLog_nativeWriteLog__ILjava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)
> ```

我今天也碰到同样的问题了，提工单问了腾讯，得到的答复是目前不支持androidx
