### ISSUE TITLE
Swift中使用TIMSDK无法编译通过

### ISSUE THREAD

**Issue by AntonyFree** [tencentyun/TIMSDK#252]
- 【iOS】-【4.4.716】：【Swift集成时报 Could not build Objective-C module 'TXIMSDK_TUIKit_iOS'】
- 【集成包】：TUIKIT
- 【当前现象】：Xcode（Swift）集成新版本TUIKit，报错，无法编译通过（Could not build Objective-C module 'TXIMSDK_TUIKit_iOS'）
- 【机型】：模拟器 iPhone XR
- 【之前版本有无此问题】：之前没有使用过
- 【截图】：
<img width="1050" alt="屏幕快照 2019-07-22 下午10 36 23" src="https://user-images.githubusercontent.com/53182512/61638023-8327a080-acd3-11e9-89eb-df067c8594ba.png">

是我设置有问题吗？请各位给点提示，谢谢。（试了网上很多方法都没有解决）

**Comment by whalehe** [comment]
参考wiki：https://github.com/tencentyun/TIMSDK/wiki/TUIKit-iOS%E5%BF%AB%E9%80%9F%E9%9B%86%E6%88%90

**Comment by AntonyFree** [comment]
谢谢回复。参考的链接是OC的，之前我用OC中也能跑起来。

不过目前项目是用Swift的，会报上述错误。看了2天了，还没解决。

请问可以请你们在Swift工程中试一下吗，谢谢。

**Comment by ench44** [comment]
请问你不知道swift中有一个 header 桥接文件么?  在那里引入TUIKit.h就行了.

**Comment by AntonyFree** [comment]
@ench44  @whalehe 
你好，我试过桥接头文件了。不过还是报错，编译不通过，可以帮忙看看是我的桥接文件写得有问题吗？谢谢。
<img width="708" alt="屏幕快照 2019-07-23 下午9 44 15" src="https://user-images.githubusercontent.com/53182512/61713556-d5c89180-ad93-11e9-8ebc-f9b6ba60a916.png">

还是报错：
<img width="1354" alt="屏幕快照 2019-07-23 下午9 48 59" src="https://user-images.githubusercontent.com/53182512/61713570-dcef9f80-ad93-11e9-82da-8d99cceeadf4.png">

**Comment by 0x0o** [comment]
检查一下 User Search Path, 加入 `${SRCROOT}` 和 `$(PODS_ROOT)`

```objc
import "TUIkit.h"
```

**Comment by Antony138** [comment]
@0x0o 
谢谢回复。问题已经解决了。
有大神已经提交PR修复这个问题了。

Reference： https://github.com/tencentyun/TIMSDK/pull/255

**Comment by AntonyFree** [comment]
@0x0o
谢谢回复。问题已经解决了。
有大神已经提交PR修复这个问题了。

Reference： #255

**Comment by leacode** [comment]
我这里
```
import ImSDK
```

就可以了，不需要额外设置，集成方式pod
