### ISSUE TITLE
[iOS 4.4.479] 关于撤回消息api设计优化改进问题

### ISSUE THREAD

**Issue by LoSenTrad** [tencentyun/TIMSDK#257]
【iOS】-【4.4.479】：关于撤回消息api设计优化改进问题
【集成包】：TUIKIT
【当前现象】：
以下是消息撤回api设计,希望可以改进优化,增加可以通过传消息id就可以进行完成撤回,而不需要太依赖消息体TIMMessage,减少耦合. [可以参考阿里IM和融云IM或者是环信IM].
- (int)revokeMessage:(TIMMessage*)msg succ:(TIMSucc)succ fail:(TIMFail)fail;
【机型】：xs max
【之前版本有无此问题】：一直都是存在设计问题
【有无日志或者截图】：暂无日志 暂无截图

**Comment by vinsonswang** [comment]
重复问题：
https://github.com/tencentyun/TIMSDK/issues/277#issuecomment-524745332
