### ISSUE TITLE
【Android】【4.4.627】在未打开回话列表的情况下，获取未读消息的方法不回调

### ISSUE THREAD

**Issue by returntoorigin** [tencentyun/TIMSDK#260]
我发现在未打开会话列表的情况下，未读消息监听不回调。我在首页有一个消息图标，需要提示用户是否有未读消息，而会话列表是在另一个界面，我应该怎么获取未读消息呢。

我在首页注册了监听：
 // 未读消息监视器
ConversationManagerKit.getInstance().addUnreadWatcher(this);
然后这个方法没有调用
@Override
    public void updateUnread(int count) {
        Log.i(TAG, "updateUnread: 未读消息数量：" + count);
    }

**Comment by parkhuang** [comment]
未读计数发生变化的时机大的来说有三种情况：
1、有消息进来，包括消息撤回
2、会话加载
3、会话被删除
你想在什么时候获取未读消息，能不能贴一下此时的log？
