### ISSUE TITLE
android : modifySelfProfile修改头像不起作用

### ISSUE THREAD

**Issue by zhuyonghao** [tencentyun/TIMSDK#262]
![image](https://user-images.githubusercontent.com/18735317/62181611-73205880-b386-11e9-9ce5-b85fabdb9e18.png)

提示修改成功，但是并没有修改头像信息

**Comment by fangkeweiyou1** [comment]
这咋整啊

**Comment by whalehe** [comment]
您好，可以参考最新TUIKit代码中，modifySelfProfile调用地方
