### ISSUE TITLE
Android - 4.3.118 ：UnsatisfiedLinkError

### ISSUE THREAD

**Issue by selfimprW** [tencentyun/TIMSDK#263]
集成版本：com.tencent.imsdk:imsdk:4.3.118

崩溃日志：
#7957664 java.lang.UnsatisfiedLinkError
Native method not found: com.tencent.imsdk.manager.NativeManager.nativeGetIdentifier:()Ljava/lang/String;
com.tencent.imsdk.manager.NativeManager.java.lang.String nativeGetIdentifier()(Native Method)

1 com.tencent.imsdk.manager.NativeManager.nativeGetIdentifier(Native Method)
2 com.tencent.imsdk.manager.BaseManager.getLoginUser(SourceFile:635)
3 com.tencent.imsdk.TIMManager.getLoginUser(SourceFile:98)
4 com.tencent.imsdk.TIMManager.logout(SourceFile:281)
5 com.xxx.module.live.liveroom.core.c.e$1.run(SourceFile:134)
6 android.os.Handler.handleCallback(Handler.java:615)
7 android.os.Handler.dispatchMessage(Handler.java:92)
8 android.os.Looper.loop(Looper.java:137)
9 android.app.ActivityThread.main(ActivityThread.java:4914)
10 java.lang.reflect.Method.invokeNative(Native Method)
11 java.lang.reflect.Method.invoke(Method.java:511)
12 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
14 dalvik.system.NativeStart.main(Native Method)

崩溃机型：
http://ww1.sinaimg.cn/large/006qOCVvly1g5ldm8xuk9j31t80scaea.jpg

**Comment by whalehe** [comment]
您好，可以升级到最新版本试试~

**Comment by selfimprW** [comment]
> 您好，可以升级到最新版本试试~

👌
