### ISSUE TITLE
Android TUIki聊天界面无法显示头像

### ISSUE THREAD

**Issue by charmeleon2** [tencentyun/TIMSDK#264]
4.4.716版本，聊天界面设置了chatinfo类，昵称能显示，头像不显示
登陆成功后已经设置过了userprofile
【机型】 oneplus 6t, nova 2s
【系统】 Android p

**Comment by fangkeweiyou1** [comment]
我看源码好像头像控件仅仅只设置了默认资源图片,要设置网络图片,你自己得去源码改

**Comment by whalehe** [comment]
4.4.900 已修复
