### ISSUE TITLE
[!] Error installing TXIMSDK_TUIKit_iOS

### ISSUE THREAD

**Issue by yuanshuainiuniu** [tencentyun/TIMSDK#272]
[!] Error installing TXIMSDK_TUIKit_iOS
[!] /usr/bin/git clone https://github.com/tencentyun/TIMSDK.git /var/folders/22/2257892x5jv0btlj9k6kvg2r0000gp/T/d20190811-19723-jn13lq --template= --single-branch --depth 1 --branch 4.4.716

Cloning into '/var/folders/22/2257892x5jv0btlj9k6kvg2r0000gp/T/d20190811-19723-jn13lq'...
warning: Could not find remote branch 4.4.716 to clone.
fatal: Remote branch 4.4.716 not found in upstream origin

**Comment by 15821111890** [comment]
cocoa pods 升级一下 可以解决 我升级到了 1.7.2 就可以了

**Comment by yuanshuainiuniu** [comment]
pod search TXIMSDK_TUIKit_iOS
[!] Unable to find a pod with name, author, summary, or description matching `TXIMSDK_TUIKit_iOS`

**Comment by lynxzhang** [comment]
-> TXIMSDK_TUIKit_iOS (4.4.900)
   TXIMSDK_TUIKit_iOS
   pod 'TXIMSDK_TUIKit_iOS', '~> 4.4.900'
   - Homepage: https://cloud.tencent.com/document/product/269/3794
   - Source:   https://github.com/tencentyun/TIMSDK.git
   - Versions: 4.4.900, 4.4.716, 4.4.627, 4.4.479, 4.3.145, 4.3.135, 4.3.118, 4.3.81,
   4.2.52, 4.2.28, 4.2.10, 4.2.9, 4.2.2, 4.2.1, 4.0.13, 4.0.12, 4.0.10 [master repo]
(END)

**Comment by lynxzhang** [comment]
升级下 cocoa pods 版本试下呢

**Comment by 815807765** [comment]
> cocoa pods 升级一下 可以解决 我升级到了 1.7.2 就可以了

在吗？我的pod都升级到1.7.5了也会报这个错误。。。

**Comment by lynxzhang** [comment]
4.4.716 的tag已经去掉了，麻烦更新下本地 Podfile 到最新的 4.4.900 版本

**Comment by 815807765** [comment]
> 4.4.716 的tag已经去掉了，麻烦更新下本地 Podfile 到最新的 4.4.900 版本

pod file 改成4.4.900会报下面这个错误：
"
[!] CocoaPods could not find compatible versions for pod "TXIMSDK_iOS":
  In Podfile:
    TXIMSDK_iOS (~> 4.4.900)

None of your spec sources contain a spec satisfying the dependency: `TXIMSDK_iOS (~> 4.4.900)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
"

**Comment by 815807765** [comment]
<img width="570" alt="tximsdk_ios" src="https://user-images.githubusercontent.com/13276527/62999218-544eb580-bea0-11e9-9d4a-b11aec449739.png">

**Comment by lynxzhang** [comment]
pod search 失败：
pod setup
pod repo update
rm ~/Library/Caches/CocoaPods/search_index.json
试下这个命令
