### ISSUE TITLE
最新版本4.4.900clone下来报错

### ISSUE THREAD

**Issue by yuanshuainiuniu** [tencentyun/TIMSDK#274]
![image](https://user-images.githubusercontent.com/9314006/62846285-8675e100-bd01-11e9-8aa5-a7ca29513355.png)

**Comment by 778549041** [comment]
是的，版本是不是更出问题了，尽快解决啊

**Comment by lynxzhang** [comment]
已经优化，麻烦更新下代码

**Comment by 15821111890** [comment]
我pod了 最新的 4.4.900 的 TXIMSDK_iOS

没有在 Pods/TXIMSDK_iOS/ 里面看到 ImSDK ... 感觉像空的.. 啥时候能解决.. ？

![TXIMSDK_iOS - 4 4 900](https://user-images.githubusercontent.com/5705654/62908806-7830cf00-bdac-11e9-9b6f-c737e7803e68.png)

**Comment by cishing** [comment]
同样的问题，请问解决了吗？

**Comment by ming-qdu** [comment]
> 我pod了 最新的 4.4.900 的 TXIMSDK_iOS
> 
> 没有在 Pods/TXIMSDK_iOS/ 里面看到 ImSDK ... 感觉像空的.. 啥时候能解决.. ？
> 
> ![TXIMSDK_iOS - 4 4 900](https://user-images.githubusercontent.com/5705654/62908806-7830cf00-bdac-11e9-9b6f-c737e7803e68.png)



> 同样的问题，请问解决了吗？

按照下面的步骤试试
1.执行命令 pod cache clean TXIMSDK_iOS
2.编辑podfile文件，注释掉pod 'TXIMSDK_iOS'，然后执行pod install
3.编辑podfile文件，删除之前添加的注释，再次执行pod install

**Comment by 15821111890** [comment]
ok 问题已解决
