### ISSUE TITLE
H5 userSigs keep changing each time

### ISSUE THREAD

**Issue by zhihaozhang** [tencentyun/TIMSDK#275]
I have configed the appID and private key , but userSig keeps changing every time I open the chrome. How to solve it?

![252501565618135_ pic](https://user-images.githubusercontent.com/4500659/62924011-c1e7dc80-bde1-11e9-9a86-1e7e01502bde.jpg)
![253141565620326_ pic_hd](https://user-images.githubusercontent.com/4500659/62924124-01162d80-bde2-11e9-95a2-e582f143f523.jpg)

**Comment by zhihaozhang** [comment]
I refreshed chrome to get a new userSig, which is different from the userSIgs before.

eJw1zFELgjAUhuH-sttCzlG3luCdiIRokEFdRs44REO21YTovze0Lr-ng-fNuvoQvZRhGYsjYOt5U6*0o4Fmfv7V9vfLOFLPMkwBYtwkyJfH0UMF5YILlDHKRdU0kgkuIJUAvwbdQrJINEwWnLn6sirQtsPO4LFcnXzd*ha3XVXVe9GIRp9z9vkC6xYu*A__&contenttype=json&sdkappid=1400217315&accounttype=2586&apn=1&reqtime=1565618218

**Comment by Rychou** [comment]
By first, please try follow steps:
1. open this link. [https://console.cloud.tencent.com/avc/list](https://console.cloud.tencent.com/avc/list)
2. login your tencent cloud account.
3. 
![image](https://user-images.githubusercontent.com/25195267/62935741-7ee63300-bdfa-11e9-86e5-85ee559d8ac1.png)
4. make sure you can see this button.
![image](https://user-images.githubusercontent.com/25195267/62936496-84447d00-bdfc-11e9-98e6-ef19f99fa6a0.png)

If you can not find the button on step 4, it means your appid is not supported for our Web Demo .

You can try to create a new appid, and try again.

If it still not work, please comment here to let me know that.

**Comment by xiezhenjian** [comment]
你好工程师大哥，这个sdkappid 安卓是可以正常登陆的。web demo里，H5/js/debug/GenerateTestUserSig.js 文件里也填入了对应的sdkappid 和 secretkey，expiretime没改。然后就出现了上面每次刷新浏览器都返回不同的userSig的bug。
纠结两天了，不知道咋回事呢。

**Comment by Rychou** [comment]
> 你好工程师大哥，这个sdkappid 安卓是可以正常登陆的。web demo里，H5/js/debug/GenerateTestUserSig.js 文件里也填入了对应的sdkappid 和 secretkey，expiretime没改。然后就出现了上面每次刷新浏览器都返回不同的userSig的bug。
> 纠结两天了，不知道咋回事呢。

你好，请确认你的 SDKAPPID 控制台的应用配置中，能否看到下方截图的“查看密钥”的按钮。如果没有这个按钮，说明你的SDKAPPID是旧版的。重新创建一个即可。
![](https://user-images.githubusercontent.com/25195267/62936496-84447d00-bdfc-11e9-98e6-ef19f99fa6a0.png)

**Comment by xiezhenjian** [comment]
> > 你好工程师大哥，这个sdkappid 安卓是可以正常登陆的。web demo里，H5/js/debug/GenerateTestUserSig.js 文件里也填入了对应的sdkappid 和 secretkey，expiretime没改。然后就出现了上面每次刷新浏览器都返回不同的userSig的bug。
> > 纠结两天了，不知道咋回事呢。
> 
> 你好，请确认你的 SDKAPPID 控制台的应用配置中，能否看到下方截图的“查看密钥”的按钮。如果没有这个按钮，说明你的SDKAPPID是旧版的。重新创建一个即可。
> ![](https://user-images.githubusercontent.com/25195267/62936496-84447d00-bdfc-11e9-98e6-ef19f99fa6a0.png)

可以看到这个按钮的呀。

**Comment by Rychou** [comment]
> > > 你好工程师大哥，这个sdkappid 安卓是可以正常登陆的。web demo里，H5/js/debug/GenerateTestUserSig.js 文件里也填入了对应的sdkappid 和 secretkey，expiretime没改。然后就出现了上面每次刷新浏览器都返回不同的userSig的bug。
> > > 纠结两天了，不知道咋回事呢。
> > 
> > 
> > 你好，请确认你的 SDKAPPID 控制台的应用配置中，能否看到下方截图的“查看密钥”的按钮。如果没有这个按钮，说明你的SDKAPPID是旧版的。重新创建一个即可。
> > ![](https://user-images.githubusercontent.com/25195267/62936496-84447d00-bdfc-11e9-98e6-ef19f99fa6a0.png)
> 
> 可以看到这个按钮的呀。

是按步骤操作后不能正常登录吗？

目前为了方便用户体验Demo, userSig是在客户端计算的，在每次登录前都会重新计算签发一次。所以会出现上述您说的，每次登录userSig都会变的情况，这是正常的。

实际的应用场景是要在服务端进行签发的。参考：[服务端计算userSig](https://cloud.tencent.com/document/product/269/32688#GeneratingdynamicUserSig)

**Comment by xiezhenjian** [comment]
可是我安卓也是在客户端计算的呀，安卓并没有每次都变

**Comment by Rychou** [comment]
> 可是我安卓也是在客户端计算的呀，安卓并没有每次都变

算法是每次计算签出来的userSig都是不一样的，是正常的。

**Comment by Rychou** [comment]
> 可是我安卓也是在客户端计算的呀，安卓并没有每次都变

算法基于当前时间计算userSig，在同一秒内计算的userSig相同
