### ISSUE TITLE
【iOS】-【4.4.900】：【私聊未读消息数异常】

### ISSUE THREAD

**Issue by iEason-git** [tencentyun/TIMSDK#276]
【当前现象】：
                - (int)getUnReadMessageNum; api 返回的未读数不正确. 在A用户离线的情况下,B用户向A用户发了100条私聊消息. 当A用户登陆后通过以上api获取的未读数确是30.
【集成包】：IMSDK
【机型】：iPhone 7  & iOS 11.2.1 (@note 任意机型都有这个问题)
【之前版本有无此问题】：4.4.716也有这个问题

**Comment by iEason-git** [comment]
![1989708656_1125881_1565769439907](https://user-images.githubusercontent.com/6859687/63011872-c4b70000-bebb-11e9-9c84-747d1073798b.png)

**Comment by lynxzhang** [comment]
B用户是通过客户端还是 RestAPI 发送的消息？

**Comment by vinsonswang** [comment]
后台对未读数量的存储限制做了优化，正在灰度中，预计8月底灰度完。

**Comment by iEason-git** [comment]
> B用户是通过客户端还是 RestAPI 发送的消息？

两个用户都是通过客户端发送的. 完全模拟线上用户场景.

**Comment by iEason-git** [comment]
> 后台对未读数量的存储限制做了优化，正在灰度中，预计8月底灰度完。

好的.
