### ISSUE TITLE
发送任何消息都是提示  message has dirty word: sb$$sb|qlogo

### ISSUE THREAD

**Issue by zhangxi28** [tencentyun/TIMSDK#278]
android所有手机
imsdk 版本  4.4.716
给个别用户发送消息，如何“你好”，“再见”等任何消息都是提示message has dirty word: sb$$sb|qlogo。
用户id:  4629909982157893632

**Comment by vinsonswang** [comment]
您需要找下您的后台排查下接入的脏字过滤功能
