### ISSUE TITLE
iOS端App进入后台后，restApi获取的IM登录状态仍然为online状态。

### ISSUE THREAD

**Issue by cishing** [tencentyun/TIMSDK#279]
【iOS】-【4.4.500】：【iOS端App进入后台后，restApi获取的IM登录状态仍然为online状态。】
【集成包】：TUIKIT
【当前现象】：App进入后台后，调用sdk提供的接口doBackground，此时服务器端通过restApi获取到的IM登录状态仍然为online状态，通过sdk中doBackground接口的描述，调用此方法后IM的登录状态应该为pushofline状态。
【机型】：与机型无关
【之前版本有无此问题】：有
【有无日志或者截图】：暂无日志

**Comment by fairytale110** [comment]
pushoffline 和登录状态没关吧。。。。

**Comment by lynxzhang** [comment]
online / pushoffline 和登录状态无关，只有在客户端程序被杀死的时候状态才会从 online -> pushoffline
