### ISSUE TITLE
新版SDK问题太多

### ISSUE THREAD

**Issue by wangshaolei** [tencentyun/TIMSDK#28]
1 历史遗留问题，无法从消息体获取自定义的头像和昵称，新SDK又没有关系链
2 新SDK 只让 支持armeabiv7，不支持armeabi，项目历史只能保留armeabi这不是冲突吗

**Comment by bewareofbears** [comment]
armeabi
armeabi-v7a
arm64-v8a

都应该支持啊！

**Comment by wangshaolei** [comment]
@bewareofbears 由于项目集成了腾讯云小视频商业版只支持abifilters armeabi，但是腾讯云IM只能支持abifilters v7a理论上我知道  v7a兼容armeabi，但是需要指定支持。

**Comment by vinsonswang** [comment]
可以先把armeabiv7中的so放到armeabi中使用

**Comment by wangshaolei** [comment]
@vinsonswang 目前考虑 放两套

**Comment by wangshaolei** [comment]
@vinsonswang 刚刚看了UGC 已经支持了armeabi 和 armeabi-v7a ，现在可以用一套了。目前 问题只有TIM  SDK 用户资料获取了。
``
/**
     * @param list   拉取所有会话资料
     * @param newOne 拉取新会话资料
     */
    private void getUserProfile(final List<TIMConversation> list, final TIMConversation newOne) {
        List<String> peers = null;
        if (list != null && list.size() > 0) {
            peers = new ArrayList<>();
            for (TIMConversation timConversation : list) {
                peers.add(timConversation.getPeer());
            }
        } else if (newOne != null) {
            peers = new ArrayList<String>() {
                {
                    add(newOne.getPeer());
                }
            };
        }
        if (peers == null) {
            swipeRefreshLayout.setRefreshing(false);
            return;
        }

        TIMFriendshipManager.getInstance().getUsersProfile(peers, new TIMValueCallBack<List<TIMUserProfile>>() {
            @Override
            public void onError(int i, String s) {
                swipeRefreshLayout.setRefreshing(false);
            }

            @Override
            public void onSuccess(List<TIMUserProfile> timUserProfiles) {
                swipeRefreshLayout.setRefreshing(false);
                if (list != null) {
                    for (TIMUserProfile timUserProfile : timUserProfiles) {
                        timUserProfileLinkedHashMap.put(timUserProfile.getIdentifier(), timUserProfile);
                    }
                } else if (newOne != null && timUserProfiles.size() == 1) {
                    TIMUserProfile timUserProfile = timUserProfiles.get(0);
                    timUserProfileLinkedHashMap.put(timUserProfile.getIdentifier(), timUserProfile);
                }
                if (timUserProfileLinkedHashMap.size() == conversations.size()) {
                    refresh();
                }
            }
        });
    }
``

**Comment by wangshaolei** [comment]
``
/**
     * @param list   拉取所有会话资料
     * @param newOne 拉取新会话资料
     */
    private void getUserProfile(final List<TIMConversation> list, final TIMConversation newOne) {
        List<String> peers = null;
        if (list != null && list.size() > 0) {
            peers = new ArrayList<>();
            for (TIMConversation timConversation : list) {
                peers.add(timConversation.getPeer());
            }
        } else if (newOne != null) {
            peers = new ArrayList<String>() {
                {
                    add(newOne.getPeer());
                }
            };
        }
        if (peers == null) {
            swipeRefreshLayout.setRefreshing(false);
            return;
        }

        TIMFriendshipManager.getInstance().getUsersProfile(peers, new TIMValueCallBack<List<TIMUserProfile>>() {
            @Override
            public void onError(int i, String s) {
                swipeRefreshLayout.setRefreshing(false);
            }

            @Override
            public void onSuccess(List<TIMUserProfile> timUserProfiles) {
                swipeRefreshLayout.setRefreshing(false);
                if (list != null) {
                    for (TIMUserProfile timUserProfile : timUserProfiles) {
                        timUserProfileLinkedHashMap.put(timUserProfile.getIdentifier(), timUserProfile);
                    }
                } else if (newOne != null && timUserProfiles.size() == 1) {
                    TIMUserProfile timUserProfile = timUserProfiles.get(0);
                    timUserProfileLinkedHashMap.put(timUserProfile.getIdentifier(), timUserProfile);
                }
                if (timUserProfileLinkedHashMap.size() == conversations.size()) {
                    refresh();
                }
            }
        });
    }
``
目前业务只加了C2C 业务，无论是在会话列表还是聊天页面，只能单独获取用户资料了。感觉很奇葩啊。SDK未来会考虑更新吗。

**Comment by wangshaolei** [comment]
``
目前只能通过这样的方法获取用户资料，在会话列表和聊天页面都是这样，感觉 很奇怪的逻辑，未来SDK会更新这部分吗。
private void getUserProfile(final List<TIMConversation> list, final TIMConversation newOne) {
        List<String> peers = null;
        if (list != null && list.size() > 0) {
            peers = new ArrayList<>();
            for (TIMConversation timConversation : list) {
                peers.add(timConversation.getPeer());
            }
        } else if (newOne != null) {
            peers = new ArrayList<String>() {
                {
                    add(newOne.getPeer());
                }
            };
        }
        if (peers == null) {
            swipeRefreshLayout.setRefreshing(false);
            return;
        }

        TIMFriendshipManager.getInstance().getUsersProfile(peers, new TIMValueCallBack<List<TIMUserProfile>>() {
            @Override
            public void onError(int i, String s) {
                swipeRefreshLayout.setRefreshing(false);
            }

            @Override
            public void onSuccess(List<TIMUserProfile> timUserProfiles) {
                swipeRefreshLayout.setRefreshing(false);
                if (list != null) {
                    for (TIMUserProfile timUserProfile : timUserProfiles) {
                        timUserProfileLinkedHashMap.put(timUserProfile.getIdentifier(), timUserProfile);
                    }
                } else if (newOne != null && timUserProfiles.size() == 1) {
                    TIMUserProfile timUserProfile = timUserProfiles.get(0);
                    timUserProfileLinkedHashMap.put(timUserProfile.getIdentifier(), timUserProfile);
                }
                if (timUserProfileLinkedHashMap.size() == conversations.size()) {
                    refresh();
                }
            }
        });
    }
``

**Comment by wangshaolei** [comment]
现在SDK 无论 是在会话列表和聊天 页面  想获取扩展的用户昵称和头像 只能TIMFriendshipManager.getInstance().getUsersProfile 通过这个API获取，这样逻辑写的时候会很奇怪 ，不知道 未来SDK 会对这部分有所改善吗。

**Comment by wangshaolei** [comment]
UGC已经支持了 v7a 这样可以用新版本了，但是新版SDK并没有 关系链。

**Comment by todo-fixme** [comment]
Google 应用商店.arm64-v8a

**Comment by liukai2530533** [comment]
我也想说 我们是海外app 现在Google商店强制要求arm64-v8a格式，你不支持64位的 我的应用面临的下架啊 唉

**Comment by wangshaolei** [comment]
@liukai2530533 没有啊，我们也是海外，我最近版本都是abifilter armeabi, 刚刚升了armeabi-v7a，gp没有提醒我啊。

**Comment by liukai2530533** [comment]
![1551861578 1](https://user-images.githubusercontent.com/23752905/53867404-b91efd80-402e-11e9-8343-d98c4edd5f49.png)
老哥关注一波 反正是尽量要求你提供64位 下架估计得到明年还是后年

**Comment by liukai2530533** [comment]
我们经理已经收到邮件，我跟他说不要慌还没到时间呢  等差不多到时间了腾讯SDK会搞64位的，😄
![1](https://user-images.githubusercontent.com/23752905/53867801-8b868400-402f-11e9-923f-7f393a508d77.png)
![2](https://user-images.githubusercontent.com/23752905/53867802-8c1f1a80-402f-11e9-8095-c5dae41f5eae.png)
确实是有这个要求 强制下架得到明年之后吧

**Comment by vinsonswang** [comment]
用户资料和关系链已经在开发中了，另外arm64-v8a也会在近期支持，大家耐心等待哈

**Comment by wangshaolei** [comment]
@liukai2530533 可能我没留意过。

**Comment by vinsonswang** [comment]
4.0.12版本已支持arm64-v8a架构

**Comment by lynxzhang** [comment]
问题已解决
