### ISSUE TITLE
【Android】-【4.4.900】：【设置了右边内容字体颜色，聊天页面字体颜色错乱】

### ISSUE THREAD

**Issue by qiuqiutang** [tencentyun/TIMSDK#280]
【集成包】：TUIKIT
【当前现象】：mChatLayout.getMessageLayout().setRightChatContentFontColor(Color.WHITE);设置非0字体颜色, 在聊天页面，左边显示的字体颜色偶尔会把右边的颜色带过来
【机型】：如华为Mate 20
【之前版本有无此问题】：之前没有这个问题

**Comment by fairytale110** [comment]
一旦有改动，你就得给sender 和receiver的holder都设置样式，不管你改没改，真的，不然一刷新就乱了，他们这个TUIKit的对话列表设计缺陷有待优化。我都懒得跟新TUIkit了，

**Comment by parkhuang** [comment]
这个问题会在下个版本解决
