### ISSUE TITLE
[android] sdk版本4.4.900 为什么回去会话列表 getConversationList 拿到的数据里面只有id 和title 头像还null

### ISSUE THREAD

**Issue by ma422213631** [tencentyun/TIMSDK#284]
[android] sdk版本4.4.900 为什么回去会话列表 getConversationList 拿到的数据里面只有id 和title 头像还null

**Comment by vinsonswang** [comment]
头像的获取可以参考https://cloud.tencent.com/document/product/269/33926#.E8.8E.B7.E5.8F.96.E6.8C.87.E5.AE.9A.E7.94.A8.E6.88.B7.E7.9A.84.E8.B5.84.E6.96.99
