### ISSUE TITLE
【Android & iOS】- 【ALL VERSION】当你们SDK发布新版本后，我们App未更新到最新SDK的IM无法收到离线消息

### ISSUE THREAD

**Issue by fairytale110** [tencentyun/TIMSDK#285]
如题，问题一直存在，
当你们的SDK发布了新版本，这时我们的App 还未及时更新或者不知道你们发布了新版本SDK时，App的离线消息就没法收到了，亲测，Android和iOS都是这样。

这就导致我们必须强制更新SDK并重新发布App，这是很大的问题。

当我们的App趋于稳定时，并不想继续更新IM的SDK，但仍要保持已有的IM功能都正常运作。

所有希望贵团队可以优化下这个问题。别你们一发布新版本，我们的老版本就无法接收到离线推送了。

**Comment by vinsonswang** [comment]
你好，新版SDK发布是不影响离线推送功能的。
可以参考 https://cloud.tencent.com/document/product/269/32486#.E6.94.B6.E4.B8.8D.E5.88.B0.E7.A6.BB.E7.BA.BF.E6.8E.A8.E9.80.81.E6.80.8E.E4.B9.88.E5.A4.84.E7.90.86.EF.BC.9F 排查一下

**Comment by fairytale110** [comment]
> 你好，新版SDK发布是不影响离线推送功能的。
> 可以参考 https://cloud.tencent.com/document/product/269/32486#.E6.94.B6.E4.B8.8D.E5.88.B0.E7.A6.BB.E7.BA.BF.E6.8E.A8.E9.80.81.E6.80.8E.E4.B9.88.E5.A4.84.E7.90.86.EF.BC.9F 排查一下

抱歉，排查了，证书用错了环境，感谢耐心解答。
