### ISSUE TITLE
Android SDK ABI - 居然还没 3.3 提供的全面

### ISSUE THREAD

**Issue by ghost** [tencentyun/TIMSDK#29]
最起码 armeabi、armeabi-v7a、arm64-v8a 需要支持啊！

其他可选呗.
难道TXIM 气量变化了？

**Comment by todo-fixme** [comment]
坐等TX大哥更新.

**Comment by vinsonswang** [comment]
后面会考虑增加arm64-v8a、x86、x86_64的支持

**Comment by vinsonswang** [comment]
4.0.12版本已增加arm64-v8a架构支持

**Comment by alex2390** [comment]
什么时候支持armeabi架构啊
