### ISSUE TITLE
iOS 账户A被挤掉后，登录另一个账户B，会话列表还是之前账户的。

### ISSUE THREAD

**Issue by lcccch** [tencentyun/TIMSDK#30]

**Comment by lcccch** [comment]
像是没登录成功

**Comment by lynxzhang** [comment]
请问您这边使用的是哪个版本？互踢的逻辑在新版本做了优化，麻烦更新新版本试下，有问题欢迎再反馈

**Comment by lcccch** [comment]
最新版本还是有问题

**Comment by lcccch** [comment]
iOS 账户A，先调用一下[TIMManager getConversationList] 。
被挤掉后，马上登录另一个账户B(不要重启app)，打开会话列表还是之前账户A的。
[TIMManager getConversationList] 得到的数据是还是A账户的。
