### ISSUE TITLE
【Android】-【4.4.900】：关于IM消息提醒

### ISSUE THREAD

**Issue by Songsongbuchifan** [tencentyun/TIMSDK#300]
在程序不杀死的情况下，按HOME键退到后台，我该怎样做能显示新消息的提示？
希望能得到回复，谢谢。

**Comment by vinsonswang** [comment]
在Android端程序不杀死情况下，目前是不会通过厂商的推送通道推送离线消息过来的。您可以自己在App业务上层判断退到后台时，接收到了新的消息(onNewMessages)通过NotificationManager弹通知栏消息

**Comment by Songsongbuchifan** [comment]
谢谢您：），想错了  一直在调试
