### ISSUE TITLE
4.4.417、4.4.900这两都有这个问题

### ISSUE THREAD

**Issue by ywx372421496** [tencentyun/TIMSDK#305]
•	【iOS】-【4.4.417】、【4.4.900】：【onDisconnect错误】
•	【集成包】：TIMSDK
•	【当前现象】：不知道什么原因，今天老是提示onDisconnect：code是0，err是nil（30秒走一次），并且onConnSucc还进入了，导致业务上出现错误
•	【机型】：iphone全部
•	【之前版本有无此问题】：TIMSDK3.3.2没有这个问题
[网络正常，网络连接断开还提示一直来.zip](https://github.com/tencentyun/TIMSDK/files/3544728/default.zip)

/**
 *  网络连接成功
 */
- (void)onConnSucc;

/**
 *  网络连接断开（断线只是通知用户，不需要重新登录，重连以后会自动上线）
 *
 *  @param code 错误码
 *  @param err  错误描述

 */
- (void)onDisconnect:(int)code err:(NSString*)err;

**Comment by jianfma** [comment]
感谢您的反馈，原因分析到了，预计下周三的版本修复问题

**Comment by ywx372421496** [comment]
> 感谢您的反馈，原因分析到了，预计下周三的版本修复问题

好的，谢谢
