### ISSUE TITLE
自定义消息 聊天界面错乱  聊天界面消息背景没有气泡  消息框压在时间上面

### ISSUE THREAD

**Issue by xusigh** [tencentyun/TIMSDK#306]
issue标题：

【Android】-【4.4.900】：【自定义消息】
【集成包】：TUIKIT
【当前现象】：自定义消息 聊天界面错乱  聊天界面消息背景没有气泡  消息框压在时间上面
【机型】：小米4移动4G版  小米2s
【之前版本有无此问题】：都有
【有无日志或者描述、截图】：
![Screenshot_2019-08-27-19-12-39-422_com hxdata iws](https://user-images.githubusercontent.com/16810599/63767120-4d439080-c8ff-11e9-985d-c8c8a5dc4fe0.png)

**Comment by xusigh** [comment]
自定义的消息 摄像头图标写在xml文件中 左右两边的头像也没有了

**Comment by fairytale110** [comment]
多看下TUIKit的扩展工具。。。。

**Comment by xusigh** [comment]
请问TUIKit的扩展工具在哪里

**Comment by xusigh** [comment]
> 多看下TUIKit的扩展工具。。。。

请问TUIKit的扩展工具在哪里
