### ISSUE TITLE
Android 发送图片、语音、视频报60008错误

### ISSUE THREAD

**Issue by jason4it** [tencentyun/TIMSDK#308]
【Android】-【4.4.900】：【聊天界面】
【集成包】：TUIKIT
【当前现象】：发送图片报60008错误
【机型】：小米9 系统9.0  、华为 EML-AL00 Android 9

{"ActionStatus":"FAIL","ErrorCode":60008,"ErrorInfo":"service timeout or request format error,please check and try again"}

**Comment by rexydimen** [comment]
我也报了，还有7006，发送图片和视频的时候报的。机型是5.1.1的vivo x7

**Comment by vinsonswang** [comment]
> 【Android】-【4.4.900】：【聊天界面】
> 【集成包】：TUIKIT
> 【当前现象】：发送图片报60008错误
> 【机型】：小米9 系统9.0 、华为 EML-AL00 Android 9
> 
> {"ActionStatus":"FAIL","ErrorCode":60008,"ErrorInfo":"service timeout or request format error,please check and try again"}

你好，这个错误是指请求超时了，新版本对上传文件消息做了优化，可以更新到最新版本再测试下
