### ISSUE TITLE
TUIKit可以支持CocoaPod吗，还有文档需要及时更新一下

### ISSUE THREAD

**Issue by Bruce-pac** [tencentyun/TIMSDK#31]

**Comment by vinsonswang** [comment]
是支持的，文档最近几天会更新上去

**Comment by Bruce-pac** [comment]
@vinsonswang   用cocoapod导入TUIKit,在TConversationCell.h里提示'TUnReadView.h' file not found，在framework和headers里面没有TUnReadView.h文件，请尽快解决

**Comment by lynxzhang** [comment]
收到，我们优化下，这边测试验证后预计下周一会和文档一起发布

**Comment by AshokaCao** [comment]
获取聊天好友的头像昵称什么的怎么没有

**Comment by lynxzhang** [comment]
@Bruce-pac   pod 集成 TUIKit 已上线 https://cloud.tencent.com/document/product/269/32704

**Comment by lynxzhang** [comment]
@AshokaCao 新版本资料关系链逻辑正在开发中
