### ISSUE TITLE
saveMessage保存消息为未读,获取未读数确为0

### ISSUE THREAD

**Issue by ysxlmk** [tencentyun/TIMSDK#310]
【Android】-【4.4.900】：【saveMessage保存消息为未读,获取未读数确为0】
【集成包】：SDK
【当前现象】：通过saveMessage方法保存消息,并设置成未读,但是获取对话的消息未读数确为0
【机型】：所有
【之前版本有无此问题】：4.4.716没有这问题
【有无日志或者截图】：暂无日志

**Comment by vinsonswang** [comment]
调用本地存消息的方法这个状态是不生效的，不会改变未读数
