### ISSUE TITLE
【小程序版本】：【#getConversationList 接口需要返回自定义消息内容】 

### ISSUE THREAD

**Issue by QingWei-Li** [tencentyun/TIMSDK#318]
现在通过 `#getConversationList` 获取的到的自定义消息都是被处理过成`[其他]`，无论是自己发的还是别人发的。希望能返回完整 payload

**Comment by Rychou** [comment]
感谢提出issue，我们会在后续版本给会话结构体中，加上最后一条消息的消息体。

**Comment by Rychou** [comment]
> 现在通过 `#getConversationList` 获取的到的自定义消息都是被处理过成`[其他]`，无论是自己发的还是别人发的。希望能返回完整 payload

你好，最新版本SDK已加上会话最后一条消息的完整 payload，请更新至最新版SDK验证。[tim-wx-sdk](https://www.npmjs.com/package/tim-wx-sdk)
