### ISSUE TITLE
【Android】-【4.5.15】：加入视频直播群会收到一条空内容的推送

### ISSUE THREAD

**Issue by gnaix** [tencentyun/TIMSDK#321]
【集成包】：TIMSDK
【当前现象】：Android Studio集成新版本TIMSDK, 加入视频直播群时，会收到一条离线推送， 
  notification的title和content都是空的，现在解决办法是自己过滤掉
 TIMManager.getInstance().setOfflinePushListener(notification -> {
           notification.doNotify(this,R.mipmap.ic_launcher);
        });
【机型】：Mate10 pro
【之前版本有无此问题】：没有

**Comment by xusigh** [comment]
借楼添加一条
除了上面同样的问题，还有发送一条无痕消息
CurrentConversation.sendOnlineMessage 会在当前聊天页面添加一条记录
退出聊天界面重新进入就消息没有了

**Comment by xusigh** [comment]
【机型】：小米4 小米2s

**Comment by vinsonswang** [comment]
你好，setOfflinePushListener这个接口已废弃，业务层可以去掉该实现。如果应用在收到消息后有自己弹通知栏的需求，需要应用调用系统的notificationManager相关的api实现。

**Comment by vinsonswang** [comment]
> 借楼添加一条
> 除了上面同样的问题，还有发送一条无痕消息
> CurrentConversation.sendOnlineMessage 会在当前聊天页面添加一条记录
> 退出聊天界面重新进入就消息没有了

sendOnlineMessage的特性是这样的，会通过onNewMessage抛出去，如果在聊天界面TUIKit默认会添加一条记录，但是并不会保存该消息。
