### ISSUE TITLE
Error installing TXIMSDK_iOS

### ISSUE THREAD

**Issue by elderJiang** [tencentyun/TIMSDK#323]
[!] /usr/bin/git clone https://github.com/tencentyun/TIMSDK.git /var/folders/f3/pm5vh3h57jzbhjy0y53y4xr40000gn/T/d20190903-48083-1on5t7f --template= --single-branch --depth 1 --branch 4.4.716

Cloning into '/var/folders/f3/pm5vh3h57jzbhjy0y53y4xr40000gn/T/d20190903-48083-1on5t7f'...
warning: Could not find remote branch 4.4.716 to clone.
fatal: Remote branch 4.4.716 not found in upstream origin

**Comment by lynxzhang** [comment]
pod setup
pod repo update
rm ~/Library/Caches/CocoaPods/search_index.json

**Comment by lynxzhang** [comment]
执行下上面的命令再试下
