### ISSUE TITLE
【iOS】-【4.5.15】- 如何登录demo

### ISSUE THREAD

**Issue by baiyidjp** [tencentyun/TIMSDK#326]
一直提示没有配置好，用户名如何配置？

**Comment by lynxzhang** [comment]
https://cloud.tencent.com/document/product/269/36838 参考下这个文档配置下 SDKAPPID 和 SECRETKEY 就可以了

**Comment by baiyidjp** [comment]
我参考了，编译通过运行起来，有个输入用户名登录的界面，我想问的是用户名哪来的？怎么配置

**Comment by fairytale110** [comment]
在管理后台生成，

**Comment by elderJiang** [comment]
麻烦把这种问题关闭！
