### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by ForiWong** [tencentyun/TIMSDK#329]
when i run the android demo.
show the log:
File google-services.json is missing. The Google Services Plugin cannot function without it. 
how  to make it?

**Comment by huangkaiqiao** [comment]
平台 [android] IDE [android studio 3.4.2] JRE [1.8.0_152] 编译不通过, 报错信息
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location:

**Comment by ForiWong** [comment]
> 平台 [android] IDE [android studio 3.4.2] JRE [1.8.0_152] 编译不通过, 报错信息
> File google-services.json is missing. The Google Services Plugin cannot function without it.
> Searched Location:

我后来去https://console.firebase.google.com注册了一个项目，下载到了google-services.json。运行还是有问题
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Duplicate class androidx.core.graphics.drawable.IconCompatParcelizer found in modules androidx.core.1.0.0.jar (androidx.core.1.0.0.jar) and classes.jar (com.android.support:support-compat:28.0.0)
Duplicate class androidx.core.internal.package-info found in modules androidx.core.1.0.0.jar (androidx.core.1.0.0.jar) and classes.jar (com.android.support:support-compat:28.0.0)

**Comment by vinsonswang** [comment]
这个是集成google的FCM推送所需的文件，已补充上传
