### ISSUE TITLE
【安卓】- 【4.5.15】：卸载重新安装后，未读消息计数清零

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#334]
【当前现象】会话界面存在未读消息，卸载应用然后重新安装后，回到会话界面，所有的消息都显示已读，未读消息计数为0
【集成包】IMSDK
【机型】小米6
【之前版本有无此问题】好像没有，没太注意

**Comment by vinsonswang** [comment]
如果是自动上报开启(默认开启)，卸载重装或者其他终端登录未读计数会清零；
如果禁用，卸载重装或者其他终端登录未读计数还会在。
接口是在TIMUserConfig中的disableAutoReport。

参考：https://cloud.tencent.com/document/product/269/9226#.E7.A6.81.E7.94.A8.E8.87.AA.E5.8A.A8.E4.B8.8A.E6.8A.A5
