### ISSUE TITLE
【微信小程序】-【2.0.5】: 单聊界面消息重复上屏Bug，2.0.3版本没有

### ISSUE THREAD

**Issue by xufangda** [tencentyun/TIMSDK#335]
【当前现象】：2.0.5官方小程序Demo单聊界面，每次发送信息会有两条消息上屏。

原因是SDK2.0.3和SDK2.0.5的行为不一致，
2.0.5在【**发送消息**】或接受消息的的时候，都会触发onMessageReceive回调函数。
但是2.0.3只在接受消息的时候，触发onMessageReceive回调函数。

这应该算SDK的问题吧，毕竟之前依赖2.0.3的都好使。。。。
如果算新添的Feature的话，可能小程序得改一下。。。

【复现方法】: 用最近更新的官方小程序Demo，分别用SDK2.0.3和SDK2.0.5编译，随便开个单聊页面，瞬间就能复现这个Bug

【集成包】：TIM-WX-SDK
【之前版本有无此问题】：2.0.3没问题，2.0.5有问题
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好

![2 0 3](https://user-images.githubusercontent.com/6506508/64389323-204b5800-d03a-11e9-8ce0-6b9043293523.png)
![2 0 5](https://user-images.githubusercontent.com/6506508/64388132-17f11e00-d036-11e9-8577-000e8a0ca7dc.png)

**Comment by anderlu** [comment]
v2.0.6已修复该问题，麻烦更新v2.0.6，非常抱歉给您造成不便。
