### ISSUE TITLE
【小程序】【2.0.6】请问 sendMessage 表现是否可以确定？

### ISSUE THREAD

**Issue by banricho** [tencentyun/TIMSDK#337]
2.0.4 版本，sendMessage 发送的出去的消息，同时也会被 `TIM.EVENT.MESSAGE_RECEIVED` 事件推送。两个消息虽然内容一样，但是 id 却不同。
升级到了 2.0.6 版本，`TIM.EVENT.MESSAGE_RECEIVED` 不再推送自身发出的消息。

请问这个表现是符合预期的，还是 bug？

**Comment by Rychou** [comment]
> 2.0.4 版本，sendMessage 发送的出去的消息，同时也会被 `TIM.EVENT.MESSAGE_RECEIVED` 事件推送。两个消息虽然内容一样，但是 id 却不同。
> 升级到了 2.0.6 版本，`TIM.EVENT.MESSAGE_RECEIVED` 不再推送自身发出的消息。
> 
> 请问这个表现是符合预期的，还是 bug？

您好，v2.0.4, v2.0.5 两个版本中，发 C2C 消息会触发 `TIM.EVENT.MESSAGE_RECEIVED` 事件，属于SDK内部的BUG.

v2.0.6已修复该问题，麻烦更新v2.0.6，非常抱歉给您造成不便。
