### ISSUE TITLE
服务器备份的历史消息和sdk返回的历史消息格式不一致

### ISSUE THREAD

**Issue by xblj** [tencentyun/TIMSDK#339]
能把源码放出来不？服务器备份的历史消息和sdk直接请求的历史消息格式不一致，能提供功能下转换消息格式方法嘛？或者吧源码放出来吧，压缩的都没法看，都不知道咋改

**Comment by parkhuang** [comment]
感谢反馈，能仔细说明一下您的目的吗？分别用的什么api，返回的消息格式不一样在哪里？
