### ISSUE TITLE
没有新消息，也会调用吗？还调两遍。。

### ISSUE THREAD

**Issue by proHUZhiYong** [tencentyun/TIMSDK#340]
![image](https://user-images.githubusercontent.com/34712940/64515089-80821880-d31e-11e9-9f0d-4e1eaf6f5053.png)

**Comment by Rychou** [comment]
@proHUZhiYong 您好，没太看明白您表达的意思，能否详细描述一下问题呢？

**Comment by proHUZhiYong** [comment]
您好，是这样的，我在好友列表页面设置消息监听（tim.on(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived);）来确认是否有新消息；但是在初始化好友列表页面(刚加载页面)时，会触发两次 消息监听，打印两次消息列表数据（如上图），不清楚是什么原因导致的；
tim.on(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived); 不是有新消息才会触发吗？

**Comment by Rychou** [comment]
> 您好，是这样的，我在好友列表页面设置消息监听（tim.on(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived);）来确认是否有新消息；但是在初始化好友列表页面(刚加载页面)时，会触发两次 消息监听，打印两次消息列表数据（如上图），不清楚是什么原因导致的；
> tim.on(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived); 不是有新消息才会触发吗？

@proHUZhiYong 您好，SDK 初始化时会同步服务器的未读消息到本地，您说的那些消息都是未读消息。只要没进行已读上报，初始化时都会把未读消息同步到本地的。

**Comment by proHUZhiYong** [comment]
好的，十分感谢
