### ISSUE TITLE
部分手机发送输入法自带表情，其它的一些手机显示乱码

### ISSUE THREAD

**Issue by zhangxi28** [tencentyun/TIMSDK#341]
发送端：   vivo手机，在软键盘自带的表情选择表情发送，
接收端：   华为mete20显示乱码，oppo手机vivo手机正常显示。

**Comment by zhangxi28** [comment]
TIMMessage{
	ConverstaionType:Group
	ConversationId:@TGS#2GLJTO6F3
	MsgId:351972217
	MsgSeq:25553
	Rand:351972217
	time:1568027201
	isSelf:false
	Status:SendSucc
	Sender:4620740519366823936
	elements:[
		{Type:Text, Content:������}
	]
}

**Comment by zhangyuiris** [comment]
手机输入法软键盘发送的表情一般都是emoji，在另外一些手机上如果没有对应可解析的字体，是会解析不了的，您需要自己做适配呢，这不属于sdk内部问题

**Comment by zhangyuiris** [comment]
> 发送端： vivo手机，在软键盘自带的表情选择表情发送，
> 接收端： 华为mete20显示乱码，oppo手机vivo手机正常显示。

@zhangxi28  手机输入法软键盘发送的表情一般都是emoji，在另外一些手机上如果没有对应可解析的字体，是会解析不了的，您需要自己做适配呢，这不属于sdk内部问题

**Comment by zhangxi28** [comment]
有没有好的适配方案提供下，比如文章链接什么的,谢谢

**Comment by zhangyuiris** [comment]
> 有没有好的适配方案提供下，比如文章链接什么的,谢谢

@zhangxi28 您可以直接搜一下`emoji适配方式`，希望能解决您的问题

**Comment by zhangxi28** [comment]
我调试发现发送消息给sdk，sdk没有unicode或者utf编码，发送给远端也没有解码

**Comment by jeekun** [comment]
@zhangxi28  解决了吗，我这边遇到同样的问题

**Comment by zhangxi28** [comment]
> @zhangxi28 解决了吗，我这边遇到同样的问题

客户端可以在发送时编码，在接收时解码。但是对于已经发出去的老版本会有问题，所以这个也不是个好的解决方案，最好还是由sdk来解决，这样只要升级sdk就好了

**Comment by jeekun** [comment]
是的，老实讲，升级到4.x之后，问题多多

**Comment by parkhuang** [comment]
@zhangxi28 vivo手机型号是什么，能不能发送也接受分别截图看看。我刚才用vivo nex默认输入法是搜狗的vivo版本
