### ISSUE TITLE
取消事件绑定调用栈溢出

### ISSUE THREAD

**Issue by xblj** [tencentyun/TIMSDK#343]
issue标题：取消事件绑定调用栈溢出

【web】-【2.0.3】：【取消事件绑定调用栈溢出】
issue内容：

【当前现象】：调用`tim.off`函数取消事件绑定会导致调用栈溢出
【集成包】：IMSDK
【机型】：pc
【之前版本有无此问题】：如4.4.479之前没有，4.4.479有
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
![image](https://user-images.githubusercontent.com/23544997/64587657-a36e0480-d3d2-11e9-9837-b66a99d51a45.png)

![image](https://user-images.githubusercontent.com/23544997/64587633-8f2a0780-d3d2-11e9-813d-ba610118fb66.png)

![image](https://user-images.githubusercontent.com/23544997/64587536-4eca8980-d3d2-11e9-9135-0db18e684ec4.png)

**Comment by Rychou** [comment]
@xblj 您好，最新版本SDK已修复该问题，请更新至最新版本SDK。带来不便，非常抱歉！
