### ISSUE TITLE
【Android】-【4.4.479】：【发送自定义打招呼消息，会重复】

### ISSUE THREAD

**Issue by coolstar1204** [tencentyun/TIMSDK#346]
【Android】-【4.4.479】：【发送自定义打招呼消息，会重复】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，
 用户发起招呼动作函数：
 private fun sendCustomMessage() {
        var json = JsonObject()
        json.addProperty("type", 101)
        chatPanel.sendMessage(MessageInfoUtil.buildCustomMessage(json.toString(), "👏已向对方发送打招呼"))
    }
此函数会在多次调用后，造成后面某些用户打招呼消息在界面显示两次

【机型】：小米 6X
【之前版本有无此问题】：
【有无日志或者截图】：

//此日志是自定义发送招呼消息触发
2019-09-11 16:33:13.112 20403-20403/I/tuikit/C2CChatManager: sendC2CMessage 1 status:2,msg:TIMMessage{
    	ConverstaionType:Invalid
    	ConversationId:
    	MsgId:3888479012
    	MsgSeq:59333
    	Rand:3888479012
    	time:1568190791
    	isSelf:true
    	Status:Sending
    	Sender:2635
    	elements:[
    		{Type:Custom
    		desc: 
    		data: {"type":101}
    		ext: 👏已向对方发送打招呼}
    	]
    }
2019-09-11 16:33:13.385 20403-20403/ I/tuikit/C2CChatManager: sendC2CMessage onSuccess time=270

//下面日志是C2CChatManager.java的loadChatMessages函数触发。
2019-09-11 16:33:13.520 20403-20403/ I/tuikit/C2CChatManager: load message status:1,msg:TIMMessage{
    	ConverstaionType:C2C
    	ConversationId:3998
    	MsgId:3888547400
    	MsgSeq:59334
    	Rand:3888547400
    	time:1568190791
    	isSelf:true
    	Status:Sending
    	Sender:2635
    	elements:[
    		{Type:Custom
    		desc: 
    		data: {"type":101}
    		ext: 👏已向对方发送打招呼}
    	]
    }
2019-09-11 16:33:13.523 20403-20403/ I/tuikit/C2CChatManager: sendC2CMessage 2 status:1,msg:TIMMessage{
    	ConverstaionType:C2C
    	ConversationId:3998
    	MsgId:3888547400
    	MsgSeq:59334
    	Rand:3888547400
    	time:1568190791
    	isSelf:true
    	Status:Sending
    	Sender:2635
    	elements:[
    		{Type:Custom
    		desc: 
    		data: {"type":101}
    		ext: 👏已向对方发送打招呼}
    	]
    }
2019-09-11 16:33:13.793 20403-20403/ I/tuikit/C2CChatManager: sendC2CMessage onSuccess time=267

**Comment by parkhuang** [comment]
Demo从4.5.15已经集成了发送自定义消息，在聊天输入框，点击“+”，弹出的列表第二屏，可以用这个测试连续发送，是否额外的消息出现

**Comment by coolstar1204** [comment]
已经发现原因，发送自定义消息时，和loadmessage有一个线程同步问题引发。两个线程执行时序有错位后，sendcustommessage发送线程晚于loadmessage后，就会出现两次

**Comment by hyde190** [comment]
我在4.8.10上面发现还会偶现

**Comment by hyde190** [comment]
我在4.8.10上面发现还会偶现

**Comment by hyde190** [comment]
请教一下，这个问题，什么时候可以更新一下？4.8.10版本还是会偶现
