### ISSUE TITLE
今天刚出现的问题

### ISSUE THREAD

**Issue by proHUZhiYong** [tencentyun/TIMSDK#348]
![image](https://user-images.githubusercontent.com/34712940/64765428-af92c700-d576-11e9-85d7-eca0168feccc.png)

登录成功后就报了一个502  不知是什么原因导致的，

错误提示：pingd:1 GET http://pingtcss.qq.com/pingd?dm=localhost:8081&pvi=293061567743928355&si=s578931568274552977&url=/%23!%2fmain%2ftopdomain%2ffriends&arg=&ty=0&rdm=&rurl=&rarg=&adt=&r2=500690998&scr=375x667&scl=24-bit&lg=zh-cn&tz=-8&ext=version=2.0.14&random=1568275260981 502 (Bad Gateway)

**Comment by yangq1990** [comment]
感谢反馈，这个http请求是mta统计上报请求，即使502也不会影响im sdk的正常使用。已将相关问题反馈给mta的开发同学
