### ISSUE TITLE
【H5】-【4.5.15】：【H5创建群组后聊天框无法打开】

### ISSUE THREAD

**Issue by jason-answer** [tencentyun/TIMSDK#351]
issue内容：

【当前现象】：创建群组后聊天框复发发送信息
【集成包】：IMSDK
【机型】：web
【之前版本有无此问题】：4.5.15
【有无日志或者描述、截图】：创建群成功后，点击群组，报错如下。
**tim-js-sdk 中 tim.getConversationProfile() , 返回无memberList 信息。**

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'filter' of undefined"

found in

---> <MessageSendBox> at src/components/message/message-send-box.vue
       <CurrentConversation> at src/components/conversation/current-conversation.vue
         <Index> at src/index.vue
           <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
Vue._render @ vue.runtime.esm.js?2b0e:3544
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
createChildren @ vue.runtime.esm.js?2b0e:6047
createElm @ vue.runtime.esm.js?2b0e:5948
updateChildren @ vue.runtime.esm.js?2b0e:6210
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
updateCurrentConversation @ conversation.js?1cbe:61
wrappedMutationHandler @ vuex.esm.js?2f62:725
commitIterator @ vuex.esm.js?2f62:391
(anonymous) @ vuex.esm.js?2f62:390
_withCommit @ vuex.esm.js?2f62:521
commit @ vuex.esm.js?2f62:389
boundCommit @ vuex.esm.js?2f62:334
(anonymous) @ conversation.js?1cbe:153
Promise.then (async)
checkoutConversation @ conversation.js?1cbe:151
wrappedActionHandler @ vuex.esm.js?2f62:732
dispatch @ vuex.esm.js?2f62:437
boundDispatch @ vuex.esm.js?2f62:331
selectConversation @ conversation-item.vue?995e:125
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'filter' of undefined
    at VueComponent.memberList (message-send-box.vue?cd3f:108)
    at VueComponent.mappedState (vuex.esm.js?2f62:836)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4578)
    at VueComponent.computedGetter [as memberList] (vue.runtime.esm.js?2b0e:4830)
    at Object.get (vue.runtime.esm.js?2b0e:2072)
    at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"ab5a1be6-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/message/message-send-box.vue?vue&type=template&id=0148fc24& (app.js:2036), <anonymous>:191:22)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3542)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)

**Comment by yangq1990** [comment]
您好，我们没有复现此问题，可以加入QQ群468195767做进一步的沟通

**Comment by yangq1990** [comment]
demo版本问题，已解决
