### ISSUE TITLE
群解散之后无法删除群会话的问题

### ISSUE THREAD

**Issue by liukai2530533** [tencentyun/TIMSDK#352]
【Android】-【4.4.900】：【群解散之后无法删除群会话的问题】
【集成包】：TIMSDK
【当前现象】：一个人解散群了，另一个人如果在线会收到监听，我会收到监听的时候把这个会话删除掉，一切正常，但是如果这个人不在线，收不到监听，无法删除这个群会话，那么会话列表上面的群头像和群名称都在，只是点进去Chat页面无法发送消息而已，这个是怎么解决？删除群之后理论上应该在获取会话列表的时候不给我这些数据吧？ 或者在群组的SDK中加一个API让我判断这个群的状态是否解散了之类的，我好删除这个会话，但是目前我没有找到这样的API,想问问这应该怎么处理？是我处理不当吗？
【机型】：All
【之前版本有无此问题】：有
【有无日志或者截图】：会话列表上面的群头像和群名称都在

**Comment by parkhuang** [comment]
再次上线仍然消息通知，有两种通知可以帮助你知道该群被删：
1、TIMRefreshListener.onRefreshConversation
2、TIMMessageListener.onNewMessages

可以断点tuikit的ConversationManagerKit.groupSystMsgHandle和GroupChatManagerKit.onReceiveSystemMessage查看整个调用逻辑
