### ISSUE TITLE
android im 4.4.900离线推送

### ISSUE THREAD

**Issue by dwdegithub** [tencentyun/TIMSDK#354]
收到im的离线推送后，点击跳转时怎么携带想要的数据？自定义跳转链接已经在后台配置了

**Comment by vinsonswang** [comment]
目前只能用restapi发消息可以灵活设置自定义的数据，参考
https://cloud.tencent.com/document/product/269/1629?!preview&!editLang=zh#.E8.AF.B7.E6.B1.82.E5.8F.82.E6.95.B0.E8.AF.B4.E6.98.8E
![image](https://user-images.githubusercontent.com/34643015/65048217-55d73600-d996-11e9-88f4-6a1c896c0146.png)
并且不同厂商的表现不同，作为应用上层实现起来也需要适配各个厂商手机。下面是目前测试各个厂商携带自定义数据的部分结论：
1、vivo：设置点击通知后打开应用或者跳转到自定义界面，OfflinePushInfo中的Ext字段内容都可以在onNotificationMessageClicked里面通过Map<String, String> paramMap = upsNotificationMessage.getParams();拿到自定义的字段，其中key值为"ext"（注意小写）
2、小米：控制台设置了打开应用，会回调小米的onNotificationMessageClicked方法从中拿到自定义内容，但是不会打开应用。如果选择了打开应用指定界面，那么从intent中的bundle也会有自定义的内容，封装消息的MiPushMessage对象通过Intent传到客户端，客户端在相应的Activity中可以调用Intent的getSerializableExtra（PushMessageHelper.KEY_MESSAGE）方法得到MiPushMessage对象。例如
`Bundle bundle = getIntent().getExtras();
MiPushMessage miPushMessage = (MiPushMessage)bundle.getSerializable(PushMessageHelper.KEY_MESSAGE);
Log.e("ChatActivity", "bundle miPushMessage = " + miPushMessage);
Map extra = miPushMessage.getExtra();
Log.e("ChatActivity", "bundle miPushMessage extra ext = " + extra.get("ext"));`
3、魅族：控制台设置了打开应用或者打开指定界面，点击通知栏消息后都会回调onNotificationClicked方法，可以从参数中获取自定义内容 mzPushMessage.getSelfDefineContentString()；并且打开的界面可以通过bundle的"ext"字段获取自定义内容。例如：
`Bundle bundle = getIntent().getExtras();
String value = bundle.getString("ext");
Log.e("ChatActivity", "intent bundle ext = " + value);`
4、华为：按照华为官网的文档，后台填充了自定义数据后，点击通知栏消息会回调华为PUSH SDK中的onEvent方法并携带自定义数据。这里Demo在华为P10上测试一直没有回调，跟华为人员沟通暂时没有答复，如果您成功回调了也欢迎一起探讨解决方案。
5、OPPO：OPPO要求发布到应用市场的App才能集成推送，因此暂时没有测试。
6、FCM：点击通知栏可以从启动页的intent中的bundle获取自定义内容，其中key值为"ext"（注意小写）。例如：
`Bundle bundle = getIntent().getExtras();
String value = bundle.getString("ext");
Log.e("ChatActivity", "intent bundle ext = " + value);`

**Comment by dwdegithub** [comment]
web端不能 在发消息的时候 给安卓端配置 ext这个扩展字段么？

**Comment by dwdegithub** [comment]
还有  腾讯离线消息  支持各个厂商的桌面未读消息角标么？通过哪些字段参数配置。
目前我们的应用场景是  web端发送消息，需要安卓端收到离线消息后  弹出通知并显示桌面未读，
点击通知后跳转聊天界面。需要在通知点击的回调中拿到用户信息，创建聊天会话。

**Comment by vinsonswang** [comment]
> web端不能 在发消息的时候 给安卓端配置 ext这个扩展字段么？

暂时不能

**Comment by vinsonswang** [comment]
> 还有 腾讯离线消息 支持各个厂商的桌面未读消息角标么？通过哪些字段参数配置。
> 目前我们的应用场景是 web端发送消息，需要安卓端收到离线消息后 弹出通知并显示桌面未读，
> 点击通知后跳转聊天界面。需要在通知点击的回调中拿到用户信息，创建聊天会话。

离线消息的角标暂时不支持

**Comment by fantasybei** [comment]
针对华为，现在的文档上：https://cloud.tencent.com/document/product/269/34999写着： 
点击通知栏的消息时，客户端在相应的 Activity 中获取自定义内容。

  Bundle bundle = getIntent().getExtras();
  String extContent = bundle.get("ext");

被这个误导了大半天，各种试，请更新下相关文档吧，不然耽误大家时间。
