### ISSUE TITLE
【iOS】-【TIMSDK】：变更群主为什么不发群系统消息？

### ISSUE THREAD

**Issue by somebear** [tencentyun/TIMSDK#355]
需要和设置管理员和取消管理员相同的一组设置群主和取消群主的群系统消息

**Comment by lynxzhang** [comment]
变更群组，群组成员会收到群tips消息，群tips消息会存漫游，群系统消息不会存漫游

**Comment by somebear** [comment]
@lynxzhang 管理员变更的话同时有tips和群系统信息，群系统消息和tips不同的是群系统信息只会发给相关人员，tips所有群成员都可以收到。我们想利用群系统消息给相关人员更强的提醒，tips太弱了。
