### ISSUE TITLE
【小程序】【BUG】【需求】- 删除会话

### ISSUE THREAD

**Issue by AjuPrince** [tencentyun/TIMSDK#356]
【BUG】微信小程序，删除会话接口，不合适，删除提示成功，但是还是可以继续聊天。
【需求】删除会话接口分成两个接口，一个接口支持删除聊天记录，另一个接口删除会话后不能聊天，但可以拉取历史聊天记录

**Comment by yangq1990** [comment]
感谢反馈。当前 deleteConversation 接口的作用是只删除会话，不删除聊天记录。您的需求我们评估下

**Comment by AjuPrince** [comment]
deleteConversation 接口删除会话，目前有BUG，删除后还是可以继续聊天的。

**Comment by 17621921195** [comment]
我的根本就删除不掉。提示没有找到相应的会话，请检查传入参数，可是我的会话id明明传了的

**Comment by yangq1990** [comment]
> deleteConversation 接口删除会话，目前有BUG，删除后还是可以继续聊天的。

当前 deleteConversation 接口的作用是只删除会话，不删除聊天记录。并且删除会话不是拉黑对方，删除会话后可以继续发起聊天

**Comment by AjuPrince** [comment]
会话都删除了，还怎么能够继续聊天呢？这算不算一个BUG

**Comment by yangq1990** [comment]
> 会话都删除了，还怎么能够继续聊天呢？这算不算一个BUG

不是bug。删除会话，只是从最近的会话列表删除，不是拉黑对方，所以删除会话后可以继续发起会话聊天

**Comment by maplehsu** [comment]
@yangq1990  调用deleteConversation删除会话 回调成功 删除完 拉取会话列表还在
