### ISSUE TITLE
【Android】【Bug】通过REST api创建群组，中文名称超过3个字即乱码

### ISSUE THREAD

**Issue by kprince** [tencentyun/TIMSDK#358]
通过REST api创建群组，中文名称超过3个字即乱码，前3个字正常，第2个及以后的中文字乱码

**Comment by 6e6e6e** [comment]
通过restapi获取群组信息，拿到的是不是正常的，还是也乱码

**Comment by kprince** [comment]
@6e6e6e 经过排查问题出在自己的代码，thanks.
