### ISSUE TITLE
android-4.4.900-关系链系统消息重复

### ISSUE THREAD

**Issue by myselyhero** [tencentyun/TIMSDK#359]
文档:(当申请好友时对方需要验证，自己和对方会收到好友申请系统通知，对方可选择同意或者拒绝，自己不能操作，同步之用)
现象：现在的问题是两个人都能收到加好友请求和被拒绝的请求，也就是说1添加2,1会同样收到一条加好友申请(2请求添加1为好友)，2在拒绝1的时候2同样能收到一条1拒绝2的消息，在onNewMessage里面进行关系链消息的拦截和处理，请问怎样过滤掉自己在发送加好友请求时的收到的系统消息和2在拒绝时收到的拒绝的消息(在对后面正常请求不造成影响的情况下)？

集成包：tuikit
机型：oppo R9s
日志截图如下，使用oppo添加vivo

oppo日志：
发送请求的日志
![3](https://user-images.githubusercontent.com/43132305/65213375-80c9a300-dad8-11e9-9a49-4e56ae54f5a5.png)

收到拒绝请求时：
![4](https://user-images.githubusercontent.com/43132305/65213382-88894780-dad8-11e9-9e26-81fa77afa5a6.png)

vivo日志：
收到好友请求
![1](https://user-images.githubusercontent.com/43132305/65213386-8d4dfb80-dad8-11e9-8b98-faba504516b8.png)

vivo拒绝时：
![2](https://user-images.githubusercontent.com/43132305/65213391-92ab4600-dad8-11e9-83ee-dc1fae8e2d1e.png)

**Comment by myselyhero** [comment]
> 文档:(当申请好友时对方需要验证，自己和对方会收到好友申请系统通知，对方可选择同意或者拒绝，自己不能操作，同步之用)
> 现象：现在的问题是两个人都能收到加好友请求和被拒绝的请求，也就是说1添加2,1会同样收到一条加好友申请(2请求添加1为好友)，2在拒绝1的时候2同样能收到一条1拒绝2的消息，在onNewMessage里面进行关系链消息的拦截和处理，请问怎样过滤掉自己在发送加好友请求时的收到的系统消息和2在拒绝时收到的拒绝的消息(在对后面正常请求不造成影响的情况下)？
> 
> 集成包：tuikit
> 机型：oppo R9s
> 日志截图如下，使用oppo添加vivo
> 
> oppo日志：
> 发送请求的日志
> ![3](https://user-images.githubusercontent.com/43132305/65213375-80c9a300-dad8-11e9-9a49-4e56ae54f5a5.png)
> 
> 收到拒绝请求时：
> ![4](https://user-images.githubusercontent.com/43132305/65213382-88894780-dad8-11e9-9e26-81fa77afa5a6.png)
> 
> vivo日志：
> 收到好友请求
> ![1](https://user-images.githubusercontent.com/43132305/65213386-8d4dfb80-dad8-11e9-8b98-faba504516b8.png)
> 
> vivo拒绝时：
> ![2](https://user-images.githubusercontent.com/43132305/65213391-92ab4600-dad8-11e9-83ee-dc1fae8e2d1e.png)

**Comment by myselyhero** [comment]
> 文档:(当申请好友时对方需要验证，自己和对方会收到好友申请系统通知，对方可选择同意或者拒绝，自己不能操作，同步之用)
> 现象：现在的问题是两个人都能收到加好友请求和被拒绝的请求，也就是说1添加2,1会同样收到一条加好友申请(2请求添加1为好友)，2在拒绝1的时候2同样能收到一条1拒绝2的消息，在onNewMessage里面进行关系链消息的拦截和处理，请问怎样过滤掉自己在发送加好友请求时的收到的系统消息和2在拒绝时收到的拒绝的消息(在对后面正常请求不造成影响的情况下)？
> 
> 集成包：tuikit
> 机型：oppo R9s
> 日志截图如下，使用oppo添加vivo
> 
> oppo日志：
> 发送请求的日志
> ![3](https://user-images.githubusercontent.com/43132305/65213375-80c9a300-dad8-11e9-9a49-4e56ae54f5a5.png)
> 
> 收到拒绝请求时：
> ![4](https://user-images.githubusercontent.com/43132305/65213382-88894780-dad8-11e9-9e26-81fa77afa5a6.png)
> 
> vivo日志：
> 收到好友请求
> ![1](https://user-images.githubusercontent.com/43132305/65213386-8d4dfb80-dad8-11e9-8b98-faba504516b8.png)
> 
> vivo拒绝时：
> ![2](https://user-images.githubusercontent.com/43132305/65213391-92ab4600-dad8-11e9-83ee-dc1fae8e2d1e.png)

**Comment by myselyhero** [comment]
望专业人员回复，项目紧急！！！

**Comment by vinsonswang** [comment]
你好，这里处理者收到系统消息是为了多终端同步用的，可以根据消息的发送方字段（sender）来区分这个消息的处理者，例如收到了加好友的系统通知，通过消息的sender字段判断是自己发出的就过滤掉

**Comment by myselyhero** [comment]
好的，感谢回复！
