### ISSUE TITLE
【iOS】-【4.5.45】：【pod中 不支持 use_frameworks!】

### ISSUE THREAD

**Issue by boyxu** [tencentyun/TIMSDK#364]
【当前现象】：当pod中开启 `use_frameworks!` 后，所有的资源文件全部都无法正确找到
【集成包】：TUIKIT
【机型】：All
【之前版本有无此问题】：所有版本都存在这个问题
【有无日志或者描述、截图】：看了下你们的实现，目前的实现仅仅只有在关闭 `use_frameworks!`时，才有效，当pod中由于有些库需要开启`use_frameworks!`时，TUIKit中的资源文件就无法被正确找到了。望解决！

**Comment by wangyutao** [comment]
同样遇到

**Comment by boyxu** [comment]
好几天了，有腾讯的开发者看到吗

**Comment by lynxzhang** [comment]
感谢您的反馈，我们今天优化下这个问题

**Comment by lynxzhang** [comment]
TUIKit 库已经优化，麻烦清空下本地 TUIkit，下载最新的试下
