### ISSUE TITLE
IOS sdk：TXIMSDK_TUIKit_iOS (4.5.15)，UI库方式集成，发送图片、语音、视频等失败

### ISSUE THREAD

**Issue by wangyutao** [tencentyun/TIMSDK#368]
TIM: 2019-09-24 10:35:26.982/I/29451-6754645 /Cache       -imcore_cache.cpp.78:Erase                                  /del msg|id:20190920144917000000000000168374|type:1|client_time:1569291739|server_time:0|seq:17093|rand:1119756364
TIM: 2019-09-24 10:35:26.983/I/29451-6754645 /Msg         -imcore_conversation_task.cpp.3768:UploadSound              /upload|param|type:sound|path:/Users/wangyutao/Library/Developer/CoreSimulator/Devices/7DC2DAB1-BE1D-49A9-A05D-268E45EE9107/data/Containers/Data/Application/9710DD30-5E07-4557-8939-933EF154F303/Documents/com_tencent_imsdk_data/voice/1400242302_20190916151739000000000000168347_voice_1569291543.amr
TIM: 2019-09-24 10:35:26.983/I/29451-6754645 /Msg         -imcore_conversation_task.cpp.3800:Upload                   /Upload File Path:/Users/wangyutao/Library/Developer/CoreSimulator/Devices/7DC2DAB1-BE1D-49A9-A05D-268E45EE9107/data/Containers/Data/Application/9710DD30-5E07-4557-8939-933EF154F303/Documents/com_tencent_imsdk_data/voice/1400242302_20190916151739000000000000168347_voice_1569291543.amr
2019-09-24 10:35:26.985001+0800 CatStreet[29451:6783997] Task <282D87C6-FACB-489C-B32E-EC39505FB45E>.<1> finished with error - code: -1002
2019-09-24 10:35:26.985393+0800 CatStreet[29451:6759946] Task <282D87C6-FACB-489C-B32E-EC39505FB45E>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-1002 "不支持的 URL" UserInfo={NSUnderlyingError=0x600000f545d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <282D87C6-FACB-489C-B32E-EC39505FB45E>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <282D87C6-FACB-489C-B32E-EC39505FB45E>.<1>"
), NSLocalizedDescription=不支持的 URL} [-1002]
TIM: 2019-09-24 10:35:26.987/E/29451-6754645 /Msg         -cos_helper.cpp.392:operator()                              /FetchToken failed, url = https://yun.tim.qq.com/v4/im_cos_sign_svr/cos?sdkappid=1400242302&identifier=20190916151739000000000000168347&usersig=eJxNTskKwjAU-JecpbyXpGlS8FJoVfQgqKjHYl5LsJbQRVzw3y1WwbnNyjzZdrUJ6OZdQyzWSgJM
PtKVGhYzHgAbeWvPuffOshiHDJdcAB8dZ6nuXOHGAqABgwpDjISBP6DSQka-NVcO4XnVJ4fi0VWU
6uOOr5c13TMtUzlrS*x9tkj4PqeTEUU6-RY7dxl*YqgMNxgaeL0B8Yo05Q__, code = -1002, response = 不支持的 URL
TIM: 2019-09-24 10:35:26.988/I/29451-6754645 /Msg         -cos_helper.cpp.66:operator()                               /code:-1 desc:Fetch token failed: http request failed
TIM: 2019-09-24 10:35:26.989/I/29451-6754645 /Msg         -imcore_conversation_task.cpp.3821:Finish                   /upload|code:-3|desc:Fetch token failed: http request failed
TIM: 2019-09-24 10:35:26.989/I/29451-6754645 /Msg         -imcore_conversation.cpp.117:operator()                     /SendMsg|code:-3|msg:Fetch token failed: http request failed

**Comment by lynxzhang** [comment]
您好，这个问题我这边没有复现，方便留个联系方式吗，我们单独调试定位下问题

**Comment by wangyutao** [comment]
账号信息：
appid:1400242302
fromTimId:2019092510022010
toTimId:2019092510052611

fromTimId:2019092510022010对应的登录sign：eJw9jlsLgjAYhv-LrkO2b9M5oQsjKkoCyRC68zDlS5KhK4LovzdadPeeHnhfpMhOgX4anDRJ4khQ
\nuvhGDz2RhEBAifdzO1TGYEsS5jYggFPwDbZ6tNihByhTVEHI3MbpP429K5vzMF5ilcJhy*sdL4ui
\ns9lalAKqq1lFm34*pvWc6-s*X-5Aizf3i4WR4lJKkO8PEa0xWw__

麻烦看看

**Comment by wangyutao** [comment]
sign如果无效，使用这个：
eJw9jlsLgjAYhv-Lbgv5NrfphO6CkLKU2eky2IyPUoZaGdF-b2R0954eeF*kXOnADg5bS5JYcoDp
\nN7rbliSEBUBG35nLyTk0JKF*wzgLgY0NGtv0WOEIAFWgmKB*4-WfxrMvO11pqdetYJv06uRyMQyP
\n8jDnt3yyP*6yOE9d89zKos6K2Q-ssfa-qJAqjKKYw-sDMH4x1w__

**Comment by lynxzhang** [comment]
上面的账号这边登录失败，请确定下账号信息是否正确，也可以留下您的qq，我们会单独联系定位这个问题

**Comment by wangyutao** [comment]
可以了，因为生成的sign出现换行符导致的，过滤掉换行符就好了
