### ISSUE TITLE
ios ---最新版---有消息来了，但是列表不提示，如何解决

### ISSUE THREAD

**Issue by yuanxiaodong1** [tencentyun/TIMSDK#369]
集成包 tuikit 
当前现象 使用tuikit  有列表显示，但是只能在，再次登录的时候，列表才能显示未读消息和消息数量，
机型，iphone 6s  机型都不行
之前版本，没有用过
暂时没有日志

**Comment by Sakihata-Suzuha** [comment]
确认是否有注册会话监听，可参考此文档：
https://cloud.tencent.com/document/product/269/9229#.E4.BC.9A.E8.AF.9D.E5.88.B7.E6.96.B0.E7.9B.91.E5.90.AC

**Comment by yuanxiaodong1** [comment]
我直接展示的这个类#import "TUIConversationListController.h"//im列表  利用a类来展示b类的视图，还需要注册会话监听吗

**Comment by Sakihata-Suzuha** [comment]
需要刷新会话就要注册会话监听

**Comment by yuanxiaodong1** [comment]
那具体是哪一块？

**Comment by yuanxiaodong1** [comment]
你好，监听已经加了，但是还是没有消息，请问是什么原因，可以帮忙看一下吗

**Comment by yuanxiaodong1** [comment]
让我加监听加了但是还是没有用，我感觉问题不是出在这，我的逻辑是利用一个button点击可以跳转到消息的列表，用的都是腾讯云im提供的，参考的demo，就是button跳转过去了，然后收到新消息，列表上就看不到了，聊天对话框是可以的

**Comment by yuanxiaodong1** [comment]
是我的列表没有和demo那样有消息来的接着提示，那样，那样怎样实现

**Comment by yuanxiaodong1** [comment]
我里面的监听方法没有走，demo里的监听方法走了

**Comment by yuanxiaodong1** [comment]
解决了，监听的地方添加一个刷新就显示了

**Comment by yuanxiaodong1** [comment]
但是我返回的时候，列表还是不刷新，请问需要修改哪里？
