### ISSUE TITLE
【iOS】-【4.5.45】获取消息未读数有问题

### ISSUE THREAD

**Issue by MrRightC** [tencentyun/TIMSDK#373]
【iOS】-【4.5.45】：【收到消息后不做任何操作杀死App后重新打开，默认会读掉一条消息】
【集成包】：TUIKIT
【当前现象】：app打开的情况下，连续发两条消失，正常显示未读数为2，不做任何操作杀死app再次打开，未读消息数显示为1了，Demo的版本也是这样
【机型】：iOS设备
【之前版本有无此问题】：TUIKIT 4.4.716版本没有，现在升级到4.5.45，出现了此问题
【有无日志或者截图】：暂无日志

**Comment by Sakihata-Suzuha** [comment]
会话类型是 C2C 吗？

**Comment by MrRightC** [comment]
是C2C单聊模式

**Comment by Sakihata-Suzuha** [comment]
下个版本修复

**Comment by MrRightC** [comment]
@Sakihata-Suzuha 请问对于修改UI库中的代码，版本升级后就会被覆盖，除了把以前修改过的复制过来再改改，还有其他好的升级方法吗？能不能把TXIMSDK_iOS单独拿出来升级？

**Comment by lynxzhang** [comment]
可以单独升级 TXIMSDK_iOS 的，TXIMSDK_TUIKit_iOS 默认会依赖最新的 TXIMSDK_iOS，如果想自定义 TXIMSDK_iOS 版本，可以在 Podfile 里面配置 pod 'TXIMSDK_iOS' , '4.5.xx' 指定 TXIMSDK_iOS 版本

**Comment by MrRightC** [comment]
@lynxzhang 谢谢
