### ISSUE TITLE
【iOS】-【4.5.45】：可以在未登录的情况下查看本地缓存的用户及群组信息吗？

### ISSUE THREAD

**Issue by LearnGittt** [tencentyun/TIMSDK#374]
【集成包】：TIMSDK
【当前现象】：通过TIMManager的initStorage方法可以在未登录的情况下加载本地存储，获得本地的会话和消息，但是好像无法获得用户及群组的信息（试了TIMFriendshipManager的queryUserProfile方法及TIMGroupManager的queryGroupInfo方法都无法获得相应的用户及群组信息，但是查看SDK创建的SQLite数据库，里面其实是有刚才要查询的用户和群组信息的）。想问一下这个功能可以实现吗？
【之前版本有无此问题】：不确定

**Comment by lynxzhang** [comment]
您好，感谢您的反馈，这个问题我们排期解决下，预计下个版本优化
