### ISSUE TITLE
【iOS】-【4.5.45】：发送消息的接口安卓发送成功会把消息体返回回来，ios只返回一个成功失败状态，那没法在消息发送成功后马上写入消息时间等数据啊

### ISSUE THREAD

**Issue by Uawful** [tencentyun/TIMSDK#375]
发送消息的接口安卓发送成功会把消息体返回回来，ios只返回一个成功失败状态，那没法在消息发送成功后马上写入消息时间等数据啊

**Comment by lynxzhang** [comment]
您这边的需求是发送消息成功后，在成功回调里面修改消息时间戳？如果是这样的话，可以直接在回调里面操作发送的消息对象就可以了

**Comment by Uawful** [comment]
需要消息id
