### ISSUE TITLE
Windows 创建会话成功后，无法从会话列表获取到创建的会话

### ISSUE THREAD

**Issue by nightlight89** [tencentyun/TIMSDK#376]
【Windows】-【4.5.15】：【TIMConvCreate创建后无法从TIMConvGetConvList获取】
【集成包】：imsdk
【当前现象】：通过TIMConvCreate接口创建一个kTIMConv_C2C类型的会话，回调已经成功创建会话了但是通过获取会话列表TIMConvGetConvList这个接口，回调拿到的会话列表没有新创建的会话！
【之前版本有无此问题】：之前版本我通过创建一个草稿就能获取到了，但是更新到这个版本就无法获取到了

**Comment by cldz123** [comment]
嗯，收到。这是必现的？可以把日志发出来吗？

**Comment by cldz123** [comment]
你创建的这个会话并没有收发任何消息，所以暂时未放到最近会话列表里面。所以TIMConvGetConvList获取不到
