### ISSUE TITLE
【iOS】-【4.5.45最新版本  ：【iPhone6真机发送语音Toast提示无文件】

### ISSUE THREAD

**Issue by simpleLiYu** [tencentyun/TIMSDK#377]
【集成包】：TUIKIT
【当前现象】：1.控制器将TUIChatController作为子控制器加入后界面位置不正确
                          2.发送语音消息时Toast提示无文件
【机型】：问题1在iPhone6和iPhone7上都出现，问题2在iPhone7上没问题，iPhone6出现
【之前版本有无此问题】：未知，新项目才接入当前SDK
【有无日志或者截图】：
![IMG_0392](https://user-images.githubusercontent.com/20043672/65813619-6bf0bc00-e20a-11e9-96aa-e809b8edb4b4.PNG)
![IMG_0393](https://user-images.githubusercontent.com/20043672/65813622-727f3380-e20a-11e9-8f37-388d282bee35.PNG)
![image](https://user-images.githubusercontent.com/20043672/65813640-a5c1c280-e20a-11e9-9576-829134fa4346.png)

**Comment by lynxzhang** [comment]
看 log 提示，语音 size 为 0，这边语音可以录制长一点，在本地调试检查下文件是否存在

**Comment by simpleLiYu** [comment]
@lynxzhang 好像是因为我的id用的中文大鹏子导致的，用了数字之后发送正常。
这个界面显示的问题是什么原因导致的呢，目前用的swift语音，按照demo一样添加TUIChatController为子控制器的。swift语音加载SDK的bundle无效，要自己导入到项目才能使用。

**Comment by lynxzhang** [comment]
界面不对的问题，可以用有问题的手机跑下我们的 demo 看下显示是否正常，swift语音加载SDK的bundle无效的问题我们会在下个版本优化。

**Comment by simpleLiYu** [comment]
@lynxzhang demo显示正常，是不是swift按照demo的方式添加成子控制器有问题，你们能测试一下吗。界面没有消息或者好友列表没有好友这些表格能加emptypage优化么
