### ISSUE TITLE
windows sdk4.5.15 编译发现意外的文件尾

### ISSUE THREAD

**Issue by nightlight89** [tencentyun/TIMSDK#378]
![image](https://user-images.githubusercontent.com/16662984/65824561-c71fbe80-e29d-11e9-82de-f2813a9a7c34.png)
TIMCloud.h 编译的时候提示有意外的文件尾。我把上面图片中的/// @} 这样的行删除就能编译通过了，？？？

**Comment by cldz123** [comment]
感谢您的反馈。
由于 IM SDK 的头文件采用 UTF-8 编码格式，部分编译器按默认系统编码格式编译源文件，可能导致编译无法通过，设置此参数可指定编译器按照 UTF-8 的编码格式编译源文件。
在 【C/C++】>【命令行】>【其他选项】，输入/source-charset:.65001，如下图所示：

![](https://main.qcloudimg.com/raw/0c9ab7746d643594fa7cf20e93c60860.png)
