### ISSUE TITLE
【小程序】【BUG】配置好 _SDKAPPID 和 _SECRETKEY 点击登录出现错误码 70009 的情况, 请问如何解决???

### ISSUE THREAD

**Issue by guowenqing1** [tencentyun/TIMSDK#379]
<img width="756" alt="屏幕快照 2019-09-29 13 28 07" src="https://user-images.githubusercontent.com/45066320/65826792-7f109400-e2bd-11e9-8612-9967957162f2.png">
<img width="898" alt="屏幕快照 2019-09-29 13 33 37" src="https://user-images.githubusercontent.com/45066320/65826851-3b6a5a00-e2be-11e9-9609-f11af8b4dda1.png">
<img width="1277" alt="屏幕快照 2019-09-29 13 33 26" src="https://user-images.githubusercontent.com/45066320/65826860-5046ed80-e2be-11e9-94cb-5859dc135fec.png">

**Comment by SaxonGao-SZ** [comment]
请确认一下GenerateTestUserSig.js  文件的路径： TIMSDK/WXMini/dist/wx/debug/GenerateTestUserSig.js 
请注意，不是： TIMSDK/WXMini/static/utils/GenerateTestUserSig.js

**Comment by guowenqing1** [comment]
> 请确认一下GenerateTestUserSig.js文件的路径：TIMSDK / WXMini / dist / wx / debug / GenerateTestUserSig.js
> 请注意，不是：TIMSDK / WXMini / static / utils / GenerateTestUserSig.js

是 dist / wx / debug / GenerateTestUserSig.js 文件路径

**Comment by yangq1990** [comment]
> > 请确认一下GenerateTestUserSig.js文件的路径：TIMSDK / WXMini / dist / wx / debug / GenerateTestUserSig.js
> > 请注意，不是：TIMSDK / WXMini / static / utils / GenerateTestUserSig.js
> 
> 是 dist / wx / debug / GenerateTestUserSig.js 文件路径

请注意，新的加密算法用的是 秘钥，旧的加密算法用的是 公私钥，这是完全不同的，具体的区别请参考这篇文章：https://cloud.tencent.com/document/product/269/32688#GeneratingdynamicUserSig
