### ISSUE TITLE
cocoapod上是iOS4.4.9的版本,希望更新到最新到4.5版本

### ISSUE THREAD

**Issue by niuernihao** [tencentyun/TIMSDK#380]
希望把iOS的cocoapod上TXIMSDK_TUIKit_iOS的版本更新到最新,现在上面的版本比最新的要低两个版本,

**Comment by niuernihao** [comment]
cocoapod上 版本从4.3更新到4.4.9,后编译在TConversationListViewModel.h文件里面150行报错:Reference to 'TIM_SYSTEM' is ambiguous,

**Comment by lynxzhang** [comment]
试下：pod setup
pod repo update
rm ~/Library/Caches/CocoaPods/search_index.json

**Comment by lynxzhang** [comment]
pod 上都是最新的： 
-> TXIMSDK_TUIKit_iOS (4.5.45)
   TXIMSDK_TUIKit_iOS
   pod 'TXIMSDK_TUIKit_iOS', '~> 4.5.45'
   - Homepage: https://cloud.tencent.com/document/product/269/3794
   - Source:  
   https://imsdk-1252463788.cos.ap-guangzhou.myqcloud.com/4.5.45/TIM_SDK_TUIKIT_iOS_latest_framework.zip
   - Versions: 4.5.45, 4.5.15, 4.4.900, 4.4.716, 4.4.627, 4.4.479 [master repo]

**Comment by niuernihao** [comment]
> 试下：pod setup
> pod repo update
> rm ~/Library/Caches/CocoaPods/search_index.json

更新到了最新 4.545编译也是TConversationListViewModel文件里报同样的错,执行了上面三个步骤pod setup....后还是编译报错

**Comment by lynxzhang** [comment]
1，先试下我们的 Demo pod 安装是否正常。
2，用最新的版本编译报错的内容是什么，我这边测试时正常的，TXIMSDK_TUIKit_iOS 默认会依赖 TXIMSDK_iOS 的最新版本，检查下 TXIMSDK_iOS 的安装是否正常。

**Comment by niuernihao** [comment]
> 1，先试下我们的 Demo pod 安装是否正常。
> 2，用最新的版本编译报错的内容是什么，我这边测试时正常的，TXIMSDK_TUIKit_iOS 默认会依赖 TXIMSDK_iOS 的最新版本，检查下 TXIMSDK_iOS 的安装是否正常。

:新建了一个工程导入TXIMSDK_TUIKit_iOS最新的,编译也是报错这个, TXIMSDK_iOS也有在pods里面,这里不能发截图出来. 其中一个错在TConversationListViewModel.m文件里面62行if([conv getType] == TIM_SYSTEM)...    错误提示:Reference to 'TIM_SYSTEM' is ambiguous

**Comment by niuernihao** [comment]
> 1，先试下我们的 Demo pod 安装是否正常。
> 2，用最新的版本编译报错的内容是什么，我这边测试时正常的，TXIMSDK_TUIKit_iOS 默认会依赖 TXIMSDK_iOS 的最新版本，检查下 TXIMSDK_iOS 的安装是否正常。

<img width="672" alt="屏幕快照 2019-09-29 下午9 51 27" src="https://user-images.githubusercontent.com/17469303/65868035-1bb06000-e3aa-11e9-8e61-a533e906ddbf.png">
<img width="172" alt="屏幕快照 2019-09-29 下午9 41 32" src="https://user-images.githubusercontent.com/17469303/65868056-27038b80-e3aa-11e9-9322-b30961e7b458.png">

**Comment by niuernihao** [comment]
把里面的@import ImSDK 换成#import "ImSDK.h" 就编译过了..   你们这边测试没问题, 而我这里就需要替换下引入方式, 难道是因为xcode版本原因?
