### ISSUE TITLE
聊天界面 - 隐藏键盘后，气泡异常

### ISSUE THREAD

**Issue by fansonq** [tencentyun/TIMSDK#381]
打开聊天界面，自动会弹起键盘，隐藏键盘后出现这个情况

![无标题](https://user-images.githubusercontent.com/11573864/65829797-ba21c000-e2db-11e9-8456-4bbb9e24e74b.png)

**Comment by parkhuang** [comment]
能提供一下版本号吗，下次可以参考下面的模板提交issue，能更快地处理问题
https://github.com/tencentyun/TIMSDK/issues/176

**Comment by parkhuang** [comment]
下周版本解决
