### ISSUE TITLE
【android】 - 【4.4.479】：【发送图片时闪退】

### ISSUE THREAD

**Issue by zhoufanGithub** [tencentyun/TIMSDK#385]
【集成包】 没有集成官方的TUIKIT,而是自己引入SDK实现功能
【当前现象】 在发送图片的时候，在部分手机上面出现闪退现象
【机型】   HUAWEI STF-AL10
【截图】
  
![图片](https://user-images.githubusercontent.com/16395368/65847355-cf4a2d80-e373-11e9-8fdd-2e6fbab7ffc8.png)

**Comment by vinsonswang** [comment]
你好，这个是必现的吗？能否把logcat过滤改成“No Filters”，再发下对应崩溃的so部分的日志？
