### ISSUE TITLE
【web】-【最新版】：【发送图片失败】

### ISSUE THREAD

**Issue by d8533995** [tencentyun/TIMSDK#386]
【当前现象】：WEB发送图片消息失败。上传成功了，没有发送http请求，也没错误提示，将createImageMessage改成createFileMessage其他都不变，可以正常发送。
【集成包】：IMSDK
【机型】：chrome
【之前版本有无此问题】：有
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/35674915/65851996-61a7fc80-e387-11e9-8132-5ba8e8d2aa43.png)
![image](https://user-images.githubusercontent.com/35674915/65852416-a5e7cc80-e388-11e9-9ff1-349b9ee101bb.png)
![image](https://user-images.githubusercontent.com/35674915/65852380-8781d100-e388-11e9-9dc6-973ce7fc7b76.png)

**Comment by d8533995** [comment]
![image](https://user-images.githubusercontent.com/35674915/65857178-deda6e00-e395-11e9-8518-b6140a16f8aa.png)

**Comment by SaxonGao-SZ** [comment]
您好，请问一下使用的SDK 是哪个版本？

**Comment by d8533995** [comment]
> 您好，请问一下使用的SDK 是哪个版本？
我已经初步确认了，通过react创建的input标签，选择图片发送图片消息会失败，sdk是最新版本

**Comment by d8533995** [comment]
> 您好，请问一下使用的SDK 是哪个版本？

`    const tim = TIM.create({
      SDKAppID: window.genTestUserSig('').SDKAppID,
    });
    // 注册 cos
    tim.registerPlugin({ 'cos-js-sdk': COS });
    tim.login({
      userID: 'user0',
      userSig: window.genTestUserSig('user0').userSig,
    });
    function sendImage() {
    const message = tim.createImageMessage({
      to: 'user27',
      conversationType: 'C2C',
      payload: {
        file: document.getElementById('imagePicker') // 或者用event.target
      },
    })
    tim.sendMessage(message)
  }
ReactDOM.render(
	<input type='file' id='imagePicker' onChange={sendImage}/>,
	document.body
);`

**Comment by wangking873** [comment]
"tim-js-sdk": "^2.0.9",

**Comment by yangq1990** [comment]
感谢反馈，问题已定位到，我们尽快修复

**Comment by yangq1990** [comment]
问题已修复，请升级2.0.10版本

**Comment by yangq1990** [comment]
> "tim-js-sdk": "^2.0.9",

请升级到最新版本 2.0.11，已经修复了此问题，抱歉给您造成了不便

**Comment by zengxp0605** [comment]
该问题在最新的版本VERSION = "2.11.0" 中仍然存在, 在调用 `tim.createImageMessage` 之后调用 `tim.sendMessage` 报错,无法发送图片, 其他代码不变的情况下, 改用 `tim.createFileMessage`创建消息可以正常发送文件
【错误日志】
```
Error: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLInputElement'
    |     property '__reactFiber$qhlgf83ze1' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at n.value (tim-js.js:formatted:1)
    at tim-js.js:formatted:1
```
【代码】
```
  	const message = timInstanse.createImageMessage({
		to: rootState.tim.toAccount,
		conversationType: "GROUP",
		payload: {
			file: document.getElementById("imagePickerRef"), // 或者用event.target
		},
		onProgress: (percent) => {
			console.log("progress: ", percent); // 手动给message 实例加个响应式属性: progress
		},
	});
	console.log("message: ", message);
	timInstanse
		.sendMessage(message)
		.then(() => {})
		.catch((imError) => {
			console.error(imError);
		});
```

【React中简单重现类似的错误】
```
	useEffect(() => {
		setTimeout(() => {
			console.log(
				JSON.stringify({
					ele: document.getElementById("imagePickerRef"),
				})
			);
		}, 3000);
	}, []);
```

初步定位结果为 tim-js.js 中以下代码导致的异常，在`sendMessageInstance` 方法中使用了 `JSON.stringify(e)`， React中似乎无法将 ` document.getElementById("imagePickerRef")` 获取到的 DOM 元素JSON.stringify 。
```
 key: "sendMessageInstance",
          value: function(e, t) {
              var n, o = this, r = null;
              switch (e.conversationType) {
              case Sn.CONV_C2C:
                  if (!(r = this.getModule(_c)))
                      return this._onCannotFindModule();
                  break;
              case Sn.CONV_GROUP:
                  if (!(r = this.getModule(mc)))
                      return this._onCannotFindModule();
                  break;
              default:
                  return jf({
                      code: Ul.MESSAGE_SEND_INVALID_CONVERSATION_TYPE,
                      message: zl
                  })
              }
              var a = this.getModule(Cc)
                , s = this.getModule(mc);
              return a.upload(e).then((function() {
                  return s.guardForAVChatRoom(e).then((function() {
                      if (!e.isSendable())
                          return jf({
                              code: Ul.MESSAGE_FILE_URL_IS_EMPTY,
                              message: cp
                          });
                      o._addSendMessageTotalCount(e),
                      n = Date.now();
                      var a = function(e) {
                          var t = "utf-8";
                          $s && document && (t = document.charset.toLowerCase());
                          var n, o, r = 0;
                          if (o = e.length,
                          "utf-8" === t || "utf8" === t)
                              for (var a = 0; a < o; a++)
                                  (n = e.codePointAt(a)) <= 127 ? r += 1 : n <= 2047 ? r += 2 : n <= 65535 ? r += 3 : (r += 4,
                                  a++);
                          else if ("utf-16" === t || "utf16" === t)
                              for (var s = 0; s < o; s++)
                                  (n = e.codePointAt(s)) <= 65535 ? r += 2 : (r += 4,
                                  s++);
                          else
                              r = e.replace(/[^\x00-\xff]/g, "aa").length;
                          return r
                      }(JSON.stringify(e));
```

**Comment by yangq1990** [comment]
感谢反馈，这个问题我们在 v2.11.2 做了修复，端午节后发版解决。可以加入 
![image](https://user-images.githubusercontent.com/6194380/121671457-214bcc00-cae1-11eb-8e72-86fa05dd1b64.png)
huode 获得第一时间的通知
