### ISSUE TITLE
【H5】-【4.5.45】：【nodejs无法使用h5的sdk】

### ISSUE THREAD

**Issue by Jessppp** [tencentyun/TIMSDK#388]
【集成包】：H5
【当前现象】：我想把nodejs当做client端，启动的时候大量报windows相关的错误
【机型】：H5网页
【之前版本有无此问题】：有
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/16432902/65862973-e4d64c00-e3a1-11e9-9ad5-8d03caaeefd7.png)

**Comment by yangq1990** [comment]
你好，当前sdk只支持浏览器HTML5环境和微信小程序环境
