### ISSUE TITLE
【Android】-【未知】：【module集成方式如何查看版本号】

### ISSUE THREAD

**Issue by JokerQuan** [tencentyun/TIMSDK#389]
【集成包】：老项目中的集成包
【当前现象】：老版本集成的IMSDK，项目中有presentation、timchat、tlslabrary、ui四个module，如何查看sdk的版本号？
【机型】：所有
【之前版本有无此问题】：。
【有无日志或者截图】：
![2VVKC(}B }UUUD9P)(E}KPU](https://user-images.githubusercontent.com/16643755/66361878-17400480-e9b3-11e9-92d8-c2883bf2ae16.png)

**Comment by vinsonswang** [comment]
在TIMManager里有个getVersion接口可以看
不过2.x和3.x的版本已经不维护了，建议升级到4.x的最新版本
