### ISSUE TITLE
腾讯IM无法关闭会话

### ISSUE THREAD

**Issue by Fuge2008** [tencentyun/TIMSDK#391]
腾讯IM版本4.3.81的jar包中的TIMManager.getInstance().deleteConversation(TIMConversationType.C2C, "hello");      找不到，什么原因?是取消了吗，但是文档上面还写有

**Comment by vinsonswang** [comment]
旧版本这个接口是在TIMManagerExt中的，新版本把TIMManagerExt这个类废弃了，接口全部挪到了TIMManager中，建议换新版本
