### ISSUE TITLE
【Android】腾讯云通信聊天消息，图片，语音在本地缓存没有找到

### ISSUE THREAD

**Issue by baohexin** [tencentyun/TIMSDK#392]

**Comment by vinsonswang** [comment]
TUIKit在初始化init时可以设置缓存的文件夹路径，如果不设置默认会保存在data/data/应用 下，可以参考TUIKit源码中的TUIKitConstants类，其中APP_DIR为缓存的根目录。
如果没有使用TUIKit，那么从文件消息下载文件时就需要app上层来设置路径。
