### ISSUE TITLE
TIMManager.getInstance().getConversation(TIMConversationType.C2C, Id).deleteLocalMessage

### ISSUE THREAD

**Issue by xusigh** [tencentyun/TIMSDK#393]
【Android】-【4.4.900】：【删除消息】
【集成包】：TUIKIT
【当前现象】TIMManager.getInstance().getConversation(TIMConversationType.C2C, Id).deleteLocalMessage
删除消息，没有删除自己发送的，只删除了“Id”发送的
【机型】：华为magic2

**Comment by vinsonswang** [comment]
你好，我们这边测试最新版本，自己发送的消息也是可以删除的，可以更新下再测试下看
