### ISSUE TITLE
最新版 消息列表不显示群名和单个聊天对象的名称

### ISSUE THREAD

**Issue by xusigh** [tencentyun/TIMSDK#394]
【Android】-【4.5.45】：【消息列表】
【集成包】：TUIKIT
【当前现象】：消息列表没有的聊天对象（对当前账号来说可能是第一次发送消息（群可能有历史消息记录，但是在消息页面删除聊天了））。进入通讯录选择一个群或者人 然后发送消息，然后返回消息页面，不显示群名或者单个聊天对象的名称
【机型】：小米4移动3G

**Comment by parkhuang** [comment]
会在下周的版本修复
