### ISSUE TITLE
【Windows IMSDK】-【4.5.45】：【windows XP 环境无法使用 跨平台版IMSDK】

### ISSUE THREAD

**Issue by clean2016** [tencentyun/TIMSDK#396]
【Windows】-【4.5.45】：【windows XP 环境无法使用跨平台版 IMSDK】
【当前现象】：win7及win10下正常使用，winXP环境无法使用IMSDK
【有无日志或者截图】：有截图附上问题截图
![TIM截图20191011114144](https://user-images.githubusercontent.com/23182324/66627929-cbe65a00-ec2f-11e9-9e2d-a742fcfcf636.png)

**Comment by 6e6e6e** [comment]
在IMSDK v4版本未做XP支持。Microsoft官方已经在2014年停止对Windows XP的支持，建议用户按照Microsoft的建议更新电脑系统：https://support.microsoft.com/zh-cn/help/14223/windows-xp-end-of-support

**Comment by Samoongeer** [comment]
请问是否可以也提供支持xp的动态库呢？
Windows下的客户端程序还是能多支持一些平台最好吧？

**Comment by Samoongeer** [comment]
我现在这个项目，自己的其他代码都可以在xp下跑，就这个动态库难受
