### ISSUE TITLE
【android】-【IMSDK4.5.55】:【crash】

### ISSUE THREAD

**Issue by kingrukawa** [tencentyun/TIMSDK#397]
-【Android】-【4.5.55】：【crash】

-【集成包】：IMSDK
-【当前现象】：集成发布后本地机型有限未发现崩溃现象，在google后台发现crash日志，上报比较多，大部分机型是samsung，os version 以android8、9为主，第二张图片不太确定是否是im的，也贴出来帮忙看下
-【机型】：sansumg、etc
-【之前版本有无此问题】：有
-【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/5400325/66696364-061e2d00-ecfe-11e9-946d-a6ba2b0c87c8.png)
![image](https://user-images.githubusercontent.com/5400325/66696414-6c0ab480-ecfe-11e9-91f4-3e5d8fc0fd7a.png)

**Comment by cldz123** [comment]
这个crash不是4.5.55的，崩溃偏移对不上

**Comment by cldz123** [comment]
感谢您的反馈，麻烦帮忙确认下crash的版本号

**Comment by kingrukawa** [comment]
1084的app版本是imsdk的4.5.45版本
1085的app对应的imsdk是4.5.55
都有native的crash问题
![image](https://user-images.githubusercontent.com/5400325/66728496-e579e280-ee77-11e9-897e-26808cc2ca44.png)
![image](https://user-images.githubusercontent.com/5400325/66728571-5a4d1c80-ee78-11e9-98ad-206f76cf2db0.png)
我们是海外英语，打包方式是bundle，以上反应的是google的报告给出的比较多的crash

**Comment by cldz123** [comment]
您好，你们用的是跨平台-Android的库吧？纯C接口的库？

**Comment by kingrukawa** [comment]
我们是从
https://github.com/tencentyun/TIMSDK/tree/master/Android/SDK
下载的sdk

**Comment by cldz123** [comment]
经过分析1085 用的IMSDK应该是 4.5.45 的 arm64-va
崩溃原因应该是本地引用表满了。
这个问题已经修复，修复代码已合入下一个发布版本。

**Comment by cldz123** [comment]
1084 那个崩溃 找不到的ImSDK版本，可以吧打包到apk的imsdk的so发来看下吗？

**Comment by kingrukawa** [comment]
https://rescdn.kktv9.com/libo/4.5.45so.zip

**Comment by cldz123** [comment]
堆栈上显示 0x15eea3 函数式 WriteLog。
![image](https://user-images.githubusercontent.com/37802395/66734767-f7b74900-ee96-11e9-868d-5879d6649444.png)

但是提供的so 0x15eea3 根本不是 WriteLog函数
![企业微信截图_15710379111553](https://user-images.githubusercontent.com/37802395/66734750-d7878a00-ee96-11e9-8d4c-25af43771dd6.png)

**Comment by cldz123** [comment]
1804 这个版本的apk方便发下吗？

**Comment by kingrukawa** [comment]
https://rescdn.kktv9.com/libo/1084.aab
抱歉有事情耽误了时间
