### ISSUE TITLE
【iOS】-【4.5.55】：【删除本地会话后还会出现】 issue内容：

### ISSUE THREAD

**Issue by deanli08** [tencentyun/TIMSDK#402]
您好，调用删除本地会话和记录后，在次进去有出现删除的消息了。应该是从服务端拉取的，这个有没有好的解决方案。期望：删除会话后，再次进去会话获取历史消息应该是空的。

**Comment by lynxzhang** [comment]
您好，这块的逻辑我们正在优化，敬请期待！

**Comment by parkhuang** [comment]
即将发布的5.x会在删除会话的同时把会话的消息也从云端删除
