### ISSUE TITLE
【跨平台内核】-【4.3.118】：【咨询 获取指定会话的消息列表接口 使用问题】

### ISSUE THREAD

**Issue by fisher21052899** [tencentyun/TIMSDK#404]
【集成包】：IMSDK
【当前现象】：
1）https://cloud.tencent.com/document/product/269/33549#timmsggetmsglist这个接口里,参数msg_getmsglist_param_last_msg的具体格式是什么啊？
2）我试着调用这个接口，使用的是同样的参数，访问的同一个群组，为什么有些时候获取不到任何数据呢？
参数json_get_msg_param:
{
  "msg_getmsglist_param_count": 15,
  "msg_getmsglist_param_is_forward": false,
  "msg_getmsglist_param_is_remble": true,
  "msg_getmsglist_param_last_msg": {}
}

【机型】：WPF客户端
【之前版本有无此问题】：不清楚
【有无日志或者截图】：
2019-10-12 14:38:24,746 线程ID:[7] DEBUG - 描述：Common.IMSDK.TIMMsgGetMsgList ret=0
2019-10-12 14:38:25,236 线程ID:[1] DEBUG - 描述：OnTIMMsgGetMsgListCallback code=0 desc= json_params=[]

**Comment by cldz123** [comment]
感谢您的反馈，有日志可以提供一下吗？

**Comment by fisher21052899** [comment]
您能先告诉我一下 msg_getmsglist_param_last_msg的具体格式吗？
