### ISSUE TITLE
【IOS】【需求】: 自定义推送消息 结构体 

### ISSUE THREAD

**Issue by deanli08** [tencentyun/TIMSDK#405]
目前离线返回的就是固定的 昵称：消息，这样的话很难做到 ，收到推送消息后，点击进入程序可以直接进去相应的聊天界面。

**Comment by lynxzhang** [comment]
您好，可以使用 msg -> TIMOfflinePushInfo -> ext 字段自定义跳转信息，程序启动后根据这个自定义跳转信息跳转到对应的界面。
