### ISSUE TITLE
 webim.js在哪呢？？？？官方Demo你用mpvue???那咋不把ide选为vscode算了

### ISSUE THREAD

**Issue by xie765257710** [tencentyun/TIMSDK#407]
沙雕腾讯

**Comment by yangq1990** [comment]
旧版1.7.x的存档目录  https://github.com/tencentyun/TIMSDK/tree/master/H5/v1.7.x

用mpvue做demo，我们只是提供了一个方案可以快速地实现，您也可以用原生或者其它框架写，都可以，任君选择。

github是个技术社区，就事论事，全世界都能看到您的言论，别给中国人丢脸哈

**Comment by xie765257710** [comment]
对不起，是我鲁莽了。就事论事，难道不应该去丰富细化文档，还在这拿 渺小的个人 给国家丢脸说事 来掩盖我陈述的事实 嗯？
