### ISSUE TITLE
【iOS】-【4.4.900】：【运行时偶发性崩溃】

### ISSUE THREAD

**Issue by damizhou** [tencentyun/TIMSDK#408]
【集成包】：IMSDK
【当前现象】：IM偶发性崩溃。断点定位在堆栈中；奔溃文件符号表解析都无法定位到具体具体代码行。
【机型】：所有iPhone机型
【之前版本有无此问题】：之前版本也出现该问题。
【有无日志或者截图】：两次崩溃的日志信息
<img width="1148" alt="WeChat79d1ce0dd7db5bafff13319c36c63579" src="https://user-images.githubusercontent.com/11433598/66901478-616b5a80-f031-11e9-9334-d7d9a31e0f16.png">
<img width="1157" alt="WeChat4752e5ed8363a9046491ec5c2f3c00f1" src="https://user-images.githubusercontent.com/11433598/66901479-616b5a80-f031-11e9-8a4b-a7868c559829.png">
<img width="1167" alt="WeChatc353ab16efe7029ba81e31c087dba3e0" src="https://user-images.githubusercontent.com/11433598/66901482-6203f100-f031-11e9-8741-615ec618c579.png">
![WechatIMG10](https://user-images.githubusercontent.com/11433598/66901486-629c8780-f031-11e9-8936-932827ca2304.jpeg)
![WechatIMG11](https://user-images.githubusercontent.com/11433598/66901489-63351e00-f031-11e9-91ed-a8dbab056801.jpeg)
![WechatIMG12](https://user-images.githubusercontent.com/11433598/66901490-63351e00-f031-11e9-8efe-88263b5def12.jpeg)
![WechatIMG13](https://user-images.githubusercontent.com/11433598/66901492-63351e00-f031-11e9-9e92-4663fe2c84fe.jpeg)

**Comment by parkhuang** [comment]
感谢反馈，已经修复，请使用4.5.55及以上版本验证
