### ISSUE TITLE
【iOS】【Android】【IMSDK4.5.55】后台使用RestAPI发送群组消息,某些群组用户偶尔收不到自己发的消息.

### ISSUE THREAD

**Issue by hLinkin** [tencentyun/TIMSDK#409]
【当前现象】：群组用户发消息,通过后端使用RestAPI发送群组消息，自己收不到的情况
【集成包】：IMSDK
【版本】:  安卓- 4.5.15~4.5.111, IOS - 4.5.15~4.5.111
【有无日志或者描述、截图】：
偶尔不定时某些群组,出现自己发送的消息自己没回调(自己看不到消息),群组内其它成功可以显示.
1.群组用户发消息,通过后端使用RestAPI发送群组消息,后端调用API显示成功.
App没有自己群组消息的回调.群组内的其它成功可以收到回调信息.
2.通过即时通讯后台控制台发送该群组消息,是有消息回调的!

**Comment by parkhuang** [comment]
感谢反馈，场景是这样的吗：是A、B、C建群X
A用Rest API往群X发消息，A却没有偶尔没收到，是吗

**Comment by hLinkin** [comment]
是的,A建群X, B,C加入群.
A发消息通过后端,Rest API往群X发消息,A没收到,BC能收到.
-经排查A用户在线,并且实际在X群组里.
-A的客户端消息回调应该是正常的.通过腾讯控制台群组那里发送消息,回调有触发收到消息.
