### ISSUE TITLE
【H5】-【4.5.45】：【图片发送，不希望通过document组件点击上传，想直接通过本地路径传一个图片，需要构造怎样的对象？】

### ISSUE THREAD

**Issue by Jessppp** [tencentyun/TIMSDK#410]
【集成包】：H5
【当前现象】：图片发送，不希望通过document组件点击上传，想直接通过本地路径传一个图片，需要构造怎样的对象？
【机型】：H5网页
【之前版本有无此问题】：有
【有无日志或者截图】：无

**Comment by Jessppp** [comment]
document.getElementById('imagePicker')对应的我想构造一个对象，是怎样的格式？

**Comment by yangq1990** [comment]
你好，这个问题调试下即可知

**Comment by Jessppp** [comment]
> 你好，这个问题调试下即可知

就是因为调试过了不行才来这边提问

**Comment by StevenRoger** [comment]
> > 你好，这个问题调试下即可知
> 
> 就是因为调试过了不行才来这边提问

对这个官方回复也是很无语。你怎么解决这个问题的呀？
