### ISSUE TITLE
Android 自定义布局 复用布局错乱

### ISSUE THREAD

**Issue by beibeiandroid** [tencentyun/TIMSDK#411]
问题：自定义布局的 addMessageItemView  addMessageContentView 两种类型的数据  滑动复用  会出现错乱 

复现步骤：官方demo 设置自定义    
        inputLayout.replaceMoreInput(new CustomInputFragment().setChatLayout(layout));
     

        自定义如下代码：

    /**
     * 自定义消息的bean实体，用来与json的相互转化
     */
    public static class CustomMessageData {
        int type;
        int version = 1;
        String text = "欢迎加入云通信IM大家庭！";
        String link = "https://cloud.tencent.com/document/product/269/3794";
    }

  public static class CustomMessageDraw implements IOnCustomMessageDrawListener {

        /**
         * 自定义消息渲染时，会调用该方法，本方法实现了自定义消息的创建，以及交互逻辑
         * @param parent 自定义消息显示的父View，需要把创建的自定义消息view添加到parent里
         * @param info 消息的具体信息
         */
        @Override
        public void onDraw(ICustomMessageViewGroup parent, MessageInfo info) {
            // 获取到自定义消息的json数据
            TIMCustomElem elem = (TIMCustomElem) info.getTIMMessage().getElement(0);
            // 自定义的json数据，需要解析成bean实例
            CustomMessageData data = null;
            try {
                data = new Gson().fromJson(new String(elem.getData()), CustomMessageData.class);
            } catch (Exception e) {
                DemoLog.e(TAG, "invalid json: " + new String(elem.getData()));
            }
            if (data == null) {
                DemoLog.e(TAG, "No Custom Data: " + new String(elem.getData()));
            }

           View view =null;
            if(data.type==0)
            {
              // 把自定义消息view添加到TUIKit内部的父容器里
               view = LayoutInflater.from(DemoApplication.instance()).inflate(R.layout.test_custom_message_layout1, null, false);
              parent.addMessageContentView(view);
            }else{
              // 把自定义消息view添加到TUIKit内部的父容器里
              view = LayoutInflater.from(DemoApplication.instance()).inflate(R.layout.test_custom_message_layout2, null, false);
              parent.addMessageItemView(view);
            }

            // 自定义消息view的实现，这里仅仅展示文本信息，并且实现超链接跳转
            TextView textView = view.findViewById(R.id.test_custom_message_tv);
            final String text = "不支持的自定义消息：" + new String(elem.getData());
            if (data == null) {
                textView.setText(text);
            } else {
                textView.setText(data.text);
            }
            final CustomMessageData customMessageData = data;
            view.setClickable(true);
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (customMessageData == null) {
                        DemoLog.e(TAG, "Do what?");
                        ToastUtil.toastShortMessage(text);
                        return;
                    }
                    Intent intent = new Intent();
                    intent.setAction("android.intent.action.VIEW");
                    Uri content_url = Uri.parse(customMessageData.link);
                    intent.setData(content_url);
                    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

                    DemoApplication.instance().startActivity(intent);
                }
            });
        }
    }

**Comment by parkhuang** [comment]
能贴图看一下错乱的现象吗

**Comment by beibeiandroid** [comment]
https://wt-android-repos.oss-cn-beijing.aliyuncs.com/dev/c2f985fa8fad50e0800114df833a0d82.mp4

**Comment by beibeiandroid** [comment]
> 能贴图看一下错错的现象吗

https://wt-android-repos.oss-cn-beijing.aliyuncs.com/dev/c2f985fa8fad50e0800114df833a0d82.mp4

**Comment by parkhuang** [comment]
是加载外部自定义view的方式有问题，刚才修改了，下一个版本预计在11月上旬发布
