### ISSUE TITLE
【iOS】-【4.5.111】：【群组解散后，获取历史消息失败】

### ISSUE THREAD

**Issue by wbinWang** [tencentyun/TIMSDK#412]
【集成包】：TXIMSDK_iOS
【当前现象】：当群组内有未读消息时，结算群组，再此通过TIMConversation.getMessage:(int)count last:(TIMMessage*)last succ:(TIMGetMsgSucc)succ fail:(TIMFail)fail接口获取历史消息时，提示：Optional(10010) this group does not exist
【机型】：iphone
【之前版本有无此问题】：TUIKIT 4.5.111版本之前没有，4.5.111有
【有无日志或者截图】：

**Comment by parkhuang** [comment]
感谢反馈，我们排查一下

**Comment by parkhuang** [comment]
您好，现在的版本返回的是正确的逻辑。
