### ISSUE TITLE
【web】-【gitHub version to 2.0.9】：【AVChatRoom接受不到消息监听】

### ISSUE THREAD

**Issue by wyh931221** [tencentyun/TIMSDK#416]
【当前现象】：如聊天界面点击xxx不显示xxx
【集成包】：IMSDK
【机型】：web 谷歌浏览器
【有无日志或者描述、截图】：日志提示[ECONNABORTED]; message: timeout of 6000ms exceeded
![image](https://user-images.githubusercontent.com/42996802/67003953-c1d1c900-f111-11e9-86a0-996acf98a53f.png)

**Comment by yangq1990** [comment]
请问有无更详细的日志？或者升级到 [2.1.1版本](https://cloud.tencent.com/document/product/269/38492) 试试
