### ISSUE TITLE
使用uniapp调用微信端sdk发送语音消息不成功

### ISSUE THREAD

**Issue by jixuan0748qwer** [tencentyun/TIMSDK#418]
正常操作流程。录音结束返回的数据格式分别是 音频地址，音频时间，音频大小。但是在调用createAudioMessage()创建消息然后发送返回的接口走的catch，提示内容“消息元素为空，无法发送”。
在观察createAudioMessage创建之后的数据其中的status状态为fail.
希望官方人员帮忙尽快核实并解决该问题

**Comment by yangq1990** [comment]
感谢反馈，请升级使用2.1.1版本，抱歉给您带来了不便
