### ISSUE TITLE
【小程序】-【tim-wx.js 2.1.1版本】：【AVChatRoom接收不到群系统通知消息】

### ISSUE THREAD

**Issue by newZhaoZilong** [tencentyun/TIMSDK#421]
小程序最新的sdk, 2.1.1,   tim-wx.js接收不到群系统通知消息,查看network发现其实是已经获取到消息了,但是解析错误

是通过服务器API,以管理员的身份,
https://console.tim.qq.com/v4/group_open_http_svc/send_group_system_notification?sdkappid=88888888&identifier=admin&usersig=xxx&random=99999999&contenttype=json
通过这个接口向聊天室发送群系统通知消息的, 群组的类型是TIM.TYPES.GRP_AVCHATROOM,就是音视频聊天室类型,

**消息其实是接收到了,但是解析错误,导致无法获取消息,这个bug已经有很长时间没解决了**

![avatar](https://wxsource.changingstudy.com/timerror2.png)

**Comment by newZhaoZilong** [comment]
发送群系统通知消息的地址:   https://cloud.tencent.com/document/product/269/1630

**Comment by yangq1990** [comment]
感谢反馈，这个问题会在近期的版本修复

**Comment by yangq1990** [comment]
已修复，请升级 2.1.2 版本，感谢理解和支持。
