### ISSUE TITLE
【小程序】【2.1.1】ready函数Bug

### ISSUE THREAD

**Issue by wuliaopage** [tencentyun/TIMSDK#422]
![image](https://user-images.githubusercontent.com/53993715/67148706-52d3ac00-f29a-11e9-9ef3-f3384880c918.png)
登录过程中tim.ready函数会报错，复现方式官方小程序demo
2.0.6 tim.ready 没问题
2.1.1 tim.ready 会提示上图错误

**Comment by yangq1990** [comment]
您好，请通过监听事件 [TIM.EVENT.SDK_READY](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/module-EVENT.html#.SDK_READY) 代替直接使用ready函数，后者已经被废弃了，不好意思给您带来了不便
