### ISSUE TITLE
【小程序(原生)】-【1.0.7】：【拉去历史消息无效果】

### ISSUE THREAD

**Issue by apppws** [tencentyun/TIMSDK#423]
【集成包】：IM Web SDK
【机型】：微信小程序
【有无日志或者描述、截图】：
我写的 在 用户登陆之后   我就获取历史消息  
 // 获取消息
  getMessageList() {
    var that = this
    var conversationID = TIM.TYPES.CONV_C2C + that.data.identifier 
    // that.data.identifier 是自己的userID
    console.log('获取消息', conversationID)
    let promise = tim.getMessageList({ conversationID: conversationID, count: 15 });
    console.log(promise)
    promise.then(function (imResponse) {
      const messageList = imResponse.data.messageList; // 消息列表。
      const nextReqMessageID = imResponse.data.nextReqMessageID; // 用于续拉，分页续拉时需传入该字段。
      const isCompleted = imResponse.data.isCompleted; // 表示是否已经拉完所有消息。
      console.log(messageList, nextReqMessageID, isCompleted)
    });
  },

我得到的 promise 是 空    我不知道哪一步写错了

**Comment by yangq1990** [comment]
你好，请升级使用最新的 2.1.1 版本试下。我们没有release过1.0.7版本
