### ISSUE TITLE
H5 好多问题！

### ISSUE THREAD

**Issue by peidundun** [tencentyun/TIMSDK#424]
- 说是云通讯SDK，结果是一个Demo.
- 按文档说明找不到对应的文件。（推测是SdK升级后文档没更新，差不多确定sdk文件是tim-js.js）
 ![微信截图_20191021140634](https://user-images.githubusercontent.com/51263995/67180373-07d9a600-f40c-11e9-9e93-40e865fa75c7.png)
- App平台的消息可包含多个Element，H5平台的不包含，文档里提也不提！测试发现当通过App发送的消息包含多个Element时，H5收到的只包含第一个Element，其它的呢？
- 很多消息收不到，比如用户发的群通知消息以及系统发的群通知消息（尤其时解散群的通知消息）。
- 未提供没加密的脚本文件，给集成工作带来一定困难。
- SdK存在报错情况（当通过Rest api解算群时H5端报错）。
 ![微信截图_20191021141805](https://user-images.githubusercontent.com/51263995/67180922-9ef32d80-f40d-11e9-9513-186748f4c064.png)
- tim-js.js文件名不含版本信息，文件顶部也没有版本信息，通过程序运行时的日志才能确定sdk的版本！

**Comment by wuliaopage** [comment]
H5 SDK  https://www.npmjs.com/package/tim-js-sdk
WX SDK https://www.npmjs.com/package/tim-wx-sdk
文档 https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html

**Comment by yangq1990** [comment]
> H5 SDK https://www.npmjs.com/package/tim-js-sdk
> WX SDK https://www.npmjs.com/package/tim-wx-sdk
> 文档 https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html
> 各个语言版本的User-Sig生成文件： https://github.com/tencentyun?utf8=%E2%9C%93&q=sig&type=&language=
> 版本信息都在npm里，package.json也有

感谢，我再补充下：
SDK手册：https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/TIM.html
在线demo: https://webim-1252463788.file.myqcloud.com/demo/index.html
github demo: https://github.com/tencentyun/TIMSDK/tree/master/H5

**Comment by peidundun** [comment]
请正视本人提出的问题，不要敷衍了事！
