### ISSUE TITLE
【web】-【1.7.3】：【获取历史消息，文件消息得不到downUrl，导致下载功能不可用】

### ISSUE THREAD

**Issue by lenosp** [tencentyun/TIMSDK#426]
【当前现象】：获取单聊消息，包含文件消息时，获取对象如下：
![image](https://user-images.githubusercontent.com/18375648/67257145-35325c80-f4bd-11e9-86c7-c4c3d1fc08c7.png)
缺少downUrl这个属性，正常是这样的：
![image](https://user-images.githubusercontent.com/18375648/67257198-7460ad80-f4bd-11e9-904c-c8dfa2ce6636.png)
包含文件下载链接。这个问题偶现，很大概率出现，上海联通请求的。
【集成包】：IMSDK
【机型】：chrome
【之前版本有无此问题】：一周前无此问题，一直使用1.7.3，我认为是服务端有bug。至于偶现，我猜测，可能是你们服务器个别节点有bug，负载均衡导致偶现。
【有无日志或者截图】：demo1.7.x 复现问题截图：
![image](https://user-images.githubusercontent.com/18375648/67257323-036dc580-f4be-11e9-89b4-823c191bb80c.png)

**Comment by lenosp** [comment]
根本原因是 file请求url会判断下，走了这个方法：getFileDownUrlV2，但是这个方法请求失败了：
![image](https://user-images.githubusercontent.com/18375648/67271727-b6a1e300-f4ed-11e9-8d50-702f384f1dd2.png)
导致其抛出，没有downUrl这个属性

**Comment by yangq1990** [comment]
此问题可以通过 getFileDownUrl 解决。工单和github issue都关闭
