### ISSUE TITLE
TUIKit重新设置聊天消息适配器问题

### ISSUE THREAD

**Issue by xukairong** [tencentyun/TIMSDK#427]
![image](https://user-images.githubusercontent.com/18733186/67257334-16809580-f4be-11e9-8c68-4bcc246556b7.png)

写了一个适配器继承MessageListAdapter，消息不显示，再次加载消息，加载成功也不显示

版本4.5.111，想要去掉消息已读未读的标识，没有找到，所以继承MessageListAdapter给MessageLayout重新设置适配器，设置后消息显示不出来

**Comment by xukairong** [comment]
版本4.5.111，想要去掉消息已读未读的标识，没有找到，所以继承MessageListAdapter给MessageLayout重新设置适配器，设置后消息显示不出来

**Comment by parkhuang** [comment]
感谢反馈，已经准备增加隐藏已读标签的接口，预计在11月上旬发布
