### ISSUE TITLE
【H5】 【2.1.1】发送视频文件的消息 在IOS 浏览器无法播放

### ISSUE THREAD

**Issue by jason-answer** [tencentyun/TIMSDK#429]
issue内容：

【当前现象】：原生端发送视频格式消息
【集成包】：IMSDK
【机型】：如iPhone 7 Plus
【之前版本有无此问题】：2.1.1 一直存在
【有无日志或者描述、截图】：发送视频文件的消息 在IOS 浏览器无法播放，视频地址不支持播放

**Comment by yangq1990** [comment]
请升级 ios TUIKit 至最新的 [4.5.111 @2019.10.16](https://cloud.tencent.com/document/product/269/1606)
