### ISSUE TITLE
TUIKit的podspec里面为啥加了Assets.car，好像导致了项目里的资源加载不出来了，请尽快检查一下

### ISSUE THREAD

**Issue by Bruce-pac** [tencentyun/TIMSDK#43]
spec.resource = ['iOS/TUIKit.framework/TUIKitFace.bundle','iOS/TUIKit.framework/TUIKitResource.bundle','iOS/TUIKit.framework/emoji.plist','iOS/TUIKit.framework/Assets.car']

**Comment by Bruce-pac** [comment]
我试过了，把'iOS/TUIKit.framework/Assets.car'去掉，就没问题了，请尽快改一下。说实话，我没见过有第三方有这么写过

**Comment by lynxzhang** [comment]
已更新
