### ISSUE TITLE
【Android】-【tuikit4.5.15】：【会话列表页面设置用户头像设置圆角，但是实现显示会有长方形的用户头像】

### ISSUE THREAD

**Issue by yiyudemei** [tencentyun/TIMSDK#430]
【Android】-【4.5.15】：【绘画列表页面用户头像显示不正确】
【集成包】：com.tencent.imsdk:tuikit:4.5.15
【当前现象】：Android Studio集成新版本TUIKit，会话列表设置用户头像圆角listLayout.enableItemRoundIcon(true);实际显示有圆角有长方形的
【机型】：如华为Mate 20
【有无日志或者截图】：暂无日志，有截图附上问题截图
![123](https://user-images.githubusercontent.com/4611005/67263456-c49a3880-f4da-11e9-877b-025a6d2c6566.png)

**Comment by parkhuang** [comment]
感谢反馈，我来验证一下长方形头像的显示

**Comment by huangcv** [comment]
同样也遇到这个问题了

**Comment by githubLittleCode** [comment]
iOS也是这个问题，设置TUIKitConfig的avatarType为TAvatarTypeRounded，但是头像是一个长方形的图片时，显示的是一个椭圆的图片

**Comment by yiyudemei** [comment]
请问这个问题什么时候可以解决

**Comment by xcoderliu** [comment]
> iOS也是这个问题，设置TUIKitConfig的avatarType为TAvatarTypeRounded，但是头像是一个长方形的图片时，显示的是一个椭圆的图片

我看了下大概知道是什么问题，请问您能接受图片居中裁剪适配么?

**Comment by githubLittleCode** [comment]
> > iOS也是这个问题，设置TUIKitConfig的avatarType为TAvatarTypeRounded，但是头像是一个长方形的图片时，显示的是一个椭圆的图片
> 
> 我看了下大概知道是什么问题，请问您能接受图片居中裁剪适配么?

你好，已经修改，在TUIMessageCell里面把显示头像的imageView的contentMode设置为aspectFill即可
