### ISSUE TITLE
web端发送图片提示跨域

### ISSUE THREAD

**Issue by StevenRoger** [tencentyun/TIMSDK#431]
【Web】-【1.7.x】：【web端发送图片提示跨域】
【集成包】：webim.js
【当前现象】：在uni-app中集成webIM SDK，调用上传文件接口时，提示跨域。可以发送文本消息。
【机型】：Windows 10
【之前版本有无此问题】：
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/15900201/67363826-c0385300-f5a0-11e9-882f-8583f0d9e4af.png)

**Comment by yangq1990** [comment]
接入侧环境问题，建议换成域名后再试试
