### ISSUE TITLE
小程序历史消息

### ISSUE THREAD

**Issue by apppws** [tencentyun/TIMSDK#433]
issue标题：

【平台】-【2.1.1】：【小程序我获取消息的时候 只能获取到对方给自己发的  自己发的记录不存在】
issue内容：

【当前现象】：只显示对方的消息  自己的消息 历史找不到
代码是 ： （selToID是对方好友的ID ）
 // 收到新消息
    tim.on(TIM.EVENT.MESSAGE_RECEIVED, this.onMessageEvent ,this)
  // 消息事件
  onMessageEvent(event) {
    console.log(event)
    var that = this
    let messageList = event.data
    const atTextMessageList = messageList.filter(
      message =>
        message.type === 'TIMTextElem' &&
        message.payload.text.includes('@')
    )
    for (let i = 0; i < atTextMessageList.length; i++) {
      const message = atTextMessageList[i]
      const matched = message.payload.text.match(/@\w+/g)
      if (!matched) {
        continue
      }
    }
    if (event.name === 'onMessageReceived') {
      let id = TIM.TYPES.CONV_C2C + that.data.selToID
      if (!id) {
        return
      }
      let list = []
      event.data.forEach(item => {
        if (item.conversationID === id) {
          list.push(item)
        }
      })
      console.log('消息事件',list)
      // 收到消息
      this.receiveMessage(list)
    }
  },
  // 收到消息
  receiveMessage(messageList) {
    var that = this
    let list = [...messageList]
    for (let i = 0; i < list.length; i++) {
      let item = list[i]
      list[i].virtualDom = that.decodeElement(item.elements[0])
      list[i].newtime = that.getLocalTime(list[i].time)
    }
    that.data.currentMessageList = [...that.data.currentMessageList, ...list]
    that.setData({
      currentMessageList: that.data.currentMessageList
    })
    setTimeout(() => {
      wx.pageScrollTo({
        scrollTop: 99999
      })
    }, 800)
  },

**Comment by Rychou** [comment]
@apppws 你好，该问题已经修复，请升级至最新版本验证一下。
