### ISSUE TITLE
（iOS）聊天页面的UI显示不正常，怎么回事，用的你们提供的UI，在iPhone11以上的设备有问题，iPhone8上没问题

### ISSUE THREAD

**Issue by 525liwenrong** [tencentyun/TIMSDK#439]

**Comment by lynxzhang** [comment]
您好，感谢您的反馈，麻烦在有问题的设备上体验下我们的 demo 看下是否正常，demo体验地址：https://cloud.tencent.com/document/product/269/36852，我们这边下个版本也会加强 iphone11 以上设备的测试
