### ISSUE TITLE
TUIKit的TTextMessageCell的formatMessageString方法需要判断一下参数是否为nil

### ISSUE THREAD

**Issue by Bruce-pac** [tencentyun/TIMSDK#44]
现在在聊天页面下拉加载老数据时，因为这个text为nil，崩溃了
`- (NSAttributedString *)formatMessageString:(NSString *)text
{
    //1、创建一个可变的属性字符串
    NSMutableAttributedString *attributeString = [[NSMutableAttributedString alloc] initWithString:text];
    
    if([[TUIKit sharedInstance] getConfig].faceGroups.count == 0){
        return attributeString;
    }`

**Comment by lynxzhang** [comment]
好的，我们本周发的版本会优化这个问题

**Comment by lynxzhang** [comment]
已优化上线
