### ISSUE TITLE
新版TIM SDK消息体 无法兼容旧版

### ISSUE THREAD

**Issue by StevenRoger** [tencentyun/TIMSDK#440]
【Web】-【2.1.1】：【新版SDK消息体 无法兼容旧版】
【集成包】：TIM
【当前现象】：旧版SDK中包含elems节点，消息内容都在elems内，旧版的web端，iOS端，Android端都是解析的elems。新版SDK中，文档定义是没有elems节点，实际情况是返回了elements节点（见下图）。web端使用新的SDK之后，与已上线旧版各端应用，消息都不互通。
建议还是在新版中，返回elems节点，以兼容旧版SDK。
【机型】：Windows 10，chrome
【之前版本有无此问题】：
【有无日志或者截图】：
新版消息结构：
![image](https://user-images.githubusercontent.com/15900201/67445632-2b853200-f640-11e9-9ecb-7cae5accc2b7.png)

旧版消息结构：
![image](https://user-images.githubusercontent.com/15900201/67446541-83716800-f643-11e9-8844-d0cba36b90b5.png)

**Comment by yangq1990** [comment]
您好，我们再次验证，新旧Webim消息是互通的。麻烦看下文档 [Message](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/Message.html)

或者用我们的体验 [demo](https://webim-1252463788.file.myqcloud.com/demo/index.html)

**Comment by StevenRoger** [comment]
那请问一下，用新版SDK，自定义消息，如果送两个element呢？
旧版就可以发送如下消息：
![image](https://user-images.githubusercontent.com/15900201/67461402-d7924180-f66f-11e9-8394-0be30b7e9a8f.png)

**Comment by yangq1990** [comment]
2.x版本简化了Message的结构，从设计原则上也是不支持发送组合消息的，优先通过type确定Message的类型，通过payload获取到Message的内容。如果通过REST API或者旧版发了组合消息，可以通过 elements 属性（此为过渡方案，实际属性以版本更新描述为准），拿到组合消息的内容，然后自主解析，此时消息的类型可以参考官网文档 [消息格式描述](https://cloud.tencent.com/document/product/269/2720)
