### ISSUE TITLE
新旧SDK消息体 兼容问题

### ISSUE THREAD

**Issue by StevenRoger** [tencentyun/TIMSDK#441]
【Web】-【2.1.1】：【新旧SDK消息体 兼容问题】
【集成包】：TIM
【当前现象】：旧版SDK中包含elems节点，消息内容都在elems内，旧版的web端，iOS端，Android端都是解析的elems。新版SDK中，文档定义是没有elems节点，实际情况是返回了elements节点。

对于自定义消息，接收到了旧版发送的自定义消息体中，elements含有两个元素，用新版SDK，如何发送出同样的自定义消息？

【机型】：Windows 10，chrome
【之前版本有无此问题】：
【有无日志或者截图】：
收到旧版SDK的消息结构：
![image](https://user-images.githubusercontent.com/15900201/67462099-74a1aa00-f671-11e9-95d8-f201eb29c2f8.png)

请问，用新版SDK发送自定义消息，如何发送elements数组含有两个元素的消息？

**Comment by StevenRoger** [comment]
另外，收到的语音消息，是这样的：
![image](https://user-images.githubusercontent.com/15900201/67473657-a91f6100-f685-11e9-9c34-94a92089eede.png)

**Comment by yangq1990** [comment]
> 另外，收到的语音消息，是这样的：
> ![image](https://user-images.githubusercontent.com/15900201/67473657-a91f6100-f685-11e9-9c34-94a92089eede.png)

关于这个，请提供下发此语音消息时的SDK版本，以及发送时带的信息，如url, uuid downloadFlag等

**Comment by StevenRoger** [comment]
![image](https://user-images.githubusercontent.com/15900201/67660233-438ae780-f999-11e9-8546-1bcf650cb08e.png)
以上截图是旧版webim.js  SDK接收到的消息，
downUrl: "http://183.3.253.65/asn.com/stddownload_common_file?authkey=3043020101043c303a0201010201010204e7893dcb02037a1db9020441fd03b702044f89740e02037a1afd0204c83e5b6502041b16a3b402045dbe83420204676b36a50400&bid=10001&subbid=1400004073&fileid=305d02010004563054020100041231343431313531393833393035343036363902037a1afd02042316a3b402045db69af00424333133343734393133333135353736393037325f38bfeffd40353d3f14525b0a2ac9cac40201000201000400&filetype=2106&openid=100060&ver=0"

uuid: "305d02010004563054020100041231343431313531393833393035343036363902037a1afd02042316a3b402045db69af00424333133343734393133333135353736393037325f38bfeffd40353d3f14525b0a2ac9cac40201000201000400"

**Comment by StevenRoger** [comment]
> > 另外，收到的语音消息，是这样的：
> > ![image](https://user-images.githubusercontent.com/15900201/67473657-a91f6100-f685-11e9-9c34-94a92089eede.png)
> 
> 关于这个，请提供下发此语音消息时的SDK版本，以及发送时带的信息，如url, uuid downloadFlag等

Android端的SDK版本：TIMSDK版本：2.7.2.13671.13673

**Comment by peterchealse** [comment]
elements[1]被删了 哈哈哈  只能改源码

**Comment by yangq1990** [comment]
v2.x 的webim，**不支持发送组合消息，但可以兼容 REST API 或 native 发的组合消息**
完善的兼容，请升级到v2.3.2或更高版本
[更新日志](https://cloud.tencent.com/document/product/269/38492)
