### ISSUE TITLE
TIMSoundElem 发送语音消息 错误码7006 但是取出当前地址获取nsdata 存在。。。。

### ISSUE THREAD

**Issue by undersix** [tencentyun/TIMSDK#443]
TIMSoundElem 发送语音消息->sendmessge 时候，错误码是7006， 但是取出当前地址获取nsdata 存在，且使用avplayer播放当前地址下nsdata，播放成功有声音，问一下是什么原因

**Comment by parkhuang** [comment]
感谢反馈，麻烦补充一下日志，或者参考以下补充：
https://github.com/tencentyun/TIMSDK/issues/176

**Comment by undersix** [comment]
TIM: 2019-10-29 11:06:26.591/I/5870-491634   /Msg         -imcore_conversation_task.cpp.3821:Finish                   /upload|code:7006|desc:File check failed
TIM: 2019-10-29 11:06:26.592/I/5870-491634   /Msg         -imcore_conversation.cpp.117:operator()                     /SendMsg|code:7006|msg:File check failed
TIM: 2019-10-29 11:07:13.828/I/5870-491634   /Network     -imsession_monitor.cpp.284:Record                           /record|

**Comment by undersix** [comment]
[imsdk_20191029.log](https://github.com/tencentyun/TIMSDK/files/3781551/imsdk_20191029.log)

**Comment by undersix** [comment]
已经上传了 帮忙看看

**Comment by lynxzhang** [comment]
这边方便留个联系方式吗，我们单独定位下

**Comment by undersix** [comment]
QQ:2596017329
