### ISSUE TITLE
消息未读上报【报BUG】

### ISSUE THREAD

**Issue by jixuan0748qwer** [tencentyun/TIMSDK#445]
获取会话列表的时候每个数据里面都有一个未读数据统计。然后点击一下。把未读消息上报已读，在当次APP运行的时候有用。在APP退出之后在进去。在拉去列表的时候的之前上报的数据又返回回来了。

**Comment by jixuan0748qwer** [comment]
补充：目前是使用小程序端SDK2.1.1

**Comment by Rychou** [comment]
@jixuan0748qwer 你好，我这边复现是正常的，请问能否提供具体的复现路径以及相应的截图呢？

**Comment by jixuan0748qwer** [comment]
![1572231048(1)](https://user-images.githubusercontent.com/56328367/67648628-3ce87a00-f971-11e9-9fa0-0f8970f80c89.jpg)
![1572231201(1)](https://user-images.githubusercontent.com/56328367/67648630-3d811080-f971-11e9-8114-eb18a0b535ff.jpg)
图片统计数为一1的是我进行上报之后返回的数据是正常的。
但是当我关闭应用在打开的时候 获取会话列表的时候 这个统计数 又变了

**Comment by jixuan0748qwer** [comment]
> @ jixuan0748qwer你好，我这边复现是正常的，请问能否提供具体的复现路径以及相应的截图呢？

你可以看看我的截图

**Comment by Rychou** [comment]
@jixuan0748qwer 你好，我看到你有改动`lastMessage`对象里的属性值（eg: lastTime），这可能是导致问题原因。

“XX分钟前”，建议添加新的属性值，而不是改动`lastTime`。

**Comment by jixuan0748qwer** [comment]
> @jixuan0748qwer 你好，我看到你有改动`lastMessage`对象里的属性值（eg: lastTime），这可能是导致问题原因。
> 
> “XX分钟前”，建议添加新的属性值或者另行处理，而不是改动`lastTime`。

你这个属性已经返回到我的本地了。我在我的本地更改，肯定不的影响服务器的代码不，如果 更改本地还能影响到服务器 ，那还得了?.我这个都是在服务器返回之后在本地做的操作

**Comment by jixuan0748qwer** [comment]
非常的棒。解决问题的效率杠杆的
