### ISSUE TITLE
离线消息点击事件处理？

### ISSUE THREAD

**Issue by myselyhero** [tencentyun/TIMSDK#447]
![image](https://user-images.githubusercontent.com/43132305/67617300-64760000-f814-11e9-9768-7e64728e0e74.png)
在推送证书中设置点击事件后点击无反应

**Comment by parkhuang** [comment]
感谢反馈，有些手机在管家或者安全中心里面，有“权限设置”-“后台弹出界面”，麻烦检查一下

**Comment by myselyhero** [comment]
> 感谢反馈，有些手机在管家或者安全中心里面，有“权限设置”-“后台弹出界面”，麻烦检查一下
感谢指导，问题已解决！
