### ISSUE TITLE
Android/ios 群聊消息收不到

### ISSUE THREAD

**Issue by yxiangTang** [tencentyun/TIMSDK#448]
issue标题：

【Android/ios】-【版本号】：【会经常出现群聊消息收不到的情况，但是C2C私聊却是完全正常，也没有上报相关错误码】
issue内容：

【当前现象】：群聊消息偶尔会收不到（一旦遇到，就再收不到），但是在同一个时间同一个群聊的其他用户是正常的，C2C私聊也是正常的，就是群聊消息完全收不到。而且查看了一下日志，是没发现有任何错误码上报的。
【集成包】：IMSDK
【机型】：各机型均有出现
【之前版本有无此问题】：如今用的是4.4.900 @2019.08.07版本，之前是2.5.7版本，两个版本都有此问题。

**Comment by parkhuang** [comment]
好的，感谢反馈，能否提供一份收不到消息的log

**Comment by yxiangTang** [comment]
你好,暂时没有相应log可提供，问题是用户反馈的~类似的问题反馈了很多例了

**Comment by yxiangTang** [comment]
你好，问题重现了，请问你们Android sdk 存储log的目录是在哪里，我发一下

**Comment by parkhuang** [comment]
/sdcard/tencent/imsdklogs/包名/
