### ISSUE TITLE
oppo收不到ios发送的消息

### ISSUE THREAD

**Issue by Peter0818** [tencentyun/TIMSDK#449]
oppo手机杀死程序收不到ios发送的离线推送

**Comment by parkhuang** [comment]
https://github.com/tencentyun/TIMSDK/issues/176
感谢反馈，麻烦提供更多信息

**Comment by Peter0818** [comment]
oppo要收到离线推送，要设置OPPOChannelID , 这个方法只有安卓端有，ios端没有对应的设置方法，希望尽快加上这个

**Comment by parkhuang** [comment]
二月中旬的版本将会加上这个改动
