### ISSUE TITLE
Android如何别人的个人资料？

### ISSUE THREAD

**Issue by ma343599083** [tencentyun/TIMSDK#45]
这个版本的SDK好像没有TIMFriendshipManager 这个类，那应该如何获取用户资料？请告知，非常感谢

**Comment by Gloud-Zhao** [comment]
同样发现了这个问题。。。官方给个说法吧。。。4.0的变化太大了。。。

**Comment by wangshaolei** [comment]
@ma343599083 用老版本吧~

**Comment by ma343599083** [comment]
> @ma343599083 用老版本吧~

老版本文档说明跟demo都找不到 尴尬

**Comment by lynxzhang** [comment]
统一回复下：4.x版本重构后，资料关系链的逻辑还在开发中，预计这周新版本会上资料逻辑，关系链逻辑后面的版本也会尽快加上

**Comment by lynxzhang** [comment]
https://cloud.tencent.com/document/product/269/33926 资料逻辑已上线
