### ISSUE TITLE
【需求】-【iOS】希望规范 Log 内容

### ISSUE THREAD

**Issue by rakuyoMo** [tencentyun/TIMSDK#452]
TIM 支持把 SDK 内部 log 转到项目自己的 log 体系，所以希望 SDK 交付 log 到客户端的时候能给给一个 Model，进一步规范 log 内容。

现在 `logFunc` 闭包只有 log 的级别和一个 string 字符串。

我们需要自己去处理截取这个字符串，然而 sdk 经常去改 log 的格式，有的时候是用 `:` 分割，更新后又变成用 `.` 分割。

所以希望有一个 Model 来抛开格式，规范内容。

**Comment by parkhuang** [comment]
好的，感谢反馈，log规范也是我们一直在做的事情。请问你们截取字符串的用途是什么，我们看能不能针对性的处理一下

**Comment by rakuyoMo** [comment]
> 好的，感谢反馈，log规范也是我们一直在做的事情。请问你们截取字符串的用途是什么，我们看能不能针对性的处理一下

我们自己的 log 大概长这个样子：

```
[↓ In `willSend(_:target:)` of LogPlugin.swift, at line 28 ↓]
[MBC_Request] 17:36:43:294 <✅ Success> : getSign 接口请求成功
```

包含 log 所在文件，所在函数，所在函数，log 时间以及 log 内容。

为了简化、规范 log 内容，我就要截取处理你们 `logFunc` 返回的字符串，从里面截取出上面的信息，处理完了大概是这样：

```
[↓ In `operator()` of log_util.cpp, at line 534 ↓]
[MBC_IM SDK] 17:36:42:910 <👾 Debug> : get log file:imsdk_20191029.log
```

希望你们的 Log 模型至少包含以下内容：

1. log 所在的文件
2. log 所在的方法
3. log 所在的行数
4. 真正的 log 内容
