### ISSUE TITLE
【Android】-【3.3.2】：【TIMMessage找不到isRead()方法】

### ISSUE THREAD

**Issue by Nstd** [tencentyun/TIMSDK#458]
【集成包】：IMSDK
【当前现象】：我们现在使用的是3.3.2的IMSDK，看到文档上TIMMessage类有一个[isRead()](https://imsdk-1252463788.cos.ap-guangzhou.myqcloud.com/IM_DOC/Android/ImSDK/com/tencent/imsdk/TIMMessage.html?&_ga=1.71951955.1145592858.1568101270#isread)方法，不知道这个方法是什么时候加入的？

------

PS：我们现在有个需求是在会话列表要提示有新的`@消息`，消息已读之后，在会话列表就不再提示了，基本正常，但是如果最后一条消息是`@消息`，已读之后，kill应用，再重新进入app，onNewMessage()会重新回调该条消息，这个不知道是怎么触发的，所以想通过isRead()来判断

**Comment by parkhuang** [comment]
感谢反馈，您看到的文档在哪里，能否贴一下

**Comment by Nstd** [comment]
@parkhuang 
这里 https://cloud.tencent.com/document/product/269/9232#.E6.B6.88.E6.81.AF.E6.98.AF.E5.90.A6.E5.B7.B2.E8.AF.BB

![image](https://user-images.githubusercontent.com/3004225/67832382-6d204c00-fb1c-11e9-809b-d17aca79d4d6.png)

**Comment by parkhuang** [comment]
您好，最新版本是4.x，文档也是4.x的文档，3.x及以下版本已经不再维护了，麻烦升级到最新版本
