### ISSUE TITLE
Android SDK中没有TIMFriendshipManager类

### ISSUE THREAD

**Issue by Gloud-Zhao** [tencentyun/TIMSDK#46]
Android SDK中没有TIMFriendshipManager类，ios和mac下有...

**Comment by Gloud-Zhao** [comment]
TIMSDK/Android/tuikit/src/main/java/com/tencent/qcloud/uikit/business/chat/c2c/model/SelfInfoManager.java
      官方人员都不知道写到这怎么写了吧。。。

**Comment by lynxzhang** [comment]
4.x版本重构后，资料关系链的逻辑还在开发中，预计这周新版本会上资料逻辑，关系链逻辑后面的版本也会尽快加上

**Comment by lynxzhang** [comment]
同步一下，TIMFriendshipManager 已经加上，资料的逻辑已经发布

**Comment by ZKLDream** [comment]
> 同步一下，TIMFriendshipManager 已经加上，资料的逻辑已经发布

ios我用pod导入也没有什么情况这是

**Comment by ZKLDream** [comment]
> > 同步一下，TIMFriendshipManager 已经加上，资料的逻辑已经发布
> 
> ios我用pod导入也没有什么情况这是

补充一下是4.0.13版本没有，最新的版本是有的，需要pod update

**Comment by Gloud-Zhao** [comment]
> 同步一下，TIMFriendshipManager 已经加上，资料的逻辑已经发布

Android貌似并没有更呀，4.2.2只更新了ios和mac
