### ISSUE TITLE
【web】-【2.1.2】：【自定义消息收不到json字符串】

### ISSUE THREAD

**Issue by 1o1w1** [tencentyun/TIMSDK#460]
【当前现象】：自定义消息收不到json字符串
【问题描述】：
下图是使用sdk中的方法createCustomMessage,创建的自定义消息
![image](https://user-images.githubusercontent.com/22697045/67758954-94720d00-fa79-11e9-9301-55a193bdc2f8.png)
下图是接收到的消息
![image](https://user-images.githubusercontent.com/22697045/67759374-47db0180-fa7a-11e9-9281-aff73936d28f.png)

**Comment by 1o1w1** [comment]
如上图content.data中的json字符串没有传过去, 这个bug间歇发作

**Comment by 1o1w1** [comment]
补充:
其中data部分的字符串是使用JSON.stringify 生成的字符串json
let message = tim.createCustomMessage({
  to: targetUserId,
  conversationType: TIM.TYPES.CONV_C2C,
  payload: {
    data: `{"roomID":"10661068","msgType":1,"msgTime":0,"content":"发起通话","version":1}`,
    description: "",
    extension: ""
  }
})
tim.sendMessage(message)

**Comment by 1o1w1** [comment]
data如果换成非字符串json可以成功,
![image](https://user-images.githubusercontent.com/22697045/67826349-2c6a0800-fb07-11e9-8485-c30ab4d75a01.png)

**Comment by guanzhanyi** [comment]
这个bug解决了吗？
