### ISSUE TITLE
【iOS】-【4.5.111】：【群组列表中无法筛选出公开群】

### ISSUE THREAD

**Issue by fandongtongxue** [tencentyun/TIMSDK#464]
【集成包】：TUIKIT
【当前现象】：目前群组列表中既有公开群 ，全员大群，也有AVChatRoom群，我想筛选出公开群，其余群组类型不显示，可以实现吗？
【机型】：所有机型
【之前版本有无此问题】：刚开始注意这个问题
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by xcoderliu** [comment]
感谢反馈，这边建议您直接修改tuikit源文件TUIGroupConversationListViewModel中的内容。

**Comment by fandongtongxue** [comment]
我是这么改的，不会有其他问题吧？
![WX20191101-100649](https://user-images.githubusercontent.com/21986591/67997551-872e6b80-fc8f-11e9-9fbe-5b21d4fbd50e.png)

**Comment by xcoderliu** [comment]
跑起来没问题应该就ok了，因为不了解具体需求，您这边可以多测试几次。
