### ISSUE TITLE
web端关于消息撤回和@功能问题

### ISSUE THREAD

**Issue by clcChen** [tencentyun/TIMSDK#465]
1. 看文档完全没有撤回相关的说明，是不支持吗？
2. 关于@功能的实现，文档上说的都是当前用户在线的情况下如何实现，但是如果被@的时候用户不在现并且@消息不是最后一条，这时候用户再上线，怎么判断未读消息里面被@了。

**Comment by Rychou** [comment]
> 1. 看文档完全没有撤回相关的说明，是不支持吗？
> 2. 关于@功能的实现，文档上说的都是当前用户在线的情况下如何实现，但是如果被@的时候用户不在现并且@消息不是最后一条，这时候用户再上线，怎么判断未读消息里面被@了。

1. SDK暂未支持撤回，目前已有排期计划支持，请持续关注。
2. @ 功能可以在接入测自行实现。主要思路如下：
2.1 发消息时带上 @+群成员 userID。可以在输入时，遇到 "@" 符号，即从群成员列表中选择某个群成员。
2.2 在收到新消息时，解析 @ 符号，遇到是@自己的，则做相应的提示或通知。Chrome浏览器可搭配Notification相关接口实现。
https://developer.mozilla.org/en-US/docs/Web/API/notification
