### ISSUE TITLE
【Windows】安装路径有中文的话第一次登录成功无法加载用户资料

### ISSUE THREAD

**Issue by clean2016** [tencentyun/TIMSDK#468]
【Windows】-【4.5.111】：如果按照路径包含中文，那么第一次登录后无法完整获取本地用户资料。
日志记录error （Cache     -sqlite_store.cpp.1082  imcore::SqliteStore::Open           /ERROR: sqlite db open step 1 failed: 14）

**Comment by cldz123** [comment]
感谢您的反馈。
如果有中文，麻烦使用utf-8编码
https://cloud.tencent.com/document/product/269/33543
![image](https://user-images.githubusercontent.com/37802395/68097593-d0cac080-fef2-11e9-92e6-7439de5aca4f.png)

**Comment by clean2016** [comment]
/**
* @brief 获取本地缓存的会话列表
* 
* @param cb 获取会话缓存列表的回调。回调函数定义和参数解析请参考 [TIMCommCallback](TIMCloudCallback.h)
* @param user_data 用户自定义数据，ImSDK只负责传回给回调函数cb，不做任何处理
* @return int 返回TIM_SUCC表示接口调用成功（接口只有返回TIM_SUCC，回调cb才会被调用），其他值表示接口调用失败。每个返回值的定义请参考 [TIMResult](TIMCloudDef.h)
* 
*/
TIM_DECL int TIMConvGetConvList(TIMCommCallback cb, const void* user_data);


这个方法中没有路径参数。
经过测试4.5.111的TIMConvGetConvList方法调用，只要程序目录包含中文就无法获取用户资料，不管第一次还是后续的每一次
