### ISSUE TITLE
【Android】-【3.1.0】：【偶发消息延迟】

### ISSUE THREAD

**Issue by Baker-abc** [tencentyun/TIMSDK#472]
【集成包】：IMSDK
【当前现象】：用户反馈偶尔消息发完一两天对方才收到，我看腾讯云官网说发消息的时候需要检查addElement的返回值，我们的代码里没有检测这个返回值，会是这个原因吗？
另外我看官方sdk包里也没有检测这个返回值，为什么？
【机型】：
【之前版本有无此问题】：不知道
【有无日志或者截图】：暂无

**Comment by Baker-abc** [comment]
在这里看到说需要检测返回值  https://cloud.tencent.com/document/product/269/32486

**Comment by parkhuang** [comment]
您好，感谢反馈，官网对应的文档是4.x的版本，您需要升级到最新版本，3.x及以下已经不再维护了。
