### ISSUE TITLE
【Android】-【4.5.111以及上个版本】 拉取进群申请列表经常（但不是每次都会）报网络错误

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#474]
【当前现象】进群聊页面，拉取群申请列表，报网络错误9508 Remain Packet Timeout，然后群消息也加载不出来，这个现象有时候发生有时候不发生，发生率还是挺高的
【集成包】IMSDK
【机型】红米 Redmi 6
【之前版本是否有次问题】上一个版本也有，再之前的就不知道了
【有无截图或日志】有截图，也有日志（从进入群聊之后开始打印的那一部分），注意截图最下面的弹框提示，loadGroupApplyList Error
![bug](https://user-images.githubusercontent.com/41293421/68089221-9a188a00-fea1-11e9-8d52-446e6b55de1d.png)
[bug_log.txt](https://github.com/tencentyun/TIMSDK/files/3801848/bug_log.txt)

**Comment by parkhuang** [comment]
感谢反馈，您的上个版本是什么版本，有没有这种问题？

**Comment by xiezhenjian** [comment]
> 感谢反馈，您的上个版本是什么版本，有没有这种问题？

上个版本是4.5.55。
另外，今天研究了下日志发现导致这个问题的原因是在登录之后，频繁报9519和9520错误，导致onRefreshConversation()这个函数没有立即调用，所以点进去群聊界面的时候，加载不出消息。但为什么报9519和9520就不清楚了，我再另开一个issue，把日志贴出来吧。

**Comment by parkhuang** [comment]
在#479上集中解决
