### ISSUE TITLE
【iOS】用含UI库，更换登录用户，但是会话列表不刷新

### ISSUE THREAD

**Issue by codeZP** [tencentyun/TIMSDK#475]
您好，我使用含UI库，如果切换用户，会话列表界面展示还是上个用户的会话列表。如果将APP从后台杀死再进来，会话列表才会展示当前用户的会话信息

**Comment by xcoderliu** [comment]
您好感谢反馈，这边暂时不能复现问题，请问可以提供下出问题的时候日志信息吗？
