### ISSUE TITLE
【Android】-【4.5.111】 置顶群会话后清除后台再打开就闪退

### ISSUE THREAD

**Issue by qq103733** [tencentyun/TIMSDK#477]
上次提交了个工单 回复说demo正常的，真的有测试吗？ 我用demo测试也是错误的
详情看日志，有时候主动退出的时不会闪退的  清除后台基本必闪退
//置顶代码 用的demo的
ConversationManagerKit.getInstance().setConversationTop(mChatInfo?.id, isChecked)
//清除后获取会话列表就会出现这个错误
[log.txt](https://github.com/tencentyun/TIMSDK/files/3802808/log.txt)

**Comment by parkhuang** [comment]
这是一个bug，已经修复了，预计下周发布的版本会带上这个修复。
