### ISSUE TITLE
iOS进群后可以拉取到进群之前到消息记录！

### ISSUE THREAD

**Issue by AssassinEzio** [tencentyun/TIMSDK#480]
iOS进群后可以拉取到进群之前到消息记录，android和web端都拿不到。并且我们也没有配置这些东西。

**Comment by parkhuang** [comment]
是新进群还是说你本地有历史记录？

**Comment by AssassinEzio** [comment]
> 是新进群还是说你本地有历史记录？

是新进群的

**Comment by AssassinEzio** [comment]
是新进群的  就是发了几条信息之后马上拉进群就会出现

发自我的 iPhone

**Comment by dawnnnnn** [comment]
这个问题还是没有解决呀

**Comment by parkhuang** [comment]
加群就拉漫游，可以拉取到进群前1分钟的历史记录
