### ISSUE TITLE
【Windows】-【4.5.15】获取群消息列表 code返回-3

### ISSUE THREAD

**Issue by clean2016** [tencentyun/TIMSDK#486]
【当前现象】：如果群消息中包含加群退群消息时，无法获取历史消息
【调用方法】：TIMMsgGetMsgList
【集成包】：IMSDK
【机型】：Windows
【之前版本有无此问题】：未知
【有无日志或者描述、截图】：有
TIM: 2019-11-06 10:37:40.421/E/4568-2640     /IMSDK     -MessageConverter.cpp.569  Json2MessageInternal             /Json2Elem Parse Json 2 std::shared_ptr<imcore::Elem> Failure!
TIM: 2019-11-06 10:37:40.421/E/4568-2640     /IMSDK     -MessageConverter.cpp.683  Json2MsgGetArgs                  /func Json2MessageInternal Json 2 lastMsg failure!

**Comment by parkhuang** [comment]
感谢反馈，我们分析一下
