### ISSUE TITLE
老是断线问题！

### ISSUE THREAD

**Issue by DoveBarnett** [tencentyun/TIMSDK#488]
【Android】-【4.3.145】：【长时间无操作后老是断开了连接】
【集成包】：imsdk
【当前现象】：长时间不在聊天界面或者息屏，无法再收到IM推送的消息即断开连接了
【机型】：如oppoA5
【之前版本有无此问题】：用的第一个版本就是这个
【有无日志或者截图】：暂无日志

**Comment by parkhuang** [comment]
感谢反馈，最近的demo是否也存在这种问题？

**Comment by DoveBarnett** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "parkhuang"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 上午10:30
收件人: "tencentyun/TIMSDK"<TIMSDK@noreply.github.com&gt;; 
抄送: "暖冬"<2291493676@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tencentyun/TIMSDK] 老是断线问题！ (#488)




感谢反馈，最近的demo是否也存在这种问题？
