### ISSUE TITLE
【小程序】-【3.1.2】：【申请加群通知怎么判断这个通知是否处理过,SDK api没有这方面的字段说明】

### ISSUE THREAD

**Issue by newStudent-ls** [tencentyun/TIMSDK#494]
RT

**Comment by newStudent-ls** [comment]
调用handleGroupApplication后，初始化通知里面一直还是有，是不是有字段可以区分是否已经处理过了？

**Comment by newStudent-ls** [comment]
![6_K_ Y JX5X$OGLT9CSN6EQ](https://user-images.githubusercontent.com/12325846/68454249-01806200-0233-11ea-9659-bc26191b6b91.png)

**Comment by Rychou** [comment]
你好，这方面的需求我们已有排期，后续的版本会解决这个问题。

**Comment by Rychou** [comment]
@newStudent-ls 你好，该问题已于v2.2.1版本修复，已处理过的【加群申请】，在下次登录时不会再收到了。
