### ISSUE TITLE
【小程序】-【2.1.3】-【获取会话列表希望能支持获取自定义字段 GROUP/C2C】

### ISSUE THREAD

**Issue by newStudent-ls** [tencentyun/TIMSDK#497]
RT

**Comment by yangq1990** [comment]
您好，为了尽快传输会话列表，[getConversationList](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#getConversationList) 拿到的信息仅够渲染用。如果想获取群或c2c会话对端用户的自定义资料，

**请升级sdk到v2.3.2以上**

并分别调用
[getGroupProfile](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#getGroupProfile)
和
[getUserProfile](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#getUserProfile)
