### ISSUE TITLE
iOS 没有群消息免打扰设置

### ISSUE THREAD

**Issue by wenhaiwang** [tencentyun/TIMSDK#500]
因为群消息比较多,消息外面小红点我想屏蔽掉,但是没见到有相关设置的,请问能否开启这样的设置

**Comment by parkhuang** [comment]
感谢反馈，目前没有这样的设置，需要您自己实现

**Comment by wenhaiwang** [comment]
希望这个功能能出现在你们产品需求列表里, 在之后迭代中能让大家用上
