### ISSUE TITLE
用户头像显示异常

### ISSUE THREAD

**Issue by fansonq** [tencentyun/TIMSDK#502]
【Android】-【4.5.111】：【绘画列表页面用户头像显示不正确】
【集成包】：com.tencent.imsdk:tuikit:4.5.111
【当前现象】：Android Studio集成新版本TUIKit，会话列表设置用户头像圆角listLayout.enableItemRoundIcon(true);实际显示有圆角有长方形的
【机型】：如Oppo R15
【有无日志或者截图】：暂无日志，有截图附上问题截图
![image](https://user-images.githubusercontent.com/11573864/68657857-67d8ed80-056f-11ea-8019-ed38fd775c3b.png)
![image](https://user-images.githubusercontent.com/11573864/68657891-732c1900-056f-11ea-8581-98269ca75e2b.png)

**Comment by parkhuang** [comment]
感谢反馈，能不能把您头像的url贴一下，我们验证一下

**Comment by fansonq** [comment]
> 感谢反馈，能不能把您头像的url贴一下，我们验证一下

已经修复了，谢谢
