### ISSUE TITLE
【Android】-【4.5.111】TIMMessage getSenderGroupMemberProfile接口中返回的群成员名片nameCard为空

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#503]
当前现象】TIMMessage getSenderGroupMemberProfile接口返回的TIMGroupMemberInfo中，字段nameCard为空，可是明明设置了的。
【集成包】IMSDK
【测试机型】红米 Redmi 6
【之前版本是否有次问题】不确定
【有无日志和截图】无

**Comment by ahqzhang** [comment]
是否从旧版本升级上来的？
检查下是否有这部分代码没有设置 nameCard 字段，建议全部注释，默认拉取全部字段
![image](https://user-images.githubusercontent.com/56570726/68761094-4e5aa300-064e-11ea-99ac-c593677277cd.png)
