### ISSUE TITLE
【小程序】-【2.1.4】：【无法监听到ready】

### ISSUE THREAD

**Issue by tianleiwufeng** [tencentyun/TIMSDK#504]
【当前现象】：无法监听到read
【集成包】：IMSDK
【机型】：所有
【之前版本有无此问题】：
【有无日志或者描述、截图】：
![readyListen](https://user-images.githubusercontent.com/13955666/68662786-82639480-0578-11ea-978f-808fbc6fc6ca.png)

代码：
`//app.js
var TIM = require("./npm/tim-wx-sdk/tim-wx.js");
var _cosWxSdkV = require("./npm/cos-wx-sdk-v5/demo/lib/cos-wx-sdk-v5.js");

App({
  onLaunch: function() {
    // 展示本地存储能力
    var logs = wx.getStorageSync('logs') || []
    logs.unshift(Date.now())
    wx.setStorageSync('logs', logs)

    // 登录
    wx.login({
      success: res => {
        // 发送 res.code 到后台换取 openId, sessionKey, unionId
      }
    })
    // 获取用户信息
    wx.getSetting({
      success: res => {
        if (res.authSetting['scope.userInfo']) {
          // 已经授权，可以直接调用 getUserInfo 获取头像昵称，不会弹框
          wx.getUserInfo({
            success: res => {
              // 可以将 res 发送给后台解码出 unionId
              this.globalData.userInfo = res.userInfo

              // 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
              // 所以此处加入 callback 以防止这种情况
              if (this.userInfoReadyCallback) {
                this.userInfoReadyCallback(res)
              }
            }
          })
        }
      }
    })

    console.log('创建实例');
    let options = {
      SDKAppID: 1400274427, // 接入时需要将0替换为您的即时通信应用的 SDKAppID
    };
    console.log('TIM', TIM);
    // 创建 SDK 实例，TIM.create() 方法对于同一个 SDKAppID 只会返回同一份实例
    var tim = TIM.create(options); // SDK 实例通常用 tim 表示
    console.log('tim',tim);
    // 注册 COS SDK 插件
    tim.registerPlugin({
      'cos-wx-sdk': _cosWxSdkV
    });
    tim.setLogLevel(0);

    // 监听事件，如：
    tim.on(TIM.EVENT.SDK_READY, function(event) {
      // 收到离线消息和会话列表同步完毕通知，接入侧可以调用 sendMessage 等需要鉴权的接口
      // event.name - TIM.EVENT.SDK_READY
      console.log('SDK_READY');
    });

    tim.on(TIM.EVENT.MESSAGE_RECEIVED, function(event) {
      // 收到推送的单聊、群聊、群提示、群系统通知的新消息，可通过遍历 event.data 获取消息列表数据并渲染到页面
      // event.name - TIM.EVENT.MESSAGE_RECEIVED
      // event.data - 存储 Message 对象的数组 - [Message]
      console.log('MESSAGE_RECEIVED');
    });

    tim.on(TIM.EVENT.CONVERSATION_LIST_UPDATED, function(event) {
      // 收到会话列表更新通知，可通过遍历 event.data 获取会话列表数据并渲染到页面
      // event.name - TIM.EVENT.CONVERSATION_LIST_UPDATED
      // event.data - 存储 Conversation 对象的数组 - [Conversation]
      console.log('CONVERSATION_LIST_UPDATED');
    });

    tim.on(TIM.EVENT.GROUP_LIST_UPDATED, function(event) {
      // 收到群组列表更新通知，可通过遍历 event.data 获取群组列表数据并渲染到页面
      // event.name - TIM.EVENT.GROUP_LIST_UPDATED
      // event.data - 存储 Group 对象的数组 - [Group]
      console.log('GROUP_LIST_UPDATED');
    });

    tim.on(TIM.EVENT.GROUP_SYSTEM_NOTICE_RECEIVED, function(event) {
      // 收到新的群系统通知
      // event.name - TIM.EVENT.GROUP_SYSTEM_NOTICE_RECEIVED
      // event.data.type - 群系统通知的类型，详情请参见 GroupSystemNoticePayload 的 <a href="https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/Message.html#.GroupSystemNoticePayload"> operationType 枚举值说明</a>
      // event.data.message - Message 对象，可将 event.data.message.content 渲染到到页面
      console.log('GROUP_SYSTEM_NOTICE_RECEIVED');
    });

    tim.on(TIM.EVENT.PROFILE_UPDATED, function(event) {
      // 收到自己或好友的资料变更通知
      // event.name - TIM.EVENT.PROFILE_UPDATED
      // event.data - 存储 Profile 对象的数组 - [Profile]
      console.log('PROFILE_UPDATED');
    });

    tim.on(TIM.EVENT.BLACKLIST_UPDATED, function(event) {
      // 收到黑名单列表更新通知
      // event.name - TIM.EVENT.BLACKLIST_UPDATED
      // event.data - 存储 userID 的数组 - [userID]
      console.log('BLACKLIST_UPDATED');
    });

    tim.on(TIM.EVENT.ERROR, function(event) {
      // 收到 SDK 发生错误通知，可以获取错误码和错误信息
      // event.name - TIM.EVENT.ERROR
      // event.data.code - 错误码
      // event.data.message - 错误信息
      console.log('ERROR');
    });

    tim.on(TIM.EVENT.SDK_NOT_READY, function(event) {
      // 收到 SDK 进入 not ready 状态通知，此时 SDK 无法正常工作
      // event.name - TIM.EVENT.SDK_NOT_READY
      console.log('SDK_NOT_READY');
    });

    tim.on(TIM.EVENT.KICKED_OUT, function(event) {
      // 收到被踢下线通知
      // event.name - TIM.EVENT.KICKED_OUT
      // event.data.type - 被踢下线的原因，例如 TIM.TYPES.KICKED_OUT_MULT_ACCOUNT 多账号登录被踢
      console.log('KICKED_OUT');
    });
    tim.login({
      userID: '768',
      userSig: 'eJyrVgrxCdZLrSjILEpVsjIzMLEwMNABi5WlFilZKRnpGShB*MUp2YkFBZkpSlaGJgYGRuYmJkbmEJnMlNS8ksy0TLAGczMLmIbMdCC-zLciRTvSpDixxDCiKDfAy6eqrCy53LkiPzGkKsI4Kdgjw6gsMaPCsigr0BaqsSQzF*gWQ1NzY1MTC0szs1oAkeYxGA__',
    }).then((imResponse) => {
      console.log('登陆成功：imResponse', imResponse)
    })
  },
  globalData: {
    userInfo: null
  }
})`

**Comment by tianleiwufeng** [comment]
试过用2.1.3原生小程序可以监听了，但是taro框架2.1.3仍然监听不到，导致消息发送不出去

**Comment by yangq1990** [comment]
[常见问题](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/tutorial-01-faq.html)

2. 用 Taro 开发项目，集成 WebIM v2.x，为什么一直收不到 TIM.EVENT.SDK_READY 事件？
WebIM v2.x 不需要被 Taro 编译。如果您通过 npm i 的方式集成了 WebIM，请手动将文件 node_modules/tim-js-sdk/tim-js-sdk.js 或 node_modules/tim-wx-sdk/tim-wx-sdk.js 拷贝到您项目的 src 目录下，并在配置文件中配置（更详细的请参考 编译配置详情）。 示例如下：

weapp: {
  compile: {
    exclude: ['src/tencent-webim/tim-wx-sdk.js']
  }
}

**Comment by yangq1990** [comment]
[taro的编译配置详情](https://nervjs.github.io/taro/docs/config-detail.html#weappcompileexclude)
