### ISSUE TITLE
【小程序】-【2.1.1】：【不能播放语音】

### ISSUE THREAD

**Issue by LiyingHong** [tencentyun/TIMSDK#506]
【集成包】：IMSDK
【当前现象】：安卓APP上传的MP3格式的音频,iOS端小程序无法播放;iOSAPP上传的MP3格式的音频,安卓端小程序无法播放
【机型】：所有
【之前版本有无此问题】：
【有无日志或者截图】：

**Comment by yangq1990** [comment]
小程序内最好用 m4a 后缀的音频文件，兼容性最好

**Comment by LiyingHong** [comment]
@yangq1990
* Android App
* Android 小程序
* iOS App
* iOS 小程序
 **四端通信,只有下面两路,传输的mp3格式文件不能播放,其他任意通信都可以正常播放**
* Android App ---->iOS微信小程序
* iOS App ---->Android微信小程序

**Comment by yangq1990** [comment]
小程序本身有莫名奇妙的兼容性问题，换 m4a  吧
