### ISSUE TITLE
Android -4.5.111 -离线推送收不到

### ISSUE THREAD

**Issue by cx324** [tencentyun/TIMSDK#507]
【Android】-【4.5.111】：【离线推送收不到】
【集成包】：TUIKIT
【当前现象】：上报token成功，但是杀掉进程，发送消息，无法收到离线推送。
目前想知道 离线推送消息在哪接收处理？  设置了 offlinePushListener ，但是无法收到离线消息，只能收到在线消息。 app杀掉进程后，在华为控制台发送通知消息可以收到。
【机型】：华为Honor 10  
【有无日志或者截图】：暂无日志

**Comment by parkhuang** [comment]
感谢反馈，麻烦按照这个流程执行一下，看问题出现在第几步，现象是什么：

1.请在手机厂商的官方控制台测试是否能收到推送。确认能收到之后进行下一步

2.请执行控制台的自助定位工具
如果返回明显的错误码提示语，则排查您的业务逻辑。
如果提示语不明确，请留言，我们会对此情况进行提示语优化

3.控制台的工具返回"推送成功"
此时测试手机上会收到一条"test"的推送。然后确认是否收到这条"test"。
如果没收到，请确认手机是否打开接收推送的开关，以及确认是否手机机型问题
有问题请留言

4.在控制台能收到推送，但是用手机发消息，接收方收不到推送
这种情况请用接收方登录，杀死进程。再用发送方发一条单聊的文本消息"hello world"，看是否能收到。（重点是杀死进程，单聊，文本）
如果还是收不到，请留言
