### ISSUE TITLE
【iOS】-【4.5.111】：收到消息没有提示音和震动

### ISSUE THREAD

**Issue by gank0326** [tencentyun/TIMSDK#508]
【iOS】-【4.5.111】：收到消息没有提示音和震动
【集成包】：TUIKIT
【当前现象】：收到消息没有提示音和震动
【机型】：iOS设备
【有无日志或者截图】：暂无日志

**Comment by xcoderliu** [comment]
您好，感谢反馈。TUIKit目前并没有实现这个功能，您可以在onnewmessage自己实现。
