### ISSUE TITLE
【iOS】-【4.6.1】：pod引入项目无法build

### ISSUE THREAD

**Issue by 0xfeedface1993** [tencentyun/TIMSDK#509]
【iOS】-【4.6.1】：pod引入项目无法build
【集成包】：TUIKIT
【当前现象】：Xocde 11.2.1 无法buil项目，因为CreatGroupAvatar.m文件错误'UIImageView+WebCache.h' file not found with <angled> include; use "quotes" instead
【机型】：iOS设备
【有无日志或者截图】：

<img width="1355" alt="截屏2019-11-16上午9 50 00" src="https://user-images.githubusercontent.com/12690698/68986064-a237d880-0856-11ea-861c-5930a823ce6c.png">

**Comment by parkhuang** [comment]
感谢反馈，我们自检一下

**Comment by xcoderliu** [comment]
感谢反馈，可能是用了比较新版本的 sdwebimage 和我们 podfile.lock 里的版本不同。

**Comment by TonyStarkGTX** [comment]
这我也遇到了 我后面把原项目的sdwebimage删掉了，重新弄路径才行

**Comment by jackieyiprylink** [comment]
确实存在这个问题，需要把#import <UIImageView+WebCache.h>改为#import "UIImageView+WebCache.h"，但是在我们自己项目里改pod进来的文件代码是不合理的做法，官方能否将sdk里CreatGroupAvatar.m文件的#import <UIImageView+WebCache.h>改为#import "UIImageView+WebCache.h"

**Comment by xcoderliu** [comment]
感谢反馈，已经改了，随下个版本发。

**Comment by jackieyiprylink** [comment]
> 感谢反馈，已经改了，随下个版本发。

大佬真快，谢谢~！什么时候发版呢？我们项目刚接入TIMSDK，已经完成测试，今天准备打包上线。期待大佬今天先提交这个bug fix。

**Comment by xcoderliu** [comment]
> > 感谢反馈，已经改了，随下个版本发。
> 
> 大佬真快，谢谢~！什么时候发版呢？我们项目刚接入TIMSDK，已经完成测试，今天准备打包上线。期待大佬今天先提交这个bug fix。

已经发布了，不过因为没更换版本号，请删除本地的tuikit 然后执行 pod cache clean --all，最后 pod install 一下，麻烦了。

**Comment by 0xfeedface1993** [comment]
> > > 感谢反馈，已经改了，随下个版本发。
> > 
> > 
> > 大佬真快，谢谢~！什么时候发版呢？我们项目刚接入TIMSDK，已经完成测试，今天准备打包上线。期待大佬今天先提交这个bug fix。
> 
> 已经发布了，不过因为没更换版本号，请删除本地的tuikit 然后执行 pod cache clean --all，最后 pod install 一下，麻烦了。

又报了另一个错误，TUIVoiceMessageCellData.m内引入imSDK错误`'ImSDK/IMMessageExt.h' file not found`:

![snap](https://user-images.githubusercontent.com/12690698/69390483-511e5d80-0d0a-11ea-8faa-4a46279c9aa8.png)

**Comment by lynxzhang** [comment]
> TUIVoiceMessageCellData
已修复，再试一下

**Comment by lynxzhang** [comment]
> > > > 感谢反馈，已经改了，随下个版本发。
> > > 
> > > 
> > > 大佬真快，谢谢~！什么时候发版呢？我们项目刚接入TIMSDK，已经完成测试，今天准备打包上线。期待大佬今天先提交这个bug fix。
> > 
> > 
> > 已经发布了，不过因为没更换版本号，请删除本地的tuikit 然后执行 pod cache clean --all，最后 pod install 一下，麻烦了。
> 
> 又报了另一个错误，TUIVoiceMessageCellData.m内引入imSDK错误`'ImSDK/IMMessageExt.h' file not found`:
> 
> ![snap](https://user-images.githubusercontent.com/12690698/69390483-511e5d80-0d0a-11ea-8faa-4a46279c9aa8.png)

已修复，再试一下

**Comment by 0xfeedface1993** [comment]
pod cache clean --all m

> > > > > 感谢反馈，已经改了，随下个版本发。
> > > > 
> > > > 
> > > > 大佬真快，谢谢~！什么时候发版呢？我们项目刚接入TIMSDK，已经完成测试，今天准备打包上线。期待大佬今天先提交这个bug fix。
> > > 
> > > 
> > > 已经发布了，不过因为没更换版本号，请删除本地的tuikit 然后执行 pod cache clean --all，最后 pod install 一下，麻烦了。
> > 
> > 
> > 又报了另一个错误，TUIVoiceMessageCellData.m内引入imSDK错误`'ImSDK/IMMessageExt.h' file not found`:
> > ![snap](https://user-images.githubusercontent.com/12690698/69390483-511e5d80-0d0a-11ea-8faa-4a46279c9aa8.png)
> 
> 已修复，再试一下

还是一样，这个bug一周了，也太慢了

**Comment by 0xfeedface1993** [comment]
此问题重装系统解决 请不要挣扎
