### ISSUE TITLE
iOS TIMConversation getReceiver方法使用有问题

### ISSUE THREAD

**Issue by absss** [tencentyun/TIMSDK#51]
从字面意思来理解getReceiver应该是获取接收者ID的意思，但是实际情况是：发送消息后，调用getReceiver 得到的ID是自己的ID；接收消息时，调用getReceiver得到的ID是对方的ID，这完全就是反的。望尽快解决，还有那个已读回执的问题。

**Comment by lynxzhang** [comment]
好的，我们先验证下，如果确定有问题，这边会尽快修复下

**Comment by lynxzhang** [comment]
对同一个 C2C 会话或则群聊会话，getReceiver 获取的会话人都是固定的，C2C 获取的是对方账号，Group 获取的是群组 Id。消息回执的问题也已在 4.2.52版本优化
