### ISSUE TITLE
【小程序】-【2.13】: Taro集成2.1.3版本 监听不到 TIM.EVENT.SDK_READY,已经配置到compile中

### ISSUE THREAD

**Issue by Joyee** [tencentyun/TIMSDK#512]
【当前问题】：已经将tm-wx.js文件拷贝到 src/lib/tim 中，在config/index.js中进行配置
weapp{
compile: {
     exclude: ['src/lib/tim/tim-wx.js']
  }
}
但还是监听不到 TIM.EVENT.SDK_READY

**Comment by yangq1990** [comment]
请提供日志，或者您的脱敏后的项目代码给我们看下

**Comment by allenou** [comment]
每次进入同无法监听到，但重新编译就可以，也已经配置 compile。@Joyee 你解决了吗？

**Comment by Joyee** [comment]
> 每次进入同无法监听到，但重新编译就可以，也已经配置 compile。@Joyee 你解决了吗？
引入TIM的时候，是要将src/lib/tim引入。我之前直接引入的node_modules的包
import TIM from '@/lib/tim-wx'

**Comment by monyee** [comment]
解决了吗？ 遇到同样的问题 配置exclude也不行

**Comment by allenou** [comment]
@monyee TIM.EVENT.SDK_READY 不能放在 Taro 的生命周期内

**Comment by tangshuoup** [comment]
> 每次进入同无法监听到，但重新编译就可以，也已经配置 compile。@Joyee 你解决了吗？
> 引入TIM的时候，是要将src/lib/tim引入。我之前直接引入的node_modules的包
> import TIM from '@/lib/tim-wx'

我把Tim-wx.js拿到本地然后也引入了本地的，也设置了 compile 为什么还是监听不到。。。

**Comment by tangshuoup** [comment]
> @monyee TIM.EVENT.SDK_READY 不能放在 Taro 的生命周期内

按照配置都弄好了，不放到生命周期里面好像也不行。。

**Comment by tangshuoup** [comment]
> @monyee TIM.EVENT.SDK_READY 不能放在 Taro 的生命周期内

你用的是taro吗。能给我截下你的代码片段吗

**Comment by monyee** [comment]
@tangshuoup 放生命周期里没问题  也不需要配置compile， 先监听再登录
