### ISSUE TITLE
设置消息免打扰后再关闭后就收不到离线消息了

### ISSUE THREAD

**Issue by shaokailin** [tencentyun/TIMSDK#517]
我先modifyReciveMessageOpt ：TIM_GROUP_RECEIVE_NOT_NOTIFY_MESSAGE 开启消息免打扰，后再改为TIM_GROUP_RECEIVE_MESSAGE，关闭，后面发的离线消息就收不到提示了。

版本号：4.6.1
平台：iOS

**Comment by xcoderliu** [comment]
重新启动app可以吗？

**Comment by xcoderliu** [comment]
您好感谢反馈，请问设置成功的回调调用了吗？
