### ISSUE TITLE
被拉黑发消息给对方居然显示发送成功，但是对方没收到

### ISSUE THREAD

**Issue by gank0326** [tencentyun/TIMSDK#518]
【iOS】-【4.5.111】：被拉黑发消息给对方没有提示语，消息发送成功，对方只是收不到
【集成包】：TUIKIT
【当前现象】：被拉黑后发送消息给对方，显示发送成功
【机型】：iOS设备
【有无日志或者截图】：暂无日志

**Comment by xcoderliu** [comment]
您好，感谢反馈，我们正在安排修复。
