### ISSUE TITLE
添加SoundElem和CustomElem时的顺序问题

### ISSUE THREAD

**Issue by HStanN** [tencentyun/TIMSDK#520]
【Android】-【4.4.900】：【添加SoundElem和CustomElem时的顺序问题】
【集成包】：TIM包
【当前现象】：单条消息多元素时，单个依次添加语音和自定义元素，发送方打印日志看到的是TIMMessage{
     ConverstaionType:C2C
     ConversationId:145204
     MsgId:3951170282
     MsgSeq:60290
     Rand:3951170282
     time:1574159081
     isSelf:true
     Status:Sending
     Sender:153236
     elements:[
      {Type:Sound}
      {Type:Custom
      desc: 
      data: {“...”}
      ext: }
     ]
    }

但是接收方接收时消息是TIMMessage{
     ConverstaionType:C2C
     ConversationId:145204
     MsgId:2006456889
     MsgSeq:30617
     Rand:2006456889
     time:1574159066
     isSelf:false
     Status:SendSucc
     Sender:145204
     elements:[
      {Type:Custom
      desc: 
       data: {“...”}
      ext: }
      {Type:Sound}
     ]
    }
元素顺序变了，我们之前的业务逻辑一直都是按照Text、Sound之类的元素在0下标，Custom是在1下标处理的，发送时也是严格按此顺序依次添加的，但是最近突然发现接收方的顺序突然变了，希望你们帮忙看一下是什么问题，然后我使用TextElem和CustomElem时没有顺序变化的问题
【机型】：所有
【之前版本有无此问题】：当前版本在集成时并没有这个问题，最近才发现有这个问题
【有无日志或者截图】：暂无日志

**Comment by parkhuang** [comment]
感谢反馈，后台不保证element的添加顺序，所以解析时不能直接按照发送的下标来处理
