### ISSUE TITLE
vue运行TIMSDK的demo时运行错误！

### ISSUE THREAD

**Issue by AleenL** [tencentyun/TIMSDK#523]
项目运行正常，但是过了大约五分钟后，会报错。

报错信息为：

Module build failed: Error: ENOENT: no such file or directory, open 'D:\TIMSDK - user1\H5\node_modules\cos-js-sdk-v5\lib\md5.js'

cos-js-sdk-v5版本为0.5.17升级为最新版本0.5.20后，BUG依旧存在

**Comment by zhangyuiris** [comment]
您好，能问一下，你是怎么用的吗，引入的时候怎么引的呢

**Comment by zhangyuiris** [comment]
可否提供一下相关代码 @AleenL

**Comment by HankBass** [comment]
> 您好，能问一下，你是怎么用的吗，日期的时候怎么引的呢

是github上面的代码直接clone下来后不改任何东西直接跑都会报这个错。

**Comment by HankBass** [comment]
找到问题了。是window10的锅，win10自带的杀毒把那个文件当成病毒杀掉了
