### ISSUE TITLE
【Android】-【4.6.1】获取用户信息返回null  TIMFriendshipManager.getInstance().queryUserProfile

### ISSUE THREAD

**Issue by EternalPlan** [tencentyun/TIMSDK#525]
【Android】-【4.6.1】获取用户信息返回null  TIMFriendshipManager.getInstance().queryUserProfile

登录之后.调用TIMFriendshipManager.getInstance().queryUserProfile()方法 获取个人信息有时候会返回null,导致聊天界面头像和用户名获取不到.

但是账号都是已经成功注册了的.并且可以成功登陆.

![异常问题](https://user-images.githubusercontent.com/18061136/69314339-da805200-0c6e-11ea-9c53-a487138b0918.png)
![正常情况](https://user-images.githubusercontent.com/18061136/69314341-db18e880-0c6e-11ea-8fdf-fcb876242b33.png)

**Comment by HystrixWong** [comment]
queryUserProfile  是查询本地有无缓存的，可以使用TIMFriendshipManager.getUsersProfile 方法获取用户资料
