### ISSUE TITLE
聊天界面消息从底部开始显示，而不是从上往下排列

### ISSUE THREAD

**Issue by HystrixWong** [tencentyun/TIMSDK#532]
如何所示，正常的应该从上往下排列，请问如何解决？
![聊天界面](https://s2.ax1x.com/2019/12/02/QneOpj.png)

**Comment by parkhuang** [comment]
您可以首先对比一下demo，然后使用Android Studio的Layout Inspector来查看你view的情况

**Comment by HystrixWong** [comment]
谢谢，已经解决！
