### ISSUE TITLE
【Android】-【4.6.1】：【建议给 语音/文字切换输入控件 暴露点击事件】

### ISSUE THREAD

**Issue by Yuanarcheannovice** [tencentyun/TIMSDK#537]
【Android】-【4.6.1】：【建议给 语音/文字切换输入控件 暴露点击事件】
【集成包】：TUIKIT
【当前现象】：   
    建议给
 /**
     * 语音/文字切换输入控件
     */
    protected ImageView mAudioInputSwitchButton;

暴露出点击事件，方便开发者控制，举个例子：点击发语音，需要认证.

**Comment by parkhuang** [comment]
感谢反馈，已经添加到需求池里。
