### ISSUE TITLE
【Android】-【4.6.1 && 4.5.111】- 群成员退群时，通过TIMGroupTipsElem的接口getChangedGroupMemberInfo()与getChangedUserInfo()拿到的Map都是空的，不包含退群用户的身份信息；但是通过接口getOpGroupMemberInfo()和getOpUserInfo()可以拿到退群人员的信息；不是很合理

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#540]
【当前现象】群成员退群后，通过TIMGroupTipsElem的接口getChangedGroupMemberInfo()与getChangedUserInfo()拿到的Map都是空的，不包含退群用户的身份信息；但是通过接口getOpGroupMemberInfo()和getOpUserInfo()可以拿到退群人员的信息。个人感觉不是很合理，因为跟退群同级别的加群、移出群、设置和取消管理员的操作，getChangedGroupMemberInfo()和getChangedUserInfo()都是正常返回结果的，建议修改一下。
【集成包】IMSDK
【测试机型】红米 Redmi 6
【之前版本是否有次问题】4.6.1 && 4.5.111都有这个问题
【有无日志和截图】无

**Comment by parkhuang** [comment]
感谢反馈，我们查一下

**Comment by vinsonswang** [comment]
带"changed"前缀的 代表是群成员的信息改变的
对于主动退群的操作，是通过"op"前缀的返回，代表是谁处理的
