### ISSUE TITLE
FetchToken failed,发语音图片失败

### ISSUE THREAD

**Issue by yuanshuainiuniu** [tencentyun/TIMSDK#546]
finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600003f44150 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <9483967F-D1E2-43F3-A410-1956E41AC4EB>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <9483967F-D1E2-43F3-A410-1956E41AC4EB>.<1>"
), NSLocalizedDescription=unsupported URL}
TIM: 2019-12-09 14:38:31.695/E/15676-5515231 /Msg       -cos_helper.cpp.422  operator()                             /FetchToken failed, url = https://yun.tim.qq.com/v4/im_cos_sign_svr/cos?sdkappid=1400247171&identifier=70&usersig=eJyrVgrxCdZLrSjILEpVsjIzMLEwMNABi5WlFilZKRnpGShB*MUp2YkFBZkpSlaGJgYGRibmhuaG
EJnMlNS8ksy0TLAGc7j6zHQgt6DYwzfEvDQ5N0I-PSC41CA3v6SizCWwwC2-MNigpDQw3Vvf06JE
OyfDy9UWqrEkMxfoFENTc1MLcyNLQ7NaAEsWMBY_, code = -1002, response = unsupported URL

**Comment by parkhuang** [comment]
是一致失败还是偶尔失败，失败的概率多大
