### ISSUE TITLE
【Android】-【4.6.1】：【聊天列表扩张问题】

### ISSUE THREAD

**Issue by allkiss** [tencentyun/TIMSDK#549]
【集成包】：TUIKIT
【当前现象】：a、列表中的头像无发设置默认头像；虽然ConversationIconView提供了setDefaultImageResId(int resId) ，可是无法调用；
                          b、列表中的头像没办法设置成圆形；（ios是可以的，这让Android开发者很背锅啊）
                          c、之定义会话列表的item；没法设置点击事件啊 ，啊，啊，啊。为什么不暴露出来，还这么自定义啊；
 switch (getItemViewType(position)) {
            case ConversationInfo.TYPE_CUSTOM:
                break;
            default:
                //设置点击和长按事件
                if (mOnItemClickListener != null) {
                    holder.itemView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            mOnItemClickListener.onItemClick(view, position, conversationInfo);
                        }
                    });
                }
                if (mOnItemLongClickListener != null) {
                    holder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
                        @Override
                        public boolean onLongClick(View view) {
                            mOnItemLongClickListener.OnItemLongClick(view, position, conversationInfo);
                            return true;
                        }
                    });
                }
                break;
        }

**Comment by parkhuang** [comment]
b在将要发布的4.6.50版本会增加圆角设置
a与c这两个需求已经收到，将会在后面的版本添加

**Comment by JingweiWang** [comment]
> b在将要发布的4.6.50版本会增加圆角设置
> a与c这两个需求已经收到，将会在后面的版本添加

请问下何时发布4.6.50 @parkhuang
