### ISSUE TITLE
【Android】-【4.6.1】：【Android Q 相册上传相册照片没有适配，提示缺少权限】

### ISSUE THREAD

**Issue by Wan7451** [tencentyun/TIMSDK#556]
【集成包】：TUIKIT
【当前现象】：提示 缺少权限
【机型】：小米 k20Pro
【之前版本有无此问题】：有
【有无日志或者截图】：暂无日志

**Comment by parkhuang** [comment]
您好，能截图或者小视频看一下吗，刚才我用demo可以正常发图片
