### ISSUE TITLE
im老是掉线问题

### ISSUE THREAD

**Issue by DoveBarnett** [tencentyun/TIMSDK#558]
【Android】-【4.5.111】：【动不动就掉线】
【集成包】：IMSDK
【当前现象】：有时候莫名其妙就掉线了，重点是下面这个设置
userConfig.setConnectionListener(new TIMConnListener() {
            @Override
            public void onConnected() {
                Log.i(tag, "onConnected");
            }

            @Override
            public void onDisconnected(int code, String desc) {
                Log.i(tag, "onDisconnected->错误码：" + code + ",原因：" + desc);
            }

            @Override
            public void onWifiNeedAuth(String name) {
                Log.i(tag, "onWifiNeedAuth");
            }
        });
其中的onDisconnected()方法有时候走，有时候不走的，有没有别的方法可以精准判断掉线呢？APP端也好做一些及时调整啊
【机型】：OPPOA5
【之前版本有无此问题】：一直都都是这样
【有无日志或者截图】：有日志

**Comment by parkhuang** [comment]
感谢反馈，这个是内部的链接状态，如果disconnect会自动重连，这个回调仅仅是通知，所以不必以此作为UI上的变化依据。

**Comment by DoveBarnett** [comment]
> 感谢反馈，这个是内部的链接状态，如果disconnect会自动重连，这个回调仅仅是通知，所以不必以此作为UI上的变化依据。

那，就是说这个内部的链接服务器状态，可能断开，然后disconnect又有可能不会自动重连，那我根据什么去手动重连呢？

**Comment by parkhuang** [comment]
> > 感谢反馈，这个是内部的链接状态，如果disconnect会自动重连，这个回调仅仅是通知，所以不必以此作为UI上的变化依据。
> 
> 那，就是说这个内部的链接服务器状态，可能断开，然后disconnect又有可能不会自动重连，那我根据什么去手动重连呢？

你的手动重连指的什么，sdk不需要主动重连

**Comment by DoveBarnett** [comment]
> > > 感谢反馈，这个是内部的链接状态，如果disconnect会自动重连，这个回调仅仅是通知，所以不必以此作为UI上的变化依据。
> > 
> > 
> > 那，就是说这个内部的链接服务器状态，可能断开，然后disconnect又有可能不会自动重连，那我根据什么去手动重连呢？
> 
> 你的手动重连指的什么，sdk不需要主动重连

重新去login啊，毕竟像你说的，内部的链接服务器状态断开又没有自动重连上你们的服务器，我不手动去重新login，能做些什么呢？

**Comment by parkhuang** [comment]
程序在活着的时候不需要重新login，只有第一次启动或者重启的时候才需要登录。
sdk网络变化会自动上线，不需要自己login的

**Comment by parkhuang** [comment]
举个例子，如果现在disconnect，你继续发消息，sdk内部会尝试连接网络、上线、发消息，对于app层来说这些都是黑盒也不需要关心的

**Comment by DoveBarnett** [comment]
> 举个例子，如果现在disconnect，你继续发消息，sdk内部会尝试连接网络、上线、发消息，对于app层来说这些都是黑盒也不需要关心的

我继续发消息，你们SDK内部会尝试连接你们IM的服务器，然后自己重新上线，将我发的消息发送到你们的IM服务器上，然后你们的IM服务器再将这个消息进行分发吗？

**Comment by parkhuang** [comment]
如果仅仅是onDisconnect，你可以完全不用关心，继续你的操作，发消息内部会重试，直到api的回调返回。

如果你发送消息失败了，肯定需要你根据错误的情况决定下一步的业务逻辑

**Comment by DoveBarnett** [comment]
> 如果仅仅是onDisconnect，你可以完全不用关心，继续你的操作，发消息内部会重试，直到api的回调返回。
> 
> 如果你发送消息失败了，肯定需要你根据错误的情况决定下一步的业务逻辑

理解了一些，就是说，我们可以不用关心login之后，内部跟服务器连接状态了，只需要关心发送消息到服务器的回调成功与否，然后根据这个结果做业务处理是吗？

**Comment by parkhuang** [comment]
> > 如果仅仅是onDisconnect，你可以完全不用关心，继续你的操作，发消息内部会重试，直到api的回调返回。
> > 如果你发送消息失败了，肯定需要你根据错误的情况决定下一步的业务逻辑
> 
> 理解了一些，就是说，我们可以不用关心login之后，内部跟服务器连接状态了，只需要关心发送消息到服务器的回调成功与否，然后根据这个结果做业务处理是吗？

对，就是这样。

**Comment by DoveBarnett** [comment]
> 如果仅仅是onDisconnect，你可以完全不用关心，继续你的操作，发消息内部会重试，直到api的回调返回。
> 
> 如果你发送消息失败了，肯定需要你根据错误的情况决定下一步的业务逻辑

那从发消息直到api的回调返回，这个时间一般是多久呢？是否可以针对这个时间做设置？

**Comment by parkhuang** [comment]
很快，一般取决于网络，绝大多数1s内就发送成功了

**Comment by DoveBarnett** [comment]
> 很快，一般取决于网络，绝大多数1s内就发送成功了

好的呢，万分感谢你的解答！

**Comment by parkhuang** [comment]
嗯嗯，感谢你的反馈
