### ISSUE TITLE
iOS 账号包含符号（邮箱地址）或者英文中包含qq字符，只能发送文字类型消息

### ISSUE THREAD

**Issue by OrangesChen** [tencentyun/TIMSDK#56]
账号包含符号（邮箱地址）或者英文中包含qq字符的账号名，无法发送语音图片等，只能发送文字。

**Comment by whalehe** [comment]
您好，发送文字、语音、图片等功能和账号包含什么字符没有关系，建议升级到最新版TUIKit试试。
