### ISSUE TITLE
【Android】-【4.6.1】：【通知栏显示问题】

### ISSUE THREAD

**Issue by allkiss** [tencentyun/TIMSDK#565]
【集成包】：TUIKIT
【当前现象】：a、接收到消息时，通知栏上显示的时id。希望在通知栏的标题处显示昵称。
                         b、接收到消息时，直接启动app，不通过点击通知栏打开app，通知栏不会直接消失。

**Comment by vinsonswang** [comment]
感谢反馈。
1、如果是程序被杀死的情况下，接收到的离线推送通知栏的标题对于C2C消息优先显示昵称，没有昵称则显示userID；对于群消息优先显示群名片，群名片为空则显示昵称，昵称为空则显示userID。
如果程序退到后台（没被杀死），这里弹的通知是app上层控制的，可以根据自己的需求弹通知。
2、打开app时通知栏显示与否可以在app上层根据需求清除，后续我们在Demo层也会加上示例代码。

**Comment by SmallCarp-Mao** [comment]
@allkiss 你好  你这个问题解决了么？ 为啥头像和名称都不会显示？

**Comment by allkiss** [comment]
> @allkiss 你好 你这个问题解决了么？ 为啥头像和名称都不会显示？

收到消息后自己实现通知栏
