### ISSUE TITLE
基于微信小程序sdk适配uniapp,nvue模式

### ISSUE THREAD

**Issue by jixuan0748qwer** [tencentyun/TIMSDK#566]
目前使用的是小程序sdk版本号是2.3.2.能否帮忙适配一下基于uniapp框架下的nvue模式

**Comment by jixuan0748qwer** [comment]
Duplicate of #
![微信截图_20191224102049](https://user-images.githubusercontent.com/56328367/71389366-170ce800-2637-11ea-81ec-3360ad0eaa12.png)
这是运行报错图

**Comment by kinm** [comment]
> Duplicate of #
> ![微信截图_20191224102049](https://user-images.githubusercontent.com/56328367/71389366-170ce800-2637-11ea-81ec-3360ad0eaa12.png)
> 这是运行报错图

如果没看错，这里应该是你用错了SDK，JSSDK和WXSDK是分开的，JSSDK的Demo中才有调用window...你在chrome环境下应该可以跑！

**Comment by yangq1990** [comment]
后续会适配uniapp electron
