### ISSUE TITLE
【小程序】-【2.3.2】: Taro集成2.3.2版本 监听不到 TIM.EVENT.SDK_READY,已经配置到compile中 

### ISSUE THREAD

**Issue by tangshuoup** [tencentyun/TIMSDK#568]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/25792077/71407970-8c98a880-2677-11ea-84b0-7a324c9901ce.png">
<img width="321" alt="image" src="https://user-images.githubusercontent.com/25792077/71407982-9ae6c480-2677-11ea-990e-f2205c0b7a62.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/25792077/71408000-a639f000-2677-11ea-9175-40cfd136ca5c.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/25792077/71408244-6e7f7800-2678-11ea-9f26-0d222fcb89a9.png">

**Comment by tangshuoup** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/25792077/71408275-8e16a080-2678-11ea-90d5-32033c81b9fa.png">

**Comment by tangshuoup** [comment]
问题已解决！taro版本问题，1.3.29之上版本都有问题

**Comment by qiangqiang93** [comment]
其实也不是taro，我用TIM 2.3.1，是可以的
