### ISSUE TITLE
【微信小程序】-【tim-wx-sdk@2.3.2】：【已在群组中接收不到消息】

### ISSUE THREAD

**Issue by cyhwinner** [tencentyun/TIMSDK#570]
当我加入群组成功的时候，下面的回调是可以被调用的。但是当我因为异常情况（断网退出直播间）未退出群组的时候，再加入这个群组时候，已经存在这个群组的时候（这是没错的），但是就是导致下面回调就无法调用。也尝试过说已加入群组时，退出当前群组在进入 但是依旧无效，连退出当前群组的then回调也没被调用
```
this.data.tim.on(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived);

let onMessageReceived = function(event) {
    console.log(event.data[0])
};
```

**Comment by Rychou** [comment]
你好，问题在最新版本已经解决。请更新至最新版本。

**Comment by yangq1990** [comment]
v2.4.0 版本修复。[更新日志](https://cloud.tencent.com/document/product/269/38492)
