### ISSUE TITLE
【微信小程序】-【tim-wx-sdk@2.3.2】：【无法关闭消息监听】

### ISSUE THREAD

**Issue by crazyliuzc** [tencentyun/TIMSDK#572]
【微信小程序】-【2.3.2】：【通过tim.off无法关闭消息监听】
【当前现象】：在一个页面中依次调用开启监听tim.on和关闭监听tim.off，消息却一直都可以收到，代码如下
`let tim = TIM.create({SDKAppID: xxx});`
`tim.setLogLevel(1);`
`let onMessageReceived = function (event) {`
`	console.log('收到监听',event);`
`};`
`function monitor(){`
`	tim.on(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived, this);`
`	console.log('开始监听');`
`}`
`function unMonitor() {`
`	tim.off(TIM.EVENT.MESSAGE_RECEIVED, onMessageReceived);`
`	console.log('关闭监听');`
`}`
【之前版本有无此问题】：2.2.0测试也有这个问题，其它版本未测试

**Comment by SaxonGao-SZ** [comment]
2.4.0 版本已修正此问题。请更新后再试试？

**Comment by yangq1990** [comment]
v2.4.0 已修复，请升级版本。 [更新日志](https://cloud.tencent.com/document/product/269/38492)
