### ISSUE TITLE
【iOS】-【4.6.51】：[[TIMManager sharedInstance] unInit] crash

### ISSUE THREAD

**Issue by baiyidjp** [tencentyun/TIMSDK#575]
官方demo也crash，
swift代码 TIMManager.sharedInstance()?.unInit()
使用也是crash
![image](https://user-images.githubusercontent.com/12672573/71466865-d6120080-27fb-11ea-929b-057a9633d876.png)
4.6.8 版本没有问题，请修复下吧

**Comment by baiyidjp** [comment]
使用这个的目的是为了重新initsdk，不想让打印日志，而自带的UI库是打印日志的，很影响其他页面的调试，有没有其他办法直接修改这个SDKConfig的配置

**Comment by lynxzhang** [comment]
1，我这边没有复现这个 crash，麻烦把复现的代码贴下，另外把 crash 的完整堆栈信息贴下
2，正对您的需求，我们 TUIKit 可以把日志级别设置接口暴露出来，预计今天可以更新 TUIkit 库，您这边也可以关注下

**Comment by baiyidjp** [comment]
![image](https://user-images.githubusercontent.com/12672573/71500568-7e79a080-28a0-11ea-98cb-4bef116dfe47.png)
![image](https://user-images.githubusercontent.com/12672573/71500577-86d1db80-28a0-11ea-8e0c-51f7ab569baf.png)
大概就是这个过程，去掉 uninit就可以了

**Comment by lynxzhang** [comment]
感谢您的反馈，问题原因我们已经找到，今天会发版修复
