### ISSUE TITLE
- (NSArray<TIMConversation *>*)getConversationList;接口获取数据有误

### ISSUE THREAD

**Issue by JinghuangLiu** [tencentyun/TIMSDK#576]
【当前现象】：我账号有12个会话，但是登录后直接调用通过getConversationList获取的数据为一个空数组。
【集成包】：IMSDK
【机型】：如iPhone 11，iOS13
【之前版本有无此问题】：一直都有这个问题。
【有无日志或者描述、截图】：截图如下
<img width="849" alt="截屏2019-12-26下午4 29 12" src="https://user-images.githubusercontent.com/6930613/71468020-99e09f00-27ff-11ea-97b2-4fe2678f8a07.png">
【解决方法】类似-(int)getFriendList:(TIMFriendArraySucc)succ fail:(TIMFail)fail;这样。获取到数据后再给个回调。不然在IM SDK内部还没获取到数据时，我们用户就调用getConversationList去获取肯定会出问题。希望新增个接口，尽快发个新版出来。

**Comment by JinghuangLiu** [comment]
@lynxzhang @

**Comment by JinghuangLiu** [comment]
@parkhuang

**Comment by JinghuangLiu** [comment]
@lynxzhang

**Comment by baiyidjp** [comment]
我的解决方法是在登陆后调用的，这样就可以获取到了。我是为了获取到未读的总数，所以需要一个个的加起来。不知道可以帮你解决不

**Comment by JinghuangLiu** [comment]
> 我的解决方法是在登陆后调用的，这样就可以获取到了。我是为了获取到未读的总数，所以需要一个个的加起来。不知道可以帮你解决不

我也是登录后调用的。延迟一段时间后应该能获取到，但这种做法也可能出问题。

**Comment by baiyidjp** [comment]
我就是直接在登陆后调用 同步调用 目前没发现什么问题呢

**Comment by JinghuangLiu** [comment]
> 我就是直接在登陆后调用 同步调用 目前没发现什么问题呢

你们有用TIMRefreshListener这个监听吗？这个接口现在感觉刷新的频率比旧版本的高，又有一些问题。

**Comment by baiyidjp** [comment]
我直接用的demo的UI库

**Comment by JinghuangLiu** [comment]
@lynxzhang @parkhuang 麻烦看下

**Comment by lynxzhang** [comment]
1，getConversationList 拿的是本地的会话列表，如果程序是第一次安装，或则禁用了本地存储，登录后直接调用这个接口拿的数据是有可能为 nil 的。
2，SDK 在登录后会去自动同步服务器的会话列表，同步成功后会和本地会话列表做合并，然后通过 onRefresh 回调通知客户，这个时候再 getConversationList 就可以拿到最新的会话列表

**Comment by JinghuangLiu** [comment]
> onRefresh
我们以前为了确保肯定能获取到，就是在onRefresh做的。但是新版的onRefresh，调用的规则迷（比如启动时为什么要调用2次），onRefresh刷新频率高，导致相应的会话页面频繁刷新。

**Comment by JinghuangLiu** [comment]
> 1，getConversationList 拿的是本地的会话列表，如果程序是第一次安装，或则禁用了本地存储，登录后直接调用这个接口拿的数据是有可能为 nil 的。
> 2，SDK 在登录后会去自动同步服务器的会话列表，同步成功后会和本地会话列表做合并，然后通过 onRefresh 回调通知客户，这个时候再 getConversationList 就可以拿到最新的会话列表

我们以前为了确保肯定能获取到，就是在onRefresh做的。但是新版的onRefresh，调用的规则迷（比如启动时为什么要调用2次），onRefresh刷新频率高，导致相应的会话页面频繁刷新。

**Comment by lynxzhang** [comment]
> > 1，getConversationList 拿的是本地的会话列表，如果程序是第一次安装，或则禁用了本地存储，登录后直接调用这个接口拿的数据是有可能为 nil 的。
> > 2，SDK 在登录后会去自动同步服务器的会话列表，同步成功后会和本地会话列表做合并，然后通过 onRefresh 回调通知客户，这个时候再 getConversationList 就可以拿到最新的会话列表
> 
> 我们以前为了确保肯定能获取到，就是在onRefresh做的。但是新版SDK的onRefresh，调用的规则迷（比如登录后为什么要调用2次），onRefresh刷新频率高，导致相应的会话页面频繁刷新。也就是因为这个，才考虑做修改的。

onRefresh 的限频是 1s 最多一次的（1s 内如果多次触发，SDK 内部会做合并），这个最近几个版本一直是这样的，登录后回调两次也有可能的，如果会话太多，SDK 内部为了让 UI 层快速展示出来会话内容，会分页拉取服务器的会话列表数据（一次 100 条），拉取完一次就会给上层抛一次更新，会话刷新的原因很多，包括但不限于：
 1. 发消息（会话的 lastmsg 出现变化，会话排序也出现变化）
 2. 收到消息（会话的 lastmsg 出现变化，未读数出现变化，排序也出现变化)
 3. 删除消息（会话的 lastmsg 可能出现变化）
 4. 撤回消息（会话的 lastmsg 可能出现变化）
 5. 设置已读（会话的未读数出现变化）
 6. 登录后同步服务器未读消息 （会话 lastmsg，未读数，排序出现变化）
