### ISSUE TITLE
JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by HMY314** [tencentyun/TIMSDK#58]
频繁进出聊天界面，一会儿就有崩溃
![image](https://user-images.githubusercontent.com/11188841/54926342-154cb180-4f4b-11e9-9f58-b6bb5d0ddd77.png)

**Comment by HMY314** [comment]
A/art: art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)
    art/runtime/indirect_reference_table.cc:132] local reference table dump:
    art/runtime/indirect_reference_table.cc:132]   Last 10 entries (of 509):
    art/runtime/indirect_reference_table.cc:132]       508: 0x12c7ca60 java.lang.String "@TGS#2OZ4DAYFB"
    art/runtime/indirect_reference_table.cc:132]       507: 0x1353bb20 byte[] (395 elements)
    art/runtime/indirect_reference_table.cc:132]       506: 0x12c81628 com.tencent.imsdk.TIMGroupMemberInfo
    art/runtime/indirect_reference_table.cc:132]       505: 0x12c6c430 com.tencent.imsdk.TIMGroupMemberInfo
    art/runtime/indirect_reference_table.cc:132]       504: 0x131cece8 com.tencent.imsdk.TIMGroupMemberInfo
    art/runtime/indirect_reference_table.cc:132]       503: 0x131ced30 com.tencent.imsdk.TIMGroupMemberInfo
    art/runtime/indirect_reference_table.cc:132]       502: 0x12cf3b08 java.util.ArrayList
    art/runtime/indirect_reference_table.cc:132]       501: 0x136ca4a0 byte[] (397 elements)
    art/runtime/indirect_reference_table.cc:132]       500: 0x131cee50 com.tencent.imsdk.TIMGroupMemberInfo
    art/runtime/indirect_reference_table.cc:132]       499: 0x131cee98 com.tencent.imsdk.TIMGroupMemberInfo
    art/runtime/indirect_reference_table.cc:132]   Summary:
    art/runtime/indirect_reference_table.cc:132]       310 of com.tencent.imsdk.TIMGroupMemberInfo (310 unique instances)
    art/runtime/indirect_reference_table.cc:132]         1 of java.lang.String
    art/runtime/indirect_reference_table.cc:132]         1 of java.util.ArrayList
    art/runtime/indirect_reference_table.cc:132]         8 of byte[] (4 elements) (8 unique instances)
    art/runtime/indirect_reference_table.cc:132]         2 of byte[] (16 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:132]         4 of byte[] (104 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:132]         4 of byte[] (105 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:132]         1 of byte[] (106 elements)
    art/runtime/indirect_reference_table.cc:132]         4 of byte[] (108 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:132]        27 of byte[] (198 elements) (27 unique instances)
    art/runtime/indirect_reference_table.cc:132]        24 of byte[] (216 elements) (24 unique instances)
    art/runtime/indirect_reference_table.cc:132]        63 of byte[] (256 elements) (63 unique instances)
    art/runtime/indirect_reference_table.cc:132]        19 of byte[] (395 elements) (19 unique instances)
    art/runtime/indirect_reference_table.cc:132]        38 of byte[] (397 elements) (38 unique instances)
    art/runtime/indirect_reference_table.cc:132]         2 of java.lang.Class (2 unique instances)
    art/runtime/indirect_reference_table.cc:132]         1 of android.database.sqlite.SQLiteDatabase

**Comment by lynxzhang** [comment]
感谢您的反馈，我们先复现下，如果有问题，会在下个版本修复

**Comment by vinsonswang** [comment]
4.2.2版本已经修复

**Comment by lynxzhang** [comment]
您好，这个问题再4.2.2的版本已经优化，麻烦更新新版本试下，如果还有问题，欢迎再反馈

**Comment by HMY314** [comment]
抱歉，就是用的4.2.2版本

**Comment by lynxzhang** [comment]
这个问题后续又进行了优化，麻烦更新4.2.52版本
