### ISSUE TITLE
【Android】-【TIMSDK】：变更群主以后，新群主昵称没有带回，只有账户id

### ISSUE THREAD

**Issue by crazywenza** [tencentyun/TIMSDK#580]
web后台管理变更群主以后，sdk收到群消息，类型是TIMElemType.GroupTips，其中这类TIMGroupTipsGroupInfoType.ModifyOwner消息，带回的信息只有新的群主的账户id，目前我无法拿到新群主的昵称。如果这里再去调用获取个人信息的接口异步处理的话，非常艰难。希望提供解决方案！
![image](https://user-images.githubusercontent.com/5308791/71622946-26ca9480-2c14-11ea-83f1-f9ce647a4087.png)

**Comment by parkhuang** [comment]
不好意思，现在只能自己再去获取
