### ISSUE TITLE
【Android】-【4.5.45】：【Crash】

### ISSUE THREAD

**Issue by Tien01** [tencentyun/TIMSDK#581]
【集成包】：TUIKIT
【当前现象】：APP启动崩溃。本地机型有限并未发现崩溃现象，在bugly后台发现崩溃日志。
【有无日志或者截图】：附上bugly日志

1 #00 pc 000000000032d168 /data/app/com.***.app-aQ7fa8KC-28U3RnDDcm48Q==/lib/arm64/libImSDK.so [arm64-v8a]
--
2 #01 pc 0000000000340f30 /data/app/com.***.app-aQ7fa8KC-28U3RnDDcm48Q==/lib/arm64/libImSDK.so [arm64-v8a]
3 #02 pc 0000000000345a38 /data/app/com.***.app-aQ7fa8KC-28U3RnDDcm48Q==/lib/arm64/libImSDK.so [arm64-v8a]
4 #03 pc 0000000000077e48 /system/lib64/libc.so (__pthread_start(void*)+36) [arm64-v8a]
5 #04 pc 000000000001fab4 /system/lib64/libc.so (__start_thread+68) [arm64-v8a]
6 java:
7 [Failed to get Java stack]

**Comment by vinsonswang** [comment]
新版本已解决
