### ISSUE TITLE
【Android】-【4.6.56】：【gradle 集成下载不下来】

### ISSUE THREAD

**Issue by wygkzqa** [tencentyun/TIMSDK#594]
ERROR: Failed to resolve: com.tencent.imsdk:tuikit:4.6.56，是啥情况

**Comment by parkhuang** [comment]
TUIKit的最新版本是4.6.51

**Comment by wygkzqa** [comment]
> TUIKit的最新版本是4.6.51

![image](https://user-images.githubusercontent.com/7590234/72231729-062d1200-35f8-11ea-8983-ce4c0d38c520.png)

这里写着 56？
