### ISSUE TITLE
Android SDK 线上频繁出现6012请求超时

### ISSUE THREAD

**Issue by HMY314** [tencentyun/TIMSDK#60]
sdk版本4.2.2

在使用一段时间后，TIM网络请求明显变慢，直到返回6012。但是我们自己的网络请求正常，打开网页也正常。

线上很多用户反馈这个问题，很影响用户体验，麻烦大家解决一下

**Comment by HMY314** [comment]
【链接】AndroidP(版本27以上)网络请求http限制
https://blog.csdn.net/mysimplelove/article/details/84063571

这个也配过了

**Comment by kakaandfigo** [comment]
我集成也出现类似情况。10次登录8次超时

**Comment by lynxzhang** [comment]
这边方便留个q号吗？我们拉群单独定位下这个问题

**Comment by lynxzhang** [comment]
周五会发新版本优化这个问题

**Comment by HMY314** [comment]
> 周五会发新版本优化这个问题

断网重连，网络切换后，有时会出现无法收到新消息，感觉长连接断了

**Comment by liukai2530533** [comment]
你配置没用  你配置是配置你这个app进程支持兼容http，但是tim-sdk它是一个单独的进程，你管不到它，需要tim-sdk的进程全面升级为https或者tim-sdk里面配置兼容http

**Comment by HMY314** [comment]
更新TIMSDK到4.2.10之后，线上有大量的登录TIM失败的错误信息。
错误码：6012 ；错误信息：tls exchange failed
