### ISSUE TITLE
【小程序】【taro框架】-【2.4.1】：【SDK_READY没触发】

### ISSUE THREAD

**Issue by lvimhere** [tencentyun/TIMSDK#602]
taro版本是2.0.1
SDK_READY注册的方法没触发。添加sdk路径到config/index/js 下的 mini.compile.exclude，使之不被编译（实际上taro文档里写的是默认不编译node_modules目录下的文件。我查看过，排不排除 sdk文件，打包之后的sdk代码是相同的。）
【集成包】：小程序sdk
【机型】：模拟器和iphone7p
【之前版本有无此问题】：未知

可能需要通过未混淆编译过的sdk代码打包成小程序代码之后，在打包后的代码里进行查看。

这里把代码拷贝到static目录了，打包之后的代码和通过node_modules里代码打包出来的代码是一样的。
![代码1](https://user-images.githubusercontent.com/18631024/72507778-7f8a6600-387f-11ea-8a33-ed172a160ee9.png)

希望能尽快查一下这个问题。辛苦～～
还需要配合的请尽管说

补充

点击登录按钮之前
![代码5](https://user-images.githubusercontent.com/18631024/72508390-8b2a5c80-3880-11ea-8670-bdfeb5d4cb32.png)

点击登录按钮之后
![代码3](https://user-images.githubusercontent.com/18631024/72508168-30910080-3880-11ea-9c09-ef45cb4db7f5.png)

注册事件
![代码4](https://user-images.githubusercontent.com/18631024/72508170-30910080-3880-11ea-9ebf-699ff7f4a810.png)

**Comment by lvimhere** [comment]
麻烦请尽快回复一下

**Comment by yangq1990** [comment]
WebIM v2.x 不需要被 Taro 编译。如果您通过 npm i 的方式集成了 WebIM，请手动将文件 node_modules/tim-js-sdk/tim-js-sdk.js 或 node_modules/tim-wx-sdk/tim-wx-sdk.js 拷贝到您项目的 src 目录下，并在配置文件中配置（更详细的请参考 编译配置详情）。 示例如下：

weapp: {
  compile: {
    exclude: ['src/tencent-webim/tim-wx-sdk.js']
  }
}

**Comment by lvimhere** [comment]
> WebIM v2.x 不需要被 Taro 编译。如果您通过 npm i 的方式集成了 WebIM，请手动将文件 node_modules/tim-js-sdk/tim-js-sdk.js 或 node_modules/tim-wx-sdk/tim-wx-sdk.js 拷贝到您项目的 src 目录下，并在配置文件中配置（更详细的请参考 编译配置详情）。 示例如下：
> 
> weapp: {
> compile: {
> exclude: ['src/tencent-webim/tim-wx-sdk.js']
> }
> }

朋友，我周五就试过了上述配置，还是不行。taro版本是2.0.1正式版

**Comment by Rychou** [comment]
你好，Taro@2.0.1 版本的配置和 1.x.x 配置有变更，具体参考 [Taro 官方文档配置](https://taro-docs.jd.com/taro/docs/config-detail.html#minicompile)

我这边刚刚测试验证通过，你也可以参考下：

![image](https://user-images.githubusercontent.com/25195267/72674294-f1e18d00-3aaf-11ea-9fd7-0f77b350f048.png)

![image](https://user-images.githubusercontent.com/25195267/72674306-06be2080-3ab0-11ea-92b3-8a57d4c3b2c8.png)

**Comment by lvimhere** [comment]
> 你好，Taro@2.0.1 版本的配置和 1.x.x 配置有变更，具体参考 [Taro 官方文档配置](https://taro-docs.jd.com/taro/docs/config-detail.html#minicompile)
> 
> 我这边刚刚测试验证通过，你也可以参考下：
> 
> ![image](https://user-images.githubusercontent.com/25195267/72674294-f1e18d00-3aaf-11ea-9fd7-0f77b350f048.png)
> 
> ![image](https://user-images.githubusercontent.com/25195267/72674306-06be2080-3ab0-11ea-92b3-8a57d4c3b2c8.png)

感谢，实际上我试过了您截图里的红框里的配置，我这边再研究研究是什么问题

**Comment by sunshine-annie** [comment]
@Rychou 你好我也遇到ready检测不到的问题，exclude配置了也还是那样的，你的代码能检测的到，能把你的demo给我借鉴一下吗？

**Comment by HeiShanLaoYao889** [comment]
如果是taro2.x 除了按照官网的配置以外，需要把支持nodeModules关了，"nodeModules": false,
