### ISSUE TITLE
【web】-【4.6.56】：【前端展开群成员无法展开】

### ISSUE THREAD

**Issue by G1thu7** [tencentyun/TIMSDK#606]
【当前现象】：群界面右侧展开群成员无法展开
【集成包】：IMSDK
【机型】：web
【之前版本有无此问题】：不确定
【有无日志或者描述、截图】：
![微信图片_20200127150453](https://user-images.githubusercontent.com/29441283/73155783-be89a880-4116-11ea-8253-2307e05438a8.png)

**Comment by Rychou** [comment]
@G1thu7 你好，没看明白你描述的问题，能具体描述下吗？
