### ISSUE TITLE
【Web】学生党想问WebDemo的问题

### ISSUE THREAD

**Issue by gx150204** [tencentyun/TIMSDK#607]
1.web demo /dist/index.html 用户是固定好的user0-29么？可不可以改变？
2.index.html页面的具体代码再哪里，把整个H5工程找了一遍没找到，是通过JS访问外网，然后回传显示的？
![1580895203(1)](https://user-images.githubusercontent.com/41406342/73829297-b4198e00-483d-11ea-9f53-6ca3f401a803.jpg)

**Comment by Rychou** [comment]
@gx150204 你好，
1. demo 为了方便演示，固定了30个账号，可以自行改变
2. demo 使用 Vue 开发，dist 目录下是打包压缩后的代码，源码在 src 目录。
