### ISSUE TITLE
注册  登录成功，发送消息可以，但接收不到消息呢，只能获取到本地的消息，聊天类型是群组的

### ISSUE THREAD

**Issue by aoaiin05** [tencentyun/TIMSDK#61]
注册  登录成功，发送消息可以，但接收不到消息呢，只能获取到本地的消息，聊天类型是群

**Comment by lynxzhang** [comment]
麻烦确认下 TIMManager 里面的 addMessageListener 有没有设置

**Comment by mrme2014** [comment]
已确认，在登陆之前调用的TIMManager#addMessageListener。始终无法接收到别人发的消息
