### ISSUE TITLE
【H5】-【2.4.1】【Android】-【4.6.56】H5与Android之间的视频通话不能互通

### ISSUE THREAD

**Issue by realphoenix** [tencentyun/TIMSDK#613]
【当前现象】：
1. H5发起视频呼叫，Android可以收到视频通话请求：
1）Android应答后，会打开手机的摄像头，看到自己摄像头拍摄的景象，但是看不到H5的。
2）H5始终显示“正在呼叫XX中”
2.Android发起视频呼叫，H5在消息窗口只收到一个[自定义消息]，该消息不能点击，无法应答。
见下面截图
![IMG_20200213_103600](https://user-images.githubusercontent.com/325735/74397490-c4d68f00-4e4f-11ea-813e-5478d617ddb0.jpg)
按官方文档，升级到最新版本，视频通话是互通的。有什么地方需要配置吗？

【H5】：SDK版本2.4.1
【浏览器版本】Chrome 81.0.4021.2，Safari 12.1
【Android】：SDK版本4.6.56
【机型】：华为Honor 9X
【之前版本有无此问题】：视频通话是H5新增的功能
【有无日志或者描述、截图】：见截图
![IMG_20200213_103600](https://user-images.githubusercontent.com/325735/74398450-98704200-4e52-11ea-8a6b-876e6cd36eea.jpg)

**Comment by QM36** [comment]
如果用Android与小程序进行以上步骤，您还会遇到同样问题吗（微信里面直接搜“云通信IM”找到小程序）
