### ISSUE TITLE
【WEBSKD】-【2.4.2】：getFriendList 等好友相关的无法正常使用

### ISSUE THREAD

**Issue by ccmyli** [tencentyun/TIMSDK#615]
【WEBSKD】-【2.4.2】：getFriendList 等好友相关的方法无法正常调用
【集成包】：TUIKIT
【当前现象】：
【机型】：CHROME
【之前版本有无此问题】 不清楚
【有无日志或者截图】：不清楚

**Comment by Rychou** [comment]
你好，WEB & 小程序端 IM SDK 目前尚未支持关系链相关功能，支持的功能接口以 [SDK 文档](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html) 为准
