### ISSUE TITLE
【WEBSKD】getGroupMemberList 无法获取到头像信息

### ISSUE THREAD

**Issue by ccmyli** [tencentyun/TIMSDK#616]
【WEBSKD】-【2.4.2】：getGroupMemberList 无法指定memberInfoFilter，这样就无法获取到用户头像等信息
【集成包】：TUIKIT
【当前现象】：
【机型】：CHROME
【之前版本有无此问题】 不清楚
【有无日志或者截图】：不清楚

**Comment by Rychou** [comment]
@ccmyli getGroupMemberList 不需要配置 memberInfoFilter，头像、昵称这些是固定会获取的。参考：[getGroupMemberList](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#getGroupMemberList)

**Comment by ccmyli** [comment]
我看到了，但是调用sdk的时候 并没有返回头像哦

**Comment by Rychou** [comment]
@ccmyli 若对应的用户没有设置过头像，是拿不到的
