### ISSUE TITLE
集成时tuikit Android Studio编译报错

### ISSUE THREAD

**Issue by huanping** [tencentyun/TIMSDK#618]
【Android】-【4.6.50】：【集成时tuikit Android Studio编译报错】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，报错，无法编译通过（描述你的问题现象，错误码、错误信息 以及具体请求或者接口）
【机型】：
【之前版本有无此问题】：
【有无日志或者截图】：Android dependency 'tv.danmaku.ijk.media:ijkplayer-java' has different version for the compile (0.7.9) and runtime (0.8.8) classpath. You should manually set the same version via DependencyResolution

**Comment by parkhuang** [comment]
您是源码集成吗，可以在build.gradle中去掉ijk的引用
![image](https://user-images.githubusercontent.com/14696119/76942389-9e1ce400-6938-11ea-8822-506e1d33d2fd.png)
