### ISSUE TITLE
小程序无法发送图片消息

### ISSUE THREAD

**Issue by kurisu994** [tencentyun/TIMSDK#623]
【小程序】-【Taro 1.3.37】：【发送图片消息无反应】
【集成包】：【tim-wx-sdk】【 cos-wx-sdk-v5】
【当前现象】：集成后文本消息正常，按照文档上发送图片消息发现sendMessage这个方法没有调用，
并且生成的message对象status为unsend
【有无日志或者截图】：
![20200220184754](https://www.lihuacats.com/upload/2020/2/20200220184754-1297bb6bace442b79a70eb69fd11c6b3.jpg)

**Comment by zzcandor** [comment]
Taro 2.0.4遇到同样问题。wx.$app.createImageMessage 正常，但是 wx.$app.sendMessage没有任何反应。已提交工单。

**Comment by zzcandor** [comment]
这边已经解决，方案如下
配置了 tim-wx-sdk，cos-wx-sdk-v5  不经过taro编译。
把从node_modules引入改为从项目引入，问题解决。

**Comment by kurisu994** [comment]
> 这边已经解决，方案如下
> 配置了 tim-wx-sdk，cos-wx-sdk-v5 不经过taro编译。
> 把从node_modules引入改为从项目引入。
> 可参考此文章：
> https://juejin.im/post/5e44c1fc6fb9a07cd614c788

感谢，虽然我已经解决了。
我是在weapp.compile.exclude里除了文档上说的加上了sdk的排除
`tim-wx-sdk.js`还加上了cos的排除
`
path.resolve(__dirname, '..', 'src/utils/cos-wx-sdk-v5'),
`
