### ISSUE TITLE
【web】-【^2.2.1】：【web登录后如何设置自己的IM昵称和头像等信息】

### ISSUE THREAD

**Issue by Chinegoodman** [tencentyun/TIMSDK#624]
【web】-【^2.2.1】：【web登录后如何设置自己的IM昵称和头像等信息】
实在是找不到参考文档或者js代码了

谢谢回复

**Comment by kurisu994** [comment]
https://cloud.tencent.com/document/product/269/37460#.E6.9B.B4.E6.96.B0.E4.B8.AA.E4.BA.BA.E8.B5.84.E6.96.99
文档有

**Comment by yangq1990** [comment]
请参考 [updateMyProfile](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#updateMyProfile)
