### ISSUE TITLE
【h5】-【0.5.23】：【npm包中php文件sonar扫描出语法错误】

### ISSUE THREAD

**Issue by warryy** [tencentyun/TIMSDK#640]
【建议】：npm 包中的 php 文件用户端是否用到了, 如果没有用到, 是否可以考虑删除掉?如果用到了, 是否可以将目前扫到的几个怀味道解决掉呢?
【当前现象】：cos-js-sdk-v5/csp/auth-json.php&cos-js-sdk-v5/server/qcloud-sts-sdk.php两个文件sonar扫描出怀味道
【集成包】：cos-js-sdk-v5
【机型】：无
【之前版本有无此问题】：无
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/22448081/76586505-fd838a00-651b-11ea-90c8-ed182a6b97f7.png)

**Comment by yangq1990** [comment]
腾讯云COS的问题，请在[这里](https://github.com/tencentyun/cos-js-sdk-v5/issues)反馈
