### ISSUE TITLE
(撤回消息api 改进优化) 强烈建议撤回api, 增加消息id和会话id 组合来撤回消息.

### ISSUE THREAD

**Issue by LoSenTrad** [tencentyun/TIMSDK#641]
(撤回消息api 改进优化) 强烈建议撤回api, 增加消息id和会话id 组合来撤回消息.
现在是通过TIMMessage消息体来撤回消息, 如果我们消息本地持久化的,就无法 保存TIMMessage这个对象.TIMMessage这个对象又没有开放实例化api出来. 
(本人使用2年多腾讯IM,希望贵团队可以采纳,一起打造优秀的IM产品)

可以参考融云 环信的撤回消息api 设计

/////////////////////////////////////////////////////////////////////////////////
//
//                      （四）撤回/删除消息
//
/////////////////////////////////////////////////////////////////////////////////
/// @name 撤回/删除消息相关接口
/// @{
/**
 *  4.1 撤回一条已发送的消息（消息发送后 ）
 *
 *  1. 消息撤回的有效时间为2分钟，即消息发出2分钟后不能再撤回。
 *  2. 仅支持 C2C 会话和 GROUP 会话中发送的消息，无法撤销 OnlineMessage，也无法撤销 AVChatRoom 和 BChatRoom 中的消息。
 *  3. 您需要在 TIMUserConfig -> TIMMessageRevokeListener 监听 onRevokeMessage() 消息撤回回调，
 *     如果消息撤回成功，消息的接收方会收到一次 onRevokeMessage:(TIMMessageLocator*) 回调，TIMMessageLocator 相当于一条消息的定位标志。
 *     您可以在已收到的历史消息里进行遍历，通过 TIMMessage 中的 respondsToLocator() 接口进行比对，以便定位到该条消息。
 *
 *  @param msg   被撤回的消息
 *  @param succ  成功时回调
 *  @param fail  失败时回调
 *
 *  @return 0：本次操作成功；1：本次操作失败
 */
- (int)revokeMessage:(TIMMessage*)msg succ:(TIMSucc)succ fail:(TIMFail)fail;

**Comment by parkhuang** [comment]
(撤回消息api 改进优化) 强烈建议撤回api, 增加消息id和会话id 组合来撤回消息.
现在是通过TIMMessage消息体来撤回消息, 如果我们消息本地持久化的,就无法 保存TIMMessage这个对象.TIMMessage这个对象又没有开放实例化api出来.
(本人使用2年多腾讯IM,希望贵团队可以采纳,一起打造优秀的IM产品)
--------------
没有看懂，是说撤回消息的api里面仅仅传消息id和会话id就好了吗？
本地消息保存通过getMessage/getLocalMessage也可以把TIMMessage的对象构造出来，然后通过对象进行撤回的

**Comment by LoSenTrad** [comment]
> ## (撤回消息api 改进优化) 强烈建议撤回api, 增加消息id和会话id 组合来撤回消息.
> 现在是通过TIMMessage消息体来撤回消息, 如果我们消息本地持久化的,就无法 保存TIMMessage这个对象.TIMMessage这个对象又没有开放实例化api出来.
> (本人使用2年多腾讯IM,希望贵团队可以采纳,一起打造优秀的IM产品)
> 没有看懂，是说撤回消息的api里面仅仅传消息id和会话id就好了吗？
> 本地消息保存通过getMessage/getLocalMessage也可以把TIMMessage的对象构造出来，然后通过对象进行撤回的

就是撤回api 可以不用TIMMessage对象, 可以用户会话id和消息id进行撤回, 我这边是自己做了本地数据持久化的, 由于需要TIMMessage才能撤回消息,我这边本地持久化不能储存TIMMessage这个对象,导致项目的撤回功能一直无法实现.

**Comment by parkhuang** [comment]
明白了，相当于你在其他地方记录了消息id和会话id，不好意思目前没有计划支持这种方式的撤回。

**Comment by LoSenTrad** [comment]
> 明白了，相当于你在其他地方记录了消息id和会话id，不好意思目前没有计划支持这种方式的撤回。

就不能学习学习一下 别人融云和环信的嘛?  不想把产品做好吗? 意见 都不接纳.真的是
