### ISSUE TITLE
求老版本SDK ，请问4.x版本能否和2.x相互通讯

### ISSUE THREAD

**Issue by maosheng1991** [tencentyun/TIMSDK#642]
你好，由于目前版本是比较老的版本2.x，想升级到最新的版本4.x，没有老的2.x的sdk。
1.请问哪里可以下载2.x的sdk ？
2.4.x版本和2.x版本是否相互通讯，发收消息。

**Comment by parkhuang** [comment]
1、2.x已经不维护了，现在已经不提供下载了
2、可以相互通讯
