### ISSUE TITLE
ios最新版本不能编译

### ISSUE THREAD

**Issue by CocoaZX** [tencentyun/TIMSDK#643]
mm_sizeToFitThan 报错

**Comment by CocoaZX** [comment]
![image](https://user-images.githubusercontent.com/28552051/76830733-d9e47a80-6860-11ea-9bb5-ede1de69be3d.png)

**Comment by Mengxiaowei** [comment]
您好，请问这个问题解决了么？

**Comment by Mengxiaowei** [comment]
@官方 来人解释一下呗

**Comment by EntityGJ** [comment]
pod   MM那个库、 或者 直接上demo里面 把部分报错的代码粘过来
