### ISSUE TITLE
【小程序】-【2.5.0】无法监听资料变更

### ISSUE THREAD

**Issue by XXig** [tencentyun/TIMSDK#644]
TIM.EVENT.PROFILE_UPDATED
这个事件无法监听到阿

**Comment by rsbella** [comment]
您好，为了更改好的定位您的问题，请详细描述下您的问题，也可以提供下相关的代码截图，或者参考下demo的实现，感谢您的支持。

**Comment by yangq1990** [comment]
> TIM.EVENT.PROFILE_UPDATED
> 这个事件无法监听到阿

感谢关注。仅好友资料变更可以收到通知，陌生人的资料变更收不到通知。想查询其他人的资料，请参考
[getUserProfile](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#getUserProfile)
