### ISSUE TITLE
【H5】-【2.4.1】：【dist目录下的的demo好友列表不显示】

### ISSUE THREAD

**Issue by y4658438** [tencentyun/TIMSDK#648]
直接打开dist目录下的index.html 登录后好友列表显示一直是暂无好友

**Comment by rsbella** [comment]
目前demo上是还没有关系链的，所以不显示好友列表，感谢您的支持

**Comment by yangq1990** [comment]
如上，关系链目前还未支持，感谢支持和关注

**Comment by liuchuanv** [comment]
是demo不支持关系链，还是 Web SDK 不支持？
对demo二次开发的话，是否可以实现好友列表？
