### ISSUE TITLE
【小程序】关于 70402 参数非法

### ISSUE THREAD

**Issue by monyee** [tencentyun/TIMSDK#650]
在使用joinGroup quiteGroup 或者 getGroupProfile 都会偶发下面的错误

"TIM GroupController.joinGroup error:Error: 参数非法，请检查必填字段是否填充，或者字段的填充是否满足协议要求。. groupID:@TGS#33FZWGIGC"
--

`const rs = await tim.joinGroup({ groupID: groupID, type: TIM.TYPES.GRP_AVCHATROOM });`

就拿joinGroup而言 入参基本就一个群id， 这个入参再我打印的日志中，发现已经是带的 类型为string

请问还有什么原因会触发此类异常？

**Comment by yangq1990** [comment]
你好，请问是否可以提供一些更为详细的日志

**Comment by monyee** [comment]
> 你好，请问是否可以提供一些更为详细的日志

没有了 调上面的函数 用户端就会偶发上面的异常

**Comment by handwill** [comment]
你好，这个问题有解决吗，我也出现了

**Comment by pengbs** [comment]
我也出现了，我发现调用logout后再调用这个入群的就是必现了
