### ISSUE TITLE
【小程序】-  群组为chatRoom的未读消息始终是0

### ISSUE THREAD

**Issue by ihupoo** [tencentyun/TIMSDK#652]
使用了接口 getConversationList  获取到了会话信息。C2C 的未读信息是正常的，但是群组类型为chatRoom 的未读消息始终为 0

**Comment by yangq1990** [comment]
聊天室（ChatRoom）和音视频聊天室（AVChatRoom）都不支持未读消息计数，详细请参考官网文档：
[群组消息管理差异](https://cloud.tencent.com/document/product/269/1502#.E6.B6.88.E6.81.AF.E7.AE.A1.E7.90.86.E5.B7.AE.E5.BC.82)
