### ISSUE TITLE
【Android】-【4.6.102】：【如何发一条不在界面上展示的信令消息？】

### ISSUE THREAD

**Issue by 13120241790** [tencentyun/TIMSDK#653]
【当前现象】：自定义消息 TIMCustomElem 消息，想让这个消息只在界面底下流转用做通知来用，实际上会走 MessageCustomHolder 最终界面会话列表和会话界面都展示"[不支持的自定义消息]" 还想请教如何做实现？TIMElemType 枚举也不支持继续扩展 谢谢感激不尽
【集成包】：TUIKit
【机型】：所有

**Comment by chengqw** [comment]
您好，请参照下这个问题和解决。
https://github.com/tencentyun/TIMSDK/issues/787
