### ISSUE TITLE
【Web】-【2.5.2】：【一些API使用上的不便】

### ISSUE THREAD

**Issue by marjune163** [tencentyun/TIMSDK#662]
- tim实例和React Component一起使用非常不便
	- tim未暴露是否已登陆状态，只能在Component内部用state维护
		- 一旦Component被外层Component重新创建，登陆状态丢失，只能重新登陆，这时tim报告已登陆，不能重复登陆，且不触发SDK_READY事件，导致Component内部后续流程无法继续（例如将发送消息按钮由disabled变为enabled）
		- 如果把登陆状态放在外部Component维护，破坏了封装性
		- 如果Component一上来创建时不管什么状态都先logout一次再login
			- 未登录时logout()调用造成console warning
			- 未登录时logout()返回undefined而不是Promise，增加了代码复杂性
			- 已登陆时调用logout()后等promise resolve再调用login()，而logout造成的SDK_NOT_READY和login的SDK_READY触发顺序无法保证（测试下来感觉是反的）
		- 如果Component销毁时logout()，创建时再login，感觉效率非常低下，但应该是正确的做法

- 很多操作有时返回Promise，有时返回undefined，非常不便
	- 例如getMessageList()在没有更多消息时返回undefined，感觉空数组Promise更合理
	- logout()调用在未登录时返回undefined，感觉rejected Promise更合理
	- login()的Promise resolve不代表login完成，必须等SDK_READY，非常不人性

**Comment by yangq1990** [comment]
感谢反馈，我们考虑下
