### ISSUE TITLE
h5 - 2.4.1: 使用uniapp创建的h5 应用，sdk 会识别成

### ISSUE THREAD

**Issue by Aeizzz** [tencentyun/TIMSDK#663]
【h5】-【2.4.1】：使用uniapp创建h5项目sdk运行会识别成微信小程序，并且加载微信的依赖
【集成包】：tim-js-sdk
【当前现象】：使用uniapp创建h5项目sdk运行会识别成微信小程序，并且加载微信的依赖
【机型】：
【之前版本有无此问题】：
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/18749645/78102930-22ce2e80-741e-11ea-86e0-bf0def6706ea.png)

![image](https://user-images.githubusercontent.com/18749645/78102945-2b266980-741e-11ea-8b0a-8bf8d4c1a24d.png)

**Comment by NeFx** [comment]
佟洋遇到了
