### ISSUE TITLE
小程序端demo输入框错乱

### ISSUE THREAD

**Issue by benny1213** [tencentyun/TIMSDK#668]
复现步骤：
1. 点击加号
2. 点击输入框弹出软键盘
3. 点击笑脸emoji图标
当输入框收下后出现如图问题
![image](https://user-images.githubusercontent.com/31154512/78759149-c0db6f00-79b1-11ea-8960-535c1c3b3724.png)

**Comment by benny1213** [comment]
安卓和苹果测试都会出现该问题

**Comment by chenximo** [comment]
谢谢，这边会尽快修复

**Comment by yangq1990** [comment]
感谢反馈，下一版本的demo会修复
