### ISSUE TITLE
如何关闭日志

### ISSUE THREAD

**Issue by Primary-Traxex** [tencentyun/TIMSDK#669]
【集成包】：TIMSDK
【当前现象】：前端日志会一直打印，大大影响了调试难度，可以控制不打印日志吗

**Comment by chenximo** [comment]
你好，可以通过设置tim.setLogLevel(4);   无日志级别，SDK 将不打印任何日志

详情可查看https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#setLogLevel
