### ISSUE TITLE
新版貌似黑名单功能没有呀

### ISSUE THREAD

**Issue by Gloud-Zhao** [tencentyun/TIMSDK#67]
即上次没有资料管理，这次新版又没有黑名单功能.另外TIMFriendshipManager的自定义字段以前传的bytes,现在直接传String 或int可以？

**Comment by lynxzhang** [comment]
ios 黑名单功能在4.2.52已经加上，Android 的会晚一个版本，下个版本加上。

**Comment by lynxzhang** [comment]
新名单功能已经加上，麻烦更新最新版本
