### ISSUE TITLE
TIM内的Mta数据统计上报与项目内Mta冲突

### ISSUE THREAD

**Issue by vinceok** [tencentyun/TIMSDK#671]
发现由于项目内引入了timjs，后续接入mta时会发现上报数据未统计，调试后发现是由于timjs内也有mta相关代码，导致了冲突，数据全上报至tim平台了。

请问该如何解决

**Comment by yangq1990** [comment]
webim确实用了mta，mta冲突的问题可以去官网查查资料，是否能通过appid或者别的手段进行区分。

**Comment by vinceok** [comment]
已经解决了，修改了mta的源代码，把全局变量改掉，只要不叫Mta就行了。
