### ISSUE TITLE
Anroid 4.7.1版本demo 内存泄漏

### ISSUE THREAD

**Issue by fengzhenggeqian** [tencentyun/TIMSDK#674]
【Android】-【4.7.1】：【运行demo时加入LeakCanary报内存泄漏】
【集成包】：TUIKIT
【当前现象】：Android Studio集成打开4.7.1版本的demo，聊天页面，点击下方+号，再退出聊天页面，LeakCanary报内存泄漏
【机型】：荣耀20s
![Screenshot_20200411_171437_com tencent qcloud tim tuikit](https://user-images.githubusercontent.com/17946327/79040028-2d57a780-7c18-11ea-9048-f511dba7936c.jpg)

**Comment by vinsonswang** [comment]
感谢反馈！
最新版本已经没有该类了，麻烦更新下最新版本再测试下
