### ISSUE TITLE
微信小程序更新用户头像和昵称在消息列表不更新

### ISSUE THREAD

**Issue by maplehsu** [tencentyun/TIMSDK#675]
【微信小程序】-【2.10.4】：【微信小程序更新用户头像和昵称在消息列表不更新】

发消息之前更新用户信息
![image](https://user-images.githubusercontent.com/4917754/79053248-80f4e000-7c6e-11ea-8dd8-3108f9f571bd.png)
发送
![image](https://user-images.githubusercontent.com/4917754/79053254-89e5b180-7c6e-11ea-90e5-758b585f81d7.png)
发送成功拉取消息列表
![image](https://user-images.githubusercontent.com/4917754/79053261-9ec24500-7c6e-11ea-92f1-734fe4852feb.png)
没有更新上，但是通过getMyProfile是可以查到已经更新了nick 和 avatar

**Comment by chenximo** [comment]
你好，Message 的 nick 和 avatar 属性，对C2C是不支持的，在群聊中，是指接收方的消息列表里边才有。

**Comment by yangq1990** [comment]
v2.6.0 [Message](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/Message.html) 增加 nick 和 avatar 属性，用于展示音视频聊天室（AVChatRoom）内消息发送者的昵称和头像地址（需提前调用 [updateMyProfile](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#updateMyProfile) 设置）。 C2C消息是不支持的，C2C消息获取消息的发送者nick和avatar，请使用 [getUserProfile](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#getUserProfile)
