### ISSUE TITLE
【小程序】：【小程序如何接入IM实现1对1单聊功能】

### ISSUE THREAD

**Issue by xiaoke369** [tencentyun/TIMSDK#68]
请问一下小程序如何接入IM实现1对1单聊功能

**Comment by renxiao1218** [comment]
> 请问一下小程序如何接入IM实现1对1单聊功能
同问  怎么实现？

**Comment by yangq1990** [comment]
hi，请参考以下内容：

新版小程序 im: 
https://github.com/tencentyun/TIMSDK/tree/master/WXMini
sdk文档：
https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/TIM.html
