### ISSUE TITLE
updateGroupProfile接口 修改avatar失败

### ISSUE THREAD

**Issue by ycy2077** [tencentyun/TIMSDK#680]
【小程序】-【v2.6.1】：【updateGroupProfile接口 修改avatar失败】
【当前现象】：聊天群群主修改通过updateGroupProfile接口 修改avatar失败,提示"参数非法，请根据错误描述检查请求是否正确"
【集成包】：IMSDK Taro
【机型】：小程序开发工具
![当前是群主身份](https://user-images.githubusercontent.com/15774890/79215645-75780380-7e7e-11ea-8106-6b9c61a99a67.png)
![updateGroupProfile调用代码](https://user-images.githubusercontent.com/15774890/79215527-4497ce80-7e7e-11ea-9d31-a530abe6a1cc.png)
![错误提示](https://user-images.githubusercontent.com/15774890/79215477-2df17780-7e7e-11ea-94bf-98bff74020e1.png)

**Comment by QM36** [comment]
怀疑你是的avatar是超过限制，只有在超出100字节时，才会提示‘参数非法’，参考文档：https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#updateGroupProfile
