### ISSUE TITLE
小程序 ，撤回出错

### ISSUE THREAD

**Issue by kiradea** [tencentyun/TIMSDK#688]
报错如下
![image](https://user-images.githubusercontent.com/12182992/79936390-eaa09580-8489-11ea-99f7-d864943d299b.png)

**Comment by chenximo** [comment]
你好，可以说明下具体情况吗？

**Comment by kiradea** [comment]
你好，我是使用wepy开发，消息列表使用wx:for渲染，然后wx:for-item="message",最后使用bindlongpress绑定message参数，但是显示如下，

![image](https://user-images.githubusercontent.com/12182992/80167736-b78a0d80-8613-11ea-8b14-307e26dafcfa.png)

**Comment by kiradea** [comment]
Hello ??

**Comment by kiradea** [comment]
> 你好，可以说明下具体情况吗？

你好，可以帮忙处理一下吗？
