### ISSUE TITLE
【Web 平台】请问 SDK Demo 是否会出 Angular 版本？

### ISSUE THREAD

**Issue by RockNHawk** [tencentyun/TIMSDK#691]
你好，
看到 Web SDK Demo 是 Vue 的，请问是否计划出 Angular 版本呢？谢谢！

**Comment by chenximo** [comment]
不好意思，暂时没有计划和排期，您可以接入我们的sdk自己开发，也会很快

**Comment by RockNHawk** [comment]
好的，谢谢！目前在参考 Vue 版本重新实现。

**Comment by lanxuexing** [comment]
Looking forward to the angular version of the Web SDK Demo
