### ISSUE TITLE
语音、图片接受时能添加自定义消息字段在里面么

### ISSUE THREAD

**Issue by shenbinxs** [tencentyun/TIMSDK#693]
请问我集成web端的IM，我想在收到的语音、图片、文件的同时，还需要隐式的获取自定义的内容，这个功能有么

**Comment by vinsonswang** [comment]
消息中暂时不支持漫游自定义字段

**Comment by zhongtiancai** [comment]
有同样的需求，TIMSDK虽然提供了自定义的方式，但如果使用了自定义，就要自己重新实现上传图片和视频的功能，建议加上一个原值返回的参数

**Comment by vinsonswang** [comment]
1、首先，消息中是没有自定义字段保存在服务器的

2、其次，Android 和 iOS 的消息是有本地自定义字段的设置接口的，仅限于本地，不存服务器，即卸载或者换手机后失效。
web 端由于对于存储空间的限制，也不支持本地设置自定义字段。

**Comment by zhongtiancai** [comment]
感谢解答，还有个问题是，我们是否可以通过图片消息发送的关键代码，自己获取cos的临时token，进行上传图片，再通过返回的地址进行自定义消息发送呢？这样就不用频繁请求企业服务端了

**Comment by vinsonswang** [comment]
SDK是不会暴露 cos 的 临时token 的。不过你可以去 cos 申请上传服务自己做上传，拿到下载的 url 再通过自定义消息发送
