### ISSUE TITLE
【需求】-【Android】：【离线推送的提示音：1按文件名，2厂商通道的自定义提示音】

### ISSUE THREAD

**Issue by hankersyan** [tencentyun/TIMSDK#695]
TIMMessageOfflinePushSettings.AndroidSettings.setSound(Uri.parse("android.resource://" + getPackageName() + "/" +R.raw.hualala));
1. 目前仅支持resource id，希望能支持文件名。因为增删资源后，resource id有可能变化，同一个文件在不同版本工程里的id有可能不一样。
2. 对于华为等厂商的设备，自定义提示音不生效，仍然是系统提示音。

**Comment by vinsonswang** [comment]
感谢反馈！
多数手机厂商不支持自定义声音，因此该需求暂时不支持。
