### ISSUE TITLE
【安卓】-【4.7.2】：【置顶、选择文件，拍照，相册】

### ISSUE THREAD

**Issue by Yuanarcheannovice** [tencentyun/TIMSDK#696]
【Android】-【4.7.2】：【置顶后，重新打开app失效、会话界面 功能块，3个无法使用】
【集成包】：TUIKIT
【机型】：如华为Mate 20
每次release 之前，能不能都检查一下，毕竟是收费的sdk，

**Comment by chengqw** [comment]
您好，感谢反馈，请在新版本关注下
