### ISSUE TITLE
【Web 平台】请问是否支持在一个 H5 App 中创建多个 TIM 实例？

### ISSUE THREAD

**Issue by RockNHawk** [tencentyun/TIMSDK#699]
Hi，

由于我们有在网页中同时登录多个账号的需求，因此需要在一个 App 中创建多个 TIM 实例，请问 SDK 能否支持？会不会有冲突？

谢谢！

**Comment by RockNHawk** [comment]
即是否可以 TIM.create 创建多个实例，并每个 tim 示例登录一个用户，并保持多个示例之间的通信独立？

	// 初始化 SDK 实例
	const tim = TIM.create({
	  SDKAppID: SDKAPPID,//window.genTestUserSig('').SDKAppID
	})


	// 无日志级别
	tim.setLogLevel(0);

	(<any>window).setLogLevel = tim.setLogLevel;

	// 注册 cos
	tim.registerPlugin({'cos-js-sdk':COSSDK});


登录

	tim.login({
		userID: imUserId,
		userSig: userSig 
	})

**Comment by yangq1990** [comment]
目前不支持，登录多个账号可以开启【Web 多实例登录】
