### ISSUE TITLE
能否在AVChatRoom这种类型添加获取历史消息功能。

### ISSUE THREAD

**Issue by 91geek** [tencentyun/TIMSDK#703]
直播间，通常新用户进入，都是首次进入直播间。之前没有参与聊天。这个时候用户消息列表就是空的。能否让首次进入的用户可以查阅之前用户之间的聊天信息。比如进入前50条消息，或者30条消息。

**Comment by chenximo** [comment]
好的，谢谢反馈，目前后台无法支持，我们暂时没有计划和排期，不好意思。
