### ISSUE TITLE
H5未读消息计数不会清零的问题

### ISSUE THREAD

**Issue by sinboun** [tencentyun/TIMSDK#710]
【当前现象】：在官方demo中会出现阅读某个回话后消息计数不会重置
【集成包】："tim-js-sdk": "^2.6.0",
【机型】： mac Chrome 版本 81.0.4044.138
【之前版本有无此问题】：位置
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/11026565/81778279-182aad00-9525-11ea-97f2-7e83c04792bc.png)
![image](https://user-images.githubusercontent.com/11026565/81778306-2d074080-9525-11ea-86d5-b4513cb22175.png)
在官方demo网站中也会出现类似问题

**Comment by chenximo** [comment]
你好，此问题已在2.6.3版本修复，你可以升级版本试下，谢谢反馈。
