### ISSUE TITLE
C2C 单聊会话如何加载自己的消息记录？

### ISSUE THREAD

**Issue by MoonandMind** [tencentyun/TIMSDK#714]
【Android】-【4.7.10】：【ChatLayout 无限加载聊天历史数据】
【集成包】：TUIKIT
【当前现象】：使用ChatLayout 打开一个单聊会话后，加载的消息记录有限。聊天消息通过回调服务保存到数据库里，Android 端从接口拿到所有消息记录，如何在ChatLayout中显示？

**Comment by chengqw** [comment]
您好，请参照下tuikit包内AbsChatLayout类getMessageLayout().setLoadMoreMessageHandler方法，拉取历史消息并显示。

**Comment by weinierfei** [comment]
@MoonandMind  哈喽  能分享下这个问题咋解决的么
