### ISSUE TITLE
[4.8.10] 没有自定义用户字段

### ISSUE THREAD

**Issue by yangzhuoming** [tencentyun/TIMSDK#717]
新的api接口不能设置自定义用户字段么？没找到相关方法

**Comment by lynxzhang** [comment]
您好，新版本 API 暂时还没有自定义字段的设置方法，我们正在开发一套更简洁，自定义性更强的自定义字段逻辑，后续版本会放开，敬请期待。

**Comment by lynxzhang** [comment]
您好，咨询一下，你这边是第一接入，还是从旧版 API 升级到 API 2.0 的呢 ？
