### ISSUE TITLE
【Android】-【4.8.10】发送自定义消息后，V2TIMAdvancedMsgListener 中的 onRecvNewMessage 没有触发调用

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#723]
在Activity A中注册了一个V2TIMAdvancedMsgListener，跳转到Activity B后，通过V2TIMManager.getMessageManager().createCustomMessage 生成一个自定义消息，成功发送出去后，Activity A 中注册的V2TIMAdvancedMsgListener的onRecvNewMessage没有触发。但是对应的V2TIMConversation 会话却更新了。（注：此条自定义消息是群消息）

**Comment by vinsonswang** [comment]
感谢反馈！
没有复现您的问题，建议您查下跳转到 ActivityB 后，有没有调用 removeAdvancedMsgListener 删除了 Activity A 中的消息监听
