### ISSUE TITLE
【Android】-【4.8.10】：【收不到群聊消息】

### ISSUE THREAD

**Issue by jackeyliu** [tencentyun/TIMSDK#724]
【Android】- 4.8.10以及其他
【集成包】：IMSDK
【当前现象】：聊天室里面（公司后台生成聊天室，加入聊天室也由公司后台处理），消息可以发出，别人可以收到，但是别人发的消息，自己收不到，此现象为偶现。
【机型】：没有具体机型，试了几款都是这种情况，荣耀 8x,荣耀10 青春版。。。
【之前版本有无此问题】：之前版本也有，试了
【有无日志或者截图】：暂无日志

**Comment by vinsonswang** [comment]
直播群（AVChatRoom）切换帐号登录后，加入同一个群会有此问题，4.8.50的版本修复了该问题，更新即可
