### ISSUE TITLE
集成 IM 实现直播带货时

### ISSUE THREAD

**Issue by SSStq1314** [tencentyun/TIMSDK#728]
在小程序管理后台发现有很多报错，

<img width="981" alt="截屏2020-05-21 上午11 33 34" src="https://user-images.githubusercontent.com/20391773/82520657-4af12880-9b57-11ea-9723-dfa1ade0e407.png">

<img width="953" alt="截屏2020-05-21 上午11 33 44" src="https://user-images.githubusercontent.com/20391773/82520674-50e70980-9b57-11ea-8b52-04ce7565f226.png">

<img width="982" alt="截屏2020-05-21 上午11 33 55" src="https://user-images.githubusercontent.com/20391773/82520681-547a9080-9b57-11ea-806d-de4f43ea7234.png">

请问这些错误信息，我应该怎么处理，

**Comment by SSStq1314** [comment]
<img width="981" alt="截屏2020-05-21 上午11 33 34" src="https://user-images.githubusercontent.com/20391773/82520741-7aa03080-9b57-11ea-9b01-13460370033e.png">


<img width="953" alt="截屏2020-05-21 上午11 33 44" src="https://user-images.githubusercontent.com/20391773/82520744-7c69f400-9b57-11ea-87a5-fc675229ca5c.png">

**Comment by hexingcheng** [comment]
请提供一下tls和tim的版本号
