### ISSUE TITLE
Android-SDK4.2.2缺失

### ISSUE THREAD

**Issue by liukai2530533** [tencentyun/TIMSDK#73]
如题com.tencent.imsdk.TIMFriendshipManager; 这个已经是有了
但是获取好友的最后消息之类的一些包还没有，类似：
com.tencent.imsdk.ext.sns.TIMFriendResult; 这个包下面都没有

有计划添加这方面的吗？

**Comment by lynxzhang** [comment]
关系链的逻辑正在开发，预计清明后1~2周时间会上线

**Comment by liukai2530533** [comment]
开发完了吗？import com.tencent.imsdk.ext.sns.TIMFriendStatus; 
我需要拓展包下面sns相关

**Comment by liukai2530533** [comment]
TIMFriendshipManagerExt 类似这种类，我需要获取好友关系链管理最后一条系统消息的回调

**Comment by lynxzhang** [comment]
您好，这个会在下个正式版本加上。
