### ISSUE TITLE
[iOS][4.8.10] 解决imsdk的消息回调收到多次

### ISSUE THREAD

**Issue by shenfengfeng** [tencentyun/TIMSDK#733]
使用的是 TUI
集成后发现有时候，有时候sdk的消息回调会收到多次
```
/**
 *  消息回调
 */
@protocol TIMMessageListener <NSObject>
@optional
/**
 *  新消息回调通知
 *
 *  @param msgs 新消息列表，TIMMessage 类型数组
 */
- (void)onNewMessage:(NSArray*)msgs;
@end
```
切换账号后，同一条消息会收到多次

---
场景：当切换账号的时候：退出 --> 退出imsdk --> 重新登录 --> 登录im
原因：每次账号登录成功后，都会调用下面的方法之一，而其内部实现中``[[TIMManager sharedInstance] addMessageListener:self];``，导致多次添加了listener，最终收到多次回调
```
/**
 *  设置sdkAppId，以便您能进一步接入IM SDK
 */
- (void)setupWithAppId:(NSInteger)sdkAppId;

/**
 *  设置sdkAppId，logLevel
 */
- (void)setupWithAppId:(NSInteger)sdkAppId logLevel:(TIMLogLevel)logLevel;
```
保证只初始化一次即可
有遇到同样问题的同学可以参考下

**Comment by 8517717164** [comment]
新版的sdk会多次添加了listener？这个你咋测出来的？

**Comment by shenfengfeng** [comment]
> 新版的sdk会多次添加了listener？这个你咋测出来的？

和版本无关，是我代码的问题，多次调用了 setupWithAppId，导致多次添加listener
