### ISSUE TITLE
能不能开源啊？

### ISSUE THREAD

**Issue by banricho** [tencentyun/TIMSDK#735]
微信小程序有体积限制，而 IM 因为其全局性无法被分包处理。
SDK 占用了大量的 main package 体积，而其中的很多功能对于项目是不需要的……

于是这个名为 TIMSDK 的仓库实则是 TIM-DEMO，而不是 SDK  源码仓库……

**Comment by banricho** [comment]
甚至还看到了 Promise / Map / WeakMap
甚至小程序版本里做了很多个 window 对象相关的操作

所以这个版本根本不是为小程序专门写的，包含了大量的不需要的代码

**Comment by yangq1990** [comment]
不好意思，TIM SDK 代码不开源。我们后续会尝试优化缩减些 SDK 的体积，目前  tim-wx.js 的大小是333KB，主包的限制是2M，业务侧能否针对主包代码做进一步的优化？SDK 的体积可预期的能减少一些，但不会很多，可能才几KB
