### ISSUE TITLE
Android 开发 TIMUI库Glide4.9.0报异常

### ISSUE THREAD

**Issue by zhoudodo** [tencentyun/TIMSDK#737]
No super method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.bocweb.fly.hengli-cESGIykoec8yXhMAWRc9pw==/split_lib_dependencies_apk.apk)
原因:
旧项目依赖低版本的Glide 我的项目Glide 有4.5.0和4.8.0
报错问题:
Glide官方issue 希望UI库能使用新的Glide避免错误
https://github.com/bumptech/glide/issues/3539

**Comment by vinsonswang** [comment]
新版本已解决
