### ISSUE TITLE
im的UI库支持androidx吗

### ISSUE THREAD

**Issue by 1885182** [tencentyun/TIMSDK#738]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

【平台】-【版本号】：【描述您的问题】
issue内容：

【当前现象】：如聊天界面点击xxx不显示xxx
【集成包】：IMSDK
【机型】：如iPhone 7 Plus
【之前版本有无此问题】：如4.8.10之前没有，4.8.10有
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
-------------------------完整的示例如下：-------------------------

【Android】-【4.4.479】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，报错，无法编译通过（描述你的问题现象，错误码、错误信息 以及具体请求或者接口）
【机型】：如华为Mate 20
【之前版本有无此问题】：TUIKIT 4.4.479版本之前没有，4.4.479有
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by vinsonswang** [comment]
感谢反馈！
新版本的 TUIKit 已经支持 AndroidX，请麻烦升级使用
