### ISSUE TITLE
【Android】-【4.8.10】 设置华为离线推送的Token时报错

### ISSUE THREAD

**Issue by xiezhenjian** [tencentyun/TIMSDK#739]
【当前现象】：ThirdPushTokenMgr.getInstance().setThirdPushToken(token);
                            ThirdPushTokenMgr.getInstance().setPushTokenToTIM();
                            日志报错
【集成包】：IMSDK
【机型】：华为 Mate 20 Pro
【之前版本有无此问题】：不清楚
【有无日志或者描述、截图】：有日志
I/IActivity: get huawei push token:  AL1mj76xlt6IVj31X85Eu-xRNC_4KAPnf0SL8yhwbayK5L135SpTF3IIEPV8PU_RjxcQYf2Crxszx5sLAjRbiwR-rUWkoqrOZII8xATV1cvwwyCPkpKCVrfaU757xwOzMA

I/imsdk: TIM: 27    2020-06-02 00:21:51.316/I/29226-29434     /IMSDK       -BaseManager.0                                              /setToken: token=10262:AL1mj76xlt6IVj31X85Eu-xRNC_4KAPnf0SL8yhwbayK5L135SpTF3IIEPV8PU_RjxcQYf2Crxszx5sLAjRbiwR-rUWkoqrOZII8xATV1cvwwyCPkpKCVrfaU757xwOzMA:2001
    TIM: 27    2020-06-02 00:21:51.316/I/29226-29434     /Common      -imcore_manager.cpp.439  SetToken                           /SetToken

E/imsdk: TIM: 28    2020-06-02 00:21:51.364/E/29226-29399     /Network     -ssodata.cpp.189  Parse                                     /sso retcode: -10005
    TIM: 29    2020-06-02 00:21:51.364/E/29226-29399     /Common      -imcore_manager_task.cpp.85  Decode                         /set token|decode|code:-10005|desc:
    TIM: 30    2020-06-02 00:21:51.364/E/29226-29399     /IMSDK       -BaseManager.0                                              /setToken failed, code -10005|descr

**Comment by vinsonswang** [comment]
设置离线推送的 token 需要在登录之后调用，否则会报错
