### ISSUE TITLE
【Android】-【4.4.479】：【偶发性Native层崩溃libImSDK.so】

### ISSUE THREAD

**Issue by g-vc** [tencentyun/TIMSDK#740]
【集成包】：IMSDK
【当前现象】：bugly上报的崩溃，绝大部分为7.1系统，偶发性问题，自测在hht7b上没有复现，bugly上报的描述#10 pc 001f7e2f /data/app/com.sfexpress.sfim-1/lib/arm/libImSDK.so [armeabi-v7a]
【机型】：HHT7B（ 7.1.1）、魅族 M6 NOTE（7.1.2）、小米 MI 8 SE（9）
【之前版本有无此问题】：没有使用老版本
【有无日志或者截图】：有（bugly上报的日志），小米 MI 8 SE（9）

1 #00 pc 0001ceb2 /system/lib/libc.so (abort+61) [armeabi-v7a]
--
2 #01 pc 0034bc0f /system/lib/libart.so (art::Runtime::Abort(char const*)+798) [armeabi-v7a]
3 #02 pc 000071c7 /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+502) [armeabi-v7a]
4 #03 pc 0022a80f /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1246) [armeabi-v7a]
5 #04 pc 001f7e2f /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
6 #05 pc 001f7d99 /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
7 #06 pc 000983d5 /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
8 #07 pc 000982f7 /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
9 #08 pc 00116bdf /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
10 #09 pc 001e6faf /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
11 #10 pc 001e1e61 /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
12 #11 pc 001e27e1 /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
13 #12 pc 001fadeb /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
14 #13 pc 001fd96f /data/app/com.sfexpress.sfim-_wYitq2wrOve5Vup1X_xCw==/lib/arm/libImSDK.so [armeabi-v7a]
15 #14 pc 00063e05 /system/lib/libc.so (__pthread_start(void*)+22) [armeabi-v7a]
16 #15 pc 0001e0a5 /system/lib/libc.so (__start_thread+22) [armeabi-v7a]
17 java:
18 [Failed to get Java stack]

**Comment by LucasDevelop** [comment]
解决了吗，老铁

**Comment by vinsonswang** [comment]
感谢反馈！
新版本已解决
