### ISSUE TITLE
最新tuikit4.7.10 没有集成最新imsdk  无V2TIMMessageManager  

### ISSUE THREAD

**Issue by Superingxz** [tencentyun/TIMSDK#741]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

【平台】-【版本号】：【描述您的问题】
issue内容：

【当前现象】：如聊天界面点击xxx不显示xxx
【集成包】：tuikit
【机型】：如华为VTR-AL00
【之前版本有无此问题】：如4.8.10之前没有，4.8.10有
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
-------------------------完整的示例如下：-------------------------

【Android】-【4.7.10】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，没有集成最新的imsdk 4.8.10 旧版本的4.7.10已读回执无效
【机型】：如华为VTR-AL00
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by vinsonswang** [comment]
4.8.50 的tuikit版本已更新 API2.0 接口的调用
