### ISSUE TITLE
是否以后都需要使用 V2TIM

### ISSUE THREAD

**Issue by XavierLost** [tencentyun/TIMSDK#744]
看里面说是高级消息,和老版本有什么区别吗?

**Comment by XavierLost** [comment]
并且demo并没有更新最新TIM SDK 2.0 版的接口 的使用

**Comment by XavierLost** [comment]
多个管理员同时修改成员资料,传入V2TIMGroupMemberFullInfo是否会和前一个管理员冲突(需要每次修改前重新获取这位成员的信息??) - (void)setGroupMemberInfo:(NSString*)groupID info:(V2TIMGroupMemberFullInfo *)info succ:(V2TIMSucc)succ fail:(V2TIMFail)fail

**Comment by vinsonswang** [comment]
API2.0 的接口主要是给新客户接入使用的，如果您的项目已经集成了旧版的接口，建议不要更换了。

**Comment by vinsonswang** [comment]
服务器以最后一个管理员修改的为准
