### ISSUE TITLE
【iOS】-【4.8.10】：【V2TIM 是否可靠】

### ISSUE THREAD

**Issue by auqarius** [tencentyun/TIMSDK#745]
【当前现象】：

V2 版本发送消息后，对方可以收到，对方发送消息后，本机也可以收到。但是使用获取会话方法，双方都无法获取会话。
（注意：以上流程都是在 V2 环境下。）

而且使用 TIM 获取会话也无法获取。使用 TIM 就发送消息没有问题，TIM 是手动创建会话，V2TIM 是自动创建会话，这说明 V2 的发送消息其实并没有创建会话，或者说在某些情况下无法创建。

文档都在推 V2TIM，而 Demo 和对接处理问题的人员都在用 TIM，处理问题成本也非常高，三天一个问题无法解决，我们目前已经计划使用 TIM 而不是 V2TIM 了。

**请问目前 V2TIM 是否真实可靠？**

【集成包】：
IMSDK
【机型】：
任意
【之前版本有无此问题】：
未知
【有无日志或者描述、截图】：

**Comment by CoderAFI** [comment]
为什么出个 V2TIM？

**Comment by JingweiWang** [comment]
个人觉得不可靠 而且文档不完善 没有demo

**Comment by XavierLost** [comment]
目前只有两种会话类型(无系统类型),自定义字段没有

**Comment by auqarius** [comment]
【问题已解决】

我们通过工单系统得到了反馈，然后对代码进行了研究，解决了这个问题。

这里是我们的调用问题，但也是文档中未写明的会话创建规则：

1. 发送自定义消息的时候，不会创建会话。
2. 发送非自定义消息的时候，_onlineUserOnly_ 字段传递为 true 的时候，也不会创建会话。

我们最早是使用自定义消息测试，_onlineUserOnly_ 设置的是 true。发现无法创建会话，设置成 false，依然无法创建，因此我们认为这个字段应该和创建会话没有关系。
后来又用 Text 类型消息测试，_onlineUserOnly_ 就设置为 true 了，却依然无法创建会话。因此造就了这个这个困扰人的问题。

**我们建议：

V2 版本不需要调用方创建会话，发送消息后会自动创建会话，那么创建会话的条件和契机应该在文档中体现出来。**

**Comment by auqarius** [comment]
希望开发组积极优化并细化文档，还有 V2 版本的 Demo也希望能早日发布。
