### ISSUE TITLE
ios集成IMSDK部分机型闪退

### ISSUE THREAD

**Issue by joserphlin** [tencentyun/TIMSDK#746]
主要在iPhone 8 ，ios 13.4.1 机型上出现了闪退，其他机型部分也有此问题
![2EEDDBB6-C9A2-47B7-A6EC-6518FDF5BE2E](https://user-images.githubusercontent.com/19528473/83988566-334ada00-a976-11ea-8066-d527994ddef0.png)
![WechatIMG92](https://user-images.githubusercontent.com/19528473/83988490-f54db600-a975-11ea-8813-47ff62722e6a.jpeg)

**Comment by parkhuang** [comment]
这个问题已经fix，请使用最新版本4.9.1验证
