### ISSUE TITLE
timsdk自带日期类的bug！！

### ISSUE THREAD

**Issue by yaoxin2017** [tencentyun/TIMSDK#75]
位置：https://github.com/tencentyun/TIMSDK/blob/master/Android/tuikit/src/main/java/com/tencent/qcloud/uikit/common/utils/DateTimeUtil.java

bug1：这句周日应该是1，不是0
                if (msgWeek == currentWeek && msgDayInWeek != 0) {}
bug2：不同年份依然会进入该else分支内
 //不同周显示具体月，日
                else {
                    msgTimeStr = calendar.get(Calendar.MONTH) + "月" + calendar.get(Calendar.DAY_OF_MONTH) + "日" + msgTimeStr + " ";
                }

**Comment by yaoxin2017** [comment]
bug3：
calendar.get(Calendar.MONTH) + "月"

我用了这个工具类，你能理解2019-3-29变成2019-2-29的尴尬吗？29 啊

**Comment by yaoxin2017** [comment]
sdk bug太多，能否用心去做

**Comment by vinsonswang** [comment]
感谢反馈，已经修复
