### ISSUE TITLE
【iOS】-【4.8.10】Swift 配置 V2TIMSDKConfig 问题

### ISSUE THREAD

**Issue by imzark** [tencentyun/TIMSDK#756]
【当前现象】：Swift 使用 `V2TIMSDKConfig` 初始化 SDK 时，配置 `logLevel` 的字段还是老版本的字段，无法使用 V2 开头的 ENUM。并且不知道如何单独关闭控制台输出，只能设置 `sdkConfig = .LOG_NONE` 关闭所有日志。
【集成包】：IMSDK
【Language】Swift5

**Comment by lynxzhang** [comment]
1，麻烦更新 4.8.50 的 TUIkit，全面支持了 V2 接口。

**Comment by lynxzhang** [comment]
2，log 级别决定了 IM 的控制台输出内容，这个只能通过设置 log 级别控制。
