### ISSUE TITLE
【iOS】-【4.8.10】V2 SDK 中不能直接拿到图片消息中的 url 了吗？

### ISSUE THREAD

**Issue by imzark** [tencentyun/TIMSDK#757]
【当前现象】：V2 版本 SDK 图片消息 `imageElem`，为何不再暴露图片的 url，让开发者可以直接通过第三方库下载图片并管理缓存。现在只能通过 SDK 提供的接口下载图片？
【集成包】：IMSDK

**Comment by SnowLittleStone** [comment]
应该暴露出来，否则这样不利于集成，增加回调难度

**Comment by lynxzhang** [comment]
您好，感谢反馈，我们下个版本优化下
