### ISSUE TITLE
TIMConversation 没有搜索历史消息

### ISSUE THREAD

**Issue by XavierLost** [tencentyun/TIMSDK#758]
issue标题： TIMConversation 没有搜索历史消息接口

【平台】-【版本号】：【描述您的问题】
issue内容：
  是否能提供搜索历史消息接口
【当前现象】：TIMConversation 没有搜索历史消息接口
【集成包】：IMSDK
【机型】： iPhone 
【之前版本有无此问题】： 
【有无日志或者描述、截图】：

**Comment by chenximo** [comment]
你好，
![image](https://user-images.githubusercontent.com/37072197/84473888-6bc31e80-acbc-11ea-8ce5-298efa19e905.png)，支持历史消息的群，可以通过getConversationList接口来获取历史消息

**Comment by XavierLost** [comment]
但是搜索特定的消息需要通过getConversationList全部加载出来才能搜索

**Comment by vinsonswang** [comment]
感谢反馈！暂时没有搜索历史消息的功能。
