### ISSUE TITLE
android-4.8.10-无法监听到群成员的进群和退群消息

### ISSUE THREAD

**Issue by qianmang2** [tencentyun/TIMSDK#760]
【当前现象】：无法监听到群成员的进群和退群消息，能监听到onReceiveRESTCustomData()和onGroupInfoChanged()收到消息.
【集成包】：IMSDK
【之前版本有无此问题】：在4.5.45版本上没有此问题
【有无日志或者截图】：暂无日志

**Comment by vinsonswang** [comment]
感谢反馈，今天发布的4.8.50版本解决了 API2.0接口 AVChatRoom 的进出群通知回调问题，请更新使用
