### ISSUE TITLE
发送视频就只支持mp4吗？

### ISSUE THREAD

**Issue by lidiewebgo** [tencentyun/TIMSDK#761]
web移动端要调用发送视频这个接口 可是ios苹果手机拍出来的视频是mov格式 然后一直发送失败 请问这个只支持mp4格式 不支持其他格式了吗？如果支持在哪里设置？

**Comment by vinsonswang** [comment]
mp4的兼容性相对比较好，可以在不同的平台播放。iOS的TUIKit源码里是从相册里取视频到App里时指定为了mp4格式，然后再发送，可以参考下。
