### ISSUE TITLE
【ios】-4.8.10：【集成后报很多崩溃】

### ISSUE THREAD

**Issue by tjjcode** [tencentyun/TIMSDK#765]
【当前现象】：查bugly日志显示用户出现此崩溃
【集成包】：IMSDK、TXLiteAVSDK_Professional
【机型】：iPhone 7 Plus、11、8p、xr、xs Max
【系统】：iOS 12.0.1、13.3.1、13.4.1、13.5
【之前版本有无此问题】：之前版本也有此问题
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/9263508/85244662-ec7dd980-b477-11ea-827d-96dc2cf2ef26.png)

**Comment by lynxzhang** [comment]
预计下个版本会优化这个问题，版本预计 7 月底发布，欢迎关注。

**Comment by lynxzhang** [comment]
4.9.1 版本优化了这块，麻烦升级下
