### ISSUE TITLE
Swift 兼容

### ISSUE THREAD

**Issue by wxlpp** [tencentyun/TIMSDK#766]
issue标题：Swift 兼容

【平台】-无平台相关性
issue内容：
能不能考虑下Swift用户，OC 的nullable nonnull能否用起来。目前一转Swift全是！强解包。稍不注意可能就造成Crash，参考下同系的QMUIKit吧。

【集成包】：IMSDK
【机型】：无机型相关
【之前版本有无此问题】：无版本相关

**Comment by rakuyoMo** [comment]
十分赞同！期望能加入相关功能

**Comment by lynxzhang** [comment]
您好，感谢您的反馈，Swift 的客户越来越多，这块我们已经做了规划，预计下个版本优化。

**Comment by wenhaiwang** [comment]
希望做一个swift demo

**Comment by cddjr** [comment]
腾讯的IM SDK估计是45岁+的老码农写的代码，要不是功能多一点根本不会考虑用。
打开头文件，犹如看到了上古时期的文物。

其它家的SDK代码写得那叫一个清爽且友好，腾讯的SDK实在是乱且复杂。
