### ISSUE TITLE
V2TIMAdvancedMsgListener多elem消息接收

### ISSUE THREAD

**Issue by wxlpp** [tencentyun/TIMSDK#767]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：V2接口多elem消息接收
使用 V2TIMAdvancedMsgListener 接收包含多个不同类型elem的message时，无法直接拿到相关elem。比如第一个elem是text第二个是custom。通过text的next方法可以拿到custom但是通过msg的customelem无法拿到

**Comment by vinsonswang** [comment]
可以参考下相关文档：
Android：https://cloud.tencent.com/document/product/269/44489#4.-.E6.9C.89.E5.A4.9A.E4.B8.AA-elem-.E7.9A.84.E6.B6.88.E6.81.AF.E5.BA.94.E8.AF.A5.E5.A6.82.E4.BD.95.E8.A7.A3.E6.9E.90.EF.BC.9F

iOS：
https://cloud.tencent.com/document/product/269/44490#4.-.E6.9C.89.E5.A4.9A.E4.B8.AA-elem-.E7.9A.84.E6.B6.88.E6.81.AF.E5.BA.94.E8.AF.A5.E5.A6.82.E4.BD.95.E8.A7.A3.E6.9E.90.EF.BC.9F
