### ISSUE TITLE
键盘挡住输入框

### ISSUE THREAD

**Issue by yongjie520** [tencentyun/TIMSDK#768]
Android的 tuikit 4.8.50 键盘挡住了输入框
我的配置 `activity
            android:name=".chat.ChatActivity"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />

**Comment by itdais** [comment]
出现一样的问题 键盘遮挡了底部栏！只能用adjustPan 整个页面顶上去
