### ISSUE TITLE
No pending exception expected: java.lang.NoSuchFieldError: no "I" field "gender" in class "Lcom/tencent/imsdk/TIMUserProfile;" or its superclassesNo pending exception expected: java.lang.NoSuchFieldError: no "I" field "gender" in class "Lcom/tencent/imsdk/TIMUserProfile;" or its superclasses

### ISSUE THREAD

**Issue by HMY314** [tencentyun/TIMSDK#77]
AndroidSDK4.2.28   启动APP就闪退

A/inker.medlinke: thread.cc:2164] No pending exception expected: java.lang.NoSuchFieldError: no "I" field "gender" in class "Lcom/tencent/imsdk/TIMUserProfile;" or its superclasses
    thread.cc:2164]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:-2)
    thread.cc:2164]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:1014)
    thread.cc:2164]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1672)
    thread.cc:2164]   at void com.tencent.imsdk.manager.NativeManager.<clinit>() (NativeManager.java:20)
    thread.cc:2164]   at boolean com.tencent.imsdk.manager.NativeManager.isSoLoaded() (NativeManager.java:30)
    thread.cc:2164]   at boolean com.tencent.imsdk.manager.BaseManager.init(android.content.Context, com.tencent.imsdk.TIMSdkConfig) (BaseManager.java:124)
    thread.cc:2164]   at boolean com.tencent.imsdk.TIMManager.init(android.content.Context, com.tencent.imsdk.TIMSdkConfig) (TIMManager.java:227)

![image](https://user-images.githubusercontent.com/11188841/55768477-a6756980-5aaf-11e9-947b-dc7ecb66d461.png)

**Comment by lynxzhang** [comment]
您好，麻烦这边通过 TIMManager 里的 GetVersion 获取下实际的版本信息

**Comment by HMY314** [comment]
> 您好，麻烦这边通过 TIMManager 里的 GetVersion 获取下实际的版本信息
应该是升级tim的时候，AS有缓存，后来ok了
