### ISSUE TITLE
【Android】-【4.7.10】：【TUIKit 聊天界面文本内容无法长按复制文字内容】

### ISSUE THREAD

**Issue by HuZengKan** [tencentyun/TIMSDK#770]
【集成包】：TUIKIT：4.7.10，IMSDK：4.8.10
【当前现象】：聊天界面文本内容无法长按复制文字内容
【机型】：如荣耀9X等
【之前版本有无此问题】：之前应该也存在这个问题
【有无日志或者截图】：暂无日志

**Comment by vinsonswang** [comment]
感谢反馈！
TUIKit可以修改源码来满足自己的需求。
