### ISSUE TITLE
V2TIMConversation showname显示异常

### ISSUE THREAD

**Issue by wxlpp** [tencentyun/TIMSDK#772]
【当前现象】：V2TIMConversation没有按预期显示昵称
【集成包】：IMSDK
![截屏2020-06-30 上午10 02 27](https://user-images.githubusercontent.com/6649664/86074578-d051ec00-bab8-11ea-91a4-0c822687a66d.png)
如图，lastmessage中可见昵称已经获取，但V2TIMConversation的showName字段为userID

**Comment by wxlpp** [comment]
同样是这个会话，V2TIMConversation 下 lastmessage有数据，调用getC2CHistoryMessageList返回空

**Comment by lynxzhang** [comment]
你好，感谢您的反馈，问题原因已经找到，预计下个版本修复 ，目前建议先自己从 lastMsg 里面拿下昵称信息。
