### ISSUE TITLE
tim-js-sdk 2.7.3升级后发送单聊消息报错

### ISSUE THREAD

**Issue by 724399396** [tencentyun/TIMSDK#773]
issue标题： tim-js-sdk 2.7.3升级后报错

web -2.7.3： 升级后api报错
issue内容：

【当前现象】：
【集成包】：tim-js-sdk
【机型】：pc
【之前版本有无此问题】：如2.7.2之前没有，2.7.3有
【有无日志或者描述、截图】：
tim.sendMessage(imMessage) 改方法报错，原因是里面调用了这个方法this._guardForAVChatRoom(e).then(() =>), 发送的单聊消息，这个方法返回了undefined, 在 undefiend方法上调用了then报错

**Comment by kiradea** [comment]
这个情况也发现，猜测是sendMessage 返回的不是Promise，你回滚到2.7.0先用着把

**Comment by yangq1990** [comment]
感谢反馈，v2.7.3 已从npm仓库废弃，请使用 [changelog](https://cloud.tencent.com/document/product/269/38492) 列出的版本
