### ISSUE TITLE
未找到对应label: login, 请在调用 logger.timeEnd 前，调用 logger.time

### ISSUE THREAD

**Issue by Primary-Traxex** [tencentyun/TIMSDK#774]
issue标题：未找到对应label: login, 请在调用 logger.timeEnd 前，调用 logger.time

【平台】-【版本号】：微信小程序最新版 tim sdk
issue内容：catch了一个错误, 未找到对应label: login, 请在调用 logger.timeEnd 前，调用 logger.time, 不知道是什么错误

【当前现象】：聊天的时候, 突然接收不到任何发言, 但是自己的发言别人能看到
【集成包】：IMSDK
【机型】：iPhone xr
【之前版本有无此问题】：没有, 没有换过版本
【有无日志或者描述、截图】：截图如下
![image](https://user-images.githubusercontent.com/16198816/86318505-af2dfe80-bc64-11ea-97b6-483a0985a0e6.png)

**Comment by yangq1990** [comment]
请使用 v2.7.6 或更高版本，详细请参考 [changelog](https://cloud.tencent.com/document/product/269/38492)
