### ISSUE TITLE
sendMessage 返回的不是Promise

### ISSUE THREAD

**Issue by kiradea** [tencentyun/TIMSDK#775]
issue标题：sendMessage 返回的不是Promise
【小程序】-【2.7.3】：【sendMessage 返回的不是Promise】
issue内容：
【当前现象】：sendMessage 返回的不是Promise
【集成包】：IMSDK
【之前版本有无此问题】：如2.7.0之前没有，2.7.3和2.7.2有

目前是回滚到2.7.0，建议官方人员查看一下最新版本代码修复

**Comment by sologuy** [comment]
遇到了这个问题 2.7.5

**Comment by yangq1990** [comment]
v2.7.3 存在问题已废弃，请使用 [changelog](https://cloud.tencent.com/document/product/269/38492) 列出的版本
