### ISSUE TITLE
【iOS】-【4.8.50】：【接入SDK后编译报错，程序无法编译】

### ISSUE THREAD

**Issue by Liuqiang96** [tencentyun/TIMSDK#776]
![WechatIMG292](https://user-images.githubusercontent.com/40254389/86345026-9423b480-bc8d-11ea-8088-6be1efdda49b.jpeg)
报错的截图

**Comment by lynxzhang** [comment]
请问这边是 oc 的工程吗，如果是的话可以尝试下在工程里面 new file -> Swift File 创建一个空的 swfit 文件，具体可以参考下我们的 demo。
