### ISSUE TITLE
TXIMSDK_TUIKit_iOS.podspec 引用冲突

### ISSUE THREAD

**Issue by liuwin7** [tencentyun/TIMSDK#781]
【iOS-TUIKit】-【4.8.50】：【TXIMSDK_TUIKit_iOS.podspec 引用冲突】

【Issue内容】：TXIMSDK_TUIKit_iOS.podspec Bug

【当前现象】：pod集成错误
【集成包】：TUIKit
【问题】

`spec.ios.deployment_target = '9.0'`
`spec.dependency 'SnapKit'`

如上，`SnapKit`最新的版本已经不支持，10.0以下的`deployment_target`，可你们还在支持9.0的，程序肯定会报错。

**依赖的第三方库，不指定版本，pod经过依赖判定后，完全有可能指定一个不适用的库。**

**这是一个非常危险的操作，特别是用别人的库，二次开发。**

**Comment by lynxzhang** [comment]
感谢反馈，这边优化下。

**Comment by lynxzhang** [comment]
已经优化，麻烦更新下 pod 再试下，再次感谢反馈。

**Comment by liuwin7** [comment]
为什么是移动的git Tag【4.8.50】的指向，而不是升级到【4.8.51】？
这种操作，只能修正新用户，并不能修正老用户。
请规范升级Pod的步骤，不能玩的那么随意。

**Comment by liuwin7** [comment]
@lynxzhang
