### ISSUE TITLE
获取AVChatRoom群成员人数最多300

### ISSUE THREAD

**Issue by H4AER** [tencentyun/TIMSDK#782]
【iOS】-【4.8.0.5】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT
【当前现象】：群成员人数几千，但是从- (int)getGroupMembers:(NSString*)groupId succ:(TIMGroupMemberSucc)succ fail:(TIMFail)fail; 获取到的最多只有300
【机型】：所有
【之前版本有无此问题】：
【有无日志或者截图】：

**Comment by lynxzhang** [comment]
AVChatRoom 最多只支持 300 的群成员，可以参考文档：https://cloud.tencent.com/document/product/269/1502#.E7.BE.A4.E7.BB.84.E5.9F.BA.E7.A1.80.E8.83.BD.E5.8A.9B.E6.93.8D.E4.BD.9C.E5.B7.AE.E5.BC.82

**Comment by H4AER** [comment]
感谢回复
