### ISSUE TITLE
发起通话问题

### ISSUE THREAD

**Issue by jplayer-top** [tencentyun/TIMSDK#786]
【Android】-【4.8.50】：【发起音视频通话，会自动发一个发起通话自定义消息，以及更新消息内容】
【当前现象】：
1 .发起实时音视频会发送一条自定义消息，也就是发起通话那条，这条消息目前我怎么都去不掉，请指点一下如何去掉。
2. 我自定义了一个发送红包的消息，现在需求是发送红包后被领取了，我需要更新这条发出的历时消息，但是在api中也没有找到相应的，有效的方式解决，请指点
【集成包】：IMSDK ,Tuikit
【机型】：所有机型
【有无日志或者描述、截图】：无需截图，我的描述已经很清晰了

**Comment by vinsonswang** [comment]
[重复问题](https://github.com/tencentyun/TIMSDK/issues/787)
