### ISSUE TITLE
【iOS】-【4.8.50】：【V2TIMMessage没有TIMMessage里面的一些方法了】

### ISSUE THREAD

**Issue by apple130** [tencentyun/TIMSDK#788]
V2TIMMessage 没有- (int)addElem:(TIMElem*)elem; - (TIMElem*)getElem:(int)index - (int)elemCount 这些方法了吗

**Comment by lynxzhang** [comment]
V2 版本简化了消息的收发解析流程，发消息去掉了多 elem 的逻辑，如果对多 elem 这块有刚需，建议用 V1 的版本，V1 的版本我们也会一直维护。

**Comment by boai** [comment]
TUIMessageCellData 里面的 innerMessage 只有V2TIMMessage 了，V2TIMMessage 里面又都是 只读属性，请问怎么发送自定义消息？
