### ISSUE TITLE
【Android】-【4.8.50】：【每次打开app都需要重新登录，有时候登录了之后从后台回到前台也提示未登录】

### ISSUE THREAD

**Issue by YuToo** [tencentyun/TIMSDK#789]
【当前现象】：APP登录成功之后将APP切到后台，一段时间之后将app切换到前台调用接口时提示未登录。还有就是调用登录接口登录成功之后下次打开app还需要调用登录接口，没法自动登录，虽然也可以做到代码实现每次打开app都调用登录接口，但是这也不相当于又做了一遍自动重连的逻辑么，当登录失败时还要做一些处理后边重新调用登录接口的逻辑。
【其他问题】：图片音视频调用下载之后没法控制，能等成功或者失败，没法取消，消息实体竟然没法在activity直接传递只能通过静态变量来传递。
【集成包】：IMSDK
【机型】：小米9
【之前版本有无此问题】：不确定
【有无日志或者描述、截图】：暂无

**Comment by chengqw** [comment]
您好，长时间切到后台，会被Android的系统策略杀掉进程，下次进入相当于重新进入所以需要登录。
