### ISSUE TITLE
Android偶现自己的消息显示在对话的左侧

### ISSUE THREAD

**Issue by HMY314** [tencentyun/TIMSDK#79]
Android TIMSDK4.2.10

判断是否是自己的消息:

String sender = timMessage.getSender();
boolean isSelf = sender.equals(TIMManager.getInstance().getLoginUser());

**Comment by lynxzhang** [comment]
感谢您的反馈，我们先验证下，如果有问题，会尽快修复

**Comment by lynxzhang** [comment]
您好，问题已经优化，麻烦更新官网最新版本
