### ISSUE TITLE
【iOS】[v4.8.50] cocoapods集成报 ISVImageScrollView.h 依赖错误。

### ISSUE THREAD

**Issue by CoderArcher** [tencentyun/TIMSDK#791]
[v4.8.50] cocoapods集成报 ISVImageScrollView.h 依赖错误。
原因：ISVImageScrollView 库已更新至Swift版本。
请及时更正依赖，并在其它的依赖库指定依赖版本，防止此类事件发生

**Comment by lynxzhang** [comment]
pod  依赖库现在都已经指定具体版本，还有什么问题欢迎随时反馈。

**Comment by Yunlou1995** [comment]
现在版本  - TXIMSDK_iOS (4.9.1)
  - TXIMSDK_TUIKit_iOS (4.6.58):

但是还是报依赖错误啊
![image](https://user-images.githubusercontent.com/18695438/92088427-6e3a9d80-edff-11ea-9bb7-8c0f645107b5.png)

**Comment by syq7970** [comment]
最新版4.9.1同样报这个错

**Comment by DullBottle** [comment]
5.0.6还有这个问题

**Comment by BigEleven** [comment]
这个问题怎么解决的? 提工单腾讯说不是他们的问题

**Comment by CoderArcher** [comment]
> 这个问题怎么解决的? 提工单腾讯说不是他们的问题

https://github.com/tencentyun/TIMSDK/pull/255#issue-300607767
我加了这个，其它正常用cocoapods 集成
