### ISSUE TITLE
【iOS】-【4.8.50】：【pod 'TXIMSDK_TUIKit_iOS'集成后项目编译出错】

### ISSUE THREAD

**Issue by JuneCheng** [tencentyun/TIMSDK#792]
【当前现象】：集成TXIMSDK_TUIKit_iOS后，项目编译失败。报错信息如下：
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
尝试了以下两个方案均无效。
1.Enable Bitcode改成NO
2.Build Active Architecrure Only改为NO
【集成包】：TXIMSDK_TUIKit_iOS
【机型】：iPhone X模拟器
【之前版本有无此问题】：第一次使用你们的SDK
【截图】：
![image](https://user-images.githubusercontent.com/36223198/87536367-91808080-c6cb-11ea-9d65-de8cf6f826b2.png)
![image](https://user-images.githubusercontent.com/36223198/87526070-ecf74200-c6bc-11ea-8e97-7b7e0f6eab17.png)
![image](https://user-images.githubusercontent.com/36223198/87526011-da7d0880-c6bc-11ea-834a-b3f553b5107b.png)

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年 https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠 https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元 https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

云建站，云服务器限时特惠，助力中小企业渡过疫情。个人级服务器限时特价低至102/年。 云服务器还等什么。 云建站，企业官网定制，价格便宜安全可靠。

**Comment by DiamoandDog** [comment]
> 【当前现象】：集成TXIMSDK_TUIKit_iOS后，项目编译失败。报错信息如下：
> clang: error: unable to execute command: Segmentation fault: 11
> clang: error: clang frontend command failed due to signal (use -v to see invocation)
> 尝试了以下两个方案均无效。
> 1.Enable Bitcode改成NO
> 2.Build Active Architecrure Only改为NO
> 【集成包】：TXIMSDK_TUIKit_iOS
> 【机型】：iPhone X模拟器
> 【之前版本有无此问题】：第一次使用你们的SDK
> 【截图】：
> ![image](https://user-images.githubusercontent.com/36223198/87536367-91808080-c6cb-11ea-9d65-de8cf6f826b2.png)
> ![image](https://user-images.githubusercontent.com/36223198/87526070-ecf74200-c6bc-11ea-8e97-7b7e0f6eab17.png)
> ![image](https://user-images.githubusercontent.com/36223198/87526011-da7d0880-c6bc-11ea-834a-b3f553b5107b.png)

hello,I have encountered the same problem as you. Could you please tell me whether you have solved this problem and how you solved it. Thank you!

**Comment by JuneCheng** [comment]
新建一个测试工程去集成TXIMSDK_TUIKit_iOS，你会发现没问题，项目可以正常运行。出现上述问题的原因就是TXIMSDK_TUIKit_iOS本身依赖了某些三方库，跟你项目里的三方库冲突，或者版本不一致导致的。所以你需要新建一个测试工程，首先依赖TXIMSDK_TUIKit_iOS，再一个一个去依赖你项目中其他的三方库，查找出冲突的三方库，然后删除这些冲突的三方库或者保持版本一致。

**Comment by DiamoandDog** [comment]
> 新建一个测试工程去集成TXIMSDK_TUIKit_iOS，你会发现没问题，项目可以正常运行。出现上述问题的原因就是TXIMSDK_TUIKit_iOS本身依赖了某些三方库，跟你项目里的三方库冲突，或者版本不一致导致的。所以你需要新建一个测试工程，首先依赖TXIMSDK_TUIKit_iOS，再一个一个去依赖你项目中其他的三方库，查找出冲突的三方库，然后删除这些冲突的三方库或者保持版本一致。

thank you so much
