### ISSUE TITLE
【iOS】-【4.8.50】：【V2TIMManager中没有获取单个会话了吗？】

### ISSUE THREAD

**Issue by Laixg** [tencentyun/TIMSDK#793]
在以前的版本 TIMManager可以获取单个会话信息
- (TIMConversation*)getConversation:(TIMConversationType)type receiver:(NSString*)conversationId;
但是更新到最新版本V2TIMManager摒弃了这个方法，请问下有替代的方法吗？
我目前的需求是在删除了会话记录后，通过获取已经加入的群组，不发送任何信息，来创建一个会话。

**Comment by lynxzhang** [comment]
v2 版本已经去掉，建议用 V1 的 API 实现
