### ISSUE TITLE
【iOS】-【4.8.50】：使用自定义消息，接收到新消息后崩溃了

### ISSUE THREAD

**Issue by huoguanghua** [tencentyun/TIMSDK#795]
【iOS】-【4.8.50】：
在收到自定义消息后，SDK 崩溃了。

自定义消息是一个 JSON 数组，如下：

[{"event":"text","data":"aaaaaa"},{"id":2708,"nickname":"smart","avatar":"http://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83equbicpKuhZxXJQiaDdZEH0WpEkc88C9koqRYn5dKoaYPk623HKwhGrtwf37uodCAISEG9JSoZZyLCw/132","gender":"male","tags":[45],"msgId":"a1f7c360-ab55-b361-9fe9-4f1a72dc3df7","auditSend":false}]

【集成包】：IMSDK
【机型】：iPhone 8 Plus

<img width="1556" alt="crash" src="https://user-images.githubusercontent.com/34032038/87855711-9dc74080-c94c-11ea-9312-f20c1505af60.png">

**Comment by lynxzhang** [comment]
SDK 这边不会去解析客户的 json 数据，麻烦 check 下上层解析的逻辑是否正常，如果是 SDK 的 crash，麻烦把 SDK 的 Crash 堆栈贴下。
