### ISSUE TITLE
iOS 图片消息 不支持gif 

### ISSUE THREAD

**Issue by wenhaiwang** [tencentyun/TIMSDK#796]
下载的最新的 sdk  运行的咱们的 demo ,  我发送的GIF 图片消息,  可是 展示根本不支持,  消息列表显示的消息是 静态图,  希望修复,或者添加下这个需求,在demo上面做下改动, 让大家能看到效果

**Comment by lynxzhang** [comment]
gif 动图，SDK 是支持发送的，TUIkit 我们在后续版本会支持，敬请期待。
