### ISSUE TITLE
【Android】-【4.7.2 】：【android10发送图片不能成功】

### ISSUE THREAD

**Issue by DyncKathline** [tencentyun/TIMSDK#798]
【Android】-【4.7.2 】：【android10发送图片不能成功】
【集成包】：TUIKIT
【当前现象】：我依赖的是4.7.2 UI库源码，sdk我目前升级到了'com.tencent.imsdk:imsdk:4.8.50'，目前Android10一下可以发送图片成功，看控制台日志显示发送的图片没有找到（Android10不能通过路径获取了），看到新版本的demo是可以，但是我对比也没看到改动了，能告诉下怎么在当前版本进行修改吗
另外
【4.8.50 @2020.06.22
SDK
Android 平台
为兼容 Android Q 版本，修改日志默认存储位置为 /sdcard/Android/data/包名/files/log/tencent/imsdk】
这块在不升级的情况下怎么修改，
【机型】：如小米9
【之前版本有无此问题】：
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by chengqw** [comment]
您好，因为Android 10采用了分区存储机制，访问会受限。建议使用mediastore访问或者做下存储适配。

**Comment by DyncKathline** [comment]
@chengqw 我知道，我想快捷的修改，因为4.8.10 UI库源码（这里的整体结构没有发生变化相对于4.7.2）我直接运行是可以发送图片成功的，然后我对比了文件，没有发现改动的地方，我就想知道你们在那块改动了，这样我改起来会快点。

**Comment by DyncKathline** [comment]
能回答一下吗？

**Comment by chengqw** [comment]
您好，从实现逻辑看，获取了图片的URI，组建消息发送存储地址;获取消息时读取地址加载。请参考demo：

组建消息：
MessageInfoUtil类，buildImageMessage方法，关注下String path = FileUtil.getPathFromUri(uri);
接受消息：
MessageImageHolder类performImage方法。

**Comment by chengqw** [comment]
FileUtil类getPath方法

**Comment by JunkmenDream** [comment]
在AndroidQ上，target SDK大于或等于29的APP默认被赋予Filtered View。
APP可以在AndroidManifest.xml中设置requestLegacyExternalStorage来修改外部存储空间视图模式，true为Legacy View，false为Filtered View。

android:requestLegacyExternalStorage="true"//启用兼容模式
