### ISSUE TITLE
android 4.8.50 聊天记录页面没有返回用户昵称

### ISSUE THREAD

**Issue by Yange820** [tencentyun/TIMSDK#799]
聊天记录页面昵称无法显示
“title”参数返回的是用户的id

**Comment by chengqw** [comment]
您好，聊天界面昵称显示，请参照MessageContentHolder类layoutViews方法，昵称获取调用getNameCard()接口。

**Comment by Yange820** [comment]
我的意思是聊天记录页面，另外，我该怎么去设置自己的头像和昵称了，我调用的 
V2TIMUserFullInfo v2TIMUserFullInfo = new V2TIMUserFullInfo();
v2TIMUserFullInfo.setFaceUrl
 v2TIMUserFullInfo.setNickname
但是没有生效，对方显示的依然是我的旧头像和旧昵称

**Comment by chengqw** [comment]
您好，请参照ProfileLayout类updateProfile()方法。设置完成后，要做好数据的同步

**Comment by Yange820** [comment]
你好，参照了updateProfile()中的V2TIMManager.getInstance().setSelfInfo方法依然没有生效，对方所看到的头像和昵称还是旧的

**Comment by chengqw** [comment]
您好，抱歉，让您久等了。设置完后，需要做好数据同步。
setSelfInfo这个接口只是将新的头像的url同步给了后台和本地，登录、发消息等都需要进行同步读取，才会生效。您的情况应该是设置成功，但对方同步没有读取到。
