### ISSUE TITLE
removeSimpleMsgListener 闪退

### ISSUE THREAD

**Issue by jiaohaili** [tencentyun/TIMSDK#800]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

【平台】-【版本号】：【描述您的问题】
issue内容：

【当前现象】：如聊天界面点击xxx不显示xxx
【集成包】：IMSDK
【机型】：如iPhone 7 Plus
【之前版本有无此问题】：如4.8.10之前没有，4.8.10有
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
-------------------------完整的示例如下：-------------------------

【Android】-【4.4.479】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，报错，无法编译通过（描述你的问题现象，错误码、错误信息 以及具体请求或者接口）
【机型】：如华为Mate 20
【之前版本有无此问题】：TUIKIT 4.4.479版本之前没有，4.4.479有
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by jiaohaili** [comment]
removeSimpleMsgListener 闪退

【iOS】-【sdk 4.9.1】：dealloc 方法里执行移除监听闪退
机型 苹果7，8，8plus


<img width="381" alt="截屏2020-07-28 13 11 30" src="https://user-images.githubusercontent.com/15994313/88621795-eeb90080-d0d3-11ea-9fa5-95cf77d999f2.png">

**Comment by lynxzhang** [comment]
感谢您的反馈，我们尽快修复下。

**Comment by lynxzhang** [comment]
麻烦删除本地 IMSDK 包， pod cache clean --all 后再集成下试下

**Comment by lynxzhang** [comment]
有什么问题欢迎这里反馈

**Comment by jiaohaili** [comment]
你们提供的方法太暴力了，老版本不崩溃，新版本崩溃，只能在viewDidDisappear里执行，在dealloc里执行闪退，肯定跟版本没有关系，你们让&nbsp; pod cache clean --all 用这个命令解决不了问题。我肯定是更新了sdk的呀


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tencentyun/TIMSDK"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上10:12
收件人:&nbsp;"tencentyun/TIMSDK"<TIMSDK@noreply.github.com&gt;;
抄送:&nbsp;"雨晴"<787172000@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/TIMSDK] removeSimpleMsgListener 闪退 (#800)





 
麻烦删除本地 IMSDK 包， pod cache clean --all 后再集成下试下
