### ISSUE TITLE
[4.9.1] joinGroup 失败率变高了

### ISSUE THREAD

**Issue by jiaohaili** [tencentyun/TIMSDK#801]
【iOS】-【4.9.1】：【进入群聊失败】

错误 /Common      -TIMGroupManager.mm.135  operator()                         /joinGroup failed,code:10010 msg:@

**Comment by lynxzhang** [comment]
10010: 群组不存在，或者曾经存在过，但是目前已经被解散.

**Comment by jiaohaili** [comment]
好的，已解决，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tencentyun/TIMSDK"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午3:03
收件人:&nbsp;"tencentyun/TIMSDK"<TIMSDK@noreply.github.com&gt;;
抄送:&nbsp;"雨晴"<787172000@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/TIMSDK] [4.9.1] joinGroup 失败率变高了 (#801)





 
10010: 群组不存在，或者曾经存在过，但是目前已经被解散.
