### ISSUE TITLE
【需求】： iOSv2版本啥时候支持多个elem

### ISSUE THREAD

**Issue by ahhsxp** [tencentyun/TIMSDK#803]
现在集成了V2版本，但是发现V2没有办法使一个消息包含多个elem ，这样感觉V2的灵活性以及功能性没有V1强大。

V2版本，不能包含多个elem，在发送消息时也不可携带其他的拓展，在实际业务中，经常需要在消息发送的同时携带一些参数来实现自己的业务逻辑。  如果V2不支持多个elem，继续使用V1，V1的后面的稳定性，以及对于bug 的修复我们没办法预估， 如果使用V2版本，多个elem是行不通的，只能发送多条消息，但又涉及到消息未读数，以及其中一条消息发送失败或者丢失等情况。。 真的是纠结
真的希望，V2的版本最好也支持多个elem 吧！

**Comment by lynxzhang** [comment]
感谢您的反馈：

**Comment by lynxzhang** [comment]
感谢您的反馈：
1.   V1 版本我们会一直维护的，这个请你放心，底层的优化针对 V1 和 V2 都是生效的。
2，V2 的版本设计的初衷就是降低 IM 的复杂度，带来的负面影响是灵活度确实会降低，如果您的业务已经基于 V1 实现了，建议还是使用 V1 版本。

V2 暂时不会支持多 ELem，后面支持支持也不太确定，要看下大部分客户的需求。
如果你一定要用 V2 的 API ，可以在发消息这块使用 V1 的接口，其他的都使用 V2 的（V2 支持多 Elem 消息的解析，文档请参考 https://cloud.tencent.com/document/product/269/44490#5.-.E5.90.84.E7.A7.8D.E4.B8.8D.E5.90.8C.E7.B1.BB.E5.9E.8B.E7.9A.84.E6.B6.88.E6.81.AF.E5.BA.94.E8.AF.A5.E5.A6.82.E4.BD.95.E8.A7.A3.E6.9E.90.EF.BC.9F）
