### ISSUE TITLE
【iOS】-【4.9.1】：【发送message消息的时候 发送语音消息 如果语音elem 后面追加了一个自定义IM群组收不到语音消息】

### ISSUE THREAD

**Issue by apple130** [tencentyun/TIMSDK#806]
发送message消息的时候 发送语音消息 如果语音elem 后面追加了一个自定义IM群组收不到语音消息
举例  一个群组有a b c3个人  这是a发送了一个语音消息  b c可以正常收到  如果a发送了一个语音消息并且后面追加了一个自定义elem  这时bc收不到这条语音消息 a自己可以收到  但是如果a把app卸载了 a也收不到了

**Comment by 173315179** [comment]
V2版本只支持发送一个elem

**Comment by 173315179** [comment]
V2版本，不能包含多个elem，在发送消息时也不可携带其他的拓展，如果需要支持多个elem，继续使用V1，V1版本我们也是维护的

**Comment by apple130** [comment]
我用的是v1版本发送的

**Comment by 173315179** [comment]
如果是具体内容 可以到我们官网提一下工单 我们有专门的人为您服务

**Comment by apple130** [comment]
你们可以测试一下 就是v1版本的发送语音追加一个自定义elem 发群消息不成功  不追加就可以成功

**Comment by lynxzhang** [comment]
![企业微信截图_52f87a79-eb7a-4f4e-b9e9-b49e17c4c966](https://user-images.githubusercontent.com/12908172/91678021-ffe3aa00-eb76-11ea-8ff4-5f38560831ab.png)
语音或则文件是禁止添加多 ELEM 的，这个在 API 注释里面有说明
