### ISSUE TITLE
【 Android 】-【4.9.1】：【 V2TIMSignalingListener 发送后不能收到 onReceiveNewInvitation】

### ISSUE THREAD

**Issue by wxmylife** [tencentyun/TIMSDK#807]
【当前现象】：当 A 用户拨打语音电话至 B 用户，B 用户不能唤起接听页面，发现是 V2TIMSignalingListener 回调后，onReceiveNewInvitation 方法并没有执行，当 A 用户取消语音后，B 用户 onInvitationCancelled 方法执行
【集成包】：IMSDK
【机型】：Pixel 3
【之前版本有无此问题】：未将 sdk 回退到老版本,后续尝试后会反馈

**Comment by wxmylife** [comment]
4.8.50 版本 onReceiveNewInvitation 方法也未执行

**Comment by JunkmenDream** [comment]
V2TIMSignalingListene 信令监听回调SDK内部会根据发送请求的时间与手机本地时间做差值。
1.如果差值小于30秒说明请求正常会回调onReceiveNewInvitation()，
2.如果差值大于30秒说明请求超时SDK内部会阻断信令回调，所以onReceiveNewInvitation()不会回调。
3.另外SDK请求的有效时间为：30秒

解决方案：只要各端时间一致可解决，时间不要相差超过30秒
这个问题之后SDK会做优化
