### ISSUE TITLE
直播群消息出现在会话列表

### ISSUE THREAD

**Issue by linxingxi** [tencentyun/TIMSDK#810]
【Android】-【4.4.479】：【直播群消息出现在会话列表，怎么屏蔽直播群消息出现在会话列表，并不记入未读数】
【集成包】：TUIKIT
【当前现象】：直播群消息出现在会话列表，怎么屏蔽直播群消息出现在会话列表，并不记入未读数？

**Comment by JunkmenDream** [comment]
IM SDK会加载所有会话列表，当用户接收到来至直播（AVChatRoom）的群消息时，会触发setRefreshListener监听的onRefreshConversation会话刷新的。TUIKit里面是在onRefreshConversation()回调里面进行会话刷新操作。
如果是TUIKit源码集成，你需要在会话刷新和拉取历史会话中统一对于直播群（AVChatRoom）会话进行过滤处理。因为没有会话列表显示就不会产生未读数，所以只需要过滤会话就可以。
