### ISSUE TITLE
无法接受群聊消息

### ISSUE THREAD

**Issue by 347008893** [tencentyun/TIMSDK#813]
【iOS】- 4.8.10
【集成包】：IMSDK
【当前现象】：群聊在某一部手机会话列表显示未读消息数，但是进入到消息页面没有最新消息，且上报已读返回会话列表页仍然有未读数提示，更换另一部手机登录同一账号无此问题。（查看日志，无错误码上传）
【机型】：iPhone 8, iOS 13.6
【之前版本有无此问题】：未知
【有无日志或者截图】：暂无日志

**Comment by parkhuang** [comment]
有可能是未读数是本地算的，但是漫游消息已经过期，可以用4.9.1+版本，未读数完全按照后台的值展示，可以避免这种问题
