### ISSUE TITLE
【IOS】-【4.6.1】: TimSoundElem getUrl 返回下载地址不能下载

### ISSUE THREAD

**Issue by leiyangyou** [tencentyun/TIMSDK#814]
【当前现象】：TimSoundElem getUrl 返回不可用地址
https://183.3.253.20/asn.com/stddownload_common_file?ver=1&...（省略）
希望返回地址例子
https://501c-1400299058-1256635546.cos.ap-shanghai.myqcloud.com/... （省略）
【集成包】：IMSDK
【机型】：iPhone 11
【之前版本有无此问题】：在某个时间点后，app无更新情况下出现该问题，Android版本没有问题，iOS版本播放语音时遇到
【有无日志或者描述、截图】：无

**Comment by zhengzhou** [comment]
TimSoundElem  getSound 也是返回下载失败 error(400): download failed

**Comment by lynxzhang** [comment]
![企业微信截图_1598444587985](https://user-images.githubusercontent.com/12908172/91677734-32d96e00-eb76-11ea-8016-8a65c55d79d8.png)
这个字段请不要修改，麻烦 check 下。
