### ISSUE TITLE
【Android】-【4.9.1】：收到消息重复问题

### ISSUE THREAD

**Issue by ruowuming** [tencentyun/TIMSDK#820]
【当前现象】：用户A进入群聊之后，再切换到单聊，其他人给用户A发送一条自定义消息，用户A的onRecvNewMessage收到两条相同消息。
【集成包】：IMSDK ,Tuikit
【机型】：所有机型
【之前版本有无此问题】：不确定
【有无日志或者描述、截图】：如描述。

**Comment by JunkmenDream** [comment]
这个时TUIKit中对于消息监听的实例化重复监听了，导致onRecvNewMessage() 接收到新消息回调了两次。

解决方案：
1. 对于收到重复消息做消息过滤
2.修改TUIKit中，ChatManagerKit.java 消息监听逻辑

    protected void init() {
        destroyChat();
        /***********TUIKit原本编写的代码（此段代码需要替换位置）************/
        /***********原因：因为设置新消息监听需要配合取消监听（之前没有需要监听的实现，导致Demo新消息会重复回调onRecvNewMessage）************/
//        V2TIMManager.getMessageManager().addAdvancedMsgListener(this);
//        MessageRevokedManager.getInstance().addHandler(this);
    }

    public void destroyChat() {
        mCurrentProvider = null;
        /***************新增移除监听实现，解决退出聊天页面还有接收到onRecvNewMessage回调，同时也防止消息重复监听***************/
        V2TIMManager.getMessageManager().removeAdvancedMsgListener(this);
    }

    public abstract ChatInfo getCurrentChatInfo();

    public void setCurrentChatInfo(ChatInfo info) {
        if (info == null) {
            return;
        }
        mCurrentProvider = new ChatProvider();
        mIsMore = true;
        mIsLoading = false;
        /************将新消息监听从init()方法迁移到这里（解决初始化只初始化一次，导致设置新消息移除监听后，退出聊天页，再次进入没有新消息回调）************/
        V2TIMManager.getMessageManager().addAdvancedMsgListener(this);
        MessageRevokedManager.getInstance().addHandler(this);
    }

之后TUIkit也会做优化处理。
