### ISSUE TITLE
【Android】-【4.9.1】：【自定义消息，位置错乱】

### ISSUE THREAD

**Issue by GodLikeThomas** [tencentyun/TIMSDK#821]
【当前现象】：在聊天界面发送一个自定义消息后，上下滑动出现位置错乱。只会与视频通话的消息类型与语音通话的消息类型的错位。

【集成包】：TUIKIT
【机型】：华为P10 PLUS
【之前版本有无此问题】：没试过
【有无日志或者描述、截图】：
![微信图片_20200824211900](https://user-images.githubusercontent.com/10253785/91050225-f32ff500-e650-11ea-9c29-4bd68bd4479b.png)
![微信图片_20200824212048](https://user-images.githubusercontent.com/10253785/91050246-faef9980-e650-11ea-9cea-bac8af4da21f.png)

**Comment by skyYoungJade** [comment]
请问解决了吗？我也遇到了类似的问题，发送消息列表消息混乱！！！QQ：1456708806

**Comment by ludaxin6** [comment]
请问解决了吗？我也遇到了类似的问题，发送消息列表消息混乱！！！QQ：836210766
之前发过这个问题，好像没有回复

**Comment by JunkmenDream** [comment]
解决方案：
TUIKit中找到MessageInfoUtil.java # createMessageInfo 方法：
原代码：
        if (isGroup) {
                  msgInfo.setMsgType(MessageInfo.MSG_TYPE_GROUP_AV_CALL_NOTICE);
          }
修改成===>
        if (isGroup) {
                  msgInfo.setMsgType(MessageInfo.MSG_TYPE_GROUP_AV_CALL_NOTICE);
        } else {
                  msgInfo.setMsgType(MessageInfo.MSG_TYPE_TEXT);
        }
