### ISSUE TITLE
iOS自定义消息获取不到头像和昵称

### ISSUE THREAD

**Issue by vitasapple** [tencentyun/TIMSDK#822]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

iOS-：版本忘了
issue内容：

【当前现象】：聊天发送的自定义消息没有显示头像
【集成包】：IMSDK
【机型】：如iPhone 7 Plus
【之前版本有无此问题】：之前我不知道，近两个月下载的
你们获取消息记录的是在TUIConversationDataProviderService这里调用getMessage方法，但是这样获取出来的TUIMessageCellData里的avatarUrl根本没有，安卓的看了说是faceUrl,可是那个是在V2Timmanager里才有的，我现在要怎么搞？

**Comment by parkhuang** [comment]
可以通过TIMMessage.h # getSenderFaceURL 获取发送者头像

**Comment by syq7970** [comment]
同样遇到这个问题，现在只有V2TIMMessage，没有TIMMessage。 @parkhuang

**Comment by smallyou** [comment]
V2TIMMessage有faceURL属性

> 同样遇到这个问题，现在只有V2TIMMessage，没有TIMMessage。 @parkhuang
