### ISSUE TITLE
【IOS】-【4.9.1】：getC2CHistoryMessageList弱网环境下响应太慢

### ISSUE THREAD

**Issue by cddjr** [tencentyun/TIMSDK#828]
【当前现象】：在网络比较糟糕的情况下，拉取历史消息会很慢（比如点开聊天窗口预拉取20条消息）。
看起来你们在API2.0中简化了老接口的在线拉取和离线拉取，统一做进了getC2CHistoryMessageList中，由你们内部判断网络超时(2秒？)再去拉取本地历史消息。
【集成包】：IMSDK
【机型】：与机型无关
【之前版本有无此问题】：未验证
【有无日志或者描述、截图】：无

建议优化或者增加仅拉取本地历史的开关

**Comment by parkhuang** [comment]
如果网络是断开的，会立即返回本地数据，如果是弱网，是会有超时时间。
