### ISSUE TITLE
删除某一条消息与列表的下标不一致

### ISSUE THREAD

**Issue by ruizhang1015** [tencentyun/TIMSDK#829]
删除某一条消息与列表的下标不一致，比如我想删position为0的那条消息，实际删除的也是0，但是列表上删除的确实1，如果删除最新一条的消息直接崩溃

**Comment by parkhuang** [comment]
因为消息列表最上面其实有个item是loading，所以下标会错开一位，可以看一下MessageListAdapter.java的实现：
![image](https://user-images.githubusercontent.com/14696119/93040306-46a7c880-f67c-11ea-943f-77e2cb817e70.png)
