### ISSUE TITLE
【Android】-【4.9.1】：【初始化会话列表时崩溃】

### ISSUE THREAD

**Issue by yibella** [tencentyun/TIMSDK#830]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

【平台】-【版本号】：【描述您的问题】
issue内容：

【当前现象】：如聊天界面点击xxx不显示xxx
【集成包】：IMSDK
【机型】：如iPhone 7 Plus
【之前版本有无此问题】：如4.8.10之前没有，4.8.10有
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
-------------------------完整的示例如下：-------------------------

【Android】-【4.4.479】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，报错，无法编译通过（描述你的问题现象，错误码、错误信息 以及具体请求或者接口）
【机型】：如华为Mate 20
【之前版本有无此问题】：TUIKIT 4.4.479版本之前没有，4.4.479有
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by yibella** [comment]
【集成包】：TUIKIT
【当前现象】：打开会话列表页面，调用initDefault()初始化后崩溃
【机型】：如华为P30
【有无日志或者截图】：

09-07 12:43:16.749 21339 21339 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
--
8209-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
8309-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
8409-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422)
8509-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
8609-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.Arrays.sort(Arrays.java:1302)
8709-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.Arrays.sort(Arrays.java:1485)
8809-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.ArrayList.sort(ArrayList.java:1470)
8909-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.Collections.sort(Collections.java:208)
9009-07 12:43:16.749 21339 21339 E AndroidRuntime: at java.util.Collections.sort(Collections.java:161)
9109-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.qcloud.tim.uikit.modules.conversation.ConversationManagerKit.sortConversations(ConversationManagerKit.java:449)
9209-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.qcloud.tim.uikit.modules.conversation.ConversationManagerKit.access$300(ConversationManagerKit.java:32)
9309-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.qcloud.tim.uikit.modules.conversation.ConversationManagerKit$1.onSuccess(ConversationManagerKit.java:98)
9409-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.qcloud.tim.uikit.modules.conversation.ConversationManagerKit$1.onSuccess(ConversationManagerKit.java:77)
9509-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.imsdk.v2.V2TIMConversationManagerImpl$2$1.onGetExtMsgFinish(V2TIMConversationManagerImpl.java:187)
9609-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.imsdk.v2.V2TIMConversationManagerImpl.getConversationExtMsg(V2TIMConversationManagerImpl.java:240)
9709-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.imsdk.v2.V2TIMConversationManagerImpl.access$300(V2TIMConversationManagerImpl.java:29)
9809-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.imsdk.v2.V2TIMConversationManagerImpl$2.onSuccess(V2TIMConversationManagerImpl.java:176)
9909-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.imsdk.v2.V2TIMConversationManagerImpl$2.onSuccess(V2TIMConversationManagerImpl.java:165)
10009-07 12:43:16.749 21339 21339 E AndroidRuntime: at com.tencent.imsdk.common.ICallback$1.run(ICallback.java:26)

**Comment by parkhuang** [comment]
已经找到原因并且fix到主线，您也可以先自己修改源码提前fix这个问题：
![image](https://user-images.githubusercontent.com/14696119/93040012-99cd4b80-f67b-11ea-90c3-2eeb8ce3b755.png)
