### ISSUE TITLE
【Android】-【4.4.716】：【退出登录时偶现Native层崩溃】

### ISSUE THREAD

**Issue by AnliaLee** [tencentyun/TIMSDK#832]
【当前现象】：频繁退出登录，会比较容易出现Native层崩溃，目前在华为Android 10机型上复现
【集成包】：IMSDK
【机型】：HUAWEI Mate 30 pro
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/20130203/92596099-db56a300-f2d7-11ea-95af-e43275f3b6ae.png)

**Comment by parkhuang** [comment]
最近一年多 imsdk 已经升级了很多版本，解决了大量的crash，建议升级到4.9.1+，稳定性会提升很多
