### ISSUE TITLE
【iOS】- 【4.7.10】- 【Login会有闪退】

### ISSUE THREAD

**Issue by baiyidjp** [tencentyun/TIMSDK#833]
【集成包】：  TXIMSDK_TUIKit_iOS (4.6.100):
【当前现象】：在Firebase看到有很多闪退问题，具体如下

Crashed: Thread

> 0  ImSDK                          0x101d39760 LogBuffer::Write(void const*, unsigned long, AutoBuffer&) + 24
> 1  ImSDK                          0x101d36d58 __openlogfile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 1020
> 2  ImSDK                          0x101d36d58 __openlogfile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 1020
> 3  ImSDK                          0x101d347a0 __log2file(void const*, unsigned long, bool) + 564
> 4  ImSDK                          0x101d32fe8 __async_log_thread() + 268
> 5  ImSDK                          0x101d3731c Thread::start_routine(void*) + 76
> 6  libsystem_pthread.dylib        0x1b5ffb914 _pthread_start + 168
> 7  libsystem_pthread.dylib        0x1b60039d4 thread_start + 8

是否可以通过更新新版本解决

**Comment by 173315179** [comment]
可以

**Comment by parkhuang** [comment]
xlog 模块多线程访问导致的crash，建议升级到4.9.1及以上

**Comment by baiyidjp** [comment]
> xlog 模块多线程访问导致的crash，建议升级到4.9.1及以上

升级到4.9.1后，TUIConversationCellData类中不包含会话类型？怎么判断当前会话类型，需要判断groupID或者userID是否为空吗？

**Comment by baiyidjp** [comment]
> xlog 模块多线程访问导致的crash，建议升级到4.9.1及以上

升级新版本，收到新消息crash

#837
