### ISSUE TITLE
tuikit没有适配精简版的IMSDK吗

### ISSUE THREAD

**Issue by zzzsssbo** [tencentyun/TIMSDK#839]
我用精简版替换了标准版后，有几个类找不到了

**Comment by zzzsssbo** [comment]
![image](https://user-images.githubusercontent.com/17812840/93319601-a51ea380-f842-11ea-8758-de24573e5cec.png)

**Comment by JunkmenDream** [comment]
精简版 SDK 在原有标准版的基础上裁剪了好友和会话两项能力.
精简版里面移除了TIM开头的api调用。目前只有V2TIM

如果使用的是TIM开头的api，不要升级到最新的精简版

**Comment by zzzsssbo** [comment]
tuikit会更新适配了精简版sdk的版本吗

**Comment by parkhuang** [comment]
未来会，暂时用的还是精简版
