### ISSUE TITLE
【iOS 】-【4.9.1】：【收不到前台推送消息】

### ISSUE THREAD

**Issue by boai** [tencentyun/TIMSDK#842]
【iOS 】-【4.9.1】：【收不到前台推送消息】
【集成包】：
  - TXIMSDK_iOS (4.9.1)
  - TXIMSDK_TUIKit_iOS (4.6.58)
【当前现象】：收不到前台推送消息，离线消息和后台推送消息可以收到
【机型】：iPhone 11
【之前版本有无此问题】：TXIMSDK_TUIKit_iOS 4.6.58 版本之前没有

**Comment by smallyou** [comment]
请消息描述一下，前台推送的消息指的是？
