### ISSUE TITLE
【iOS14】-【5.0.6、以及以前的所有版本】：【聊天页cell事件不响应】

### ISSUE THREAD

**Issue by CarrySniper** [tencentyun/TIMSDK#848]
【iOS】-【5.0.6、以及以前的所有版本】：【聊天页cell事件不响应】

【当前现象】：在iOS14系统系统上聊天页面点击cell不响应
【集成包】：TUIKit
【机型】：iPhone8、iPhone11等
【有无日志或者描述、截图】：TUIMessageCell文件，UI都加载在cell的self上了，不是self.contentView上。或者是其他原因……

**Comment by Jijingcheng** [comment]
同样遇到了

**Comment by lynxzhang** [comment]
感谢您的反馈，我们会尽快修复这个问题

**Comment by lynxzhang** [comment]
TUIkit 5.0.7 版本已发布，修复了聊天页 cell 不响应的问题。
