### ISSUE TITLE
【iOS】-【5.0.7】：【更新 TXIMSDK_TUIKit_iOS 后 Masonry 无法使用致程序闪退】

### ISSUE THREAD

**Issue by ahuinee** [tencentyun/TIMSDK#854]
【iOS】-【5.0.7】：【更新 `TXIMSDK_TUIKit_iOS` 后 `Masonry` 无法使用致程序闪退】
【集成包】：TUIKIT
【当前现象】：

SDK更新到5.0.7后程序闪退。

最后找到是`Masonry`的原因。

 更新 `TXIMSDK_TUIKit_iOS` 导致 `Masonry` **无法使用？？？**

#### 下载官方Demo来重现Bug：

1. 下载并打开官方Demo 打开 **TUIKitDemo /TUIKitDemo.xcworkspace**

2. 修改：Podfile 添加 **Masonry**

```
# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'TUIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for Example
  pod 'Masonry'
  pod 'TXIMSDK_TUIKit_iOS'
end
```

安装更新： ` pod repo update`

3. 修改 ConversationController.m 的 **viewDidLoad** 方法 添加**Masonry**代码

```
		UIView *testView = [UIView new];
    testView.backgroundColor = [UIColor redColor];
    [self.view addSubview:testView];
    [testView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.view.mas_topMargin).mas_equalTo(100);
        make.left.mas_equalTo(100);
        make.width.height.mas_equalTo(100);
    }];
```

4. Run -> 报错闪退。

#### 尝试新建项目测试来确认是TXIMSDK_TUIKit_iOS的问题

1. Xcode新建一个**Test项目** 只导入`Masonry`

```
platform :ios, '9.0'
target 'Test' do
  use_frameworks!
  pod 'Masonry'
end
```

2. 修改 ViewController 的 **viewDidLoad** 方法 添加**Masonry**代码

```
	UIView *testView = [UIView new];
    testView.backgroundColor = [UIColor redColor];
    [self.view addSubview:testView];
    [testView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.view.mas_topMargin).mas_offset(100);
        make.left.mas_equalTo(100);
        make.width.height.mas_equalTo(100);
    }];
```

3. Run -> 正常渲染

【机型】：iPhoneX iOS14、模拟器iPhone11 iOS14
【之前版本有无此问题】：更新之前用的 4.6.100版本是好的
【有无日志或者截图】：

> **2020-09-24 16:52:06.620699+0800 TUIKitDemo[4485:486225] \**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mas_topMargin]: unrecognized selector sent to instance 0x7fb2c9f96f30'**
>
> ***\** First throw call stack:**
>
> **(**
>
> ​	**0  CoreFoundation           0x00007fff2043a126 __exceptionPreprocess + 242**
>
> ​	**1  libobjc.A.dylib           0x00007fff20177f78 objc_exception_throw + 48**
>
> ​	**2  CoreFoundation           0x00007fff20448c6f +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0**
>
> ​	**3  UIKitCore              0x00007fff24695af8 -[UIResponder doesNotRecognizeSelector:] + 292**
>
> ​	**4  CoreFoundation           0x00007fff2043e666 ___forwarding___ + 1489**
>
> ​	**5  CoreFoundation           0x00007fff20440698 _CF_forwarding_prep_0 + 120**
>
> ​	**6  TUIKitDemo             0x0000000100233a97 __37-[ConversationController viewDidLoad]_block_invoke + 183**
>
> ​	**7  TUIKitDemo             0x000000010024b6a7 -[UIView(MASAdditions) mas_makeConstraints:] + 135**
>
> ​	**8  TUIKitDemo             0x0000000100233913 -[ConversationController viewDidLoad] + 1923**
>
> ​	**9  UIKitCore              0x00007fff23f2c73b -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 88**
>
> ​	**10 UIKitCore              0x00007fff23f31022 -[UIViewController loadViewIfRequired] + 1084**
>
> ​	**11 UIKitCore              0x00007fff23e6800e -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 162**
>
> ​	**12 UIKitCore              0x00007fff23e682f8 -[UINavigationController _startTransition:fromViewController:toViewController:] + 154**
>
> ​	**13 UIKitCore              0x00007fff23e69371 -[UINavigationController _startDeferredTransitionIfNeeded:] + 851**
>
> ​	**14 UIKitCore              0x00007fff23e6a6dc -[UINavigationController __viewWillLayoutSubviews] + 150**
>
> ​	**15 UIKitCore              0x00007fff23e4af1e -[UILayoutContainerView layoutSubviews] + 217**
>
> ​	**16 UIKitCore              0x00007fff24bbd9ce -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2874**
>
> ​	**17 QuartzCore             0x00007fff27a3dd87 -[CALayer layoutSublayers] + 258**
>
> ​	**18 QuartzCore             0x00007fff27a44239 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575**
>
> ​	**19 QuartzCore             0x00007fff27a4ff91 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65**
>
> ​	**20 QuartzCore             0x00007fff27990078 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496**
>
> ​	**21 QuartzCore             0x00007fff279c6e13 _ZN2CA11Transaction6commitEv + 783**
>
> ​	**22 QuartzCore             0x00007fff279c7fcf _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79**
>
> ​	**23 CoreFoundation           0x00007fff203a76b3 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23**
>
> ​	**24 CoreFoundation           0x00007fff203a1f3f __CFRunLoopDoObservers + 547**
>
> ​	**25 CoreFoundation           0x00007fff203a24e2 __CFRunLoopRun + 1113**
>
> ​	**26 CoreFoundation           0x00007fff203a1b9e CFRunLoopRunSpecific + 567**
>
> ​	**27 GraphicsServices          0x00007fff2b773db3 GSEventRunModal + 139**
>
> ​	**28 UIKitCore              0x00007fff24660af3 -[UIApplication _run] + 912**
>
> ​	**29 UIKitCore              0x00007fff24665a04 UIApplicationMain + 101**
>
> ​	**30 TUIKitDemo             0x000000010022ec60 main + 112**
>
> ​	**31 libdyld.dylib            0x00007fff20257415 start + 1**
>
> ​	**32 ???                 0x0000000000000001 0x0 + 1**
>
> **)**
>
> **libc++abi.dylib: terminating with uncaught exception of type NSException**
>
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mas_topMargin]: unrecognized selector sent to instance 0x7fb2c9f96f30'
>
> terminating with uncaught exception of type NSException
>
> CoreSimulator 732.17 - Device: iPhone 11 Pro Max (55376F1B-CFFF-40B3-B2B0-8DAC29D98525) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11 Pro Max

**Comment by ahuinee** [comment]
## 可以吐槽一下吗？

- 为什么依别的库还要限制版本？

想请问：项目里依赖SDWebImage  Toast  ReactiveObjC，他们更新后我们如何更新？

```
- TXIMSDK_TUIKit_iOS (5.0.7):
    - MMLayout (= 0.2.0)
    - ReactiveObjC (= 3.1.1)
    - SDWebImage (= 5.9.0)
    - Toast (= 4.0.0)
    - TXIMSDK_iOS (= 5.0.6)
    - TXLiteAVSDK_TRTC (= 7.4.9203)
```

- 为什么不让使用动态库？

 https://github.com/tencentyun/TIMSDK/issues/364  这里说已解决，为什么又改回来了？

```
target 'TUIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
```

**Comment by smallyou** [comment]
> 【iOS】-【5.0.7】：【更新 `TXIMSDK_TUIKit_iOS` 后 `Masonry` 无法使用致程序闪退】
> 【集成包】：TUIKIT
> 【当前现象】：
> 
> SDK更新到5.0.7后程序闪退。
> 
> 最后找到是`Masonry`的原因。
> 
> 更新 `TXIMSDK_TUIKit_iOS` 导致 `Masonry` **无法使用？？？**
> 
> #### 下载官方Demo来重现Bug：
> 1. 下载并打开官方Demo 打开 **TUIKitDemo /TUIKitDemo.xcworkspace**
> 2. 修改：Podfile 添加 **Masonry**
> 
> ```
> # Uncomment the next line to define a global platform for your project
> source 'https://github.com/CocoaPods/Specs.git'
> platform :ios, '9.0'
> 
> target 'TUIKitDemo' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   #use_frameworks!
>   use_modular_headers!
> 
>   # Pods for Example
>   pod 'Masonry'
>   pod 'TXIMSDK_TUIKit_iOS'
> end
> ```
> 
> 安装更新： ` pod repo update`
> 
> 1. 修改 ConversationController.m 的 **viewDidLoad** 方法 添加**Masonry**代码
> 
> ```
> 		UIView *testView = [UIView new];
>     testView.backgroundColor = [UIColor redColor];
>     [self.view addSubview:testView];
>     [testView mas_makeConstraints:^(MASConstraintMaker *make) {
>         make.top.equalTo(self.view.mas_topMargin).mas_equalTo(100);
>         make.left.mas_equalTo(100);
>         make.width.height.mas_equalTo(100);
>     }];
> ```
> 
> 1. Run -> 报错闪退。
> 
> #### 尝试新建项目测试来确认是TXIMSDK_TUIKit_iOS的问题
> 1. Xcode新建一个**Test项目** 只导入`Masonry`
> 
> ```
> platform :ios, '9.0'
> target 'Test' do
>   use_frameworks!
>   pod 'Masonry'
> end
> ```
> 
> 1. 修改 ViewController 的 **viewDidLoad** 方法 添加**Masonry**代码
> 
> ```
> 	UIView *testView = [UIView new];
>     testView.backgroundColor = [UIColor redColor];
>     [self.view addSubview:testView];
>     [testView mas_makeConstraints:^(MASConstraintMaker *make) {
>         make.top.equalTo(self.view.mas_topMargin).mas_offset(100);
>         make.left.mas_equalTo(100);
>         make.width.height.mas_equalTo(100);
>     }];
> ```
> 
> 1. Run -> 正常渲染
> 
> 【机型】：iPhoneX iOS14、模拟器iPhone11 iOS14
> 【之前版本有无此问题】：更新之前用的 4.6.100版本是好的
> 【有无日志或者截图】：
> 
> > **2020-09-24 16:52:06.620699+0800 TUIKitDemo[4485:486225] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mas_topMargin]: unrecognized selector sent to instance 0x7fb2c9f96f30'**
> > **_*_ First throw call stack:**
> > **(**
> > ​	**0  CoreFoundation           0x00007fff2043a126 __exceptionPreprocess + 242**
> > ​	**1  libobjc.A.dylib           0x00007fff20177f78 objc_exception_throw + 48**
> > ​	**2  CoreFoundation           0x00007fff20448c6f +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0**
> > ​	**3  UIKitCore              0x00007fff24695af8 -[UIResponder doesNotRecognizeSelector:] + 292**
> > ​	**4  CoreFoundation           0x00007fff2043e666 _**forwarding**_ + 1489**
> > ​	**5  CoreFoundation           0x00007fff20440698 _CF_forwarding_prep_0 + 120**
> > ​	**6  TUIKitDemo             0x0000000100233a97 __37-[ConversationController viewDidLoad]_block_invoke + 183**
> > ​	**7  TUIKitDemo             0x000000010024b6a7 -[UIView(MASAdditions) mas_makeConstraints:] + 135**
> > ​	**8  TUIKitDemo             0x0000000100233913 -[ConversationController viewDidLoad] + 1923**
> > ​	**9  UIKitCore              0x00007fff23f2c73b -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 88**
> > ​	**10 UIKitCore              0x00007fff23f31022 -[UIViewController loadViewIfRequired] + 1084**
> > ​	**11 UIKitCore              0x00007fff23e6800e -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 162**
> > ​	**12 UIKitCore              0x00007fff23e682f8 -[UINavigationController _startTransition:fromViewController:toViewController:] + 154**
> > ​	**13 UIKitCore              0x00007fff23e69371 -[UINavigationController _startDeferredTransitionIfNeeded:] + 851**
> > ​	**14 UIKitCore              0x00007fff23e6a6dc -[UINavigationController __viewWillLayoutSubviews] + 150**
> > ​	**15 UIKitCore              0x00007fff23e4af1e -[UILayoutContainerView layoutSubviews] + 217**
> > ​	**16 UIKitCore              0x00007fff24bbd9ce -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2874**
> > ​	**17 QuartzCore             0x00007fff27a3dd87 -[CALayer layoutSublayers] + 258**
> > ​	**18 QuartzCore             0x00007fff27a44239 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575**
> > ​	**19 QuartzCore             0x00007fff27a4ff91 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65**
> > ​	**20 QuartzCore             0x00007fff27990078 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496**
> > ​	**21 QuartzCore             0x00007fff279c6e13 _ZN2CA11Transaction6commitEv + 783**
> > ​	**22 QuartzCore             0x00007fff279c7fcf _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79**
> > ​	**23 CoreFoundation           0x00007fff203a76b3 **CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 23**
> > ​	**24 CoreFoundation           0x00007fff203a1f3f __CFRunLoopDoObservers + 547**
> > ​	**25 CoreFoundation           0x00007fff203a24e2 __CFRunLoopRun + 1113**
> > ​	**26 CoreFoundation           0x00007fff203a1b9e CFRunLoopRunSpecific + 567**
> > ​	**27 GraphicsServices          0x00007fff2b773db3 GSEventRunModal + 139**
> > ​	**28 UIKitCore              0x00007fff24660af3 -[UIApplication _run] + 912**
> > ​	**29 UIKitCore              0x00007fff24665a04 UIApplicationMain + 101**
> > ​	**30 TUIKitDemo             0x000000010022ec60 main + 112**
> > ​	**31 libdyld.dylib            0x00007fff20257415 start + 1**
> > ​	**32 ???                 0x0000000000000001 0x0 + 1**
> > **)**
> > **libc++abi.dylib: terminating with uncaught exception of type NSException**
> > *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView mas_topMargin]: unrecognized selector sent to instance 0x7fb2c9f96f30'
> > terminating with uncaught exception of type NSException
> > CoreSimulator 732.17 - Device: iPhone 11 Pro Max (55376F1B-CFFF-40B3-B2B0-8DAC29D98525) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11 Pro Max

===============

使用masonry的方式不对

make.top.equalTo(self.view.mas_topMargin).mas_equalTo(100);

masonry官方说明中，如果直接使用equalTo需要定义指定的宏，可以试着将其修改为

make.top.mas_equalTo(self.view.mas_topMargin).mas_equalTo(100);

**Comment by smallyou** [comment]
> ## 可以吐槽一下吗？
> * 为什么依别的库还要限制版本？
> 
> 想请问：项目里依赖SDWebImage Toast ReactiveObjC，他们更新后我们如何更新？
> 
> ```
> - TXIMSDK_TUIKit_iOS (5.0.7):
>     - MMLayout (= 0.2.0)
>     - ReactiveObjC (= 3.1.1)
>     - SDWebImage (= 5.9.0)
>     - Toast (= 4.0.0)
>     - TXIMSDK_iOS (= 5.0.6)
>     - TXLiteAVSDK_TRTC (= 7.4.9203)
> ```
> 
> * 为什么不让使用动态库？
> 
> #364 这里说已解决，为什么又改回来了？
> 
> ```
> target 'TUIKitDemo' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   #use_frameworks!
> ```

==============

由于依赖的第三方库有静态库，所以不能使用use_frameworks!     cocoapods 1.9.0 新增了新特性，可以支持，修改podfile文件，增加下面内容：

use_frameworks! :linkage => :static
