### ISSUE TITLE
【iOS】4.8.50升到5.0.6直接编不过

### ISSUE THREAD

**Issue by Meterwhite** [tencentyun/TIMSDK#861]
【iOS】-【5.0.6】：【4.8.50升到5.0.6直接编不过】
issue内容：

【当前现象】：编译不通过
【集成包】：IMSDK
  xcode 11
  pod 'TXIMSDK_iOS'
  pod 'TXLiteAVSDK_TRTC'
  手动导入的TUIKit
  其他依赖：
  pod 'ISVImageScrollView', '~> 0.1.2'
  pod 'ReactiveObjC'
  pod 'SDWebImage'
  pod 'Toast'
  pod 'SnapKit'
  pod 'Toast-Swift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NVActivityIndicatorView'
  pod 'Material'
  pod 'Alamofire'
 
<img width="881" alt="1WX20201007-225318@2x" src="https://user-images.githubusercontent.com/9498919/95348515-b3ffef80-08f0-11eb-8e00-aa3c727a3672.png">

<img width="879" alt="2WX20201007-225342@2x" src="https://user-images.githubusercontent.com/9498919/95348546-b9f5d080-08f0-11eb-8298-6bb794eca99f.png">

我把版本回滚4.8.50是可以编过的。

**Comment by wenhaiwang** [comment]
请问 你解决了吗?

**Comment by Meterwhite** [comment]
> 请问 你解决了吗?

没有，你也遇到了吗？

**Comment by boai** [comment]
新版本去掉了好多东西，自定义消息都发不了了

**Comment by wenhaiwang** [comment]
> 新版本去掉了好多东西，自定义消息都发不了了

最新的是 5.0.6 吧,  你这是 mac 版本吗

**Comment by 173315179** [comment]
这个是 改一下File->Workspace setting->build System 模式应该就好了

**Comment by Meterwhite** [comment]
> 这个是 改一下File->Workspace setting->build System 模式应该就好了

使用旧编译系统能通过，但这种方式并不是恰当的。这个问题本身是TIM造成的，需要解决问题。

**Comment by Meterwhite** [comment]
> 好像升级到 5.0.10 可以编过。

你试成功了吗。我试的时候没有。

**Comment by 173315179** [comment]
这个跟Xcode 版本有点关系 你升级到xocde 12 不用改也能编译过

**Comment by CoderAFI** [comment]
对，我用的 xcode 12.

**Comment by smallyou** [comment]
是的，修改成File->Workspace setting->build System即可
新版xcode不会出现该问题
