### ISSUE TITLE
【iOS】-【5.0.7】：【V2TIMCustomElem 不支持 addElem】

### ISSUE THREAD

**Issue by boai** [tencentyun/TIMSDK#862]
【iOS】-【5.0.7】：【V2TIMCustomElem 不支持 addElem】

【当前现象】：发送自定义消息 V2TIMCustomElem 不支持 addElem，旧版本 TIMCustomElem 是支持的
【集成包】：TXIMSDK_TUIKit_iOS
【机型】：iPhone 7 Plus
【之前版本有无此问题】：如4.6.58之前没有，5.0.7有
TUIMessageCellData 之前的 innerMessage 是可读可写，新版本换成 V2TIMMessage 之后，里面所有东西都只读了，
那怎么发送自定义消息？
<img width="710" alt="image" src="https://user-images.githubusercontent.com/13014692/95648323-d66c5580-0b08-11eb-861f-6744825fe345.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/13014692/95648336-e3894480-0b08-11eb-866e-c7328a2f9717.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/13014692/95648351-f8fe6e80-0b08-11eb-9186-3e8d76c93e51.png">

你们发布这些SDK 都不内测吗？

【有无日志或者描述、截图】：
<img width="653" alt="image" src="https://user-images.githubusercontent.com/13014692/95648193-eb94b480-0b07-11eb-8c9b-31502d38b0ac.png">

**Comment by 173315179** [comment]
V2版本自定义消息不在 用Elem添加 给出了新的消息创建
<img width="820" alt="企业微信截图_8133879c-ec6e-4eba-989a-0c2396fa8790" src="https://user-images.githubusercontent.com/12524416/95711352-2841e680-0c95-11eb-80f8-052cd3fc42cb.png">

**Comment by boai** [comment]
> V2版本自定义消息不在 用Elem添加 给出了新的消息创建
> <img alt="企业微信截图_8133879c-ec6e-4eba-989a-0c2396fa8790" width="820" src="https://user-images.githubusercontent.com/12524416/95711352-2841e680-0c95-11eb-80f8-052cd3fc42cb.png">

我封装了自定义消息的cellData，里面的字典内容需要特殊处理，比如小程序、web多端交互消息类型，V2 版本只用一个data怎么处理？我怎么创建当前的cellData?

**Comment by 173315179** [comment]
这个消息类型都可以穿在data里面  你传什么给服务端，服务端返回给你什么
<img width="1000" alt="企业微信截图_e80464a5-689d-448f-a101-01f75557ac7d" src="https://user-images.githubusercontent.com/12524416/95714375-b7053200-0c9a-11eb-96db-648c03762a65.png">

**Comment by boai** [comment]
> 这个消息类型都可以穿在data里面 你传什么给服务端，服务端返回给你什么
> <img alt="企业微信截图_e80464a5-689d-448f-a101-01f75557ac7d" width="1000" src="https://user-images.githubusercontent.com/12524416/95714375-b7053200-0c9a-11eb-96db-648c03762a65.png">

收到，我回头试试看，多谢大佬！
