### ISSUE TITLE
【Android & IOS】-【5.0.10】：【V2TIMManager 不支持 findMessage】

### ISSUE THREAD

**Issue by JiangJuHong** [tencentyun/TIMSDK#877]
【当前现象】：V2TIMManager 不支持 findMessage
【集成包】：IMSDK
【机型】：All
【之前版本有无此问题】：4.x 可通过`TIMConversation`对象中调用`findMessage`接口
【有无日志或者描述、截图】：无

目前需要通过 findMessage 查找到 V2TIMMessage，然后调用revokeMessage方法，请问是否有类似接口(接口文档中没找到)。如果没有，近期是否会有支持计划。

感谢。

**Comment by smallyou** [comment]
这个接口可以满足需求不

**Comment by smallyou** [comment]
/**
 *  4.9 根据 messageID 查询指定会话中的本地消息
 *  @param messageIDList 消息 ID 列表
 */
- (void)findMessages:(NSArray<NSString *>*)messageIDList succ:(V2TIMMessageListSucc)succ fail:(V2TIMFail)fail;

**Comment by JiangJuHong** [comment]
你好，请问这个接口属于哪个管理器，我在Android和IOS中均为找到

**Comment by JiangJuHong** [comment]
以message管理器，目前Android和IOS序列号最多为4.8，暂未找到4.9
![image](https://user-images.githubusercontent.com/17740963/97550602-da570d80-1a0c-11eb-84ab-d18dcd2052d9.png)
![image](https://user-images.githubusercontent.com/17740963/97550671-f064ce00-1a0c-11eb-99b8-1c5d7cea2cbc.png)

**Comment by smallyou** [comment]
近两天会更新，稍等下

**Comment by JiangJuHong** [comment]
好的，感谢
