### ISSUE TITLE
【Taro】-【3.0.15】：【集成tim-js-sdk报错】

### ISSUE THREAD

**Issue by xuya227939** [tencentyun/TIMSDK#878]
issue内容：

【当前现象】：集成tim-js-sdk报错
【集成包】：npm tim-js-sdk
【机型】：微信开发者工具
【之前版本有无此问题】：Taro2.1.5可以完美集成
【有无日志或者描述、截图】：
![image](https://user-images.githubusercontent.com/16217324/97387475-08572780-1911-11eb-98ca-6df372b092b7.png)

**Comment by rsbella** [comment]
2.8.0对Taro 3.x 集成 WebIM 时的兼容性问题有做修复，请升级sdk到最新版本再尝试看看

**Comment by xuya227939** [comment]
@rsbella 感谢，已解决。
