### ISSUE TITLE
【iOS-Swift】- 5.0.10 : pod install error

### ISSUE THREAD

**Issue by baiyidjp** [tencentyun/TIMSDK#879]
`
  pod 'TXIMSDK_TUIKit_iOS', '5.0.10'
  pod 'TXIMSDK_iOS', '5.0.10'

Swift 项目， 使用了use_frameworks!      pod  install 之后报错

The 'Pods-StaffApp' target has transitive dependencies that include statically linked binaries: (/Users/peng/Desktop/SteyCode/StaffApp/Pods/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC.framework)

OC项目没有问题
`

**Comment by baiyidjp** [comment]
pod 'TXIMSDK_TUIKit_iOS', '4.6.100'
  pod 'TXIMSDK_iOS', '4.7.1'

这个版本在Swift项目还是可以用的，不知道为啥新版的不能用

**Comment by lynxzhang** [comment]
新版本 TUIKit 集成了 TXLiteAVSDK_TRTC 音视频静态库，这里需要屏蔽 use_frameworks!

**Comment by lynxzhang** [comment]
https://cloud.tencent.com/document/product/269/37060#cocoapods-.E9.9B.86.E6.88.90.EF.BC.88.E6.8E.A8.E8.8D.90.EF.BC.89

**Comment by baiyidjp** [comment]
> 新版本 TUIKit 集成了 TXLiteAVSDK_TRTC 音视频静态库，这里需要屏蔽 use_frameworks!

Swift是需要加的吧？

**Comment by hpzerozero** [comment]
我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理

**Comment by hpzerozero** [comment]
> 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理
问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
use_frameworks! :linkage => :static

**Comment by hpzerozero** [comment]
> 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理


问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
use_frameworks! :linkage => :static

**Comment by PSSDeveloper** [comment]
> > 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理
> 
> 问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
> use_frameworks! :linkage => :static

你好，请问你这样设置之后，在Swift项目中引入 import TXIMSDK_TUIKit_iOS 编译会报Could not build Objective-C module 'TXIMSDK_TUIKit_iOS'的错误码？

**Comment by hpzerozero** [comment]
> > > 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理
> 
> > 
> 
> > 问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
> 
> > use_frameworks! :linkage => :static
> 
> 
> 
> 你好，请问你这样设置之后，在Swift项目中引入 import TXIMSDK_TUIKit_iOS 编译会报Could not build Objective-C module 'TXIMSDK_TUIKit_iOS'的错误码？



我这是oc项目，Swift要使用的话我放桥接文件，目前没问题。Swift项目没试过，不知道会不会报这个错误

**Comment by smallyou** [comment]
> > 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理
> 
> 问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
> use_frameworks! :linkage => :static

此种方式可以解决，如果是swift项目，尝试将头文件引用修改成@import模块名引入方式

**Comment by baiyidjp** [comment]
> > > 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理
> > 
> > 
> > 问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
> > use_frameworks! :linkage => :static
> 
> 此种方式可以解决，如果是swift项目，尝试将头文件引用修改成@import模块名引入方式

OK，我准备尝试下

**Comment by baiyidjp** [comment]
> > > 我OC和Swift混编项目，现在就因为这个use_frameworks!没法集成，OC需要去掉，而Swift需要加上，这叫我如何处理
> > 
> > 
> > 问题解决，没有去掉use_frameworks!，而是换成下面这行，就可以pod成功了
> > use_frameworks! :linkage => :static
> 
> 此种方式可以解决，如果是swift项目，尝试将头文件引用修改成@import模块名引入方式

pod之后还是报错。跟我刚开始一样

**Comment by smallyou** [comment]
use_frameworks! :linkage => :static 是cocoapods 1.9.0新支持的特性    看看cocoapods的版本

**Comment by RogerAbyss** [comment]
> use_frameworks! :linkage => :static 是cocoapods 1.9.0新支持的特性 看看cocoapods的版本

Swift项目, 也使用了动态库。使用use_frameworks! :linkage, 更多的报错...有没有其他解决办法

**Comment by smallyou** [comment]
请列出其他的报错信息
