### ISSUE TITLE
【小程序版本】：【SDK有支持小程序框架mpvue吗？】

### ISSUE THREAD

**Issue by wjf9492** [tencentyun/TIMSDK#88]
SDK有支持小程序框架mpvue吗？

**Comment by yangq1990** [comment]
有的哈。请参考以下内容：

新版小程序 im:
https://github.com/tencentyun/TIMSDK/tree/master/WXMini
sdk文档：
https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/TIM.html
