### ISSUE TITLE
【iOS】-【5.0.10】：【TXIMSDK_TUIKit_iOS 和 TXLiteAVSDK_Professional 同时集成会有很多重复文件】

### ISSUE THREAD

**Issue by boai** [tencentyun/TIMSDK#881]
【iOS】-【5.0.10】：【TXIMSDK_TUIKit_iOS 和 TXLiteAVSDK_Professional 同时集成会有很多重复文件】
【集成包】：TXIMSDK_TUIKit_iOS TXLiteAVSDK_Professional
【当前现象】：xcode 集成新版本TUIKit，报错，无法编译通过
【机型】：11
【之前版本有无此问题】：TUIKIT 4.6.58版本之前没有，5.0.10有

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/13014692/97966528-ea009880-1df6-11eb-8fc8-44088d9dced4.png">

duplicate symbol '_OBJC_IVAR_$_TXCTwoPassFilter.secondOutputFramebuffer' in:
    /Users/**/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/TXLiteAVSDK_Professional(TXCTwoPassFilter.o)
    /Users/**/Pods/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC/TXLiteAVSDK_TRTC.framework/TXLiteAVSDK_TRTC(TXCTwoPassFilter.o)

**Comment by hunanldc** [comment]
podfile文件内容发一下。
从报错上看，是因为同时集成了:TXLiteAVSDK_TRTC+TXLiteAVSDK_Professional。
这两个只需要集成一个即可。

**Comment by boai** [comment]
> podfile文件内容发一下。
> 从报错上看，是因为同时集成了:TXLiteAVSDK_TRTC+TXLiteAVSDK_Professional。
> 这两个只需要集成一个即可。

是的，我们要集成直播和IM ，两个都要用，请问具体使用哪个 pod?

**Comment by smallyou** [comment]
腾讯云的 音视频库 不能同时集成，会有符号冲突，如果您使用了非 TRTC 版本的音视频库，建议先去掉，然后 pod 集成 TXIMSDK_TUIKit_iOS_Professional 版本，该版本依赖的 LiteAV_Professional 音视频库包含了音视频的所有基础能力。

集成 TXIMSDK_TUIKit_iOS_Professional  这个

**Comment by boai** [comment]
> 腾讯云的 音视频库 不能同时集成，会有符号冲突，如果您使用了非 TRTC 版本的音视频库，建议先去掉，然后 pod 集成 TXIMSDK_TUIKit_iOS_Professional 版本，该版本依赖的 LiteAV_Professional 音视频库包含了音视频的所有基础能力。
> 
> 集成 TXIMSDK_TUIKit_iOS_Professional 这个

@smallyou 多谢大佬，已经集成好了！

**Comment by boai** [comment]
TXIMSDK_TUIKit_iOS_Professional 这个库现在不更新了吗？
