### ISSUE TITLE
ios SDK pod 还是4.2.28 什么时候更新呀？

### ISSUE THREAD

**Issue by ppqx** [tencentyun/TIMSDK#89]

**Comment by lynxzhang** [comment]
-> TXIMSDK_iOS (4.2.52)
   TXIMSDK_iOS
   pod 'TXIMSDK_iOS', '~> 4.2.52'
   - Homepage: https://cloud.tencent.com/document/product/269/3794
   - Source:   https://github.com/tencentyun/TIMSDK.git
   - Versions: 4.2.52, 4.2.28, 4.2.10, 4.2.9, 4.2.2, 4.2.1, 4.0.13, 4.0.12,
   4.0.10, 4.0.8, 4.0.7, 4.0.4, 4.0.3, 4.0.2, 4.0.1 [master repo]

**Comment by lynxzhang** [comment]
pod 已更新
