### ISSUE TITLE
[Flutter] 麻烦腾讯的看下这个库是不是你们的？

### ISSUE THREAD

**Issue by CListery** [tencentyun/TIMSDK#896]
https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin

昨天咨询过腾讯云的客服说是腾讯云国际站的，但是我在国际站上并没有找到相关文档

@parkhuang

**Comment by JunkmenDream** [comment]
是的，目前还没有对外开放，还数据测试阶段，等我们测试后好，会选择一些需要使用flutter的用户开始接入。

给您带来不便，请谅解。

**Comment by JunkmenDream** [comment]
是的，目前还没有对外开放，还在测试阶段，等我们测试后好，会选择一些需要使用flutter的用户开始接入。

给您带来不便，请谅解。

**Comment by JunkmenDream** [comment]
> https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin
> 
> 昨天咨询过腾讯云的客服说是腾讯云国际站的，但是我在国际站上并没有找到相关文档
> 
> park

您好，目前 flutter sdk 已经开发完成，准备内测发布。如您有需要，可以提供下QQ。如接入中有问题可随时与我们联系，感谢支持。

**Comment by CListery** [comment]
> > https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin
> > 昨天咨询过腾讯云的客服说是腾讯云国际站的，但是我在国际站上并没有找到相关文档
> > park
> 
> 您好，目前 flutter sdk 已经开发完成，准备内测发布。如您有需要，可以提供下QQ。如接入中有问题可随时与我们联系，感谢支持。

QQ:  1083088795

**Comment by gxhjsnt** [comment]
> > https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin
> > 昨天咨询过腾讯云的客服说是腾讯云国际站的，但是我在国际站上并没有找到相关文档
> > park
> 
> 您好，目前 flutter sdk 已经开发完成，准备内测发布。如您有需要，可以提供下QQ。如接入中有问题可随时与我们联系，感谢支持。

您好，我们也在开发flutter im，可以协助测试，QQ:492670

**Comment by 152dyn** [comment]
> > https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin
> > 昨天咨询过腾讯云的客服说是腾讯云国际站的，但是我在国际站上并没有找到相关文档
> > park
> 
> 您好，目前 flutter sdk 已经开发完成，准备内测发布。如您有需要，可以提供下QQ。如接入中有问题可随时与我们联系，感谢支持。

您好，我们也在开发flutter im，可以协助测试，QQ:823150076

**Comment by fearclear** [comment]
> > https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin
> > 昨天咨询过腾讯云的客服说是腾讯云国际站的，但是我在国际站上并没有找到相关文档
> > park
> 
> 您好，目前 flutter sdk 已经开发完成，准备内测发布。如您有需要，可以提供下QQ。如接入中有问题可随时与我们联系，感谢支持。

您好，我们目前已使用了微信和网页的sdk，最近有计划使用flutter开发，可以协助测试，QQ：527085767

**Comment by bai-3** [comment]
您好，我们也在开发flutter im，可以协助测试，QQ:422145328

**Comment by hexingcheng** [comment]
>



> 您好，我们也在开发flutter im，可以协助测试，QQ:422145328

加群：788910197
