### ISSUE TITLE
版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！

### ISSUE THREAD

**Issue by Combome** [tencentyun/TIMSDK#9]
版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！版本号4.0.0.1导致上架失败！官方要求三位不为负数，你们能不能长点心！！！

**Comment by vinsonswang** [comment]
请问是哪个应用市场要求版本号只能三位的呢？
除了检查App的版本号，也会检查使用的sdk的版本号吗？

**Comment by ywdonga** [comment]
上个版本正常上架，这个版本加入`ImSDK`完全没法上架呀，打包提交到App Store就报错了，希望尽快修复，等着上线呢。
<img width="745" alt="image" src="https://user-images.githubusercontent.com/16291063/52535048-7007c080-2d84-11e9-89e6-50b7072024f6.png">

**Comment by lynxzhang** [comment]
问题已经优化，麻烦更新新的版本
