### ISSUE TITLE
getRecvFlag 群组消息通知类型永远为ReceiveAndNotify

### ISSUE THREAD

**Issue by liukai2530533** [tencentyun/TIMSDK#908]
之前版本4.4.900
升级之后当前版本为5.0.6

之前的版本再群里面设置消息接收类型为接收不提示，然后再收到消息的回调中通过
msg.getRecvFlag() == TIMGroupReceiveMessageOpt.ReceiveNotNotify
判断是否是这个消息接收类型选择不弹通知

现在升级版本到5.0.6之后msg.getRecvFlag() 过时了 并且不管怎么设置群的消息接收类型，永远得到是ReceiveAndNotify，请问这个问题该如何解决

**Comment by mayifan0908** [comment]
同问

**Comment by mayifan0908** [comment]
同问，4.9.1只有setReceiveMessageOpt 没有get方法.通过TIMGroupManager.ModifyMemberInfoParam.getReceiveMessageOpt()获取到的也永远是ReceiveAndNotify
