### ISSUE TITLE
【小程序版本】：【有没有小程序单聊的demo？】

### ISSUE THREAD

**Issue by renxiao1218** [tencentyun/TIMSDK#91]

**Comment by lynxzhang** [comment]
小程序 demo 正在紧锣密鼓开发中，敬请等待

**Comment by yangq1990** [comment]
hi，请参考以下内容：

新版小程序 im:
https://github.com/tencentyun/TIMSDK/tree/master/WXMini
sdk文档：
https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/TIM.html
