### ISSUE TITLE
【小程序】-【tim-wx-sdk  ^2.8.4】：【严格根据官方文档的教程，调用 createImageMessage 报错】

### ISSUE THREAD

**Issue by AlkVo** [tencentyun/TIMSDK#915]
【小程序】-【tim-wx-sdk   2.8.4】：【严格根据官方文档的教程，调用 createImageMessage 报错】
【当前现象】：根据官方文档，将 wx.chooseImage 的 success 回调的 res 值，作为 payload.file 传入 createImageMessage 时，报错。
【集成包】：tim-wx-sdk_2.8.4
【小程序框架】：Taro_3.0.17
【之前版本有无此问题】：不知
【有无日志或者描述、截图】
报错如下:
`MiniProgramError
HTMLInputElement is not defined
ReferenceError: HTMLInputElement is not defined`

【官方文档】：https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#createImageMessage
【❌暂时解决方案】：将 tim-wx.js 中的以下代码注释掉，暂时忽略该错误。接下去能成功完成 sendMessage 操作。
`                        if (! (e.file instanceof HTMLInputElement || de(e.file))) return console.warn(to({
                            api: "createImageMessage",
                            param: "payload.file",
                            desc: "类型必须是 HTMLInputElement 或 File"
                        })),
                        !1;
                        if (e.file instanceof HTMLInputElement && 0 === e.file.files.length) return console.warn(to({
                            api: "createImageMessage",
                            param: "payload.file",
                            desc: "您没有选择文件，无法发送"
                        })),
                        !1`

**Comment by yangq1990** [comment]
![image](https://user-images.githubusercontent.com/6194380/108796124-f89bd700-75c2-11eb-8319-ef0a27f5e6e9.png)

请升级到v2.9.2或更高版本
