### ISSUE TITLE
IM登录成功后设置自己的资料报错闪退了

### ISSUE THREAD

**Issue by AnJiuZhe** [tencentyun/TIMSDK#93]
下面是代码和错误日志。
![image](https://user-images.githubusercontent.com/30287547/56633002-ee3ee800-668e-11e9-8084-0a3f1bc6fc3c.png)
![image](https://user-images.githubusercontent.com/30287547/56633033-10d10100-668f-11e9-9af1-04f2ca029035.png)

**Comment by AnJiuZhe** [comment]
用上一个版本4.2.28就没问题，新版bug有点多啊。还有就是demo很多功能不是很完善，特别是头像和昵称的处理逻辑没有，这个是最基本的吧。

**Comment by AnJiuZhe** [comment]
希望大佬们完善下，辛苦了！！！

**Comment by lynxzhang** [comment]
您好，感谢您的反馈，今天会发最新的版本修复这个问题，demo 的问题这个版本也做了一些优化，后续版本会重点优化demo的问题
