### ISSUE TITLE
【iOS】-【5.1.13】：【无法解析组合消息中的自定义消息】

### ISSUE THREAD

**Issue by syq7970** [tencentyun/TIMSDK#935]
【iOS】-【5.1.13】：【无法解析组合消息中的自定义消息】
根据文档构造了类似这种的组合消息：
```
{
    "MsgBody": [
        {
            "MsgType": "TIMTextElem", 
            "MsgContent": {
                "Text": "hello"
            }
        }, 
        {
            "MsgType": "TIMCustomElem", 
            "MsgContent": {
                "Index": 1, 
                "Data": "content"
            }
        }
    ]
}
```
在onNewMessage回调里面的V2TimMessage对象只有TextElem而没有CustomElem，安卓版可以正常解析。

**Comment by Tencent-Alice** [comment]
您好，已与您沟通提供了相关步骤解决 。如下 
需求：
需要在普通文本消息里面扩展一些字段
1、发送方：创建文本消息：http://doc.qcloudtrtc.com/im/categoryV2TIMManager_07Message_08.html#a609f4d4c374d9df3abf9974ff8112fc3
 然后添加一个elem元素：http://doc.qcloudtrtc.com/im/interfaceV2TIMTextElem.html
2、接收方：收到消息后判断消息类型 然后解析取第一个 Elem，然后在取后面的：https://cloud.tencent.com/document/product/269/44490#3.-.E6.9C.89.E5.A4.9A.E4.B8.AA-elem-.E7.9A.84.E6.B6.88.E6.81.AF.E5.BA.94.E8.AF.A5.E5.A6.82.E4.BD.95.E8.A7.A3.E6.9E.90.EF.BC.9F
如后续遇到问题，欢迎反馈。Q2562367495 注明来意 ，感谢您对腾讯云的支持
