### ISSUE TITLE
webSdk有获取历史记录的接口，为什么不能有删除消息的接口？

### ISSUE THREAD

**Issue by bbc-594** [tencentyun/TIMSDK#936]
【TIM 】-【2.9.1】：【TIM 没有删除聊天消息的接口】
【集成包】：TIM 
【当前现象】：TIM获取历史消息，但是没有删除聊天消息的接口
【机型】：
【之前版本有无此问题】：有
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/45661726/103389782-edd93e80-4b4b-11eb-847c-2cb727e4d44d.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的描述，了解到使用是V1版本，最新版本已优化删除消息相关需求，具体和您确认具体的群组类型https://cloud.tencent.com/document/product/269/2359可参考 
如有技术问题，欢迎私信Q2562367495，注明来意 ，感谢您对腾讯云的支持
