### ISSUE TITLE
【小程序】-【tim-wx-sdk ^2.9.1】：【严格根据官方文档的教程，调用 createVideoMessage报错】

### ISSUE THREAD

**Issue by lmm1990** [tencentyun/TIMSDK#938]
【小程序】-【tim-wx-sdk 2.9.1】：【严格根据官方文档的教程，调用 createVideoMessage报错】
【当前现象】：根据官方文档，将 wx.chooseVideo 的 success 回调的 res 值，作为 payload.file 传入 createVideoMessage时，报错。
【集成包】：tim-wx-sdk_2.9.1
【小程序框架】：Taro v3.1.0-beta.4
【之前版本有无此问题】：不知
【有无日志或者描述、截图】
报错如下:
ReferenceError: HTMLInputElement is not defined
类型必须是 HTMLInputElement 或 File

createVideoMessage: {
      to: no,
      conversationType: no,
      payload: u(u({}, ro), {}, {
        validator: function validator(e) {
          if (!ye(e)) return console.warn(to({
            api: "createVideoMessage",
            param: "payload",
            desc: "类型必须为 plain object"
          })), !1;
          if (Me(e.file)) return console.warn(to({
            api: "createVideoMessage",
            param: "payload.file",
            desc: "不能为 undefined"
          })), !1;

          if (G) {
            if (!(e.file instanceof HTMLInputElement || me(e.file))) return console.warn(to({
              api: "createVideoMessage",
              param: "payload.file",
              desc: "类型必须是 HTMLInputElement 或 File"
            })), !1;
            if (e.file instanceof HTMLInputElement && 0 === e.file.files.length) return console.warn(to({
              api: "createVideoMessage",
              param: "payload.file",
              desc: "您没有选择文件，无法发送"
            })), !1;
          }

          return !0;
        }
      }),
      onProgress: {
        type: "Function",
        required: !1,
        validator: function validator(e) {
          return Me(e) && console.warn(to({
            api: "createVideoMessage",
            desc: "没有 onProgress 回调，您将无法获取上传进度"
          })), !0;
        }
      }
    },

【官方文档】：https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#createVideoMessage

https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseVideo.html

选择视频后，res既不是HTMLInputElement 也不是file

**Comment by lmm1990** [comment]
暂时解决办法：
注释以下代码
// if (G) {
                    //     if (! (e.file instanceof HTMLInputElement || me(e.file))) return console.warn(to({
                    //         api: "createVideoMessage",
                    //         param: "payload.file",
                    //         desc: "类型必须是 HTMLInputElement 或 File"
                    //     })),
                    //     !1;
                    //     if (e.file instanceof HTMLInputElement && 0 === e.file.files.length) return console.warn(to({
                    //         api: "createVideoMessage",
                    //         param: "payload.file",
                    //         desc: "您没有选择文件，无法发送"
                    //     })),
                    //     !1
                    // }

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，需要您提供以下信息，以便这边为您处理
1 请问您选择的视频时来源于相册还是来源于拍摄的画面，您可以提供一下
技术问题，欢迎私信，Q2562367495 注明来意

**Comment by lmm1990** [comment]
已添加：Q2736618530 问题正在解决中

**Comment by Tencent-Alice** [comment]
OK，可以

**Comment by lmm1990** [comment]
@Tencent-Alice 
这个问题的原因：
tim-wx-sdk 中 判断环境的代码    G = "undefined" != typeof window,
![image](https://user-images.githubusercontent.com/4828501/103848775-1cbc5b00-50de-11eb-8596-758d57ee3bfa.png)
taro框架自己模拟了个window对象，导致的

tim-wx-sdk是否可以公开一个设置环境的方法

如：
/**
* @param environmentType 环境：1、web，2、小程序
*/
setEnvironment(environmentType:number){
*******
}

**Comment by yangq1990** [comment]
![image](https://user-images.githubusercontent.com/6194380/108796099-e9b52480-75c2-11eb-8958-5c85adeba6b8.png)

请升级到v2.9.2或更高版本
