### ISSUE TITLE
iOS在调用modifySelfProfile 设置了昵称后，别的用户在getSenderProfile里经常出现获取不到昵称。

### ISSUE THREAD

**Issue by ZiShengXie** [tencentyun/TIMSDK#94]
iOS在调用modifySelfProfile 设置了昵称后，别的用户在getSenderProfile里经常出现获取不到昵称。头像设置后能通过getSenderProfile正常获取，但是昵称设置后老会变成@""。
SDK为pod集成：
Using TXIMSDK_TUIKit_iOS (4.2.52)
Using TXIMSDK_iOS (4.2.52)

**Comment by lynxzhang** [comment]
感谢您的反馈，我们定位下，如果有问题会在下个版本修复，您可以先通过 getUsersProfile 接口获取下用户的昵称。
