### ISSUE TITLE
关于TXLiteAVSDK BitCode的兼容

### ISSUE THREAD

**Issue by MourinhoLove** [tencentyun/TIMSDK#946]
【iOS】-【5.1.2】：【关于TXLiteAVSDK BitCode的编译报错】
【集成包】：TUIKIT
【当前现象】：集成TXIMSDK_TUIKit_iOS_Professional，编译出现 TXLiteAVSDK BitCode的错误。。。。是否一定要关闭bitcode？
【机型】：iPhone XR
【之前版本有无此问题】：暂无报告
【有无日志或者截图】：暂无日志

**Comment by Tencent-Alice** [comment]
您好，关于您的问题， 先提供下报错和说明下具体的操作过程，这边看下报错信息，才能核实回复 
如有技术问题 欢迎交流 Q2562367495 注明来意

**Comment by MourinhoLove** [comment]
就是继承通过cocoapods集成TUIKit。之后项目真机运行的时候提示TXLiteAVSDK BitCode的错误。关闭bitcode后。错误消失

**Comment by Tencent-Alice** [comment]
您好，尝试关闭bitcode运行是否正常，若运行无误，建议您关闭。
关于bitcode的是否开启，参考
https://www.jianshu.com/p/6042a734db69
如有技术问题 欢迎交流 Q2562367495 注明来意

**Comment by MourinhoLove** [comment]
好的，好的
