### ISSUE TITLE
腾讯IM群组管理设置管理员报错10007

### ISSUE THREAD

**Issue by xiaoyu915** [tencentyun/TIMSDK#953]
【Android】：【腾讯IM群组管理设置管理员报错10007】
【集成包】：imsdk 4.6.51
【当前现象】：TIMGroupManager.ModifyMemberInfoParam param = new TIMGroupManager.ModifyMemberInfoParam(groupId, identifier);
param.setRoleType(TIMGroupMemberRoleType.ROLE_TYPE_ADMIN);
TIMGroupManager.getInstance().modifyMemberInfo(param, new TIMCallBack() {
            @Override
            public void onError(int code, String desc) {
                Log.e(tag, "设置管理员failed, code:" + code + "|msg: " + desc);
            }

            @Override
            public void onSuccess() {
                Log.d(tag, "modifyMemberInfo succ");
            }
        });
房间类型为ChatRoom
【机型】：华为荣耀8

**Comment by Tencent-Alice** [comment]
您好，根据您的描述 您是哪个角色进行设置的管理员 
提供下sdkappid、群组id 和设置者userid、被设置者userid 具体确认下 
技术问题  欢迎交流 Q2562367495 注明来意

**Comment by xiaoyu915** [comment]
> 您好，根据您的描述 您是哪个角色进行设置的管理员
> 提供下sdkappid、群组id 和设置者userid、被设置者userid 具体确认下
> 技术问题 欢迎交流 Q2562367495 注明来意

已解决。我这边userId传错了，被设置者id传的是群主
