### ISSUE TITLE
小程序消息撤回

### ISSUE THREAD

**Issue by mengSmile** [tencentyun/TIMSDK#954]
小程序撤回消息的时候 revokeMessgae(message) 里边的message如何构建 不能直接传消息列表中的message吗

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 接口的传参可以设置为收到的消息对象：https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#revokeMessage
![image](https://user-images.githubusercontent.com/74762384/106226046-4cfca280-6221-11eb-8904-2ec6e727ffe2.png)
消息体打印
![image](https://user-images.githubusercontent.com/74762384/106226077-5e45af00-6221-11eb-989f-2924314c6d50.png)
希望可以帮到您
