### ISSUE TITLE
初始化本地存储， TIMManagerExt.getInstance().initStorage sdk没有实现吧

### ISSUE THREAD

**Issue by zhangxi28** [tencentyun/TIMSDK#96]
public int initStorage(@nonnull String identifier, @nonnull TIMCallBack cb) {
return 0;
}
请问这是什么情况

**Comment by lynxzhang** [comment]
您好，这个接口还未实现，后面的版本会优化

**Comment by zhangxi28** [comment]
好的，希望你们能尽快支持

**Comment by shingohu** [comment]
搞不明白,老版本都有,新版就没了

**Comment by todo-fixme** [comment]
IM 新版本 v3 开始到现在 v4 是换了 TEAM ,重构了吗？
@zhangxi28

**Comment by iOSniuniu** [comment]
V3 上的功能 少了好的

**Comment by iOSniuniu** [comment]
v3 上的功能少了好多啊

**Comment by whalehe** [comment]
您好，新版本已实现此接口，可以升级到最新版本验证下。
