### ISSUE TITLE
【Android】-【5.1.50】：通过aar集成的方式/Users/xxx/.gradle/caches/transforms-2/files-2.1/2784058064189e1431c82db5ad3f2bf6/jetified-tuikit-5.1.50/res/layout/audiocall_item_user_layout.xml:27: AAPT: error: resource style/AVLoadingIndicatorView.Large (aka net.coding.android_demo:style/AVLoadingIndicatorView.Large) not found.

### ISSUE THREAD

**Issue by CHparis** [tencentyun/TIMSDK#961]
issue内容：
通过aar集成的方式，可以正常编译通过，运行的时候，出现如下的异常，

/Users/xxx/.gradle/caches/transforms-2/files-2.1/2784058064189e1431c82db5ad3f2bf6/jetified-tuikit-5.1.50/res/layout/audiocall_item_user_layout.xml:27: AAPT: error: resource style/AVLoadingIndicatorView.Large (aka net.coding.android_demo:style/AVLoadingIndicatorView.Large) not found.

compileSdkVersion 29

**Comment by Tencent-Alice** [comment]
您好 根据您的问题，是真机还是模拟机进行测试的？
技术问题 欢迎交流  Q2562367495 注明来意

**Comment by CHparis** [comment]
您好 是真机运行的时候出错的哈

**Comment by CHparis** [comment]
排查到问题了，是因为我在app的gradle里面配置了引起的，删掉就好了
packagingOptions {
        exclude 'classes.dex'
        exclude '**.**'
    }
