### ISSUE TITLE
有Swift版本的自定义消息那块的demo吗？

### ISSUE THREAD

**Issue by sjxt** [tencentyun/TIMSDK#965]
issue标题： 有Swift版本的自定义消息那块的demo吗？

用swift能集成聊天，但是按照oc的demo去弄自定义消息的时候一直显示不出来

**Comment by Tencent-Alice** [comment]
您好 和您确认下，现在使用的IM版本号 和 自定义消息  显示不出来具体的操作 已便定位问题 
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by sjxt** [comment]
> 您好 和您确认下，现在使用的IM版本号 和 自定义消息 显示不出来具体的操作 已便定位问题
> 技术问题 欢迎交流 Q2562367495 注明来意

已经搞定了

**Comment by ZClee128** [comment]
怎么处理，我也想知道
