### ISSUE TITLE
[iOS SDK] 每次从后台进入都会 crash 

### ISSUE THREAD

**Issue by heronlyj** [tencentyun/TIMSDK#97]
例如: QQ 验证之后打卡 app

![image](https://user-images.githubusercontent.com/5340305/56708035-d7ab9600-674d-11e9-988b-93ba6cb0b869.png)

**Comment by lynxzhang** [comment]
这边使用的版本是？每次从后台进入的时候你这边调用的是SDK的哪些函数？
