### ISSUE TITLE
【微信小程序】使用 uniapp 开发小程序，引入微信小商店插件时冲突

### ISSUE THREAD

**Issue by KITTEEE** [tencentyun/TIMSDK#970]
微信开发者工具版本：1.03.2012120

问题描述：使用 uniapp 开发小程序，引入 tim-js-sdk 是没问题的，但是注册微信小商店插件时就会报 TypeError: Cannot redefine property: toString，不注册插件就没事。

报错截图：
<img width="826" alt="截屏2021-03-17 下午3 48 00" src="https://user-images.githubusercontent.com/31150961/111432614-34e0d400-8738-11eb-8c05-5c191f4b1e7e.png">

去了 uniapp 论坛，官方说是小插件会禁止对内置对象某些属性的修改：[uni-app引入微信小商店插件后某些页面出现未注册的情况](https://ask.dcloud.net.cn/question/118918)

官方解答：
<img width="739" alt="截屏2021-03-17 下午3 51 30" src="https://user-images.githubusercontent.com/31150961/111432978-a91b7780-8738-11eb-9885-f294c8c40626.png">

**Comment by KITTEEE** [comment]
tim-js-skd 版本：2.9.3

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，是js报错，可以提供下小程序版本号和相关日志，具体定位分析
技术问题 欢迎交流 q2562367495 注明来意

**Comment by KITTEEE** [comment]
小程序调试基础库：2.15.0  低版本也会报错


问题定位：
<img width="1063" alt="截屏2021-03-17 下午4 22 39" src="https://user-images.githubusercontent.com/31150961/111436504-05809600-873d-11eb-80f0-dc57605ca548.png">


<img width="1068" alt="截屏2021-03-17 下午4 23 58" src="https://user-images.githubusercontent.com/31150961/111436674-3660cb00-873d-11eb-86d5-38de6a4dc05c.png">


推测是代码里重复或重新定义了 toString

**Comment by KITTEEE** [comment]
微信小商店插件版本：1.1.54

**Comment by KITTEEE** [comment]
测试了一下如果有下面这样的操作就会报类似的错误

`
Object.defineProperty(Function.prototype, 'toString', {});
`

**Comment by KITTEEE** [comment]
测试了一下应该是 SDK 的源码里有下面这样的操作造成的：

Object.defineProperty(Function.prototype, 'toString', {});

**Comment by KITTEEE** [comment]
测试了一下应该是 SDK 的源码里有下面这样的操作造成的：

`

Object.defineProperty(Function.prototype, 'toString', {});

`

**Comment by KITTEEE** [comment]
在源码这里加了 return，SDK 还有小插件都可以正常运行了

![WechatIMG6](https://user-images.githubusercontent.com/31150961/111447735-af195480-8748-11eb-9d85-f0075656893d.jpeg)

不过控制台会报这些错误：

![WechatIMG7](https://user-images.githubusercontent.com/31150961/111447950-e8ea5b00-8748-11eb-9059-e765dc7cca55.jpeg)

然后去搜了一下相关报错的原因，微信小程序官方的解答跟 uniapp 官方的解释类似： [小程序引入插件报错](https://developers.weixin.qq.com/community/develop/doc/000ea418f4cc1066ca77439a357800)

下面是官方解释的截图：
![WechatIMG8](https://user-images.githubusercontent.com/31150961/111448479-6ada8400-8749-11eb-93e5-029bbaa5717f.jpeg)


是不是 SDK 有重新或重复定义了某些属性？

**Comment by akaziki** [comment]
我也遇到了同样的问题，希望官方能尽快解决。目前看来应该是编译tim-js-sdk到es5时加了一些polyfill导致的错误。
如果方便的话， 可不可以提供一份tim-js-sdk打包前的es2015+的源码，不进行编译，让小程序编辑器来做转es5处理。

**Comment by KITTEEE** [comment]
发现是装错包了，装成了 Web 的包( tim-js-sdk )，小程序的包是 tim-wx-sdk 。🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
