### ISSUE TITLE
【Android】-【5.1.56】：【Android平台项目不支持AndroidX只能使用4.8.10以下版本吗】

### ISSUE THREAD

**Issue by kHRYSTAL** [tencentyun/TIMSDK#974]
【当前现象】：由于compileSdkVersion目前还是26 使用的都是appcompat包
【集成包】：IMSDK tuikit:5.1.56
【机型】：Android
【之前版本有无此问题】：4.8.1后androidx不兼容
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，4.8.50以后的SDK都支持androidx，4.8.50之前的版本是不支持的，进行了UI处理 ，请知悉
技术问题 欢迎交流 q 2562367495 注明来意
