### ISSUE TITLE
tim-js-sdk发送组合消息，消息中有多张图片时只有第一张图片被上传并生成url了，其他图片url都为空

### ISSUE THREAD

**Issue by senwa** [tencentyun/TIMSDK#976]
【tim-js-sdk】-【2.10.1】：【组合消息无法发送多张图片】
【集成包】：TUIKIT
【当前现象】：续创建2个单独的图片类型的message,然后把第二个中的element合并到第一个图片的message里面调用sendMessage发出去，发现只有第一个有地址，后面的图片消息里面都没有地址，创建图片消息的时候是选择了图片的路径的
【pc】：firefox
【有无日志或者截图】：
![1](https://user-images.githubusercontent.com/13153329/112643106-f6a58c00-8e7e-11eb-9acd-c3adc891be77.png)
![2](https://user-images.githubusercontent.com/13153329/112643109-f73e2280-8e7e-11eb-8e9f-33f9099b1111.png)
![3](https://user-images.githubusercontent.com/13153329/112643118-f9a07c80-8e7e-11eb-8262-87e4277a005a.png)

**Comment by senwa** [comment]
<img width="622" alt="截屏2021-03-26 21 47 32" src="https://user-images.githubusercontent.com/13153329/112652850-d37fda00-8e88-11eb-8cd0-7e0d2d2fc47d.png">
看了一下sdk压缩后的代码发现这里只处理了第一个element,这块导致即使传了多个图片或者文件语音视频等类型也不会上传，请修复一下

**Comment by yangq1990** [comment]
webim v2.x 不支持发送组合消息，感谢您的理解和支持
