### ISSUE TITLE
[小程序]为何小程序版本demo是mpvue 而不是原生小程序

### ISSUE THREAD

**Issue by myccckkk** [tencentyun/TIMSDK#981]

**Comment by Tencent-Alice** [comment]
您好，小程序的demo 暂时只有mpvue  的框架项目，暂时没有原生的小程序demo，请知悉
技术问题 欢迎交流 q2562367495 注明来意

**Comment by myccckkk** [comment]
> 您好，小程序的demo 暂时只有mpvue 的框架项目，暂时没有原生的小程序demo，请知悉
> 技术问题 欢迎交流 q2562367495 注明来意

mpvue框架都不维护了 这不是挖坑吗😅改成UniApp也行啊

**Comment by Tencent-Alice** [comment]
哈哈哈 有技术问题 欢迎交流

**Comment by yangq1990** [comment]
原生的正在规划了，开发好后替换现有的demo

**Comment by myccckkk** [comment]
> 原生的正在规划了，开发好后替换现有的demo

喜大普奔😄

**Comment by Aliom252181** [comment]
所以原生的已经要有了嘛，我也是跟着文档写了半天，那个客户端加密是真的原生接入失败，需要一个GenerateTestUserSig 小程序版本

**Comment by myccckkk** [comment]
> 所以原生的已经要有了嘛，我也是跟着文档写了半天，那个客户端加密是真的原生接入失败，需要一个GenerateTestUserSig 小程序版本

userSig直接后端加密返回给你就行 我是用原生写的
