### ISSUE TITLE
【微信小程序】 - 【2.9.1】：小程序相互之间收不到加入直播群的消息

### ISSUE THREAD

**Issue by zhang704** [tencentyun/TIMSDK#989]
issue标题：【微信小程序】 - 【2.9.1】：小程序相互之间收不到加入直播群的消息

issue内容：

【当前现象】：小程序相互之间收不到加入直播群的消息
【集成包】：IMSDK
【机型】：全部
【有无日志或者描述、截图】：暂无，App和网页进入，小程序能收到加入的群消息

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以描述下具体操作和收集下日志具体看下，方便进一步定位case
技术问题 欢迎交流 q2562367495 注明来意
