### ISSUE TITLE
【android】-【5.3.425】：【一直报9519，切换网络后第一次能连接，后面都是失败】

### ISSUE THREAD

**Issue by zwb474287221** [tencentyun/TIMSDK#995]
【android】-【5.3.425】：【一直报9519，切换网络后第一次能连接，后面都是失败】
issue内容：

【当前现象】：一直报9519，切换网络后第一次能连接，后面都是失败。 imsdk:5.1.56是好的
【集成包】：imsdk-smart:5.3.425
【机型】：小米9
【之前版本有无此问题】：前几天 imsdk:5.1.56是好的
![image](https://user-images.githubusercontent.com/32866552/118438473-06bb4880-b717-11eb-8d7b-efe91cb9e032.png)

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，请您提供下问题复现的完整sdk log日志，这边看下，方便查看您的问题。
获取日志链接
https://cloud.tencent.com/developer/article/1502366
技术问题 欢迎交流 q2562367495 注明来意
