### ISSUE TITLE
iOS - 精简版v5.3.425 ：退出登录后依旧可获取上次登录用户的会话数据

### ISSUE THREAD

**Issue by wbcyclist** [tencentyun/TIMSDK#998]
【当前现象】：退出登录后依旧可获取上次登录用户的数据
【集成包】：TXIMSDK_Smart_iOS_Bitcode_XCFramework v5.3.425

登录后调用  `[V2TIMManager sharedInstance] logout` ，退出成功，并调用 `[[V2TIMManager sharedInstance] getLoginUser]` 返回nil，之后调用 `[V2TIMManager sharedInstance] getConversationList` 返回上个登录用户的会话列表数据

**Comment by Tencent-Alice** [comment]
您好，请问您的问题是否必现，如果必现请您提供一下您的日志，方便我们查看问题
https://cloud.tencent.com/developer/article/1502366
技术问题 欢迎交流 q2562367495 注明来意

**Comment by wbcyclist** [comment]
日志就不提供了，按描述去操作可必现。
