### ISSUE TITLE
 web端 2.11.0 create 失败

### ISSUE THREAD

**Issue by ItAzeY** [tencentyun/TIMSDK#999]
【 web端 2.11.0 create 失败
【集成包】：TIMSDK
【当前现象】：h5 中 使用 2.11.0 会出现 create 错误, 初始化失败
【浏览器】：谷歌浏览器
【之前版本有无此问题】：2.1.4 和  2.10.2 都没有此问题.npm的官方下载版本是 2.11.0, 如果是 npm 安装,建议安装时指定版本为 2.10.2 .
【有无日志或者截图】：
![image](https://user-images.githubusercontent.com/42231507/119482185-27724680-bd86-11eb-967c-26e70a7ad962.png)
![image](https://user-images.githubusercontent.com/42231507/119482213-2f31eb00-bd86-11eb-8d83-2a661db1b5c7.png)
![image](https://user-images.githubusercontent.com/42231507/119482249-3a851680-bd86-11eb-9a36-bd2fad15bfab.png)
![image](https://user-images.githubusercontent.com/42231507/119482263-3f49ca80-bd86-11eb-9ce7-714b855d580f.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题 
请您提供一下您的create代码，这边好定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by ItAzeY** [comment]
import TIM from 'tim-js-sdk';
const options = {
  SDKAppID: 0 // 接入时需要将0替换为您的即时通信应用的 SDKAppID
};
// 创建 SDK 实例，TIM.create() 方法对于同一个 SDKAppID 只会返回同一份实例
const tim = TIM.create(options);

就是这个地方. 我把 SDKAppID 已经更改为我的应用 id 了.

**Comment by momoca** [comment]
我也发现同样的问题 Uncaught TypeError: this._socket.onClose is not a function

**Comment by ItAzeY** [comment]
@momoca 建议你更换成 2.10.2 的版本,这边尝试是没有问题的呢

**Comment by momoca** [comment]
@ItAzeY 是的已经回退到 2.10.2

**Comment by yangq1990** [comment]
请问是用 uni-app 接入的么
